### ISSUE TITLE
Connection Status - Error 600s Timeout

### ISSUE THREAD

**Issue by jacoblroberts** [Chia-Network/chia-blockchain#11637] opened 2022-05-19 16:48 UTC
Hello.  I've been experiencing random issues where the full node will timeout on a challenge and never recover.  The 'farm' tab doesn't show error but isn't trying new challenges.  The 'full node' tab will show Error under the 'connection status' block with an info tip that says it timed out after 600 seconds.   When closing down the gui, it will not close since all operations will not stop.  It requires a manual close and a full reboot.

**Comment by wallentx** [comment] 2022-05-26 17:29
Are you able to provide us with logs? What OS are you on, and what version are you running?

**Comment by wallentx** [comment] 2022-05-26 17:34
This is a duplicate of https://github.com/Chia-Network/chia-blockchain/issues/11584

**Closed by wallentx** 2022-05-26 17:34 UTC
