### ISSUE TITLE
chia gui wont connect to wallet, i start the app it says it is connectin to wallet and stays like thar for ever [BUG]

### ISSUE THREAD

**Issue by mflex183** [Chia-Network/chia-blockchain#7585] opened 2021-07-17 04:48 UTC
When I open Chia GUI, its just loading Wallet and stuck there.

**Comment by madrigo64** [comment] 2021-07-17 17:01
It might be error on DB. I recommend do backups of DB when all is work fine.

**Comment by deanrey** [comment] 2021-07-18 00:30
I have the same issue. Sometimes it connects fine and other times its stuck at the 'Connecting to Wallet' screen with spinning circle and never connects.

I have deleted my wallets directory several times and issue keeps returning

**Comment by kunalchachan** [comment] 2021-07-18 08:50
I have also the same problem . Please me , what to do ?

**Comment by mflex183** [comment] 2021-07-18 09:07
> I have also the same problem . Please me , what to do ?

Uninstall the Chia GUI, Remove the folder from the Drive and Install it back. It will take time to sync all your plots. But, that's the only way It worked for me.

**Comment by RulixConception** [comment] 2021-07-19 22:03
Having the same issue as well...

**Comment by yiluzhou** [comment] 2021-07-20 23:06
Having the same issue as well.

**Comment by vdx660** [comment] 2021-07-22 00:07
I noticed this issue happens if the Sync of the Wallet is too far away from the Full Node Sync. For what worked for me was to delete all the files on the below folders:

1. C:\Users\\[user]\\.chia\mainnet\wallet\db
2. C:\Users\\[user]\\.chia\mainnet\db
3. C:\Users\\[user]\\AppData\Roaming\Chia Blockchain\Local Storage\leveldb

**Comment by emlowe** [comment] 2021-07-22 03:18
Duplicate of #6993

**Closed by emlowe** 2021-07-22 03:18 UTC
Labels: bug
