### ISSUE TITLE
Negative Balance break wallet after Pool NFT if only 1 mojo in wallet

### ISSUE THREAD

**Issue by LouisLoudogTrottier** [Chia-Network/chia-blockchain#8599] opened 2021-09-25 19:14 UTC
### First occurence
I've sent myself one sigle mojo and was able created a singleton NFT, but now when i type `chia wallet show` i get in stdout `Exception from 'wallet' {'error': 'Value -1 of does not fit into uin128', 'success': False}`

And ~/.chia/testnet/log/debog.log loop with the error:
`ERROR    Exception: 'NoneType' object is not iterable <class 'TypeError'>, closing connection {'host': '127.0.0.1', 'port': 58444}. Traceback (most recent call last):
`
also noticed an:
` WARNING  Trying to ban localhost for 10, but will not ban
`
Yes, this is testnet.
` I'Ve restared with chia start farmer -r 
` 
My transaction to create the singleton is still in mempool after 45 minutes, the wallet is broken and loop has started to loop `TypeError: 'NoneType' object is not iterable` Followed by `RuntimeError: Was not able to add blocks 634051-634083`

Will have to wait to fininsh sync the last 5 wallets to consolidate my mojo before being able to delete db.
Thank again,

#### BEFORE  NFT:
```
Wallet height: 634285
Sync status: Synced
Balances, fingerprint: ...
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 1e-12 txch (1 mojo)
   -Pending Total Balance: 1e-12 txch (1 mojo)
   -Spendable: 1e-12 txch (1 mojo)

```
#### chia plotnft create return successfully with 
`Do chia wallet get_transaction -f .. -tx ... to get status`

#### AFTER NFT:
```
Wallet height: 634303
Sync status: Synced
Balances, fingerprint: ...
Exception from 'wallet' {'error': 'Value -1 of does not fit into uin128', 'success': False}


```
#### TX STUCK
```
Transaction ...
Status: In mempool
Amount: 1E-12 txch
To address: ...
Created at: 2021-09-24 03:11:29

```
#### LOGS since NFT:
```
2021-09-24T03:15:18.203 wallet wallet_server              : ERROR    Exception: 'NoneType' object is not iterable, {'host': '127.0.0.1', 'port': 58444}. Traceback (most recent call last):
...
TypeError: 'NoneType' object is not iterable

```
Ya, this is broken, twice on 2 different walers. Will try with more than just one mojo, but if making a singleton break you wallet, ouff..

_Originally posted by @LouisLoudogTrottier in https://github.com/Chia-Network/chia-blockchain/issues/7292#issuecomment-926290358_

**Comment by LouisLoudogTrottier** [comment] 2021-09-25 19:15
See comment for follow up, https://github.com/Chia-Network/chia-blockchain/issues/7292#issuecomment-926329557

**Comment by LouisLoudogTrottier** [comment] 2021-09-25 19:21
More than 24h later al tx are still in mempool and every tx i make is now getting stuck in mempool. latest one being

Transaction 53ad75387cadad5d2ff1d446667f6d6580a576e386d1f9b5c2dd0cf166e0d8b1
Status: In mempool
Amount: 9.92E-10 txch
To address: txch1lvawglxsd5pz0ual8rlq4uq6gaps3l83pp8j0l6m6q8ctrakargqz5gd7s
Created at: 2021-09-25 04:33:46

**Comment by LouisLoudogTrottier** [comment] 2021-09-25 22:23
How/Can someone remove/cancel transaction stuck in mempool?

**Comment by LouisLoudogTrottier** [comment] 2021-09-26 20:46
I've deleted all the .chia/testnet folder and restarted syncing everything on 1.2.7
I've turned on DEBUG in logs
Still have 6 mainnet wallets to consolidates, so 6 potentials testnet dummies for ... testing.
This also removed tx from mempol (it sems).

**Comment by paulhainsworth-chia** [comment] 2021-11-11 22:22
In our backlog https://trello.com/c/edQOPBPG

**Comment by emlowe** [comment] 2022-04-26 17:44
I could not reproduce this issue in more recent builds. I created a plotnft without any problems with just a single mojo and the wallet did not have any issues as described.

I suspect this was fixed at some point along the way. Closing issue

**Closed by emlowe** 2022-04-26 17:44 UTC
Labels: bug, Sev4
