### ISSUE TITLE
[BUG] MacOs Time Zone Wrong

### ISSUE THREAD

**Issue by querywilly** [Chia-Network/chia-blockchain#4684] opened 2021-05-12 13:52 UTC
time settings look wrong. 
mac os catalina 10.15.7
5 days ahead.
How can I fix. 

![Screen Shot 2021-05-12 at 4 51 39 PM](https://user-images.githubusercontent.com/1374669/117986486-5928ed80-b342-11eb-85d7-708f61dca699.png)

**Comment by yijiasu** [comment] 2021-05-12 17:30
This is not a bug. It shows the "lastest block time" of your local copy of the blockchain.

You have to wait until the syncing completed, then this time will be showing correctly.

**Comment by sargonas** [comment] 2021-05-12 23:14
To elaborate a bit more on the previous response for others who might find this while searching a similar quetsion: While you are in the process of syncing your node and catching up, your "peak" is the highest block your local node is aware of. Not necessarily the highest node in the chain, just the highest it is aware of. This slowly goes up as you sync and catch up to the live blockchain, at which point you will be in sync. Until then, the "peak time" is literally the time (and date) of your current peak. What it is telling you is, the current peak of your local copy of the node is block 143000 from 4/17/2021 at 2:53:20PM. Thats how far you have synced on your path to completion.

**Closed by sargonas** 2021-05-12 23:14 UTC
Labels: bug
