### ISSUE TITLE
How can I know the progress when "cmd chia create plots xxxx"?

### ISSUE THREAD

**Issue by qqqcai** [Chia-Network/chia-blockchain#2961] opened 2021-04-28 02:14 UTC
How can I know the progress when "cmd chia create plots xxxx"?

Will there be log files here?

**Comment by royimous** [comment] 2021-04-28 04:48
This is not a bug. Close this. Read the Wiki to answer your question. Read the FAQ on proper support channels.

**Closed** 2021-04-29 01:15 UTC
Labels: bug
