### ISSUE TITLE
[Bug]  Full Node Error

### ISSUE THREAD

**Issue by wanirai** [Chia-Network/chia-blockchain#12114] opened 2022-06-27 13:24 UTC
### What happened?

![chia full note error__1](https://user-images.githubusercontent.com/107934369/175952008-23ac319d-40cf-4fde-9419-dfc1adfa0742.PNG)

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wanirai** [comment] 2022-06-27 13:36
Relevant log add


FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.512 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.517 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.521 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.526 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.531 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.537 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.542 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.546 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.551 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.555 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.560 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.564 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T07:04:34.569 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service

**Comment by wanirai** [comment] 2022-06-27 13:40
Relevant log add

2022-06-22T09:19:34.365 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T09:19:34.370 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T09:19:34.374 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T09:19:34.379 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T09:19:34.385 daemon __main__                   : ERROR    problem starting chia_full_node_simulator
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
2022-06-22T11:21:10.424 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: Connection lost Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 239, in incoming_connection
  File "aiohttp\web_ws.py", line 308, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 659, in _send_frame
  File "aiohttp\base_protocol.py", line 80, in _drain_helper
ConnectionResetError: Connection lost
2022-06-22T11:31:09.382 wallet chia.wallet.wallet_node    : ERROR    Exception while adding state:  Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 668, in receive_and_validate
  File "chia\wallet\wallet_state_manager.py", line 644, in new_coin_state
  File "chia\wallet\wallet_state_manager.py", line 540, in fetch_parent_and_check_for_cat
  File "chia\wallet\wallet_node.py", line 1439, in get_coin_state
AssertionError

2022-06-22T11:31:27.426 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '217.19.18.164', 'port': 8444} None response from peer 217.19.18.164 for register_interest_in_puzzle_hash Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 964, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 543, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 62, in subscribe_to_phs
ValueError: None response from peer 217.19.18.164 for register_interest_in_puzzle_hash

2022-06-22T11:31:27.426 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '217.19.18.164', 'port': 8444} Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 964, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 543, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 62, in subscribe_to_phs
ValueError: None response from peer 217.19.18.164 for register_interest_in_puzzle_hash

2022-06-22T11:31:27.448 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '217.19.18.164', 'port': 8444} did not respond in time.
2022-06-22T11:31:27.448 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-22T11:31:27.449 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-22T11:31:27.449 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-22T11:31:27.450 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-22T11:31:27.451 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '217.19.18.164', 'port': 8444} did not respond in time.
2022-06-26T21:53:34.546 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.546 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.547 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.547 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.548 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.548 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.549 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.549 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:53:34.550 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:55:03.814 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:55:03.815 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:55:03.816 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:55:03.816 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-26T21:55:45.233 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1267' coro=<WalletNode.long_sync() done, defined at chia\wallet\wallet_node.py:497> exception=ValueError('None response from peer 156.34.174.57 for register_interest_in_puzzle_hash')>
Traceback (most recent call last):

**Comment by xerfo** [comment] 2022-06-27 15:40
yo tengo el mismo error y no he podido corregirlo

**Comment by emlowe** [comment] 2022-06-28 22:13
The problem is that your system is trying to start the simulator - but that shouldn't be happening.
Please verify that you DO NOT have an environment variable `LOCAL_TEST` set or a `.env` file that sets this variable.

Note, the windows installer doesn't include the simulator at all

**Comment by jack60612** [comment] 2022-06-28 22:32
Solved by https://github.com/Chia-Network/chia-blockchain-gui/pull/817

**Comment by jack60612** [comment] 2022-06-28 22:34
https://trello.com/c/O6bod7Xe/1562-disable-simulator-in-gui

**Comment by jack60612** [comment] 2022-07-07 03:29
Issue will be fixed in next update, and it is already fixed in gui

**Closed by jack60612** 2022-07-07 03:29 UTC
Labels: bug
