### ISSUE TITLE
[BUG]1.20 not refreshing plots automatically

### ISSUE THREAD

**Issue by obeykarma** [Chia-Network/chia-blockchain#7393] opened 2021-07-12 05:09 UTC
I was plotting by madMAx43v3r ( windows/mac m1) NFT, 
the destination directories are added to chia official apps but after madMAx43v3r copied the finished plot to the directory the chia official apps not refreshing automatically.
Sloved after manually refreshed.

Problem occured on windows and mac clients.

**Comment by xludodx** [comment] 2021-07-12 06:37
I have the same problem since 1.2.0

**Comment by nort774** [comment] 2021-07-12 06:50
Similar problem in UBUNTU

**Comment by scriper88** [comment] 2021-07-12 10:17
Same Problem here on Windows, Mac and Ubuntu.
On the pool tab it will not refresh automatic.

**Comment by limebinary** [comment] 2021-07-12 11:40
Same Problem here on Windows. Need to manual refresh.

**Comment by brasrox** [comment] 2021-07-12 14:07
same here windows 10

**Comment by emlowe** [comment] 2021-07-12 15:28
Duplicate of #7262

**Closed by emlowe** 2021-07-12 15:28 UTC
Labels: bug
