### ISSUE TITLE
[BUG] WALLET STUCK ON "CONNECTING TO WALLET"

### ISSUE THREAD

**Issue by MintyFreshFarmer** [Chia-Network/chia-blockchain#5868] opened 2021-05-23 12:36 UTC
Wallet is stuck on connecting to wallet. Any solutions?

Using windows 10

I've tried close, forced close, restart, shut down. Don't know what else to do.

**Comment by caminotr** [comment] 2021-05-23 15:33
I just resolve this issue deleting  mainnet/db and mainnet/wallet and than it works, but it needs to sync everything again.
BUT i did the same in my another pc, and the problem continues.

**Comment by MitchellBauer** [comment] 2021-05-23 15:46
Same thing is happening to one of my computers. 

Except all I had to do was delete/rename the user/.chia/mainnet/wallet folder. If you do that you don't lose the full sync.

**Comment by mediccby** [comment] 2021-05-23 16:08
> Same thing is happening to one of my computers.
> 
> Except all I had to do was delete/rename the user/.chia/mainnet/wallet folder. If you do that you don't lose the full sync.

Yep that worked for me too. Just renamed to .old

**Comment by caminotr** [comment] 2021-05-23 16:15
> Same thing is happening to one of my computers.
> 
> Except all I had to do was delete/rename the user/.chia/mainnet/wallet folder. If you do that you don't lose the full sync.

But it will sync the wallet again right?

**Comment by samy63** [comment] 2021-05-23 23:44
![image](https://user-images.githubusercontent.com/84105006/119280403-912d0c00-bc31-11eb-855f-7f4c5bdec869.png)

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
