### ISSUE TITLE
Always Connecting to Wallet[BUG]

### ISSUE THREAD

**Issue by 53221** [Chia-Network/chia-blockchain#6960] opened 2021-06-24 10:38 UTC
APP shows connecting to wallet after a forced reboot to finish windows update, below is the log copy from APP's develop mode
0
main.js:1 Already connected, not reconnecting.
main.js:1 0
events.js:292 Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)
exceptionWithHostPort @ internal/errors.js:563
afterConnect @ net.js:1141
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
events.js:292 Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)
exceptionWithHostPort @ internal/errors.js:563
afterConnect @ net.js:1141
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
events.js:292 Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)
exceptionWithHostPort @ internal/errors.js:563
afterConnect @ net.js:1141

**Comment by mariano54** [comment] 2021-06-28 07:36
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check that issue

**Closed by mariano54** 2021-06-28 07:36 UTC
Labels: bug
