### ISSUE TITLE
need help ASAB, I have been stuck here for a long time its not working  [BUG]

### ISSUE THREAD

**Issue by far0o0s** [Chia-Network/chia-blockchain#6391] opened 2021-06-03 15:58 UTC
The application is not working and I have been on this case for 8 days knowing that it has been working for a long time suddenly this happened
![Screenshot 2021-06-03 18 54 50](https://user-images.githubusercontent.com/85304692/120675342-a6116700-c49d-11eb-903d-72dc350b301e.png)

**Comment by q1k** [comment] 2021-06-03 16:10
close the program,
open task manager, switch to 'details' tab.
end all 'chia' processes, including the ones 'start_harvester', start_farmer, etc.
Launch chia again.
Sometimes the only solution would be to reboot the computer.

Have you changed any settings in the config?

**Comment by far0o0s** [comment] 2021-06-03 16:27
I did all those steps and uninstalled the program then installed it but it still doesn't work

**Comment by q1k** [comment] 2021-06-03 22:22
Go to your user profile, then to \.chia\mainnet\wallet\db
delete the sqlite database, or move it to another folder in case this is not the issue.
The wallet will have to resync.
You might have to try the same with the \mainnet\db

**Comment by NunoFilipeMota** [comment] 2021-06-04 12:23
I have this exact same problem every time I close Chia. The first time, deleting the DB folder fixed the issue, now that doesn't work anymore. My only solution is to completely uninstall and re-install it. It's becoming impossible to use it...

**Comment by mariano54** [comment] 2021-06-28 07:57
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:57 UTC
Labels: bug
