### ISSUE TITLE
[Enhancement] Continue to farm good plot directories in config.yaml when bad plot directories are found in config.yaml

### ISSUE THREAD

**Issue by ksulfa** [Chia-Network/chia-blockchain#3586] opened 2021-05-03 22:38 UTC
every time i start chia GUI on windows 10 aa error pop up like on the screenshot. i'm using Intel core i7-9750H. 

**Additional context**
<img width="779" alt="chia error" src="https://user-images.githubusercontent.com/83577609/116941828-93501a80-acc4-11eb-9e88-e560d031de62.PNG">

**Comment by salvarez1988** [comment] 2021-05-03 23:53
Hello, I have a similar issue when I try to add a plot directory, any idea or suggestion? 
![2021-05-03_19-51-15](https://user-images.githubusercontent.com/26015637/116946840-33685e00-ac49-11eb-9d65-b9fa65dd1e73.png)
?

**Comment by mariano54** [comment] 2021-05-04 05:30
Try backing up the full node DB, and then deleting the entire ~/.chia/mainnet folder
Then put your full node DB back in there

**Comment by mariano54** [comment] 2021-05-04 05:30
And check out the permissions in the hard drive where the plots are.

**Comment by PedroLEGA** [comment] 2021-05-05 00:53
> And check out the permissions in the hard drive where the plots are.



> Try backing up the full node DB, and then deleting the entire ~/.chia/mainnet folder
> Then put your full node DB back in there

Nice, that worked for me, Thanks!

**Comment by salvarez1988** [comment] 2021-05-05 04:28
> Hello, I have a similar issue when I try to add a plot directory, any idea or suggestion?
> ![2021-05-03_19-51-15](https://user-images.githubusercontent.com/26015637/116946840-33685e00-ac49-11eb-9d65-b9fa65dd1e73.png)
> ?

ok guys, I fix it.... this is the way to fix the [error 13] (Credits to the user vladimircicovic)

1. Go to C:\Users{YOUR_USERNAME}\.chia\mainnet\config\
2. Backup and THEN edit config.yaml
3. find inside of yaml: plot_directories:
4. Remove paths that are you not using or not existing or remove all (this is just where are directory for plot are)
5. save config.yaml
6. Start Chia app - if missing plot dir - add them

**Comment by hunsao** [comment] 2021-05-11 10:31
I solved it by editing config.yaml plot directories. After installing some drives the letters changed, so just change it again.

**Comment by Chaya89** [comment] 2021-05-29 03:00
Excuse i have the same problem, I keep my plot in Synology. and how to config it.

**Comment by charlesponiente** [comment] 2021-06-01 01:35
> Try backing up the full node DB, and then deleting the entire ~/.chia/mainnet folder
> Then put your full node DB back in there

How do you backup the full node DB?

**Comment by damianmadeira** [comment] 2021-06-07 01:17
hello everybody, i did what you sey but i can't add the plot directory. Also install version 1.1.7 and i get the same error "argument of type 'NoneType' is not iterable ".
My SO: Win 10 Pro.
![image](https://user-images.githubusercontent.com/56444256/120946992-bc752800-c714-11eb-8f5d-44b429037a78.png)

**Comment by damianmadeira** [comment] 2021-06-07 01:26
new error when starting to create plots:
![image](https://user-images.githubusercontent.com/56444256/120947502-23dfa780-c716-11eb-91bb-ce07e883e7cc.png)

**Comment by damianmadeira** [comment] 2021-06-07 23:56
I found the solution.
1. save the mainet folder.
2 uninstall chia
3 install
4 recover the db folder to the new mainet directory

**Comment by demusWiesbaden** [comment] 2021-07-13 18:56
Just now having the same bug for the first time, after changing and adding USB disks.
With chia 1.2.0.
And now with the update to 1.2.1.

**Comment by loppefaaret** [comment] 2021-07-27 14:24
WINDOWS COMPLETE CONFIG RESET

Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time:
```
mv ~\.chia\mainnet ~\.chia\old
cd ~\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon\
.\chia.exe init
mv ~\.chia\old\db ~\.chia\mainnet\
```
This will remove all settings you had, you will have to resync you wallet, but keep the old blockchain database. You will have to re-add any plot directories and other settings you may have had set.

**Comment by number435398** [comment] 2021-07-28 15:55
I repeatedly have this issue.  If one of the plot folders in the config.yaml has an issue, then why doesn't the program remove that particular folder or point it out to me?  Why do I have to, usually every few weeks, have to go in and delete the file manually?  Its usually associated with me adding and or removing drives.  Also, why does one folder having a problem mean that the program has to pretend I have no other folders that don't have problems?

**Comment by i00** [comment] 2021-07-29 23:04
Chia stopped submitting profs for me this morning; I restarted and got this message.
Sure enough one of my shares was down; but **I HAVE 15 OTHERS** why was it not listing ANY plots or submitting proofs for the other 15!??

**Comment by Poutakidis** [comment] 2021-08-08 10:58
Hello everybody, i sold the problem with:

1. Open with Notepad++ the file config.yaml (C:\Users\your username\.chia\mainnet\config\config.yaml)
2. find inside of yaml: plot_directories: 
3. put [] after plot directories (s. screenshot)
4. save config.yaml
Start Chia app - if missing plot dir - add them


![plot directories](https://user-images.githubusercontent.com/60475775/128629670-fdd47255-160c-4f60-bb07-dd1af7e82144.JPG)

**Comment by number435398** [comment] 2021-08-08 13:39
> 
> 
> Hello everybody, i solve the problem with:
> 
>     1. Open with Notepad++ the file config.yaml (C:\Users\your username.chia\mainnet\config\config.yaml)
> 
>     2. find inside of yaml: plot_directories:
> 
>     3. put [] after plot directories (s. screenshot)
> 
>     4. save config.yaml
>        Start Chia app - if missing plot dir - add them
> 
> 
> ![plot directories](https://user-images.githubusercontent.com/60475775/128629670-fdd47255-160c-4f60-bb07-dd1af7e82144.JPG)

Yes, in the rare instances that one would expect this problem to arise, that fix works. But that's not really the issue. The issue is that when it happens every week or so and or is programmed to ignore ALL plots because only 1 is claimed to have an issue in config.yaml, it leaves us wanting.

**Comment by number435398** [comment] 2021-08-28 11:39
The fact that the config.yaml file stops reading all plot files because 1 folder is wrong definitely seems like a bug. I don't think this issue is really a matter of a mere "enhancement" unless you think you are "enhancing" it by fixing the bug, but then that would negate the significance of a "bug" label to begin with.

**Comment by emlowe** [comment] 2024-11-05 15:48
Closing as this is substantially changed over the years and unlikely occurs in the same way anymore

**Closed by emlowe** 2024-11-05 15:48 UTC
Labels: enhancement
