### ISSUE TITLE
passphrase on file not working with the start command [BUG]

### ISSUE THREAD

**Issue by mcanto73** [Chia-Network/chia-blockchain#9105] opened 2021-11-03 19:03 UTC
**Describe the bug**

**To Reproduce**
(venv) pi@mcanto:~/chia-blockchain $ chia --passphrase-file /home/pi/.chia_keys/my_passphrase keys show
Showing all public keys derived from your master seed and private key:

Fingerprint: 31xxxx

(venv) pi@mcanto:~/chia-blockchain $ chia --passphrase-file "/home/pi/.chia_keys/my_passphrase" start farmer
(Unlock Keyring) Passphrase:
Unlocking daemon keyring

Steps to reproduce the behavior: just run the above commands

So the start command seems to ignore the passphrase-file

**Expected behavior**

Raspberry PI4 4GB - ARM Cortex-A72 (arm v8)
Linux mcanto 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux

Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

**Comment by emlowe** [comment] 2021-11-03 22:44
Duplicate of #9032

**Closed by emlowe** 2021-11-03 22:44 UTC
Labels: bug
