### ISSUE TITLE
fully sync and says not synced in red lettering[BUG]

### ISSUE THREAD

**Issue by hjason7812** [Chia-Network/chia-blockchain#2954] opened 2021-04-28 01:12 UTC
can't mine had a hard time syncing the network when i got close to the end it would change to sync more until it went to this see picture. 

[https://www.mediafire.com/view/84j2zu1ja31cdfg/Screenshot_2021-04-27_210723.png/file](url)

this doesn't make any sense at all. please fix this asap thank you. also my plot says not available because of this and it is fully done to the plot.

**Comment by dorkmo** [comment] 2021-04-28 01:14
you might try to restart you computer? how many peer nodes are you connnected to? are you passing the plot filter?

**Comment by royimous** [comment] 2021-04-28 01:14
This is not a bug. This is a support request and this is not the place for that. Read the FAQ.

You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?

**Comment by dorkmo** [comment] 2021-04-28 01:17
> 
> 
> This is not a bug. This is a support request and this is not the place for that. Read the FAQ.
> 
> You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?

lots of github newbies have been created by chia lol! wish there was a better github introduction explanation on how issues work.

**Comment by hjason7812** [comment] 2021-04-28 01:20
> This is not a bug. This is a support request and this is not the place for that. Read the FAQ.
> 
> You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?

wow you are a complete dick sucker huh? why do you have to be such an asshole to people who pissed in your serial in the morning? guess you hate people huh? jerk smh
I don't know how to write a stupid bug report you are lucky anyone is using this crap in the first place because as i see it it is garbage

**Comment by hjason7812** [comment] 2021-04-28 01:22
> This is not a bug. This is a support request and this is not the place for that. Read the FAQ.
> 
> You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?

Sorry jerk, i just won't come here and i will post everywhere i am to not use this garbage gui or program because they hate people have fun making money dick

**Comment by dorkmo** [comment] 2021-04-28 01:25
> 
> 
> > This is not a bug. This is a support request and this is not the place for that. Read the FAQ.
> > You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?
> 
> Sorry jerk, i just won't come here and i will post everywhere i am to not use this garbage gui or program because they hate people have fun making money dick

if youre finished you can click the "close issue" button :D

**Comment by royimous** [comment] 2021-04-28 01:45
> > This is not a bug. This is a support request and this is not the place for that. Read the FAQ.
> > You also didn't take the time to fill out the basic bug form. Why do you thin anyone would want to help you?
> 
> Sorry jerk, i just won't come here and i will post everywhere i am to not use this garbage gui or program because they hate people have fun making money dick

Don't confuse your unwillingness to do basic work to read the FAQ to me being a jerk. 

This is not a bug. Close it. You're looking for support, read the FAQ. You want to make XCH? You have got to do the work to earn it.

**Closed** 2021-04-30 05:49 UTC
Labels: bug
