### ISSUE TITLE
 Only this loading plot NFT

### ISSUE THREAD

**Issue by neurocodigomecatronica** [Chia-Network/chia-blockchain#7371] opened 2021-07-11 12:47 UTC
**Describe the bug**

![chia erro nft](https://user-images.githubusercontent.com/20406848/125195658-3ae54e00-e21c-11eb-8ce6-545d50c285c5.png)

**Comment by loppefaaret** [comment] 2021-07-12 10:03
if you select the wallet, is the wallet synced to the same height as the full node ?

**Comment by emlowe** [comment] 2021-07-12 15:30
Duplicate of #7361

**Closed by emlowe** 2021-07-12 15:30 UTC
Labels: bug
