### ISSUE TITLE
[Bug] 1.3.0 wallet is not recognizing old coins after a clean sync.

### ISSUE THREAD

**Issue by RnMss** [Chia-Network/chia-blockchain#10620] opened 2022-03-09 08:13 UTC
###  What i did

Upgraded to 1.3

Deleted old wallet db (because it was corrupted for some reason)

wait until wallet synced

### What happened

Balance is 0.0

### My researches

I checked the default puzzle hash generated by the old-version wallet, and found it still have unspent coin. So the balance shouldn't be 0.

I checked the `derivation_paths` table in the new wallet db on another computer. 

Figured out the old-version default puzzle hash has `derivation_index = 0, hardened = 0`, while the new-version default puzzle hash has `derivation_index = 0, hardened = 1`.

And I thought the new wallet does not recognize the old addresses.

### updates

Now the old default puzzle hash received a new coin, the wallet now recognized the new coin, but not the older coins.

So the bug is no longer "new wallet does not recognize old addresses", and it's not because the old addresses were generated using non-hardened pubkeys.

### Version

1.3.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by said026** [comment] 2022-03-11 12:05
I have the same issue, after upgrading to 1.3.0 and resyncing from scratch I cannot see my old coins, besides that my plot NFT wasn't recovered so my existing plots were not recognized for pooling.

**Comment by jxyjest** [comment] 2022-03-13 13:14
What a joke,Shames on U all

**Comment by iliasorazov** [comment] 2022-04-14 11:50
I have the same problem, downloaded new 1.3.3 chia-blockchain on linux machine, upgraded the node blockchain db, removed old wallet db, run it wait until sync complete and `chia wallet show` prints:

    Sync status: Synced
    Balances, fingerprint: ...
    Wallet ID 1 type STANDARD_WALLET Chia Wallet
       -Total Balance: 0.0 xch (0 mojo)
       -Pending Total Balance: 0.0 xch (0 mojo)
       -Spendable: 0.0 xch (0 mojo)

at the same time command `chia wallet get_transactions` actually prints the last unspent transaction, but for some reason it is not counted by the wallet while it calculates the total balance sum.

@wallentx can you confirm that the error exists and have you reproduced it? Are you working on a patch? Why isn't it affect everyone?

**Comment by wallentx** [comment] 2022-04-15 09:22
I've seen a few issues relating to the wrong info being displayed, and it depends on a few factors. If upgrading from a version older than 1.3.0, to 1.3.0 later, there are several activities that take place that, if disrupted, can lead to some info not showing up once you are "Synced".

Specifically with 1.3.3 (technically, with 56804a0b4), I just tested a wallet this evening that was showing different balances on different systems. There are a few theories, suspicions, and rough understandings that I have as to what causes this, and have filed GH issues to get these resolved, but I'll skip right to what fixed the balances and transactions for me.

If it's not too much trouble for you, I think it'd be safest to ensure that you aren't working with some old values in your `config.yaml` by backing it up and removing it, and letting `chia init` create a fresh one. Don't worry too much about the details within it just yet, since it will be updated as you sync. If you'd rather not do that, I wrote a [tool](https://github.com/wallentx/farm-and-ranch-supply-depot/tree/main/bin/config-management) (nothing official) that lets you do a diff against the latest values from the repo. Whichever you decide to do, it may be useful to enable DEBUG logging, so that you can share the details of that if you continue to have problems.

This next part assumes that you've already migrated the a v2 blockchain DB.
If you run a local trusted `full_node` (or use the GUI in "Farming" mode), and already have a fully synced blockchain DB, then you can stop all Chia services, and set `connect_to_unknown_peers: false` in your `config.yaml`, delete your **wallet** DB, and `chia start node wallet` (or launch the GUI and run in "Farming" mode). If you have more than 1 set of keys, you'll need to `chia wallet show` and select the fingerprint of the wallet that you want to sync.
Once it starts syncing, just let it run, and try not to execute any other commands while it's syncing. Reasons: https://github.com/Chia-Network/chia-blockchain/issues/11175
How long this will take depends on the number of transactions you have, your machine, etc.

If you don't have a fully synced v2 blockchain DB, and you have no desire to run a local trusted `full_node`, or you only want to use the GUI in "Wallet" mode, then stop all Chia services, and set `connect_to_unknown_peers: true` in your `config.yaml`, delete your **wallet** DB, and `chia start wallet` (or launch the GUI and run in "Wallet" mode. If it launches in "Farming" mode, then switch it to "Wallet" mode, exit the GUI, and then start the GUI again).
Again, sync time will vary, and this method may take a bit longer. It took me a few hours on a wallet with ~3,000 transactions. Once it starts syncing, let it sync, and try not to interact with Chia.

Doing things such as editing the config, stopping and starting services, deleting/adding peers, or anything else that could disrupt the syncing process, could lead to bad data in your db, or gaps of blocks that you never actually synced.

I've managed to find several ways to break things during syncing, but each of those get reported, worked on, and I'm certain we'll have a really solid experience for everyone here soon. Let me know if any of that information helps sort out your balance, or feel free to message me (wallentx) on keybase.

**Comment by iliasorazov** [comment] 2022-04-15 13:19
Apparently the unspent transaction was indeed spent. The problem is probably caused by the fact that my `derivation_paths` list had discontinuity and I didn't use addresses in a middle of it, so it wasn't completely filled during conversion and resync. I've tried to add the missed puzzlehash row to the db. How to initiate resync against the new list manually? Since the issue is probably different from the posted above I should probably open a new issue.

**Comment by wallentx** [comment] 2022-04-15 16:27
> Apparently the unspent transaction was indeed spent. The problem is probably caused by the fact that my `derivation_paths` list had discontinuity and I didn't use addresses in a middle of it, so it wasn't completely filled during conversion and resync. I've tried to add the missed puzzlehash row to the db. How to initiate resync against the new list manually? Since the issue is probably different from the posted above I should probably open a new issue.

I would delete anything that you may have hand-edited, and do a clean resync. You might have better results if you try to run this from `git checkout 56804a0b4c5e06bdc5ac918aa319fdbfbe689f2b`. If you are still having issues, I would suggest making a new GH issue, since the bulk of this one is in reference to 1.3.0, and there have been many changes since then https://github.com/Chia-Network/chia-blockchain/compare/0e7cc5a88393ef02b4057dd4bf894be2e73bc00b...56804a0b4c5e06bdc5ac918aa319fdbfbe689f2b

**Comment by iliasorazov** [comment] 2022-04-16 21:25
Ok, the new wallet mess up DB conversion, dropped the `derivation_paths` and is not able to manually add and update the balance of an address later on. I've fixed this specifying a huge number in `initial_num_public_keys` field.
But how this new wallet suppose to work with multiple thousands of coins? Like those of big exchanges or pools. This wallet prints a huge number of `new coin state received` messages and also `Successfully subscribed and updated ... coin ids` on each restart. Even for an already spent coins. Is there an option to keep the old wallet DB on upgrade which I've missed?

**Comment by wallentx** [comment] 2022-04-28 21:37
@iliasorazov Are you able to download the Latest Dev and see if this still happens? We put in some fixes yesterday that seem to resolve this problem in our testing so far. https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
If this does work for you, please let us know!

**Comment by emlowe** [comment] 2022-04-29 16:51
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by iliasorazov** [comment] 2022-04-30 12:08
@wallentx which issue are you referring to? My problem was caused by the `derivation_paths` table, it wasn't preserved during the wallet db upgrade. A huge number of "new coin state received" messages on each run worry me but it wasn't the cause of the problem.

**Comment by emlowe** [comment] 2022-05-11 21:59
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5

**Closed by emlowe** 2022-05-11 21:59 UTC
Labels: bug, Wallet, balance
