### ISSUE TITLE
[Bug] Self pooling cannot change PlotNFT payout target via CLI

### ISSUE THREAD

**Issue by gWOLF3** [Chia-Network/chia-blockchain#10774] opened 2022-03-16 19:43 UTC
### What happened?

Basically, reopening previously incorrectly closed issue: 

https://github.com/Chia-Network/chia-blockchain/issues/7311

it seems almost 1 year later and the cli still does not support this basic functionality. the config yaml contains the puzzle hash of the plot receive address under pool_list and some people have reported success changing it there:

[libredd.it/r/chia/comments/oqtf59/sending_pool_farming_reward_automatically_to_cold](https://libredd.it/r/chia/comments/oqtf59/sending_pool_farming_reward_automatically_to_cold/)
[chiaforum.com/t/changing-payout-instructions-in-a-pool/10762/3](https://chiaforum.com/t/changing-payout-instructions-in-a-pool/10762/3)

### Version

1.2.10

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment] 2022-03-17 02:02
Self-pooling, correct you cannot change the payout address, claiming goes the current wallet - marking as a duplicate of #10707

**Closed by emlowe** 2022-03-17 02:02 UTC
Labels: bug
