### ISSUE TITLE
[Bug] DID is not usable anymore. Neither minting nor moving NFTs to it works.

### ISSUE THREAD

**Issue by codephunk** [Chia-Network/chia-blockchain#14350] opened 2023-01-15 19:36 UTC
### What happened?

I can't use a DID I created some time ago anymore. I'm neither able to mint with it nor to move NFTs to it.

This is the error message I get when I try to use the DID:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1454125/212563186-d0c456af-3d29-411f-8ce4-1ef31c60671b.png">

This is a follow up to https://github.com/Chia-Network/chia-blockchain/issues/13691 since the issue is not resolved yet. My minting operation is halted for several months now and it would be really great if this issue could finally be resolved.

### Version

1.6.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment] 2023-01-19 21:03
Duplicate of #14347 - Closing current.

**Closed by MumfMeisterT** 2023-01-19 21:03 UTC
Labels: bug, duplicate, support, GUI, MacOS, NFT, 1.6.2
