### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Augustju** [Chia-Network/chia-blockchain#3503] opened 2021-05-03 07:07 UTC
**Describe the bug**
word wrongly translated into Spanish,  the English word "Farming" has been translated as "Joseando" . The right Spanish translation of "Farming" should be "Cultivando"

**To Reproduce**

1. Go to 'Plots'
2. See error on the Status column

**Expected behavior**
I expected to see "cultivando" on the status column.

**Screenshots**
![Farming](https://user-images.githubusercontent.com/83571720/116849108-531e6880-abee-11eb-809d-6e3534d015a7.jpg)
![Joseando](https://user-images.githubusercontent.com/83571720/116849109-53b6ff00-abee-11eb-8442-4c1e41c03cec.jpg)

**Desktop (please complete the following information):**

- OS: Windows10
- OS Version/Flavor: 64bits
- CPU: AMD Ryzen 5 2600 Six-Core 

**Additional context**

**Comment by lipalong** [comment] 2021-05-03 16:28
Duplicate of #3415 – please see the comments there.

**Closed by lipalong** 2021-05-03 16:28 UTC
Labels: bug
