### ISSUE TITLE
Node exception thrown during initial sync in rc2

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#978] opened 2021-02-19 23:20 UTC
### Reproduce
Don't know how, the node seemed to continue syncing afterwards.

### Error Message thrown

17:07:10.627 full_node full_node_server        : ERROR    Exception: , closing connection {'host': '2602:47:2475:7300:546f:2eff:feaf:1', 'port': 58444}. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/src/full_node/full_node_api.py", line 109, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/chia/chia-blockchain/src/full_node/full_node.py", line 329, in new_peak
    await self.short_sync_batch(peer, uint32(0), request.height)
  File "/home/chia/chia-blockchain/src/full_node/full_node.py", line 208, in short_sync_batch
    success, advanced_peak, fork_height = await self.receive_block_batch(response.blocks, peer, None)
  File "/home/chia/chia-blockchain/src/full_node/full_node.py", line 664, in receive_block_batch
    ] = await self.blockchain.pre_validate_blocks_multiprocessing(blocks)
  File "/home/chia/chia-blockchain/src/consensus/blockchain.py", line 507, in pre_validate_blocks_multiprocessing
    return await pre_validate_blocks_multiprocessing(self.constants, self.constants_json, self, blocks, self.pool)
  File "/home/chia/chia-blockchain/src/consensus/multiprocess_validation.py", line 219, in pre_validate_blocks_multiprocessing
    for batch_result in (await asyncio.gather(*futures))
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia-blockchain/src/server/server.py", line 446, in api_call
    response: Optional[Message] = await asyncio.wait_for(coroutine, timeout=300)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by aqk** [comment] 2021-02-19 23:25
Issue seems to happen here - a timeout while verifying info from another peer.

https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L325

If so, we need a way to get our hands on the problematic block(s), so we can reproduce the issue.

**Comment by LordRayden2020** [comment] 2021-02-19 23:33
I have the same Issue but, on my RYZEN CPU and 7th Generation Intel its running fine just the old AMD Phenom II X6 1090T Black I have the issue. It’s just stuck on one random block....

**Comment by mariano54** [comment] 2021-02-20 06:39
OK here is the main performance issue with these slower CPUS:
We have something called "batch sync" which is activated when you are less than 300 blocks away from the peak. This downloads blocks in batches of 32 from a peer, until you get to the peak.
The problem is that if you have 10 peers, you will start batch syncing to all 10 at the same time, and therefore you are downloading and validating many blocks multiple times, and it's hard to ever catch up. Apart from this, there is a global lock, so each asyncio thread has to wait for the others to finish.
The reason it downloads from all 10 is that if only one peer is honest, you still want to make sure you are getting those blocks.
One way to fix this would be to check if the blocks in the batch have already been validated and added, before adding each batch.

**Comment by mariano54** [comment] 2021-02-21 03:26
The method is fetch_and_add_blocks in full node.py. We should not validate blocks already in the chain.

**Comment by mariano54** [comment] 2021-02-21 07:39
This should be fixed by https://github.com/Chia-Network/chia-blockchain/pull/986. However, we need to test the transaction validation

**Closed** 2021-02-21 16:26 UTC
Labels: bug
