### ISSUE TITLE
not 1.2.8 down &install

### ISSUE THREAD

**Issue by Vagex** [Chia-Network/chia-blockchain#8671] opened 2021-10-01 15:22 UTC
new upgrade version 1.2.8 is wrong version，it 1.2.6-dev67，
so dont upgrade to 1.2.8

**Comment by emlowe** [comment] 2021-10-01 16:01
It's a display issue only in the about box - closing as duplicate of #8658

**Closed by emlowe** 2021-10-01 16:01 UTC
Labels: bug
