### ISSUE TITLE
[Bug] 'chia rpc wallet push_tx' accepts only hex encoded spend_bundle

### ISSUE THREAD

**Issue by DrakoPensulo** [Chia-Network/chia-blockchain#18734] opened 2024-10-19 03:27 UTC
### What happened?

'chia rpc wallet push_tx' accepts only request (or json file) in the format '{"spend_bundle":"hex encoded spend  bundle"}'  It does not accept dict encoded spend bundles of the form  '{"spend_bundle": { "coin_spends":[ ... ] ...  } }'

### Version

2.4.4

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia rpc wallet push_tx -j spend80_4.json
Request failed: RPC response failure: {"error": "'dict' object has no attribute 'startswith'", "success": false, "traceback": "Traceback (most recent call last):\n  File \"chia\\rpc\\util.py\", line 84, in inner\n  File \"chia\\rpc\\wallet_rpc_api.py\", line 630, in push_tx\n  File \"chia\\util\\byte_types.py\", line 8, in hexstr_to_bytes\nAttributeError: 'dict' object has no attribute 'startswith'\n"}
```

**Comment by wjblanke** [comment] 2024-10-23 16:10
quex is this a regression? It looks like startswith expects a string

**Comment by Quexington** [comment] 2024-10-24 20:12
As far as I can tell, this is not a regression but it's not a bad idea to support the behavior regardless.

**Comment by emlowe** [comment] 2024-10-31 18:24
Thanks for the bug - Closing, this will be in the next release and is available in `main`

**Closed by emlowe** 2024-10-31 18:24 UTC
Labels: bug
