### ISSUE TITLE
Unable to retrieve unfinished temporary plots. This is a big problem in the event of a power outage or equipment problems. This should be corrected immediately.[BUG]

### ISSUE THREAD

**Issue by mitora1** [Chia-Network/chia-blockchain#2937] opened 2021-04-27 19:57 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by znsoftm** [comment] 2021-04-27 22:35
Nod.

**Comment by royimous** [comment] 2021-04-27 23:58
This is not a bug. Close this.

**Closed** 2021-04-28 06:13 UTC
Labels: bug
