### ISSUE TITLE
[Bug] Plotting Status not updating correctly

### ISSUE THREAD

**Issue by predawnia** [Chia-Network/chia-blockchain#14656] opened 2023-02-23 03:18 UTC
### What happened?

While plotting in GUI, the Plotting Status is not updating correctly. It only updates whenever you open the Log file to view the progress. Log file viewer also not updating. 

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment] 2023-02-23 19:58
Duplicate of #14639 "Status doesn't update" - Linking this bug to original & closing.

**Closed by MumfMeisterT** 2023-02-23 19:58 UTC
Labels: bug, duplicate, GUI, Windows, plotting, 1.7.0
