### ISSUE TITLE
[BUG] Wallet not syncing

### ISSUE THREAD

**Issue by AlexJofer** [Chia-Network/chia-blockchain#4838] opened 2021-05-13 18:14 UTC
Same issue every time!!!!!!!

**Comment by jmoe28** [comment] 2021-05-13 18:19
I am also experiencing sync issues for the past 2 days

**Comment by JamesDJchia** [comment] 2021-05-13 18:38
Same here while I have two Nodes (on separate PCs) running in DHCP mode. But one node is always well while the other lost sync several times even if I tried to restart the node and recover it. Can this Wallet software detects itself to revive sync?

**Comment by JamesDJchia** [comment] 2021-05-13 18:41
More comments. Is it possible to split the plotting processor independently from its farming processors?
The wallet software seems can NOT handle the plotting while doing farming at the same time.

**Comment by shobukle** [comment] 2021-05-13 21:42
> 
> 
> More comments. Is it possible to split the plotting processor independently from its farming processors?
> The wallet software seems can NOT handle well enough the plotting while doing farming at the same time.

You're better off running the plotting on another computer. I think that's what most people do.

**Comment by davidkoid** [comment] 2021-05-14 02:48
![image](https://user-images.githubusercontent.com/21050197/118214218-eb93d300-b4a1-11eb-8927-1e373897d4ce.png)
not sync for few days
try all
https://chia.keva.app/
not helping

**Comment by N00bl0rd999** [comment] 2021-05-14 08:31
> You're better off running the plotting on another computer. I think that's what most people do.

The sync problems have nothing to do with plotting but are caused by how crappy the wallet software is.
**It just does not sync properly**, even if you move plotting to another planet.

I have been trying this on multiple machines at different locations with different routers and different ISPs.

**The fault is the bad software and nothing else.**

**Comment by HudsonProdigy** [comment] 2021-05-16 00:48
if your clock is accurat, ports are open and still having issues. try closing gui. then right click and run as admin

**Comment by padik11** [comment] 2021-05-16 05:31
Uninstall the wallet and reinstall it. Make sure the temporary files are removed. It helped me.

**Comment by N00bl0rd999** [comment] 2021-05-16 07:36
> Make sure the temporary files on the ssd are removed.

Which exact file location would that be?

**Comment by padik11** [comment] 2021-05-16 08:02
This is the disk where you create temporary plots. Uninstall all chia app and reinstall.

**Comment by N00bl0rd999** [comment] 2021-05-16 08:04
> This is the disk where you create temporary plots
Ah ok, I always delete this after failed plots :)

> Uninstall all chia app and reinstall.
Will do that tomorrow when the sync is lost again after ISP reconnect. Thank you!

**Comment by davidkoid** [comment] 2021-05-16 10:20
solved
can't plot and farm at same time...
need plot complete then farm

**Comment by inigosola** [comment] 2021-05-16 10:33
> Uninstall the wallet and reinstall it. Make sure the temporary files on the ssd are removed. It helped me.

How uninstall the wallet? I have a ubuntu base linux distribution (Pop! OS)

**Comment by AlexJofer** [comment] 2021-05-16 10:33
I make a wallet update from 1.1.4 to 1.1.5 and until now is working well!!

**Comment by inigosola** [comment] 2021-05-16 11:41
> I make a wallet update from 1.1.4 to 1.1.5 and until now is working well!!

How do you do?

**Comment by AlexJofer** [comment] 2021-05-16 11:55
> > I make a wallet update from 1.1.4 to 1.1.5 and until now is working well!!
> 
> 
> 
> How do you do?


The easy way is download the last version of Chia Wallet and install

**Comment by jh442** [comment] 2021-05-16 23:57
> solved
> can't plot and farm at same time...
> need plot complete then farm

Is this really the case? The wallet will not sync if plotting on the same machine?

**Comment by dasbrow** [comment] 2021-05-17 01:06
> > solved
> > can't plot and farm at same time...
> > need plot complete then farm
> 
> Is this really the case? The wallet will not sync if plotting on the same machine?

This can't be the case my wallet is not synced on my main box that only farms and serves as master for my other systems.

**Comment by AlexJofer** [comment] 2021-05-17 07:05
On my machine I'm farming and plotting at same time without any issues until now!

**Comment by ryu007za** [comment] 2021-05-17 20:09
> > solved
> > can't plot and farm at same time...
> > need plot complete then farm
> 
> Is this really the case? The wallet will not sync if plotting on the same machine?

You can do both at the same time

**Comment by vmajor** [comment] 2021-05-19 08:37
I am running a command line Ubuntu 20.04 farm and my wallet is not syncing. The farm is hosted in a data center so this is not a consumer router problem, or a GUI problem. What can I do to fix this?

**Comment by avancia** [comment] 2021-05-22 08:12
Full node status is synced but my wallet is syncing !!

**Comment by LouisLoudogTrottier** [comment] 2021-06-05 19:21
Same issues,
My node is Synced,
My 1st wallet is stuck at height 92811 on testnet
My 2nd wallet is stuck at height 1760 on testnet
My 3rd wallet is Synced to the testnet

**Comment by mariano54** [comment] 2021-06-28 08:00
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:00 UTC
Labels: bug
