### ISSUE TITLE
[Bug] About the performance problem that the harvester cannot carry 177 hard disks on a single computer

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11357] opened 2022-04-28 19:26 UTC
### What happened?

Questions about the harvester
There are 177 hard disks on my computer, but when I add these hard disks to the harvester, the output of the harvester is abnormal, or even no output.
So I only added some hard disks and 50 hard disks to the harvester, and the harvester was normal.
So I judged that the harvester was not capable enough to carry 177 hard drives in a single PC.
Hope that the official verification optimizes the performance of the harvester.
Or the harvester can be improved so that the harvester can be opened more on the computer, so that each harvester is only responsible for harvesting a part of the hard disk.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by stefan-lange** [comment] 2022-04-28 20:18
you could use multiple harvesters with ~50 HDDs each as workaround. separate app folders, separate configs and start with `chia start -r harvester`

**Comment by 0X1231** [comment] 2022-04-29 08:36
> 您可以使用多个收割机，每个收割机约 50 个 HDD 作为解决方法。单独的应用程序文件夹，单独的配置并从`chia start -r harvester`

但是我在Windows server2022上面测试了，只能开一个收割机实例，无法打开多个收割机实例。请问您是怎么做到收割机多开的呢？

**Comment by emlowe** [comment] 2022-04-29 15:26
You create this same issue already - marking as a duplicate of #11225


we have profiled 300+ drives on a single harvester instance with consistent lookup times of 1.2 seconds. There are multiple improvements coming with commits already in main branch, but the workaround for now is to set plot loading frequency very high if you are not plotting anymore

see https://github.com/Chia-Network/chia-blockchain/issues/11225#issuecomment-1104532949

**Closed by emlowe** 2022-04-29 15:26 UTC
Labels: bug

**Comment by 0X1231** [comment] 2022-04-29 19:18
> 您已经创建了相同的问题 - 标记为[#11225的副本](https://github.com/Chia-Network/chia-blockchain/issues/11225)
> 
> 我们已经在单个收割机实例上分析了 300 多个驱动器，一致的查找时间为 1.2 秒。已经在主分支中提交了多项改进，但现在的解决方法是如果您不再绘图，则将绘图加载频率设置得非常高
> 
> 见[#11225（评论）](https://github.com/Chia-Network/chia-blockchain/issues/11225#issuecomment-1104532949)

Clearly the method you provided does not solve this problem!
Is there an update for the harvester planned in 1.3.5?
