### ISSUE TITLE
2022-11-18T10:19:19.984 data_layer asyncio                : ERROR    Unclosed client session

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#13952] opened 2022-11-18 09:47 UTC
### What happened?

2022-11-18T00:08:03.598 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.042993783950805664
2022-11-18T00:08:23.701 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024FB4913BB0>
2022-11-18T10:19:19.984 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D4E395D9D0>
2022-11-18T10:33:38.127 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T10:33:38.129 wallet wallet_server              : WARNING  Banning 64.231.206.34 for 120 seconds
2022-11-18T10:36:35.975 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025B555E1FD0>
2022-11-18T10:41:39.070 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024DDA8F1EB0>

### Version

17.0b2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-18T00:08:03.598 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.042993783950805664
2022-11-18T00:08:23.701 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024FB4913BB0>
2022-11-18T10:19:19.984 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D4E395D9D0>
2022-11-18T10:33:38.127 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T10:33:38.129 wallet wallet_server              : WARNING  Banning 64.231.206.34 for 120 seconds
2022-11-18T10:36:35.975 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025B555E1FD0>
2022-11-18T10:41:39.070 data_layer asyncio                : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024DDA8F1EB0>
```

**Comment by emlowe** [comment] 2023-01-09 21:13
I'm not able to reproduce this issue and with just the available log data I'm not able to discern what steps might be taken to resolve this. This error may entirely be benign depending on context.

If you aren't using data_layer you can disable this from the GUI settings panel.

If you continue to see this, please reply with more details on when you see this error, and what you are doing when it happens, and perhaps include more of the log file.

Closing at this time - will reopen if more information becomes available

**Closed by emlowe** 2023-01-09 21:13 UTC
Labels: bug, GUI, Windows, data, 1.7.0-b1
