### ISSUE TITLE
full node is synced but wallet is stuck at syncing[BUG]

### ISSUE THREAD

**Issue by alx0317** [Chia-Network/chia-blockchain#5802] opened 2021-05-22 16:53 UTC
**Describe the bug**
full node is synced but wallet never get synced like it show syncing forever

**To Reproduce**

1. Go to 'wallet'
2. stautus : syncing

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- OS Version/Flavor: OS build : 19042.985
- CPU: Intel i7 5820K

**Additional context**

**Comment by vgadfly** [comment] 2021-05-22 22:05
Same. Log is full of errors:

```
2021-05-22T22:01:03.307 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 0-32
2021-05-22T22:01:03.309 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 
8444}
2021-05-22T22:01:03.520 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: e1c058df509f
d1ad41ca1b2bb63873997d254f50ed8105d98232948982e332cb
2021-05-22T22:01:03.521 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'por
t': 8444}
2021-05-22T22:01:03.523 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned
 no response Traceback (most recent call last):
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 605, in _sync
    peer, uint32(start_height), uint32(end_height), None if advanced_peak else fork_height
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 643, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response

2021-05-22T22:01:03.524 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0
-32. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 515, in sync_job
    await self._sync()
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 614, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32

2021-05-22T22:01:03.524 wallet chia.wallet.wallet_node    : INFO     Loop end in sync job

```

**Comment by alx0317** [comment] 2021-05-22 22:27
i reinstall the chia gui 1.1.6, now all done already. synced

**Comment by vgadfly** [comment] 2021-05-23 13:16
Changed localhost to ${HOST_IP} in config and wallet started syncing

**Comment by wht3** [comment] 2021-05-23 15:49
> Changed localhost to ${HOST_IP} in config and wallet started syncing

Where can i find that config?

**Comment by caminotr** [comment] 2021-05-23 15:52
> Changed localhost to ${HOST_IP} in config and wallet started syncing

What you mean? my Ip?

**Comment by vgadfly** [comment] 2021-05-23 15:55
Jail ip in my case. I run chia in jail.

**Comment by wht3** [comment] 2021-05-23 16:18
> Jail ip in my case. I run chia in jail.

External IP or default gateway?

**Comment by wht3** [comment] 2021-05-23 17:03
Update: tried a clean install: 
uninstalled chia
deleted c:/users/user/.chia
deleted c:/users/user/AppData/local/chia-blockchain
deleted c:/users/user/AppData/Roaming/Chia Blockchain

After that, wallet was syncing. PS: already tried this like 10 times this week and this is the first time it worked.
But then i copied my already synced full node file to c:/users/user/.chia/mainnet/db so i wouldnt have to download it all again, and my wallet never synced again. Maybe my full node file is buggy??

Did another clean install and now i'm gonna wait for it all to sync again, at last it syncs after 4 days.

**Comment by k3a** [comment] 2021-06-02 00:12
vgadfly: I have seen similar errors logged, it was constantly connecting and disconnecting my wallet from the full node. I fixed it by deleting the config directory at the wallet side and doing `chia init` again (to get fresh TLS certs for the wallet node). Similarly to #5965. Maybe worth a try (but better backup config and other files just in case before trying init again).

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
