### ISSUE TITLE
Transactions Issue

### ISSUE THREAD

**Issue by dobromir2** [Chia-Network/chia-blockchain#6169] opened 2021-05-28 12:21 UTC
Hi guys,
 Here are few problems I found using Chia Wallet : 

- Fees??? This is like shooting in the darkness. Please make it clear/automatic like Monero as soon as possible. 
- I made simple transaction and is staying with status Outgooing for 9 hours till now. What should I do to make it go through ?

Tranasactions are the basics - I dont know why it is so complicated right now. Please after the pools are running focus on the wallet functions. 

Thank you,
Dobromir

**Comment by dobromir2** [comment] 2021-05-28 12:50
update - transaction just went trough, so the issue is changed from not going through to - super slow.

**Comment by dobromir2** [comment] 2021-05-28 12:57
update 2 - just made 2nd transaction and it went trough immediatly.

**Comment by BonTron1** [comment] 2021-05-28 15:36
Great, if the issue is resolved, please close it.

**Comment by dobromir2** [comment] 2021-05-28 21:04
Thank you BonTron1,
 What about Fees ? 
How one can know what about has to be used in Fees ? 

Tnx,
D

**Closed** 2021-05-29 22:01 UTC
