### ISSUE TITLE
[BUG] Self Pooling NFT pool does not update plots in GUI

### ISSUE THREAD

**Issue by DrakeFS** [Chia-Network/chia-blockchain#7277] opened 2021-07-09 08:36 UTC
Self Pooling NFT pool does not update plots in GUI.  Plotted 2 plots so far for self pooling and once they finished I had to swap to another key to see the pools plot total update.  Not sure if this is a graphical issue or if the plots are not being farmed until I force the pool to update.

**To Reproduce**

Plot to self pool from GUI (tried via using the pools "Add a Plot" and manually setting up the plot.  Testing CLI now.

**Expected behavior**

When a Plot finishes, the pool reflects that a new plot has been added to the pool by ways of updating the number of plots in said pool.

**Desktop**
Windows 10
i5-6600k 4 Core @ 3.4GHz
RAM 16GB @ 1066.7 MHz 

**Additional context**

I have another pool (maxiopool) with 4 plots and it seemed to update as soon as the plots where finished.  This pool is on a different private key though.

**Comment by mbaric1** [comment] 2021-07-09 11:04
See #7262 and Chia-Network/chia-blockchain-gui#487

**Comment by emlowe** [comment] 2021-07-12 15:34
Duplicate of #7262

**Closed by emlowe** 2021-07-12 15:34 UTC
Labels: bug
