### ISSUE TITLE
Chia Gui 1.2.0-1.2.1 doesn't update number of portable plots in the pool tab[BUG]

### ISSUE THREAD

**Issue by bcredford** [Chia-Network/chia-blockchain#7442] opened 2021-07-13 09:59 UTC
**Describe the bug**
Chia gui wallet version 1.2.0-1.2.1 does not update the number of portable plots from mapped plot directories automatically. Shutting down and restarting the wallet, or selecting the keys tab and reentering the wallet by selecting the corresponding fingerprint to reenter the wallet, then selecting pools again will update the number of portable plots in mapped directories.

**To Reproduce**
1. Open chia wallet and select the fingerprint that is used for pooling.
2. click on the pools tab.
3. use a plotting software to create portable plots.
4. observe that while finished plots are copied into mapped directories, the chia gui wallet, plots tab does not update the number of portable plots.
5. exit or restart wallet and reenter/restart wallet and select fingerprint and pools tab to force chia wallet to manually update number of portable plots in mapped directories.

**Expected behavior**
Chia gui wallet should automatically update the number of portable plots as they are copied into mapped plot directories.

**Screenshots**

- OS: Windows 10 and all Linux builds
- CPU: amd 5950x and intel i9

**Comment by brasrox** [comment] 2021-07-13 10:06
![image](https://user-images.githubusercontent.com/21345109/125433668-49ff6010-cff6-483e-ade3-b5e5f5c18e23.png)

same

**Comment by emlowe** [comment] 2021-07-14 19:05
Duplicate of #7262

**Closed by emlowe** 2021-07-14 19:05 UTC
Labels: bug
