### ISSUE TITLE
[BUG] so what is going on  while  starting the app? 

### ISSUE THREAD

**Issue by jonny77** [Chia-Network/chia-blockchain#2662] opened 2021-04-25 04:38 UTC
![image](https://user-images.githubusercontent.com/1962170/115980967-1f768980-a5c3-11eb-9d8f-02a2433243d4.png)

**Comment by lipalong** [comment] 2021-04-28 23:39
Duplicate of #2692 – see the comments there.
Also, we've made the wording for this error more clear in the next release.

**Closed by lipalong** 2021-04-28 23:39 UTC
Labels: bug
