### ISSUE TITLE
[Bug]  nft mints never get included in mempool

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#14351] opened 2023-01-16 09:09 UTC
### What happened?

since a couple of months, I have the issue that NFT Mints never get executed and get stuck.

- I make sure to set a fee high enough (10k mojos)
- I make sure, the client shows the pending amount and the wallet shows the transaction:
```
chia wallet get_transactions
Transaction 734e31fabe45eff5d130df3d7186070f4b130cc3e051a26f88911c489d97903e
Status: Pending
Amount sent: 1E-12 TXCH
To address: txch1alc82gjf2psvqehkdue2es480caruum6e296afx35e82fnwp8k5shty4cp
Created at: 2023-01-15 22:26:10*
```
- I check the mempool with `get_all_mempool_items`
```
"{\"mempool_items\": {}, \"success\": true}"
```

the particular example from above is from testnet. the transaction id could not be found in the logs

I have the issue both, on testnet and mainnet.

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/10424159/debug.log)

**Comment by MumfMeisterT** [comment] 2023-01-19 21:10
In your log it's showing that your fee is too low. The mempool was full at the time, so you will need to increase your fee or wait for the pool to calm down.
Please refer to this article on txn fees. https://devs.chia.net/guides/nft-intro#clvm-cost

**Comment by emlowe** [comment] 2023-01-19 21:14
When you mint you should keep an eye on your log - if you see this `INVALID_FEE_TOO_CLOSE_TO_ZERO` - this means at that time the mempool is full, and you need to specify a much larger fee to bump someone out and get your transaction in. For this, you need to remove this transaction (delete_unconfirmed_transaactions) and resubmit following the chart here: https://devs.chia.net/guides/nft-intro#clvm-cost

However, the wallet does have a built-in retry feature and it will retry to submit this transaction again for you. At some point, it may go through when the mempool is no longer full.

**Comment by KryptomineCH** [comment] 2023-01-24 21:12
I dont think its the fee. i've had this discussion already:

![image](https://user-images.githubusercontent.com/117320700/214416927-fae93753-1aa5-4bb5-b95c-df2cc33d4bcb.png)
its been 4 hours and the fee was 10k mojos

**Comment by KryptomineCH** [comment] 2023-01-24 21:17
Can you clarify the fee amount listed in the table? It appears to be very high, and I haven't seen this amount mentioned elsewhere. Also, is there a way to determine when the mempool is full using the RPC interface, specifically through a wallet rather than a full node?

**Comment by emlowe** [comment] 2023-01-24 23:42
When the mempool is full, you need to add a fee that is high enough to remove some other transaction from the mempool. Currently, this is set at 5mojo per clvm COST of the spend bundle. Since the clvm cost of a NFT mint is quite high, it results in the fees in the table. When you see `INVALID_FEE_TOO_CLOSE_TO_ZERO` this means the mempool is full, and your fee was insufficient to get into the mempool. There is no wallet RPC to find out the state of the mempool

**Comment by KryptomineCH** [comment] 2023-01-26 14:23
another test, this time with the insane fee of 620 mil mojos.
Result were 7 transactions which all completed at once. But only one nft out of the 7 got minted:
![image](https://user-images.githubusercontent.com/117320700/214857429-3c2642c8-05c7-4867-8663-6547b21ee2dc.png)

The log shows interesting etries:
```
2023-01-26T14:46:39.126 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x8af545304b929f45e391ca6a4754f29ddec85b13b6b52f33762e2a8b9674abe8'}
2023-01-26T14:46:39.143 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x8af545304b929f45e391ca6a4754f29ddec85b13b6b52f33762e2a8b9674abe8'}
2023-01-26T14:46:39.293 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x8af545304b929f45e391ca6a4754f29ddec85b13b6b52f33762e2a8b9674abe8'}
2023-01-26T14:46:39.428 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x8af545304b929f45e391ca6a4754f29ddec85b13b6b52f33762e2a8b9674abe8'}
2023-01-26T14:46:39.662 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x8af545304b929f45e391ca6a4754f29ddec85b13b6b52f33762e2a8b9674abe8'}
```

what struck me was that the transaction ids were all the same.
I verified that the Spendbundles I received from the node from my RPCs were different but there seems to be an error:
The first coin which appears to resemble the resulting nft differs (im trying to mint different nfts) BUT the parent coins are the same! I conclude that the wallet attempts double spends and the fee is not (the primary) issue.
![image](https://user-images.githubusercontent.com/117320700/214859360-c9e27d88-4f2b-41d4-b114-fbfcdd7fce51.png)

[CryptoCrests_Potion_of_Ice-9 - Copy.txt](https://github.com/Chia-Network/chia-blockchain/files/10510097/CryptoCrests_Potion_of_Ice-9.-.Copy.txt)
[CryptoCrests_Potion_of_Ice-10 - Copy.txt](https://github.com/Chia-Network/chia-blockchain/files/10510098/CryptoCrests_Potion_of_Ice-10.-.Copy.txt)

For now im trying to implement a timeout of 0.5 seconds in between each mint. If that does not help, I may have to go back to minting one nft at a time and verifying that minting is complete

**Comment by KryptomineCH** [comment] 2023-01-26 15:25
final attempt for now, this time with a 0.5 second delay between pushing transactions.
It does not seem to be a fee issue:
![image](https://user-images.githubusercontent.com/117320700/214873969-8c1e8b21-3da2-4c35-adbf-4d929e9c32b0.png)

The log file does not seem to contain relevant info
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/10510639/debug.log)

The spend bundles still seem to have some duplicate info so I believe there may still be some duplicate spends:
![image](https://user-images.githubusercontent.com/117320700/214875209-098793c8-ad72-4100-b07c-742f3dad2017.png)

The final test I do is going back to fee 10k mojos and executing one single mint at a time.
Assuming 1 mint takes up to 1 minute, that would require 166 hours or one full week of minting 24 hours, never falling out of sync for a collection of 10k images. likely its gonna take a lot longer.

**Comment by KryptomineCH** [comment] 2023-01-26 15:50
Minting one nft at a time works as expected. 
![image](https://user-images.githubusercontent.com/117320700/214880843-35d529ce-01fd-427c-873c-0f0d49da4d8a.png)

I rule out a fee issue. 

I dont fully understand the issue Labels. As far As I know, the gui has no capability to mint. 
I only use it to quickly verify if the mint was successful.

I have the same issue on windows ( wallet only, mainnet ) as well as on ubuntu headless server (cli, full node, testnet)
I'm minting with an rpc request against the wallet node. The rpc files have not been changed throughout the testruns (except for the fee)

I have attached a copy of the rpc but im quite certain there is no issue with it:
[CryptoCrests_Potion_of_Ice.rpc.txt](https://github.com/Chia-Network/chia-blockchain/files/10510930/CryptoCrests_Potion_of_Ice.rpc.txt)

**Comment by cameroncooper** [comment] 2023-01-26 19:23
Minting more than one NFT with your DID per block is going to give you trouble, because each mint requires a spend of your DID. If you want to mint multiple NFTs per block, you really should be using the bulk mint tool.

**Comment by KryptomineCH** [comment] 2023-01-27 08:00
okay, for the bulk minting tool, I need some clarifications, the documentation is not fully clear to me:
- `target_address_list` what happens if multiple addresses are given?
- `mint_number_start` - what is this used for?
- `mint_total` i guess this is for minting the same nft multiple times
- `xch_coin_list` I guess I normally leave that empty
- `xch_change_target` is this relevant? In the provided example of the documentation, it does not seem like an adrress. I guess if this is left empty, the change is received by the farmernode which mints the block
- `did_coin_dict` what is this used for? It seems like an object but the documentation does not specify further
- `did_lineage_parent_hex` what does "Needed for bulk minting when the coin will be created in the future" mean?
- `mint_from_did` yes, I kow what this does. But I want to mint from did. In the single rpc, I can specify did-id. Bulk mint seems to use  `did_lineage_parent_hex`  && `did_coin_dict` instead. How Do I mint from a did? Do I have to set it after the fact with `nft_set_did_bulk`?

**Comment by MumfMeisterT** [comment] 2023-02-02 20:13
I am not sure which documentation you are using, but please refer to the documentation here and let us know if you still have issues. Thanks. 
https://docs.chia.net/guides/nft-bulk-mint/?_highlight=bulk

**Comment by emlowe** [comment] 2023-03-23 18:40
closing issue - please feel free to comment or re-open if there are further details

**Closed by emlowe** 2023-03-23 18:40 UTC
Labels: GUI, Windows, NFT, 1.6.2
