### ISSUE TITLE
Problem of spendable balance after creation of offer in xch

### ISSUE THREAD

**Issue by Jones1982** [Chia-Network/chia-blockchain#16801] opened 2023-11-09 10:37 UTC
### What happened?

With an active and spendable balance of 7 Chia, I created an offer (uploaded on dexie) of 1 xch > * usdsc, the spendable total reported in the gui went from 7 to 0, while everything available went to the "Balance item total pending", preventing me from making further offers with the XCH token, until the offer is accepted or cancelled.

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by KryptomineCH** [comment] 2023-11-15 12:19
The issue is that your wallet has several Coins in it. Your coin likely has a value of 7 xch. 

now you create an offer where you have to reseve the coin. So your whole balance is locked.

what you can try:
1. cancel the offer
2. send half the amount to yourself

now you have 2 coins with a value of 3.5 each in your wallet and can create 2 offers.

if you need more than 2 coins:
Use the coin split from the commandline, or, if this is easier for you, send the amount to another wallet you create and then send eg. 1 chia bit by bit to your main wallet. That way you have 7 coins with 1 chia each.

When yol have your wallet for longer, you will have more, smaller coins which the wallet can piece together to make your offers.

**Comment by wjblanke** [comment] 2023-11-15 17:28
Closing as per above. Thanks KryptomineCH !!

**Closed by wjblanke** 2023-11-15 17:28 UTC
Labels: bug
