### ISSUE TITLE
[BUG] Harvester crashes loading more than 256 paths.

### ISSUE THREAD

**Issue by kiwihaitch** [Chia-Network/chia-blockchain#858] opened 2021-02-07 20:51 UTC
**Describe the bug**
After loading > 256 paths the harvester throws an exceptions, then dies after completing loading the paths.

**To Reproduce**
Start harvester with 255 paths, harvester loads and begins farming. Add another path to the config.yaml, after 2 minutes the path is added and farming resumes. Add 257th path, harvester loads the files, throws exception and dies.

**Expected behavior**
Harvester should load the 257th and greater path and continue.

**Screenshots**
debug.log attached. At 14:33:42.259 is when path 257 is being processed.

**Desktop (please complete the following information):**
- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: TR 3990x
[Harvester-debug.zip](https://github.com/Chia-Network/chia-blockchain/files/5939981/Harvester-debug.zip)

**Additional context**

**Comment by hoffmang9** [comment] 2021-02-07 20:55
And just for the record... 257 plot directories... you animal!

**Comment by mariano54** [comment] 2021-02-08 11:07
Are you sure it's the plot directories and not the number of plots? From the logs it looks like the data size of the plots list is overwhelming the rpc server

**Comment by loppefaaret** [comment] 2021-02-08 11:21
back when we were chasing the total number of plots - last wall was at 16307 / 16317 with small k23...

**Comment by kiwihaitch** [comment] 2021-02-08 12:51
Not 100% certain it's number of paths and not number of plots, but with it repeatedly occuring when the number of paths exceeded the upper bound of a byte sized variable it was the obvious conclusion. I can do some additional testing today to determine if it's paths or plots.

**Comment by mariano54** [comment] 2021-02-08 13:11
My suspicion is that the websocket message limit is not getting set correctly, so it's at 4MB instead of 50MB. ill investigate

**Comment by mariano54** [comment] 2021-02-21 12:09
Potentially fixed by https://github.com/Chia-Network/chia-blockchain/pull/986

**Comment by mariano54** [comment] 2021-02-22 11:19
This has not been fixed yet. This happens even when loading just a few files (as soon as you pass that 257 directories or 16k files).  However I was not able to replicate it locally yet.

**Comment by kiwihaitch** [comment] 2021-02-25 21:39
Issue still occurs with rc3.dev77

```15:32:07.766 harvester src.plotting.plot_tools : INFO     Found plot /home/haitch/local/sm11/06/plot-k32-2020-10-14-18-01-6497f010095541a1d51fd647e0496d90cd3e98906d6f63e9087f785763420311.plot of size 32
15:32:07.801 harvester src.plotting.plot_tools : INFO     Found plot /home/haitch/local/sm11/06/plot-k32-2020-12-19-13-28-8fc61292884de19c28f85a6e70ce4c87b09ab1641e6caa269770a82720f93d4f.plot of size 32
15:32:07.838 harvester src.plotting.plot_tools : INFO     Found plot /home/haitch/local/sm11/06/plot-k32-2020-12-22-00-50-66ae19557e73ca96de0b9ad73e4cb1bf28719a159d94d97d98b0a49ae440be71.plot of size 32
15:32:15.877 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/haitch/chia-blockchain/src/daemon/server.py", line 149, in safe_handle
    async for message in websocket:
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/haitch/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by hoffmang9** [comment] 2021-03-08 08:59
Confirmed fixed in https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0rc5

**Closed by hoffmang9** 2021-03-08 08:59 UTC
Labels: bug
