### ISSUE TITLE
[BUG] endless connecting to wallet, or circles of loading full node status, blocks and connections

### ISSUE THREAD

**Issue by 85256638** [Chia-Network/chia-blockchain#6923] opened 2021-06-22 22:32 UTC
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

![image](https://user-images.githubusercontent.com/3270742/123007944-efc0e380-d3b1-11eb-8337-222281a6c0cf.png)

wake up folks, surely Bram can pay you enough salary with his 21M pre-mined even with the current Chia price.

**Comment by 85256638** [comment] 2021-06-23 00:11
![image](https://user-images.githubusercontent.com/3270742/123015297-f0607680-d3bf-11eb-8c25-d66eddd91fb9.png)
 
stupid error, has been around on github for ages.

**Comment by joelrb** [comment] 2021-06-23 03:25
The only stupid solution is to delete the db... then  you have to wait for days again to sync... copying the db from another fully sync machine doesn't work.

**Comment by Fistrake** [comment] 2021-06-23 19:29
![wallet_bug](https://user-images.githubusercontent.com/35198558/123156664-d4191400-d469-11eb-87a3-5018cb473908.jpg)

So my electricity runoff today for 5 mins and when I started everything this bug came up...endless running connection to wallet with maximizing my RAM usage to 99% - I had to uninstall chia and delete DB to get it fix.

**Comment by 85256638** [comment] 2021-06-23 19:31
> ![wallet_bug](https://user-images.githubusercontent.com/35198558/123156664-d4191400-d469-11eb-87a3-5018cb473908.jpg)
> 
> So my electricity runoff today for 5 mins and when I started everything this bug came up...endless running connection to wallet with maximizing my RAM usage to 99% - I had to uninstall chia and delete DB to get it fix.

this is a really stupid bug which has been existing for ages... god knows what the devs are doing

**Comment by mariano54** [comment] 2021-06-28 07:38
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check that issue

**Closed by mariano54** 2021-06-28 07:38 UTC
Labels: bug
