### ISSUE TITLE
Help analyze log errors

### ISSUE THREAD

**Issue by huangmeibao** [Chia-Network/chia-blockchain#1444] opened 2021-03-23 04:35 UTC
My system is Windows10, I haven't dug a coin in four days, so I checked the log:

09:14:22.769 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x104b7df296a7d8a113031b9fb2a1c81eda6d04916bbdbce51a5706864801021e',
 'index_from_challenge': 44,
 'last_rc_infusion': '0x2efcce0d7b451d87707d3556d0edd55f7e414a03594c81a52387176b8dbcf65c'}
09:14:24.114 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x104b7df296a7d8a113031b9fb2a1c81eda6d04916bbdbce51a5706864801021e',
 'index_from_challenge': 44,
 'last_rc_infusion': '0x2efcce0d7b451d87707d3556d0edd55f7e414a03594c81a52387176b8dbcf65c'}
11:37:33.592 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

12:16:09.920 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 514, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

12:16:10.724 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 514, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

12:18:02.037 full_node full_node_server        : ERROR    Exception: Failed to fetch block 18350 from {'host': '167.114.67.242', 'port': 8444}, timed out, {'host': '167.114.67.242', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 344, in new_peak
  File "src\full_node\full_node.py", line 293, in short_sync_backtrack
  File "src\full_node\full_node.py", line 278, in short_sync_backtrack
ValueError: Failed to fetch block 18350 from {'host': '167.114.67.242', 'port': 8444}, timed out

12:18:02.070 full_node full_node_server        : ERROR    Exception: Failed to fetch block 18350 from {'host': '167.114.67.242', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '167.114.67.242', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 514, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "src\server\server.py", line 512, in wrapped_coroutine
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 344, in new_peak
  File "src\full_node\full_node.py", line 293, in short_sync_backtrack
  File "src\full_node\full_node.py", line 278, in short_sync_backtrack
ValueError: Failed to fetch block 18350 from {'host': '167.114.67.242', 'port': 8444}, timed out

12:18:35.361 full_node full_node_server        : WARNING  Banning 167.114.67.242 for 10 seconds
12:18:35.394 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at src\server\server.py:477> exception=CancelledError()>
concurrent.futures._base.CancelledError

I hope you can help me to see what the problem is and whether it affects the issuance of coins. Thank you very much

**Comment by bobochi** [comment] 2021-03-23 14:38
yeah, i'm in the same boat.  no coins dug and seeing similar messages.  I'm using Windows 10 as well.  I wanted to wait a few days before raising a red flag, but glad i'm not the only one seeing the error and hope it turns out to be a non-issue.  thanks in advance!

22:09:16.325 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

22:41:52.350 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '50.40.186.82', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

23:09:10.871 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '99.184.71.83', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

00:22:40.005 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.105.224.24', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

00:59:38.815 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x4c88096cfcc638984a914dfc859f8fc9d3f560b2add19acd72431b1c4a018010',
 'index_from_challenge': 63,
 'last_rc_infusion': '0xe3a29c7fa1e075b757a1e87b65af8295e10cc066679610dfb211c92806f767b5'}
02:22:49.885 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '91.82.82.40', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

02:59:14.345 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x8b2b2b7097677b0c0bd4beac5afaf6247e9d1066d2e8d3690d1950c80c405b92',
 'index_from_challenge': 62,
 'last_rc_infusion': '0xdc2d52de0982b78ba637dd4530719f161ec303123f0bd8272917ee4c3fffc126'}
02:59:14.399 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x8b2b2b7097677b0c0bd4beac5afaf6247e9d1066d2e8d3690d1950c80c405b92',
 'index_from_challenge': 63,
 'last_rc_infusion': '0xdc2d52de0982b78ba637dd4530719f161ec303123f0bd8272917ee4c3fffc126'}
03:39:02.505 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x63bc80048c1d7b77ee491bfdf45c7fa909cd26fe5a50f9c52f9efd709550a8b6',
 'index_from_challenge': 63,
 'last_rc_infusion': '0xd78a969db6176758d594eea97a0122f585abf43e3014d264320fd230e00c68d1'}
05:00:42.300 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '80.201.122.69', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

05:08:30.229 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x60bb141e83042c3a865d6a175ea633e838b86e8a9ffe56648091d43016d5dab4',
 'index_from_challenge': 60,
 'last_rc_infusion': '0x7d116d66512f97c896d1717f618e5c69d83fb77ccb0935693f7faf5a3389e465'}
05:08:30.276 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x60bb141e83042c3a865d6a175ea633e838b86e8a9ffe56648091d43016d5dab4',
 'index_from_challenge': 61,
 'last_rc_infusion': '0x7d116d66512f97c896d1717f618e5c69d83fb77ccb0935693f7faf5a3389e465'}
05:08:30.323 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x60bb141e83042c3a865d6a175ea633e838b86e8a9ffe56648091d43016d5dab4',
 'index_from_challenge': 62,
 'last_rc_infusion': '0x7d116d66512f97c896d1717f618e5c69d83fb77ccb0935693f7faf5a3389e465'}
05:08:30.354 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x60bb141e83042c3a865d6a175ea633e838b86e8a9ffe56648091d43016d5dab4',
 'index_from_challenge': 63,
 'last_rc_infusion': '0x7d116d66512f97c896d1717f618e5c69d83fb77ccb0935693f7faf5a3389e465'}
06:45:07.909 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '141.126.212.137', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

08:06:03.447 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '46.8.178.111', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 481, in api_call
  File "src\server\node_discovery.py", line 128, in update_peer_timestamp_on_message
  File "src\server\address_manager.py", line 649, in connect
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

**Comment by bobochi** [comment] 2021-03-23 15:48
these messages also just appeared, still no XCH.

11:35:57.191 full_node full_node_server        : ERROR    Exception: Failed to fetch block 20622 from {'host': '73.12.76.131', 'port': 8444}, timed out, {'host': '73.12.76.131', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 344, in new_peak
  File "src\full_node\full_node.py", line 293, in short_sync_backtrack
  File "src\full_node\full_node.py", line 278, in short_sync_backtrack
ValueError: Failed to fetch block 20622 from {'host': '73.12.76.131', 'port': 8444}, timed out

11:35:57.217 full_node full_node_server        : ERROR    Exception: Failed to fetch block 20622 from {'host': '73.12.76.131', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '73.12.76.131', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 514, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "src\server\server.py", line 512, in wrapped_coroutine
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 344, in new_peak
  File "src\full_node\full_node.py", line 293, in short_sync_backtrack
  File "src\full_node\full_node.py", line 278, in short_sync_backtrack
ValueError: Failed to fetch block 20622 from {'host': '73.12.76.131', 'port': 8444}, timed out

**Comment by mariano54** [comment] 2021-03-24 06:57
There is nothing wrong with these logs. Please check the following to ensure you are farming:
1. Full node is synced `chia show -s -c`
2. Wallet is synced `chia wallet show`
3. All plots show up on farmer: `chia farm summary`
4. Challenges update every 9 seconds: `chia farm challenges`

Also consider restarting everything:
`chia stop all -d`
`chia start farmer`

**Closed by mariano54** 2021-03-24 06:57 UTC
Labels: bug

**Comment by bobochi** [comment] 2021-03-24 10:41
ah.  good to hear that there's nothing wrong. thanks for the peace of mind, Mariano!  sounds like i just need to be more patient.  cheers!

**Comment by bobochi** [comment] 2021-03-24 10:47
just for one last piece of mind, i didn't include this debug log output, but hopefully it's also not an issue.  can you confirm?  thanks!

00:35:33.119 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 02eed21fd898b4d30ec59a47ab5190d4539a93ffcf753ef34d8951461c49362f
00:35:33.154 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 02eed21fd898b4d30ec59a47ab5190d4539a93ffcf753ef34d8951461c49362f
00:35:33.216 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 02eed21fd898b4d30ec59a47ab5190d4539a93ffcf753ef34d8951461c49362f
00:35:33.232 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 02eed21fd898b4d30ec59a47ab5190d4539a93ffcf753ef34d8951461c49362f
01:15:40.274 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 696b2dbef615468c7cb639594b8e983a236383fd74f2edf6d751600b78ad197d

**Comment by Adam0148** [comment] 2021-04-11 16:28
im getting this on start :
`15:33:49.384 wallet src.wallet.wallet_node     : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
15:33:53.848 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<FullNode.initialize_weight_proof() done, defined at src\full_node\full_node.py:145> exception=AttributeError("'NoneType' object has no attribute 'header_hash'")>
Traceback (most recent call last):
  File "src\full_node\full_node.py", line 147, in initialize_weight_proof
AttributeError: 'NoneType' object has no attribute 'header_hash'
15:33:59.665 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "src\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 989, in create_connection
  File "asyncio\base_events.py", line 1017, in _create_connection_transport
concurrent.futures._base.CancelledError`

many of this kind of Errors :
`20:26:35.599 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\adam0\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_4141743163.sqlite
00:42:20.979 full_node full_node_server        : WARNING  Cannot write to closing transport 175.27.188.60
00:49:12.125 full_node full_node_server        : ERROR    Exception: Failed to fetch block 111258 from {'host': '98.38.122.149', 'port': 8444}, wrong type <class 'src.util.streamable.RequestBlock'>, {'host': '98.38.122.149', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 336, in new_peak
  File "src\full_node\full_node.py", line 285, in short_sync_backtrack
  File "src\full_node\full_node.py", line 273, in short_sync_backtrack
ValueError: Failed to fetch block 111258 from {'host': '98.38.122.149', 'port': 8444}, wrong type <class 'src.util.streamable.RequestBlock'>

00:49:12.129 full_node full_node_server        : ERROR    Exception: Failed to fetch block 111258 from {'host': '98.38.122.149', 'port': 8444}, wrong type <class 'src.util.streamable.RequestBlock'> <class 'ValueError'>, closing connection {'host': '98.38.122.149', 'port': 8444}. Traceback (most recent call last):
  File "src\server\server.py", line 514, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "src\server\server.py", line 512, in wrapped_coroutine
  File "src\server\server.py", line 505, in wrapped_coroutine
  File "src\full_node\full_node_api.py", line 94, in new_peak
  File "src\full_node\full_node.py", line 336, in new_peak
  File "src\full_node\full_node.py", line 285, in short_sync_backtrack
  File "src\full_node\full_node.py", line 273, in short_sync_backtrack
ValueError: Failed to fetch block 111258 from {'host': '98.38.122.149', 'port': 8444}, wrong type <class 'src.util.streamable.RequestBlock'>

00:49:12.965 full_node full_node_server        : WARNING  Banning 98.38.122.149 for 10 seconds
00:49:12.967 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at src\server\server.py:477> exception=CancelledError()>
concurrent.futures._base.CancelledError
15:44:59.313 full_node full_node_server        : WARNING  Cannot write to closing transport 24.96.161.113`

**Comment by VolodymyrDit** [comment] 2021-04-27 20:16
Hey there, I know that this ticket is closed, but would ask anyway.


> There is nothing wrong with these logs. Please check the following to ensure you are farming:
> 
> 1. Full node is synced `chia show -s -c`
> 2. Wallet is synced `chia wallet show`
> 3. All plots show up on farmer: `chia farm summary`
> 4. Challenges update every 9 seconds: `chia farm challenges`
> 
> Also consider restarting everything:
> `chia stop all -d`
> `chia start farmer`

Greetings, I know that this bug is in closed state, but would ask anyway.
I've used  `chia wallet show` and got an error:
Exception from 'wallet' {'error': "'dict' object has no attribute 'get_confirmed_balance_for_wallet'", 'success': False}
Have you seen this before?
