### ISSUE TITLE
Meu Farmer nao inicia e fica apenas carregando[BUG]

### ISSUE THREAD

**Issue by marcostraderminer** [Chia-Network/chia-blockchain#6890] opened 2021-06-21 17:11 UTC
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

Boa tarde 

Meu iniciador nao inicia a sincronização e fica apenas carregando, ja reiniciei o computador e nada.

**Comment by mariano54** [comment] 2021-06-28 07:45
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check that issue

**Closed by mariano54** 2021-06-28 07:45 UTC
Labels: bug
