### ISSUE TITLE
NFTs not picked up by second Full Node

### ISSUE THREAD

**Issue by panagiotisverras** [Chia-Network/chia-blockchain#7138] opened 2021-07-06 15:36 UTC
**Describe the bug**
NTF created on one machine is not picked up on another and when manually adding it to the config file I receive the warning "This plot NFT is assigned to a different key. You can still create plots for this plot NFT, but you can not make changes"

both clients are definitively on the same key.

**To Reproduce**
The exact sequence of how this happened. (all in windows)
- Full Node running 1.1.7 on main machine. (Client A) harvesting regular plots
- New installation on secondary machine of 1.1.795 (Client B)
- Client B Init with seed
- Client B, Joined pool, created NFT.
- Client B, build some plots, pooling all good.
- Client A, upgrade to 1.1.795
- Client A, No pools showed up, even after one hour and ensuring everything is synced.
- Client A, Mistakenly thinking that trying to join the pool again will pick up the NFT. it didn't, created new NFT.
- Client A, Original NFT still not showing up
- Client B, Newly created NFT from Client A shows up. (at this stage i was really confused)
- Client A, trying to cancel the second NTF... created a third NTF of self pooling... (here there is possible another bug)
- Client A now showing an NFT with status Invalid State, and another one of Self Pooling
- Client B now showing all 3.
- Seeing that this is getting me nowhere upgraded both to 1.1.797, seeing no change at all.
- Client A, edited the config.yaml to add manually the first NFT.
- Client A, showing the first NFT with the message "This plot NFT is assigned to a different key. You can still create plots for this plot NFT, but you can not make changes"
- Client A, copied the entire config.yaml from Client B. same result.

I don't understand why the original NFT which was created on the same key is not recognised.

**Expected behavior**
NFT to be picked up seamlessly. 

**Desktop (please complete the following information):**
OS: Windows

![nft issue](https://user-images.githubusercontent.com/46977985/124656569-0be07c80-deaa-11eb-94f9-b5c8bcb6a916.png)

**Comment by emlowe** [comment] 2021-07-07 05:48
Client A likely needs a complete resync of the wallet to see the PlotNFT. The problem is that it likely synced to the height beyond the PlotNFT while running the old code. So the new code doesn't get a chance to see the PlotNFT as it's already been synced past that height.

**Comment by mariano54** [comment] 2021-07-07 07:07
Exactly, you need to upgrade on both machines *before* creating your plot NFT, as explained here:
https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-User-Guide

**Comment by jd1900** [comment] 2021-07-07 07:36
> Client A likely needs a complete resync of the wallet to see the PlotNFT. The problem is that it likely synced to the height beyond the PlotNFT while running the old code. So the new code doesn't get a chance to see the PlotNFT as it's already been synced past that height.

How can we "resync" the wallet from scratch?
I don't see a command or similar to do that.

**Comment by panagiotisverras** [comment] 2021-07-07 12:29
Thank you for the response, apologies for submitting as a bug, I didn't have a clear understanding of what was happening.

**Comment by emlowe** [comment] 2021-07-07 18:38
Closing issue

**Closed by emlowe** 2021-07-07 18:38 UTC
Labels: bug

**Comment by aboukouris** [comment] 2021-07-10 18:05
I think this is still a bug and should be able to be fixed.
There are times that machines are offline. So if you create an NFT you need to re-install (some days of resyncing) for all offline machines? Should be an easy way to fix like "re-download last X packages" or get info of "X" package (that includes your NFT).

**Comment by devilouss** [comment] 2021-07-11 11:37
> Thank you for the response, apologies for submitting as a bug, I didn't have a clear understanding of what was happening.
 by doing the full resync does it work now ?

**Comment by Proulx-S** [comment] 2021-12-21 16:52
I agree with @devilouss. It is still an issue.

I switched machines, copied the blockchain and wallet files to the new machine and got ride of the old machine (and lost the config.yaml, my bad). New machine is farming fine, but my pools are not receiving my shares, and nothing suggests that on my new machine, even in the log.debug file.

I basically farmed for two days with no pool reward.

Note: I am CLI only.

Expected behavior: If the harvester and farmer encounters plots associated with an unknown plotnft, throwing at least some warning would be great.

Thanks Chia devs!

**Comment by Proulx-S** [comment] 2021-12-21 17:10
BTW, the solution, per the "important note" in [https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-User-Guide#step-1--sync-your-full-node-and-wallet](url), is to:
1-Shutdown chia
2-Delete your .chia/wallet/db
3-Open chia and let it resync.

Doing that right now. So far resyncing just the wallet (i.e. not the .chia/db) seems faster then when you resync both.
