### ISSUE TITLE
Incorrect behavior on low disk space[BUG]

### ISSUE THREAD

**Issue by smasharov** [Chia-Network/chia-blockchain#7789] opened 2021-07-26 07:02 UTC
**Describe the bug**
The plot deleted instead of moving to the final directory if there no enough space in the final directory

**To Reproduce**

The end of the log is below

**Expected behavior**
The process should pre-allocate required disk space before the copy. There are the functions for that, to quick allocate disk space without writing the zeroes to it and it should be not a sparse file.

**Screenshots**
Time for phase 4 = 2975.248 seconds. CPU (45.330%) Sun Jul 25 15:56:12 2021
Approximate working space used (without final file): 269.336 GiB
Final File size: 101.351 GiB
Total time = 52890.377 seconds. CPU (119.660%) Sun Jul 25 15:56:12 2021
Could not copy "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp". Error There is not enough space on the disk.. Retrying in five minutes.
Copied final file from "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp"
Copy time = 1902.478 seconds. CPU (2.230%) Sun Jul 25 16:27:55 2021
Removed temp2 file "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp"? 1
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot.2.tmp" to "\\\\T1\\PLOTS\\plot-k32-2021-07-25-01-14-9f1e36cba5bd3bb1196f9c76384ec59bbcb1ad844509046d558ad1660fb556ee.plot". Error The system cannot find the file specified.. Retrying in five minutes.
**Desktop**

- OS: Windows 
- OS Version/Flavor: Version 10.0.17763.2061
- CPU: AMD Ryzen 7 1700

**Additional context**
in 1.1.6 I have faced several times the issue then if I have no enough space in temp dir the plotting eventually will be failed, despite "retraing in 5 min" message. Even if the file will be created, it will be corrupted an unusable, plotting process will be crashed or hanged, consuming 100% of the one CPU thread.

**Comment by emlowe** [comment] 2021-07-26 16:16
Duplicate of #3852

**Closed by emlowe** 2021-07-26 16:16 UTC
Labels: bug

**Comment by smasharov** [comment] 2021-07-28 08:23
It is not a complete duplicate, but anyway. The main problem is that the "Retrying in five minutes" is pointless now, because it is not handled properly.
