### ISSUE TITLE
App wont open

### ISSUE THREAD

**Issue by mdze** [Chia-Network/chia-blockchain#6161] opened 2021-05-28 09:46 UTC
Yesterday i had problem with application, it was only white screen. I tried to restart app, but now i only get message "Connecting to wallet" and nothing happens, i even tried to reinstall app and still same.

**Comment by mdze** [comment] 2021-05-28 09:47
Yesterday i had problem with application, it was only white screen. I tried to restart app, but now i only get message "Connecting to wallet" and nothing happens

**Comment by tihanibel** [comment] 2021-05-28 11:31
exactly the same problem

**Comment by nodaone** [comment] 2021-05-28 17:57
Same here, and [here](https://github.com/Chia-Network/chia-blockchain/issues/6076), and [here](https://github.com/Chia-Network/chia-blockchain/issues/6075) , and [here](https://github.com/Chia-Network/chia-blockchain/issues/6031) and [here](https://github.com/Chia-Network/chia-blockchain/discussions/6049)...

So it's not a random issue, I think it's a bug somewhere..

**Comment by nodaone** [comment] 2021-05-28 18:08
A **solution** that worked for me after trying sooo many things:

1. In this folder "C:\Users\(...)\.chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
2. Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
3. then I started the GUI..

This worked for me, I hope it solves your problems as well. Good luck

**Comment by mdze** [comment] 2021-05-31 11:15
> 
> 
> A **solution** that worked for me after trying sooo many things:
> 
>     1. In this folder "C:\Users(...).chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
> 
>     2. Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
> 
>     3. then I started the GUI..
> 
> 
> This worked for me, I hope it solves your problems as well. Good luck

Thanks, it worked.

**Comment by mariano54** [comment] 2021-06-28 07:56
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:56 UTC
Labels: bug

**Comment by bitsam** [comment] 2022-07-22 03:14
@nodaone , with your workaround, does that force a full chain sync? I.e. how quick is it to get back to operation if you delete all the files in "C:\Users(...).chia\mainnet\wallet\db" ?
