### ISSUE TITLE
[Bug] Farm page of the GUI of 1.3.4 Windows version is not working correctly.

### ISSUE THREAD

**Issue by lawson1972** [Chia-Network/chia-blockchain#11228] opened 2022-04-20 01:33 UTC
### What happened?

GUI Issues:
1. Very slow when I click the icons.
2. After click farming or plots menu, The GUI shows " connecting to daemon" for a long long time.
3. The Plot count and Total Size of Plots are not correct ( In Plots menu and Farming menu)
4. In the Farming menu: 
4.1 Some items are keep circling without showing values.
4.2 Last Attempted Proof is not updating.
4.3 When the circling stops, the value is ERROR (not connected)
![farmingmenuerror](https://user-images.githubusercontent.com/84708986/164128908-9c67d800-1d68-4f1b-ae47-a006cbf86366.JPG)

I have upgraded the remote harvester and full node.  The issues happen when both nodes are running version 1.3.4.

The real process seems OK,( I checked the debug log on my local nodes and partial point status on Pool website). 
The GUI is buggy.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by leandroabarone** [comment] 2022-04-20 02:58
Same problem here with 5 harvester and 16000 plots.

**Comment by chiavivi** [comment] 2022-04-20 03:14
3台收割机 也是显示不正确，而且还是领不了奖励，

**Comment by iSky1ine** [comment] 2022-04-20 08:05
Had same problem. 
1.3.4 on Windows 10

**Comment by ects-io** [comment] 2022-04-20 09:03
Same problem on Farming tab.
GUI 1.3.4 in Windows 10
Running GUI on separated machine connected to an Ubuntu farmer/harvester + one additional Ubuntu harvester. Farmer and harvester machines seem to work correct.

**Comment by 85256638** [comment] 2022-04-20 12:00
Same problem here!!! You guys don't even do a code check before releasing?

**Comment by yang1782** [comment] 2022-04-20 13:51
I'm having the same issue on Windows 11. It looks like plots are passing filter on my farmer and harvesters after reviewing my logs but the GUI is messed up. My farming status shows not available. My plot count is also incorrect. This issue happened within minutes of installing the latest release. I'm with farming with Space Pool but my stats aren't updating.

**Comment by 85256638** [comment] 2022-04-20 13:53
> I'm having the same issue on Windows 11. It looks like plots are passing filter on my farmer and harvesters after reviewing my logs but the GUI is messed up. My farming status shows not available. My plot count is also incorrect. This issue happened within minutes of installing the latest release. I'm with farming with Space Pool but my stats aren't updating.

Yes, I believe the bug is purely with the GUI, the farmer and harvester are actually still working correctly.

**Comment by PAVoutsinas** [comment] 2022-04-20 14:22
same issue here. I'm bailing on this version until fixed

**Comment by chriskungtw** [comment] 2022-04-20 14:53
I'm having the same issue on Windows Server 2019

**Comment by PAVoutsinas** [comment] 2022-04-20 17:16
I have already rolled back. It was my main farmer and all harvesters that's
i ran the update on.

**Comment by seeden** [comment] 2022-04-20 18:28
Can anybody share error message? I will help me a lot because I am not able to reproduce it on my machine

**Comment by 85256638** [comment] 2022-04-20 18:36
> Can anybody share error message? I will help me a lot because I am not able to reproduce it on my machine

the error message simply says "connection closed". You could reproduce on your main machine with farmers connected.

**Comment by PAVoutsinas** [comment] 2022-04-20 20:51
Do you still need that error message? If you do I can reinstall and see if
I get it again for you to see. Let me know.

-Peter

**Comment by lawson1972** [comment] 2022-04-21 03:23
> Can anybody share error message? I will help me a lot because I am not able to reproduce it on my machine

The issue is not happened only in Farming page, the Plots, Farming and Pool page all affected.

My  experiences and guesses  for the issues are summarized as followings:
1. The issues are related to the number of plots (maybe greater than 10000 or more)
2. The issues are related to the interaction between new harvester protocols and daemon.
3. The real process seems ok. That means the daemon can not work properly with real process (overload or something)
4. The daemon can not be connected with GUI, (The daemon is too busy or down)
5. The reaction time after click the icons is long (The GUI process is busy)
6. The Chia CPU process of Windows 10 is very high (Busy CPU Utilization)
    (It also affect file transfer (move the plots )rate (265MB/sec down to 65MB/Sec, after I rolled back to 1.3.3, the file transfer rate is back to 265MB/sec, So the Whole OS is affect, not only for the chia )
7. The plots page is freezing with incorrect plot numbers, I can not add a plot directory under the scene. 
8. The pool page shows incorrect plot numbers (submit to pool) , but the real process seems ok.

**Comment by ects-io** [comment] 2022-04-21 07:20
I can confirm that the problem only occurs with a high plot count.
When I disable one harvester leaving the farm with 5578 plots the farming tab works as indented.
Reenabling the 2nd harvester with a total of 12594 plots forces the GUI to reconnect to the daemon and then brings up a working farm summary once.
Restarting the GUI with 12594 plots brings back the non working state.

**Comment by ects-io** [comment] 2022-04-22 15:20
This are the error messages from the GUI:
![img7](https://user-images.githubusercontent.com/98576096/164743994-c0b24cb2-a54a-474d-888c-1ca4a6a03834.png)

This is the DEBUG level logfile from the farmer node after pressing the "Farming" icon in the GUI until the faulty view occures
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8542117/debug.log)

**Comment by BigSilverOrb** [comment] 2022-04-24 06:50
Are we seeing progress on this issue? Can't say it's critical, as I did farm a block in this condition, but the GUI tells me to go suck one.

**Comment by chiavivi** [comment] 2022-04-24 10:26
感觉问题一直没有解决，反应了这么久了，奖励一直无法申领，我只有回滚到1.3版本。

**Comment by chiavivi** [comment] 2022-04-24 10:31
回滚到1.3的版本但是还是不能申领奖励，有没有那个朋友 回滚到 1.2的版本的？

**Comment by hedandan1989** [comment] 2022-04-24 13:54
> Same problem here!!! You guys don't even do a code check before releasing? ![image](https://user-images.githubusercontent.com/3270742/164228156-136497bb-232b-482c-94e6-b6631e6df017.png)

same problem.
I'm trying cli mode.

**Comment by emlowe** [comment] 2022-04-25 16:03
We are actively working on fixes

**Comment by seeden** [comment] 2022-04-25 22:00
All GUI work can be tracked here:
https://github.com/Chia-Network/chia-blockchain-gui/tree/harvesters_pagination

**Comment by navyfeng** [comment] 2022-04-27 03:25
> 回滚到1.3的版本但是还是不能申领奖励，有没有那个朋友 回滚到 1.2的版本的？

用命令行申领  .\chia.exe plotnft claim -i 启动器序号

**Comment by ects-io** [comment] 2022-05-01 22:15
Hmmm, I usually have a winning rate way below the average, just by using enterprise hardware and therefore not being affected by dust. but since I have upgraded to 1.3.4 two week ago I had only one win, I normaly have about 5 to 6 in this timeperiod. I don't blame anyone beside the luckgod for this. I have downgraded now to 1.3.3, does this even work if I have been on 1.3.4. I also left keybase when the not winning has begun. Just delete this post if it keybase related ;)

**Comment by chiavivi** [comment] 2022-05-03 08:47
还是不能申领奖励，是所有的都不能还是 部分不能领取奖励。快一个月了，都没有解决。

**Comment by wallentx** [comment] 2022-05-05 17:25
This should be fixed in main. Are you able to try this with a build from Latest Dev - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
Let us know how your experience is with this

**Comment by iced-caffeine** [comment] 2022-05-06 13:55
The latest beta appears stable for me.  Have been running for approx 10 mins, no issues.  Response time for switching between main tabs is also much improved, near instantaneous (definitely better than 1.3.3).

Thanks guys.

**Comment by emlowe** [comment] 2022-05-11 22:09
Closing, fixed in 1.3.5

**Closed by emlowe** 2022-05-11 22:09 UTC
Labels: bug, GUI
