### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hongchendashu** [Chia-Network/chia-blockchain#3078] opened 2021-04-29 08:31 UTC
![image](https://user-images.githubusercontent.com/81615161/116522606-f4b06c00-a907-11eb-849c-dce5a57ac010.png)
I plots the file is missing, how to solve this problem?

**Comment by hongchendashu** [comment] 2021-04-29 09:31
>
 我的情节文件丢失了，如何解决这个问题？
 ![图像](https://user-images.githubusercontent.com/81615161/116522606-f4b06c00-a907-11eb-849c-dce5a57ac010.png)
> 我的情节文件丢失了，如何解决这个问题？

**Comment by lipalong** [comment] 2021-04-29 16:28
Duplicate of #2692  – see the comments there.
Also, we've made the wording for this error more clear in the next release.

**Closed by lipalong** 2021-04-29 16:28 UTC
Labels: bug
