### ISSUE TITLE
[Bug] Not able to mint NFT if reuse_puzhash  (reopen)

### ISSUE THREAD

**Issue by YeungTing** [Chia-Network/chia-blockchain#16592] opened 2023-10-11 14:47 UTC
### What happened?

Not able to mint NFT if reuse_puzhash and if there are invalid spendable coin record in DID wallet, like this 

{
"confirmed_records": [
{
"coin": {
"amount": 0,
"parent_coin_info": "xxxxxxxxxxxxxxxxxxxxx",
"puzzle_hash": "xxxxxxxxxxxxxxxxxxxxx"
},
"coinbase": false,
"confirmed_block_index": 38XXXXX,
"spent_block_index": 0,
"timestamp": 168XXXXXX
},
{
"coin": {
"amount": 1,
"parent_coin_info": "xxxxxxxxxxxxxxxxxxxxx",
"puzzle_hash": "xxxxxxxxxxxxxxxxxxxxx"
},
"coinbase": false,
"confirmed_block_index": 43XXXXX,
"spent_block_index": 0,
"timestamp": 169XXXXXX
},
....
]

this is spendable coin record in did wallet, some how it contain invalid information. some coint "amount" = 0. 
The implementation in 1.8.3 can filter out invalid coin, much better than the implementation in 2.1.0. Please revert it.

### Version

2.1.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
File "chia\wallet\nft_wallet\nft_wallet.py", line 413, in generate_new_nft
  File "chia\wallet\nft_wallet\nft_wallet.py", line 311, in get_did_approval_info
  File "chia\wallet\did_wallet\did_wallet.py", line 773, in create_message_spend
AssertionError
```

**Comment by wjblanke** [comment] 2023-10-11 16:12
https://github.com/Chia-Network/chia-blockchain/blame/release/2.1.0/chia/wallet/did_wallet/did_wallet.py#L773

parent_info = self.get_parent_for_coin(coin)
assert parent_info is not None

OK we will take a look thanks

**Comment by geoffwalmsley** [comment] 2023-10-17 04:37
Hi @YeungTing , thanks for the report. I'm trying to reproduce this issue so would be good to understand where the coins with `amount=0` are coming from. Do you know what transaction types created them? For example, nft mints, or some other DID spends?

**Comment by YeungTing** [comment] 2023-10-17 05:20
I don't know where is it from, but only thing i did is nft mints. After i mint many nfts, its there

**Comment by geoffwalmsley** [comment] 2023-11-06 02:39
Hi @YeungTing apologies this has taken a while to come back to. I'm still unable to reproduce the did wallet creating zero value coins. Are you still having the issue, and have you tried resyncing the wallet from scratch?

**Comment by emlowe** [comment] 2024-02-09 23:06
closing issue due to reproducibility - can be re-opened if further information is discovered

**Closed by emlowe** 2024-02-09 23:06 UTC
Labels: bug
