### ISSUE TITLE
Gui will not load [BUG]

### ISSUE THREAD

**Issue by Chevdevi76** [Chia-Network/chia-blockchain#6311] opened 2021-06-01 11:21 UTC
<img width="1202" alt="chia problem" src="https://user-images.githubusercontent.com/85167907/120314878-b3fe9680-c2a9-11eb-97c6-666ad65d573e.PNG">
After I shut down yesterday and windows auto-updated, I cant load the gui. After it times out it just stays on a white screen. I have tried Reinstalling the program.

**Comment by movbx** [comment] 2021-06-01 11:27
so am I

**Comment by boybun** [comment] 2021-06-01 13:42
me too

**Comment by aradesl766** [comment] 2021-06-01 13:49
mee too

**Comment by sawicpx** [comment] 2021-06-01 15:49
me too

**Comment by Muasin94** [comment] 2021-06-01 16:42
For Windows:
Shut down Chia GUI
User\YOURNAME\.chia\mainnet\wallet\db
and delete all the file with: BLOCKCHAIN_WALLET
Then restart GUI.

**Comment by Chevdevi76** [comment] 2021-06-01 16:50
> For Windows:
> Shut down Chia GUI
> User\ YOURNAME\ .chia \ mainnet \ wallet \ db
> and delete all the file with: BLOCKCHAIN_WALLET
> Then restart GUI.

I tried that from another board, it doesn't seem to change anything.

**Comment by Muasin94** [comment] 2021-06-01 17:03
> > For Windows:
> > Shut down Chia GUI
> > User\ YOURNAME\ .chia \ mainnet \ wallet \ db
> > and delete all the file with: BLOCKCHAIN_WALLET
> > Then restart GUI.
> 
> I tried that from another board, it doesn't seem to change anything.

then I don't know how to help you, this method worked for me

**Comment by boybun** [comment] 2021-06-01 17:27
i try it and it worked
thank you

**Comment by Muasin94** [comment] 2021-06-01 17:29
> i try it and it worked
> thank you

np, happy to have helped

**Comment by mariano54** [comment] 2021-06-28 07:59
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:59 UTC
Labels: bug
