### ISSUE TITLE
[BUG] Plots not refreshing once created.

### ISSUE THREAD

**Issue by Ross1882** [Chia-Network/chia-blockchain#7478] opened 2021-07-14 03:50 UTC
Once a plot has been created on madmax the plot count on the chia programme is not increasing you have to press the refresh option on the plots page each time. If i setup madmax to do 50 they don't adjust until I refresh unlike the previous 1.1.795 version.

Is this going to be fixed?

**Comment by forReason** [comment] 2021-07-14 06:22
I found the same issue for me. But if you are in a pool, check your net space on the pool. I found that it still increases, eventhough not shown in chia gui.
Chia on the commandline meanwhile does not show plotcount at all. unless specifying command chia farm summary

Have you had good experience using madmax plotter?

**Comment by hhenrry501** [comment] 2021-07-14 10:26
> I found the same issue for me using default chia plotting with Plotmanager. If you are in a pool, check your net space on the pool. I found that it still increases, eventhough not shown in chia gui.
> Chia on the commandline meanwhile does not show plotcount at all. unless specifying with chia farm summary
> 
> Have you had good experience using madmax plotter? (speedwise)

same here, and im using madmax on Windows..very unstable..and GUI does not update with new plots, and after i click refresh button, GUI showing nothing now.

**Comment by djdd87** [comment] 2021-07-14 13:30
Same here since 1.2.0. Same issue on 1.2.1.

**Comment by adic20** [comment] 2021-07-14 14:12
agreed, on windows OS auto refresh not working for update v1.2.1

**Comment by emlowe** [comment] 2021-07-14 19:05
Duplicate of #7262

**Closed by emlowe** 2021-07-14 19:05 UTC
Labels: bug
