### ISSUE TITLE
[BUG] Wallet Sync is tOOOOOOO SLOW!!!!

### ISSUE THREAD

**Issue by overdoignism** [Chia-Network/chia-blockchain#7221] opened 2021-07-08 12:39 UTC
**Describe the bug**

I downloaded the 1.2.0 to begin my Chia test.

You guess what, I need sync the wallet from 0 to 542,088

AND, AFTER 2 HOURS PAST, I have done about 9% (49,248)

９％！！！！！！！

And MY CPU HAS A LOT OF USAGE PEAK!!!!!!!

I have a modern PC, has AMD R5 2400G and 16G DDR4 memory, 100Mbps internet connect,

But I need to wait for using my wallet in 22hrs+

Are you kidding me? It's not a blockchain which already exist 10 years, right!? 

Who can use the wallet after 3 years? What problem with this project?

**Screenshots**

![IMAGE](https://i.imgur.com/dIQQ04C.jpg?2)

**Desktop**

Windows 10
AMD R5 2400G
8Gx2 = 16G DDR4 memory
512G SSD

**Comment by mariano54** [comment] 2021-07-08 13:34
Yeah, there is some work to be done to optimize the speed. Not a bug though, so closing.

**Closed by mariano54** 2021-07-08 13:34 UTC
Labels: bug
