### ISSUE TITLE
MacOS Catalina - Kernel panic crash [BUG]

### ISSUE THREAD

**Issue by mikeindustries** [Chia-Network/chia-blockchain#1563] opened 2021-03-29 16:38 UTC
System shut itself down on its own last night and here is the crash report:

------------------------------------------------

0xffffff8118e4bf10 : 0xffffff800ee45c1e 
0xffffff8118e4bfa0 : 0xffffff800ecbf94f 

BSD process name corresponding to current thread: Chia

Mac OS version:
19H114

Kernel version:
Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
Kernel UUID: A477D537-F87E-3978-8D7F-A84B7C02E62E
Kernel slide:     0x000000000ea00000
Kernel text base: 0xffffff800ec00000
__HIB  text base: 0xffffff800eb00000
System model name: iMac17,1 (Mac-B809C3757DA9BB8D)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 5877698119262590
last loaded kext at 5874258114201653: >!AXsanScheme	3 (addr 0xffffff7f939aa000, size 32768)
last unloaded kext at 5874405635678466: >!AXsanScheme	3 (addr 0xffffff7f939aa000, size 32768)
loaded kexts:
at.obdev.nke.LittleSnitch	5618
com.3dconnexion.driver	10.4.4
|SCSITaskUserClient	422.120.3
>!U!SCoexistentDriver	489.120.1
@filesystems.afpfs	11.2
@nke.asp-tcp	8.1
>!ATopCaseHIDEventDriver	3430.1
@fileutil	20.036.15
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AMikeyHIDDriver	131
>!AMikeyDriver	283.15
>!AUpstreamUserClient	3.6.8
@kext.AMDRadeonServiceManager	3.1.0
@kext.AMDFramebuffer	3.1.0
>!AHDA	283.15
@kext.AMDRadeonX4000	3.1.0
>!A!ISKLGraphics	14.0.7
>!AGraphicsDevicePolicy	5.2.7
>!AThunderboltIP	3.1.4
>!A!ISKLGraphicsFramebuffer	14.0.7
@AGDCPluginDisplayMetrics	5.2.7
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f8
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.14
>!ASMCLMU	212
>AudioAUUC	1.70
>!A!IPCHPMC	2.0.1
@kext.AMD9000!C	3.1.0
|Broadcom!B20703USBTransport	7.0.6f8
>eficheck	1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.141.1
|!ABCM5701Ethernet	10.3.5
>!ASDXC	1.7.7
>AirPort.BrcmNIC	1400.1.1
@private.KextAudit	1.0
>!AAHCIPort	341.140.1
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
|IOUSBMass!SClass	4.0.4
$SecureRemotePassword	1.0
>!AHIDKeyboard	209
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.6f8
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@kext.AMDRadeonX4070HWLibs	1.0
@kext.AMDRadeonX4000HWServices	3.1.0
>!AGraphicsControl	5.2.7
|IOAccelerator!F2	438.7.3
>!AThunderboltEDMSink	4.2.3
|IOAVB!F	850.1
>!ASMBusPCI	1.0.14d1
@!AGPUWrangler	5.2.7
|IOSlowAdaptiveClocking!F	1.0.0
|IONDRVSupport	576.1
>!ASMBus!C	1.0.18d1
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
@kext.AMDSupport	3.1.0
@!AGraphicsDeviceControl	5.2.7
|Broadcom!BHost!CUSBTransport	7.0.6f8
|IO!BHost!CUSBTransport	7.0.6f8
|IO!BHost!CTransport	7.0.6f8
|IO!B!F	7.0.6f8
|IO!BPacketLogger	7.0.6f8
@plugin.IOgPTPPlugin	840.3
>!AHDA!C	283.15
|IOGraphics!F	576.1
|IOHDA!F	283.15
>!UAudio	323.4
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>!AThunderboltDPOutAdapter	6.2.6
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AThunderboltPCIDownAdapter	2.5.4
|IOAHCIBlock!S	316.100.5
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
|IOEthernetAVB!C	1.1.0
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOSkywalk!F	1
|IOAHCI!F	290.0.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOUSBHIDDriver	900.4.2
|IOUSB!F	900.4.2
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|IOHID!F	2.0.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by mariano54** [comment] 2021-04-07 11:29
Duplicate of this: 
https://github.com/Chia-Network/chia-blockchain/issues/1672

Merging discussion

**Closed by mariano54** 2021-04-07 11:29 UTC
