### ISSUE TITLE
chia gui wont connect to wallet, i start the app it says it is connectin to wallet and stays like thar for ever [BUG]

### ISSUE THREAD

**Issue by Baha1708** [Chia-Network/chia-blockchain#7569] opened 2021-07-16 13:57 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Baha1708** [comment] 2021-07-16 13:57
![image](https://user-images.githubusercontent.com/87533907/125959524-3e3f3ba1-790f-4783-8ebd-1d3c9f15363f.png)

**Comment by Baha1708** [comment] 2021-07-16 13:59
Successfully merging a pull request may close this issue? dont understand

**Comment by Marce0719** [comment] 2021-07-17 01:20
Me ocurre lo mismo. Al abrir el cliente chia no conecta con la billetera. Llevo horas esperando y no conecta. 
It happens the same to me. When opening the chia client it does not connect with the wallet. I've been waiting for hours and it doesn't connect.

**Comment by mflex183** [comment] 2021-07-17 04:50
Its happening with me as well
How to solve this?

**Comment by ryu007za** [comment] 2021-07-17 12:06
I had to do complete reinstall to fix it.... but now copy pasting old DB isnt working either so may have to re sync everything

**Comment by Harkostar** [comment] 2021-07-17 14:27
same here. plotting goes on  node and wallet are syncd but no conection to plots , far and pool

**Comment by Max7e** [comment] 2021-07-17 18:07
The same, after upgrading 1.1.7 to 1.2.1 (1.2.2). (win7 pro x64, Intel I5-6500) Deleting mainnet folder doesn't help, new folder not creating. Uninstall 122
![074](https://user-images.githubusercontent.com/87579585/126046023-2a2a3698-576b-498e-8ae5-9103e6d5726f.jpg)
![072](https://user-images.githubusercontent.com/87579585/126046024-d75a1f94-c18e-4a08-97b8-4660a281336f.jpg)
 and install 117 back - works fine again! WTH.

**Comment by kalufinnle** [comment] 2021-07-17 18:59
seems to be the problem from clvm_rs. Python has problem to import name 'deserialize_and_run_program2' from 'clvm_rs'

**Comment by Kgonla** [comment] 2021-07-18 07:49
Same problem than:
https://github.com/Chia-Network/chia-blockchain/issues/7363
https://github.com/Chia-Network/chia-blockchain/issues/3869

The older one is more than 2 months old, it looks developers will do nothing about this.
Personally I deleted plots and software, I will not upgrade my OS to run chia.

**Comment by Max7e** [comment] 2021-07-20 18:21
Appears to be that Python 3.9.x, used as part of chia 1.2.x software, officially doesn' support win7 (and doesn't work on it). Maybe there is some way to make use of older version of Python?

**Comment by kalufinnle** [comment] 2021-07-20 19:07
I dont think it is Windows problem and neither it is python's version
problem. I am using Python 3.8 and Ubuntu

**Comment by emlowe** [comment] 2021-07-22 03:40
Duplicate of #6993

**Closed by emlowe** 2021-07-22 03:40 UTC
Labels: bug
