### ISSUE TITLE
[Bug] ip6-localhost not working

### ISSUE THREAD

**Issue by d1m1trus** [Chia-Network/chia-blockchain#13532] opened 2022-09-25 15:50 UTC
### What happened?

if you replace **localhost** with **ip6-localhost** in the config, the **GUI** and **Wallet** do not work.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by emlowe** [comment] 2022-09-26 15:59
I believe this is a duplicate of #11387.

**Closed by emlowe** 2022-09-26 15:59 UTC
Labels: bug
