### ISSUE TITLE
[Bug] Deleting chia wallet error

### ISSUE THREAD

**Issue by KevinOnFrontEnd** [Chia-Network/chia-blockchain#17331] opened 2024-01-13 14:37 UTC
### What happened?

![image](https://github.com/Chia-Network/chia-blockchain/assets/133973062/cf8d76a7-f5bf-49eb-a8d3-a9fffbd616cf)

**Steps to reproduce:**
- Add wallet to client
- Logout of wallet
- Selectt a wallet that you would like to remove by clicking  ellipsis and clicking **delete**
- Entering wallet fingerprint and clicking **delete** button results in error **h.filter is not a function** as per screenshot

I've noticed this in 2.1.4 release, however have checked the previous release I had installed (2.1.2) and it still exists.

### Version

2.1.2 / 2.1.4 

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
Error popup
h.filter is not a function
```

**Comment by wjblanke** [comment] 2024-01-17 17:39
Izumi can u take a look at this? Seems like GUI delete wallet isnt working.

**Comment by ChiaMineJP** [comment] 2024-01-18 10:35
@wjblanke OK, I'll take a look.

**Comment by ChiaMineJP** [comment] 2024-01-18 17:24
I identified the root cause and created a PR.
https://github.com/Chia-Network/chia-blockchain-gui/pull/2260

Also, there is a work around.
1. Open `$CHIA_ROOT/gui/Chia Blockchain/prefs.yaml`.
2. Append the line `sortedWallets: []` to the file.
Then you will be able to remove wallet without raising error.

**Comment by ChiaMineJP** [comment] 2024-01-25 15:36
https://github.com/Chia-Network/chia-blockchain-gui/pull/2260
The fixing PR has been merged into `main`.
Closing this issue.

**Closed by ChiaMineJP** 2024-01-25 15:36 UTC
Labels: bug
