### ISSUE TITLE
How to fix MadMAx Plotter not installed error

### ISSUE THREAD

**Issue by AlphaVlogger-YT** [Chia-Network/chia-blockchain#13326] opened 2022-09-04 08:25 UTC
Recently I Entered the world of Chia (I was about to Farm Chia plots after 1 weeks of wallet sync);

I am using Ubuntu-22.04 (Running Natively on a SSD)
Chia Blockchain version 1.5.1 (GUI Version).

Recently I had a notification on the Ubuntu showing up a system update notification (which included an update for chia on the preview) and I updated and restarted the system. After that the Chia Blockchain started showing the MadMAx plotter was not installed when plotting a new plot. 

![Screenshot 2022-09-03 122327](https://user-images.githubusercontent.com/103718216/189476681-df9ab2be-43a4-4697-88de-0ab31dd0156f.png)

I tried uninstalling the Chia Blockchain app and reinstalling it, and tried various command shown on the internet to install the MadMAx plotter, but I was not able to resolve it. So at last I erased my system and reinstalled the Ubuntu-22.04 again (Sync started from first) and downloaded the Chia app from official page using terminal: [https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian](url), and its the GUI Version again but the error still continuous. All the images added here are taken after fresh installation of ubuntu-22.04. The system I am using is only for chia not for any other purpose!

![Terminal-1 edit](https://user-images.githubusercontent.com/103718216/189476641-9a219c4b-c0bb-4cd4-a7da-483e6689259b.png)

Website Links I have visited:

1) [How To Install MadMAx Plotter on Ubuntu 20.04 | Incredigeek](https://www.incredigeek.com/home/how-to-install-madmax-plotter-on-ubuntu-20-04/)
2) [1.2.11 missing Mad Max plotter in list](https://chiaforum.com/t/1-2-11-missing-mad-max-plotter-in-list/14645)

I am not sure what to do, please someone help me.
Thank You very much,

Eagerly Waiting for your replay,

**Comment by amandobond** [comment] 2022-09-04 15:32
I`ve got the same issue.
Chia 1.5.1
Ubuntu 22.04.1 LTS.
Madmax is installed, but it can`t be operated through gui.

**Comment by AlphaVlogger-YT** [comment] 2022-09-05 01:48
> I`ve got the same issue. Chia 1.5.1 Ubuntu 22.04.1 LTS. Madmax is installed, but it can`t be operated through gui.

Thanks for your replay,

what are the other solution you have tried to resolve it. I saw few complaints on chi forum saying that they had same problem with ubuntu 18-chia v.1.3.5 and when upgraded to ubuntu 20 the problem was resolved.

 Chia Forum Link: [https://chiaforum.com/t/madmax-plotter-not-installed-issue/16977/4](url)

![Screenshot 2022-09-05 071616](https://user-images.githubusercontent.com/103718216/188344385-afa617b4-3a1a-4878-82e5-cd37816f78f8.png)

**Comment by AlphaVlogger-YT** [comment] 2022-09-05 01:49
> I`ve got the same issue. Chia 1.5.1 Ubuntu 22.04.1 LTS. Madmax is installed, but it can`t be operated through gui.

Thanks for your replay,

what are the other solution you have tried to resolve it. I saw few complaints on chi forum saying that they had same problem with ubuntu 18-chia v.1.3.5 and when upgraded to ubuntu 20 the problem was resolved.

 Chia Forum Link: [https://chiaforum.com/t/madmax-plotter-not-installed-issue/16977/4](url)

![Screenshot 2022-09-05 071616](https://user-images.githubusercontent.com/103718216/188344385-afa617b4-3a1a-4878-82e5-cd37816f78f8.png)

**Comment by AlphaVlogger-YT** [comment] 2022-09-05 01:50
> I`ve got the same issue. Chia 1.5.1 Ubuntu 22.04.1 LTS. Madmax is installed, but it can`t be operated through gui.

Thanks for your replay,

what are the other solution you have tried to resolve it. I saw few complaints on chi forum saying that they had same problem with ubuntu 18-chia v.1.3.5 and when upgraded to ubuntu 20 the problem was resolved.

 Chia Forum Link: [https://chiaforum.com/t/madmax-plotter-not-installed-issue/16977/4](url)

![Screenshot 2022-09-05 071616](https://user-images.githubusercontent.com/103718216/188344385-afa617b4-3a1a-4878-82e5-cd37816f78f8.png)

**Comment by amandobond** [comment] 2022-09-08 20:32
Hi again.
After reinstalling madmax, reinstalling chia and all the shit around nothing gets better.
What did work for me was deleting /opt/chia/libstdc++.so.6
So if your madmax plotter is not listed in gui in plotter menu like above try this:
close chia
cd /opt/chia/
sudo rm chia/libstdc++.so.6
run chia

Good luck!

**Comment by AlphaVlogger-YT** [comment] 2022-09-09 20:21
> Hi again. After reinstalling madmax, reinstalling chia and all the shit around nothing gets better. What did work for me was deleting /opt/chia/libstdc++.so.6 So if your madmax plotter is not listed in gui in plotter menu like above try this: close chia $ cd /opt/chia/ $ sudo rm chia/libstdc++.so.6 run chia
> 
> Good luck!

**Comment by ChiaMineJP** [comment] 2022-09-10 07:06
Hi, thanks for reporting the issue.
I've confirmed this is reproducible on my Ubuntu 22 environment.

The error comes from this line:
https://github.com/Chia-Network/chia-blockchain/blob/1.5.1/chia/plotters/madmax.py#L50

When chia tries to check madmax version by `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/madmax/chia_plot --version` it seems it returns `-1` as return code.
You can see error logs by
`grep 'madmax' ${CHIA_ROOT-"$HOME/.chia/mainnet/log/debug.log"}`

I tried to run the above command in my bash terminal and it returns `0` as return code.
I'm investigating the root cause as to what makes it return `-1` when it is invoked in a context of chia services.

**Comment by ChiaMineJP** [comment] 2022-09-10 08:33
I manged to capture stderr from `madmax`.
![image](https://user-images.githubusercontent.com/84098616/189475606-160c99f2-4826-4354-b798-787a9fb6cbb7.png)

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 08:38
> Hi again. After reinstalling madmax, reinstalling chia and all the shit around nothing gets better. What did work for me was deleting /opt/chia/libstdc++.so.6 So if your madmax plotter is not listed in gui in plotter menu like above try this: close chia $ cd /opt/chia/ $ sudo rm chia/libstdc++.so.6 run chia
> 
> Good luck!



> Hi, thanks for reporting the issue. I've confirmed this is reproducible on my Ubuntu 22 environment.
> 
> The error comes from this line: https://github.com/Chia-Network/chia-blockchain/blob/1.5.1/chia/plotters/madmax.py#L50
> 
> When chia tries to check madmax version by `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/madmax/chia_plot --version` it seems it returns non-zero as return code. You can see error logs by `grep 'madmax' ${CHIA_ROOT-"$HOME/.chia/mainnet/log/debug.log"}`
> 
> I tried to run the above command in my bash terminal and it returns `0` as return code. I'm investigating the root cause as to what makes it return non-zero return code when it is invoked in a context of chia services.



> Hi again. After reinstalling madmax, reinstalling chia and all the shit around nothing gets better. What did work for me was deleting /opt/chia/libstdc++.so.6 So if your madmax plotter is not listed in gui in plotter menu like above try this: close chia $ cd /opt/chia/ $ sudo rm chia/libstdc++.so.6 run chia
> 
> Good luck!

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 08:49
> Hi again. After reinstalling madmax, reinstalling chia and all the shit around nothing gets better. What did work for me was deleting /opt/chia/libstdc++.so.6 So if your madmax plotter is not listed in gui in plotter menu like above try this: close chia $ cd /opt/chia/ $ sudo rm chia/libstdc++.so.6 run chia
> 
> Good luck!

Hey thanks for your replay and your effort,
But still after trying yours's, this also showed me the same error:

![Screenshot from 2022-09-10 07-56-57](https://user-images.githubusercontent.com/103718216/189476093-6aedf6c4-01ec-46c1-b32d-a94bc3ec5f8c.png)

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 08:53
> Hi, thanks for reporting the issue. I've confirmed this is reproducible on my Ubuntu 22 environment.
> 
> The error comes from this line: https://github.com/Chia-Network/chia-blockchain/blob/1.5.1/chia/plotters/madmax.py#L50
> 
> When chia tries to check madmax version by `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/madmax/chia_plot --version` it seems it returns non-zero as return code. You can see error logs by `grep 'madmax' ${CHIA_ROOT-"$HOME/.chia/mainnet/log/debug.log"}`
> 
> I tried to run the above command in my bash terminal and it returns `0` as return code. I'm investigating the root cause as to what makes it return non-zero return code when it is invoked in a context of chia services.

Thankyou very much,
I now got some hope that I can still Use Chia-GUI for farming,
Eagerly waiting for you replay and solution to this problem.

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 08:55
> I manged to capture stderr from `madmax`. ![image](https://user-images.githubusercontent.com/84098616/189475606-160c99f2-4826-4354-b798-787a9fb6cbb7.png)
> 
> `/opt/chia/resources/app.asar.unpacked/daemon/madmax/chia_plot: /opt/chia/resources/app.asar.unpacked/daemon/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/madmax/chia_plot)`

With this How am I supposed to proceed further, I think this is the same error showed up in the terminal pic.

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 09:00
Today morning I visited the debug.log and here are the top most error showed;

The debug.log:

1) 2022-09-04 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.

2) 2022-09-04 daemon chia.plotters.madmax       : ERROR    Failed to determine madmax version: Failed to call madmax with --  version option Command '['/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/madmax/chia_plot', '--version']' returned non-zero exit status 1. Traceback (most recent call last):

This is same has you said, it is returning to " 0 " at the end,
Hope this is helpful to you.

**Comment by ChiaMineJP** [comment] 2022-09-10 09:03
This can make you forward but I cannot assure you that this is the final solution.
```bash
cd /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/
sudo mv libstdc++.so.6 libstdc++.so.6.backup
```
The real issue might reside in chia's installer or something.
Please keep this issue open.

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 09:09
> This can make you forward but I cannot assure you that this is the final solution.
> 
> ```shell
> cd /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/
> sudo mv libstdc++.so.6 libstdc++.so.6.backup
> ```
> 
> The real issue might reside in chia's installer or something. Please keep this issue open.

Sure I will keep this issue opened,
Can you make sure the command in the image below is not the same as you suggested

![Screenshot from 2022-09-10 07-56-57](https://user-images.githubusercontent.com/103718216/189476786-83a7ca43-80e3-4023-90ed-6b898cd9a339.png)

I also made a copy of this issue in the reddit, please do visit the page;
[https://www.reddit.com/r/chia/comments/x88p7y/how_to_fix_madmax_plotter_not_installed_error/](url)

**Comment by ChiaMineJP** [comment] 2022-09-10 09:15
> Can you make sure the command in the image below is not the same as you suggested

This is almost the same.
`/opt/chia` is just the symbolic link to `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon`.
Maybe he mistyped `sudo rm chia/libstdc++.so.6` instead of `sudo rm libstdc++.so.6`.

Also my version doesn't delete `libstdc++.so.6` and just renamed it because it is more useful to be able to restore `libstdc++.so.6`.

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 09:28
> > Can you make sure the command in the image below is not the same as you suggested
> 
> This is almost the same. `/opt/chia` is just the symbolic link to `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon`. Maybe he mistyped `sudo rm chia/libstdc++.so.6` instead of `sudo rm libstdc++.so.6`.
> 
> Also my version doesn't delete `libstdc++.so.6` and just renamed it because it is more useful to be able to restore `libstdc++.so.6`.

Ok then I will try yours's and let you know the result in a while

**Comment by ChiaMineJP** [comment] 2022-09-10 09:38
Relevant issue: https://github.com/Chia-Network/chia-blockchain/issues/13242

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 10:06
> Relevant issue: #13242

Noted

**Comment by amandobond** [comment] 2022-09-10 12:39
Thanks. My bad. I`ve already updated wrong comment.

**Comment by AlphaVlogger-YT** [comment] 2022-09-10 13:58
@ChiaMineJP, and @amandobond, etc.

Thankyou very much my problem has resolved. Now I am to see the madmax plotter.

I used the flowing command:
cd /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/
sudo mv libstdc++.so.6 libstdc++.so.6.backup

![Screenshot from 2022-09-10 18-57-35](https://user-images.githubusercontent.com/103718216/189486464-9f2861ba-cfda-4733-a416-d235107cb156.png)

I still have one more request, will I be able to backup by wallet sync??;
Because I would like to farm on two separate device which has ubuntu-22.04 loaded, and if I had the backup of the current sync I no need to wait for another 3 days for db sync and then to plot or farm.

**Comment by ChiaMineJP** [comment] 2022-09-10 14:56
If you haven't set `CHIA_ROOT`, all your user data is stored under `$HOME/.chia/mainnet` (on Ubuntu).
Typically just copying the folder into new machine to the same location works, but please be sure to take a backup when all of chia services stop.
Since chatting another topic here would make it difficult for future readers to follow, I'll leave from the topic for now.

**Comment by amandobond** [comment] 2022-09-21 17:07
After updating Chia to 1.6.0 same thing happened (Mad Max not listed in gui). Removing libstdc++.so.6 still do the job.

**Comment by emlowe** [comment] 2022-09-29 23:39
Closing issue as this is a duplicate of #13242

**Closed by emlowe** 2022-09-29 23:39 UTC
Labels: bug, Linux, plotting, 1.5.1
