### ISSUE TITLE
[Bug] Offers can end up in perpetual pending state

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#9854] opened 2022-01-18 17:48 UTC
### What happened?

It is believed that when several people attempt to take an offer, the losers can sometimes end up in a state where the offer is pending, and it won't complete nor fail and stays pending.

Note it is believed that the person who wins and actually takes the offer does actually complete the transaction

Not all details are known but certainly some offers end up in this state

### Version

Light Wallet Offers beta

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
None at this time
```

**Comment by paninaro** [comment] 2022-01-19 00:15
I've repro'd this a few times and have a workaround to return the spendable balance:

Workaround steps:
1) Copy the "Offer Identifier" for the offer stuck in a "Pending Confirm" state. This can be copied from the offer details page (Click the 3 dots button in the offer row and select "Show Details"). The offer ID will be a hex string like: `0x1a832f4598fa06e177e94fdd8b82b4cf7d28dee4a32a0d2a5b99abf15754fffe`

2) From the command line, use the chia executable to cancel the offer:
(Windows using cmd.exe)
`%LOCALAPPDATA%\chia-blockchain\app-1.2.11265\resources\app.asar.unpacked\daemon\chia wallet cancel_offer -id <copied offer ID> --insecure`
(macOS using a terminal)
`/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia wallet cancel_offer -id <copied offer ID> --insecure`
(Linux using a terminal)
`/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia wallet cancel_offer -id <copied offer ID> --insecure`

3) Delete unconfirmed transactions. In the GUI this option is accessible from the wallet screen, using the 3 dots button in the upper-right. From the command line, you can use `chia wallet delete_unconfirmed_transactions` (using the path to chia as described in step 2).

**Comment by paninaro** [comment] 2022-01-19 21:58
The bug is in `delete_trade_transactions()`. `tx.name()` raises an exception because `name` is a property, not a method.
https://github.com/Chia-Network/chia-blockchain/blob/protocol_and_cats_rebased/chia/wallet/wallet_state_manager.py#L1218

The issue has already been fixed in main:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/wallet_state_manager.py#L1292

**Comment by paninaro** [comment] 2022-01-19 22:01
Closing as this is already fixed in main.

**Closed by paninaro** 2022-01-19 22:01 UTC
Labels: bug
