### ISSUE TITLE
1.3.0 pool bug

### ISSUE THREAD

**Issue by OMeliante** [Chia-Network/chia-blockchain#10610] opened 2022-03-08 23:51 UTC
Updated to 1.3.0. I have 4 different NFT on the same wallet. All of tem was mining at space pool. After app update, all nft returned to mine at the first pool they were inserted. And I try to change pool and the pool does not change. It is stuck with the first pool they were created.

**Comment by Panteraldo** [comment] 2022-03-09 06:35
same here

**Comment by nmurray67** [comment] 2022-03-09 09:15
Same here, but... after copying back the old config.yaml file (no restart required), pooling resumed properly.

**Comment by mariano54** [comment] 2022-03-09 15:39
What operating system are you using, and what chia version were you using before?

**Comment by Muslix** [comment] 2022-03-09 15:55
Rename the Appdata/roaming/chia blockchain file and try to install the chia 1.3.0 update again.  it should work after that .  maybe u have to delete the wallet db as well.

**Comment by OMeliante** [comment] 2022-03-09 15:59
> If possible can you send me your config file to me on keybase (sorgente711)?

Already uninstalled 1.3.0 and running 1.2.11...

**Comment by OMeliante** [comment] 2022-03-09 16:02
> Rename the Appdata/roaming/chia blockchain file and try to install the chia 1.3.0 update again. it should work after that . maybe u have to delete the wallet db as well.

Already uninstalled 1.3.0. Running 1.2.11 and will wait for a new app version

**Comment by mariano54** [comment] 2022-03-09 16:06
If anyone is experiencing this issue, can you please send me your config.yaml and debug.log? It would really help us to solve this faster and make a new release with the fix.

Sorry for the issues.

**Comment by Muslix** [comment] 2022-03-09 16:17
> 

i think this problem is because of some cache folders in the roaming/chia blockchain folder. i tried some stuff and just after deleting(renamed) this one it all worked again.

**Comment by advlive** [comment] 2022-03-09 18:36
I was install 1.3 then I done upgrade but pool show like self and up mention name of pool!!!!
so many try change config file then tired and downgrade to 1.2.11 but always start make db file from 0 and interesting from v2. so many problem in this version 
most issue is all CAT tokens you have to add your self then show number of token!! and if I have some Cat but I don't know about that means need forget it

**Comment by mariano54** [comment] 2022-03-09 21:35
I think this should be fixed by: https://github.com/Chia-Network/chia-blockchain/pull/10631

**Comment by advlive** [comment] 2022-03-10 10:14
actually I find problem for not showing pool correct or show address pool but same time show as self pool
all because in config file authentication_public_key: show address without `0x` and only xchpool can understand for others need add 0x at firt of address 
also some pools remove name in pool_url:
and this also need add manually

**Comment by mariano54** [comment] 2022-03-10 15:26
@advlive are you on version 1.2.11? Version 1.3 should not use authentication_public_key anymore.

**Comment by OMeliante** [comment] 2022-03-10 15:31
I think when you download a Windows app, it should come ready to use, not needing to put something manually. I recomend use 1.2.11 until this 1.3.0 problem ( unexisted on other versions) is solved

**Comment by advlive** [comment] 2022-03-10 15:42
> @advlive are you on version 1.2.11? Version 1.3 should not use authentication_public_key anymore.

All issue happened in 1.3 new version also a lot more on wallet as can not show what CAT token you have ,need to add manually asset ID. and story become nice when you don't know in which token you have something

**Comment by nmurray67** [comment] 2022-03-10 18:22
At least for me, this isn't #10631. I'm running the node on Ubuntu 21.10, and upgraded from 1.2.11.

**Comment by emlowe** [comment] 2022-03-10 19:32
Consolidating issues - marking duplicate of #10590

**Closed by emlowe** 2022-03-10 19:32 UTC
