### ISSUE TITLE
[BUG] UI "Total Chia Farmed" stuck at 50

### ISSUE THREAD

**Issue by cameroncooper** [Chia-Network/chia-blockchain#1025] opened 2021-02-23 21:20 UTC
**Describe the bug**
My UI seems to get stuck at 50 under "Total Chia Farmed". I did see it briefly go to 51.5 but then quickly went back to 50.

**Expected behavior**
My wallet says 276 TXCH so I would expect my "Total Chia Farmed" to reflect that.

**Screenshots**
![image](https://user-images.githubusercontent.com/898689/108909664-6f989600-75ea-11eb-81b2-8d554ddd10ba.png)
![image](https://user-images.githubusercontent.com/898689/108909691-78896780-75ea-11eb-87ed-5d0ad04cf415.png)

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: i7-5820k

**Additional context**
Running 1.0rc2 from git main

**Comment by hoffmang9** [comment] 2021-02-23 21:22
Duplicate of https://github.com/Chia-Network/chia-blockchain-gui/issues/69 - gui issues go in the chia-blockchain-gui repo.

**Closed by hoffmang9** 2021-02-23 21:22 UTC
Labels: bug

**Comment by cameroncooper** [comment] 2021-02-23 21:23
Explains why I couldn't find it. Thanks, sorry about that.

**Comment by hoffmang9** [comment] 2021-02-23 21:24
No apology needed!  The issue is that once you hit 50 your rewards are paged off on the next page of results. Should be fixed in next release.
