### ISSUE TITLE
[BUG] Chia just shows window with number in it and doesn't find plots

### ISSUE THREAD

**Issue by LoculusMcMarx** [Chia-Network/chia-blockchain#3028] opened 2021-04-28 17:38 UTC
Yo, it suddenly just shows a number after restart, with a close field, then it doesn't find any plots that have been created. I add plots, but it doesn't add any. 

Win10 GUI i7 8700 - 32 gb ram -

**Comment by lvcivs** [comment] 2021-04-28 17:44
likely another duplicate of #2692

check there for comments

**Comment by lipalong** [comment] 2021-04-28 23:36
Yes, see the comments in #2692 
Also, we've made the wording for this error more clear in the next release.

**Closed by lipalong** 2021-04-28 23:36 UTC
Labels: bug
