### ISSUE TITLE
chia.rpc.rpc_server   

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#14026] opened 2022-11-29 16:43 UTC
### What happened?

2022-11-27T19:17:36.993 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 324, in safe_handle
  File "chia/rpc/rpc_server.py", line 315, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 2616, in pw_absorb_rewards
  File "chia/pools/pool_wallet.py", line 874, in claim_pool_rewards
ValueError: Nothing to claim, no unspent coinbase rewards

### Version

1.7.0b2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-27T19:17:06.268 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.0199739933013916
2022-11-27T19:17:36.993 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 324, in safe_handle
  File "chia/rpc/rpc_server.py", line 315, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 2616, in pw_absorb_rewards
  File "chia/pools/pool_wallet.py", line 874, in claim_pool_rewards
ValueError: Nothing to claim, no unspent coinbase rewards

2022-11-27T19:18:35.705 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.03621673583984375
2022-11-27T19:18:54.388 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.020396709442138672
```

**Comment by MumfMeisterT** [comment] 2022-12-15 20:10
Unsure of what the issue is. -- May be future enhancement to traceback error. Closing.

**Closed by MumfMeisterT** 2022-12-15 20:10 UTC
Labels: bug, RPC, GUI, Linux, need info, 1.7.0-b1
