### ISSUE TITLE
[BUG] Connecting to wallet issue

### ISSUE THREAD

**Issue by samy63** [Chia-Network/chia-blockchain#5904] opened 2021-05-23 23:39 UTC
![image](https://user-images.githubusercontent.com/84105006/119280467-dbae8880-bc31-11eb-9a3e-981a1d8577c2.png)

I tried to remove .chia and after  to reinstall chia  but nothing works, i have still "connecting to wallet" issue

kindly fix this bug, a lot of people has this issue connection

this issue high priority, can't use the application

thank you in advance

**Comment by mezcalz9** [comment] 2021-05-23 23:56
I got the same problem

**Comment by Ozarkstacker** [comment] 2021-05-24 02:23
Me too!!!! Spools with "Connecting to Wallet".  Is there a fix?

**Comment by agueromauro** [comment] 2021-05-24 08:13
el mismo problema, ya probé reinstalando, finalizando tareas, y nada

**Comment by lvpcguru** [comment] 2021-05-24 12:04
> 
> 
> ![image](https://user-images.githubusercontent.com/84105006/119280467-dbae8880-bc31-11eb-9a3e-981a1d8577c2.png)
> 
> I tried to remove .chia and after to reinstall chia but nothing works, i have still "connecting to wallet" issue
> 
> kindly fix this bug, a lot of people has this issue connection
> 
> this issue high priority, can't use the application
> 
> thank you in advance

What OS? What Version of Chia?

**Comment by mezcalz9** [comment] 2021-05-24 14:56
For my part, I did this and it worked, but I had to close chia and lost my plots in progess..

Close the Chia wallet or exit

Kill all Chia processes from “Task Manager”

Navigate to: C:\Users\YourUserName\.chia\mainnet\db
Delete all bolockchain* files.

**Comment by juliootoni** [comment] 2021-05-25 00:45
Aqui deu certo!! obrigado!!

**Comment by juliootoni** [comment] 2021-05-25 00:48
https://youtu.be/836HaeLLpxA

**Comment by lvpcguru** [comment] 2021-05-25 19:05
> 
> 
> Aqui deu certo!! obrigado!!

Nice! close the issue then please.

**Comment by wht3** [comment] 2021-05-26 17:15
Got this issue yesterday, after spending 4 days just trying to overcome another bug which i couldnt sync the wallet. 
After i finally solved and synced, my wallet wont connect anymore, i tried uninstalling and starting from 0 and it works, but come on, i'll have to sync my wallet all over again? I tried copying my synced wallet but then i get the "connecting to wallet" forever.
Its been a frustrating week.

**Comment by lvpcguru** [comment] 2021-05-27 02:34
Yeah the wallet syncing still has some work to do especially when dealing with existing dbs from a migration or an attempt to preseed the file from an already synced system. Glad you got it going tho. I know it took me a few days of troubleshooting to get it to be happy.

**Comment by mariano54** [comment] 2021-06-28 07:56
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:56 UTC
Labels: bug
