### ISSUE TITLE
start wallet failed[Bug] 

### ISSUE THREAD

**Issue by evelynEdison** [Chia-Network/chia-blockchain#11982] opened 2022-06-20 07:27 UTC
### What happened?

start wallet failed

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
C:\Users\86150\AppData\Local\chia-blockchain\app-1.3.5\resources\app.asar.unpacked\daemon>chia start wallet
Daemon not started yet
Starting daemon
chia_wallet: started

C:\Users\86150\AppData\Local\chia-blockchain\app-1.3.5\resources\app.asar.unpacked\daemon>Traceback (most recent call last):
  File "Lib\site-packages\chia\server\start_wallet.py", line 99, in <module>
  File "Lib\site-packages\chia\server\start_wallet.py", line 94, in main
  File "chia\server\start_service.py", line 286, in run_service
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\server\start_service.py", line 280, in async_run_service
  File "chia\server\start_service.py", line 190, in run
  File "chia\server\start_service.py", line 152, in start
  File "chia\wallet\wallet_node.py", line 213, in _start
  File "chia\wallet\wallet_state_manager.py", line 165, in create
  File "chia\wallet\wallet_blockchain.py", line 51, in create
  File "chia\wallet\key_val_store.py", line 47, in get_object
  File "chia\util\streamable.py", line 549, in from_bytes
  File "chia\util\streamable.py", line 491, in parse
  File "chia\util\streamable.py", line 490, in <genexpr>
  File "chia\util\streamable.py", line 473, in <lambda>
  File "chia\util\streamable.py", line 231, in parse_list
  File "chia\util\streamable.py", line 491, in parse
  File "chia\util\streamable.py", line 490, in <genexpr>
  File "chia\util\streamable.py", line 473, in <lambda>
  File "chia\util\streamable.py", line 231, in parse_list
  File "chia\util\streamable.py", line 491, in parse
  File "chia\util\streamable.py", line 490, in <genexpr>
  File "chia\util\streamable.py", line 464, in <lambda>
  File "chia\util\streamable.py", line 214, in parse_optional
  File "chia\util\streamable.py", line 491, in parse
  File "chia\util\streamable.py", line 490, in <genexpr>
  File "chia\util\streamable.py", line 195, in parse_bool
ValueError: Bool byte must be 0 or 1
[8156] Failed to execute script 'start_wallet' due to unhandled exception!
```

**Comment by arvidn** [comment] 2022-06-26 10:28
at the lowest level, this error means that the value for `SYNCED_WEIGHT_PROOF` (in the `key_val_store` table) is corrupt. We try to parse the blob as a `WeightProof`, and that fails. The bytes in there cannot be parsed as that object.

Do you have any reason to believe your wallet database can have become corrupt?

**Comment by evelynEdison** [comment] 2022-06-27 05:44
No, but I think so.  How to check it out? My pc crashed before the error occurred. I renamed the wallet database folder and it works now.

**Comment by arvidn** [comment] 2022-06-28 11:36
> My pc crashed before the error occurred.

I suspect that's what caused it.

**Comment by emlowe** [comment] 2022-06-28 22:15
I believe you will need is move/delete you wallet DB and let it resync.

**Comment by emlowe** [comment] 2023-01-06 19:32
Closing issue likely caused by PC crash

**Closed by emlowe** 2023-01-06 19:32 UTC
Labels: bug
