### ISSUE TITLE
In Farm Tab on the GUI, Last Attempted Proof has the older challenge at the top, when it should be at the bottom[BUG]

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#8265] opened 2021-08-29 09:38 UTC
Hi Team,

The order in the Last Attempted Proof area in the Farm tab still has the oldest Challenge at the top, and the newest at the bottom. Previous versions had this the other way around, ie newest at the top, which I find is better.  Would it be possible to revert this back to the way it was previously, or have a toggle to change it at a user level

![image](https://user-images.githubusercontent.com/36589806/131245903-a060573c-c4ca-4ace-a1cb-fceb2d703370.png)

**Comment by emlowe** [comment] 2021-08-30 22:52
Duplicate of #7856

**Closed by emlowe** 2021-08-30 22:52 UTC
Labels: bug, enhancement
