### ISSUE TITLE
[Bug] NFT Javascript error

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#13830] opened 2022-11-05 08:34 UTC
### What happened?

When minting new NFT's, I get the following Javascript error:
![image](https://user-images.githubusercontent.com/12736950/200111112-2c7ff25f-db43-439c-b992-b0dc3dd7ebfb.png)

The error usually occurrs once per loading of each of my nfts.
afterwards its working fine. But it's very annoying and I suspect that also ppl who buy buy it get this issue.

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment] 2022-11-10 20:53
Have you tried to see if installing 1.6.1 resolves this?

**Comment by forReason** [comment] 2022-11-10 22:09
not yet. Im staying on 1.6 for a little while until the release is a little older. 
I need to keep kompatibility with offer files and 1.6.1 might break that as stated in the release notes.

I might try it out though to see if this error is resolved. What would be the rollback procedure for 1.6.1 -> 1.6?

**Comment by bwccnft** [comment] 2022-11-11 17:05
we have experie
![JavaScript161](https://user-images.githubusercontent.com/115654928/201392291-e5938120-e4a8-4f4b-a336-c75e069f587c.png)
nced the similar issue on 1.6.1.

**Comment by forReason** [comment] 2022-11-12 14:00
upgraded to 1.6.1 due to other issues

**Comment by wallentx** [comment] 2022-11-17 20:33
This should be fixed in `main` currently via https://github.com/Chia-Network/chia-blockchain-gui/pull/1147

**Closed by wallentx** 2022-11-17 20:33 UTC
Labels: bug, javascript, GUI, Windows, Wallet, NFT, 1.6.0

**Comment by KryptomineCH** [comment] 2022-12-02 12:00
recently, couldnt reproduce the issue. thx

**Comment by Darbletan** [comment] 2023-02-06 20:38
I am hitting this error on 2 machines now. 

1 of them is even a fresh install that's never had an older version of Chia, both are on 1.6.2. 

![image](https://user-images.githubusercontent.com/69985952/217079884-1cb15d27-71dd-4b8d-b714-d493aef69fd7.png)

**Comment by forReason** [comment] 2023-02-24 10:33
also still get the issue with 1.7.0
