### ISSUE TITLE
[BUG] Harvester periodically segfaults

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#477] opened 2020-10-17 22:12 UTC
**Describe the bug**
When running just the harvester that connects to a farmer running on another machine, the harvester process sometimes segfaults.

This seems to happen only when rcloning or rsyncing completed plots from other machines to the harvester. My guess is the harvester happens to be trying to read a proof from a plot with a partially copied file.

**To Reproduce**
Setup Farmer on another machine.
Start harvester.
Start large amount of rclone copies of completed plots to harvester.

**Expected behavior**
Harvester should not segfault.

**Desktop (please complete the following information):**
- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.1 LTS
- CPU: Intel Xeon Silver 4215R

**Additional context**
Contact @efishcent or @lamiaceae on Keybase for followup questions.

**Comment by hoffmang9** [comment] 2020-11-09 14:05
I'm closing this as I think it's a duplicate of the issue fixed in #500

**Closed by hoffmang9** 2020-11-09 14:05 UTC
Labels: bug
