### ISSUE TITLE
[Bug] Latest beta release 1.3.6926

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#12018] opened 2022-06-22 19:11 UTC
### What happened?

The log file is filling up faster than I can open to read it. Goes to 51k in less than 2 minutes.

### Version

13.6926

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-22T15:04:03.013 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.016 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.021 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.024 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.028 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.030 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.033 wallet wallet                     : INFO     Started wallet service on network_id: mainnet
2022-06-22T15:04:03.036 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.039 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-06-22T15:04:03.057 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.062 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.066 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-22T15:04:03.069 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Tas
```

**Comment by 0X1231** [comment] 2022-06-23 04:46
1.3.6935问题仍然存在

**Comment by 0X1231** [comment] 2022-06-23 17:38
1.3.6943问题仍然存在

**Comment by wallentx** [comment] 2022-06-23 18:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/11980

**Closed by wallentx** 2022-06-23 18:18 UTC
Labels: bug

**Comment by Drhicom** [comment] 2022-06-23 19:38
Why are we still releasing new beta versions with the same issues?
