### ISSUE TITLE
[BUG] SSL Error continues on Chia 1.2.1

### ISSUE THREAD

**Issue by Kobryta** [Chia-Network/chia-blockchain#7444] opened 2021-07-13 10:32 UTC
**Describe the bug**
I just updated to Chia 1.2.1 and the SSL error is still there. My pool points and stats are still freezed. 

**To Reproduce**

My Debug log:

2021-07-13T11:30:21.712 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://eu1.pool.space, Cannot connect to host eu1.pool.space:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

**Expected behavior**
I thought that with version 1.2.1 this will be fixed but it is not.

**Screenshots**
![image](https://user-images.githubusercontent.com/87368023/125437400-386d8f9f-0b07-469e-a485-1d90f8c13e78.png)

- OS: Mac
- OS Version/Flavor: Mojave
- CPU: 2,7 GHz Intel Core i5

**Additional context**

**Comment by Kobryta** [comment] 2021-07-13 12:40
Let's see if anyone has a good fix for this of we have to wait until 1.2.2!

**Comment by btcbay-net** [comment] 2021-07-13 13:20
same here , Plz fix it . OS :  MACOS 11.3.1 

2021-07-13T21:16:31.065 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

**Comment by Portago9** [comment] 2021-07-13 14:45
Same here, on win10

**Comment by scriper88** [comment] 2021-07-13 15:48
i have the same problem with 1.2 and 1.2.1

**Comment by scriper88** [comment] 2021-07-13 15:49
"Pool Login Link"-Button shows a Error: Something went wrong.
Same Problem?

**Comment by bernharl** [comment] 2021-07-13 17:31
Happens on Arch Linux as well

**Comment by sdbarrish** [comment] 2021-07-13 23:09
021-07-13T19:08:27.937 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9be70470>
transport: <_SelectorSocketTransport fd=111 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Comment by dcrafti** [comment] 2021-07-14 06:43
I'm also having this problem. How come most people aren't?
Is it related to developer tools and/or VPNs being installed?

**Comment by Aidan24** [comment] 2021-07-14 13:48
I also have the same problem. But it only seems to occur when I am plotting using above about 50% CPU. Perhaps something is timing out. I also now can't see the Pool Login Link and I notice the farming tab is showing Challenges out of time order and lagging behind by about 10 minutes.

**Comment by Aidan24** [comment] 2021-07-14 13:53
I should also add Challenge Hashes are out of order too. 
![New Bitmap Image](https://user-images.githubusercontent.com/41297044/125634083-20c01a98-82e1-45a2-8718-5a0dbef36c00.png)

**Comment by Bingo821227** [comment] 2021-07-14 19:17
1+

**Comment by emlowe** [comment] 2021-07-14 19:18
Duplicate of #7273

**Closed by emlowe** 2021-07-14 19:18 UTC
Labels: bug

**Comment by sdbarrish** [comment] 2021-07-14 19:55
2021-07-14T15:54:59.556 full_node asyncio                 : ERROR    Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fa486a208>
transport: <_SelectorSocketTransport fd=95 read=polling write=<polling, bufsize=19923>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2021-07-14T15:54:59.561 full_node full_node_server        : INFO     Connection closed: 1.48.5.56, node id: 99ee1fd3ea9e9b522459ce6b0fbece941ed978f33d4f4dc8a2600c93ddf38bfd

**Comment by sdbarrish** [comment] 2021-07-14 21:32
Running v1.2.2 on a Raspberry Pi 4

2021-07-14T17:30:25.894 full_node full_node_server        : ERROR    Exception: Failed to fetch block 571953 from None, timed out, None. Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/pi/chia-blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 398, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 571953 from None, timed out

2021-07-14T17:30:25.895 full_node full_node_server        : ERROR    Exception: Failed to fetch block 571953 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/home/pi/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/home/pi/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/pi/chia-blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 398, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 571953 from None, timed out

**Comment by njtnestor** [comment] 2021-07-15 07:18
I have same problem in 1.2.2
