### ISSUE TITLE
[BUG]1.1.6 in centos7, install error

### ISSUE THREAD

**Issue by adi100** [Chia-Network/chia-blockchain#5656] opened 2021-05-21 05:00 UTC
**Describe the bug**
Python version is 3
Requirement already satisfied: pip in ./venv/lib/python3.6/site-packages (21.1.1)
Requirement already satisfied: wheel in ./venv/lib/python3.6/site-packages (0.36.2)
Looking in indexes: https://pypi.org/simple, https://pypi.chia.net/simple/
Requirement already satisfied: miniupnpc==2.1 in ./venv/lib/python3.6/site-packages (2.1)
Looking in indexes: https://pypi.org/simple, https://pypi.chia.net/simple/
Obtaining file:///home/admin/chia-blockchain
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting aiosqlite==0.17.0
  Downloading aiosqlite-0.17.0-py3-none-any.whl (15 kB)
Collecting keyring==23.0.1
  Using cached keyring-23.0.1-py3-none-any.whl (33 kB)
Collecting dnspython==2.1.0
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Collecting PyYAML==5.4.1
  Using cached PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
Collecting clvm==0.9.6
  Downloading clvm-0.9.6-py3-none-any.whl (19 kB)
ERROR: Could not find a version that satisfies the requirement chiavdf==1.0.1 (from chia-blockchain) (from versions: 0.2b1, 0.2b2, 0.2b3, 0.2b4, 0.2b6, 0.3b1, 0.3b2, 0.3b3, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10)
ERROR: No matching distribution found for chiavdf==1.0.1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hb020** [comment] 2021-05-21 06:19
<rant>Somewhat miffed by the excruciatingly low quality of the issue reports here.</rant>

You do not seem to have followed the installation instructions. 
See https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#centosred-hatfedora
It explicitly states that you need Python 3.7, multiple times. You have Python 3.6.
Please close this issue, it is not a bug.

**Closed** 2021-05-21 07:23 UTC
Labels: bug
