### ISSUE TITLE
Stuck connecting to wallet in 1.1.16 on Win 10

### ISSUE THREAD

**Issue by wcbutler** [Chia-Network/chia-blockchain#6478] opened 2021-06-05 16:55 UTC
Rebooted my machine, uninstalled, removed %appdata% info, reinstalled. No luck. Same issue if I backrev to 1.1.15

**Comment by 13361217208** [comment] 2021-06-05 17:25
我的也是

**Comment by wcbutler** [comment] 2021-06-05 17:29
Also note I removed the chia directory in /roaming and /local

**Comment by FSys77** [comment] 2021-06-05 17:42
> 
> 
> Rebooted my machine, uninstalled, removed %appdata% info, reinstalled. No luck. Same issue if I backrev to 1.1.15

Same here. Blockchain is fully synced, but Wallet stopped syncing a few days ago.

Chia software is such a piece of shit!

**Comment by wcbutler** [comment] 2021-06-05 18:04
Okay I had to blast out my whole c:\users\Username\.chia directory and finally got back up to syncing wallet. Here's a days wait to see if this fixes things. Tried moving my blockchain_v1_mainnet.sqlite file over to save me from resyncing but it didn't seem to know what to do with it and just said it was unsynched

**Comment by jmz-bit** [comment] 2021-06-05 20:41
Similar problem. I didn't use Chia Windows app for a week. Blockchain was fully synced after 2 hours. But wallet didn't start syncing at all.

Please improve syncing problems as this is really bad looking!

Full sync should be done much quicker and it should be reliable!

**Comment by Ron-ski** [comment] 2021-06-05 22:47
I'm also having issues, rebooted the PC after closing GUI. Stuck connecting to wallet, closed GUI. Backup and deleted wallet, eventually got GUI to open, but wallet not syncing. Closed and restored the back up wallet DB, GUI opened, wallet stuck at height of 387,359 with 1 connection for 12 hours now. Have noticed the following in the logs.

For now have deleted the wallet DB and peer DB, will see what happens over night.

> 2021-06-05T23:24:42.483 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
>   File "chia\server\server.py", line 526, in wrapped_coroutine
>   File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
>   File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
>   File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
>   File "chia\consensus\blockchain.py", line 695, in get_block_records_at
>   File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
>   File "aiosqlite\core.py", line 184, in execute
>   File "aiosqlite\core.py", line 129, in _execute
>   File "aiosqlite\core.py", line 102, in run
> sqlite3.OperationalError: too many SQL variables
> 
> 2021-06-05T23:24:42.484 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
>   File "chia\server\server.py", line 536, in api_call
>   File "asyncio\tasks.py", line 442, in wait_for
>   File "chia\server\server.py", line 533, in wrapped_coroutine
>   File "chia\server\server.py", line 526, in wrapped_coroutine
>   File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
>   File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
>   File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
>   File "chia\consensus\blockchain.py", line 695, in get_block_records_at
>   File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
>   File "aiosqlite\core.py", line 184, in execute
>   File "aiosqlite\core.py", line 129, in _execute
>   File "aiosqlite\core.py", line 102, in run
> sqlite3.OperationalError: too many SQL variables
> 
> 2021-06-05T23:24:42.485 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
> 2021-06-05T23:24:42.486 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id:

**Comment by walruzperil** [comment] 2021-06-05 23:05
Same error.. wtf?

**Comment by MarcusB2105** [comment] 2021-06-06 02:18
There are four issues to the same problem already: #6478 and #6466 and #6450 including this one #6455 .

**Comment by mariano54** [comment] 2021-06-28 07:56
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:56 UTC
