### ISSUE TITLE
[BUG] The Delete button (to delete plotting file) is disabled in Windows version.

### ISSUE THREAD

**Issue by panleicim** [Chia-Network/chia-blockchain#5982] opened 2021-05-25 07:21 UTC
**Describe the bug**
We cannot delete a plotting file in Windows: the delete button is disabled in windows.

**To Reproduce**

1. Install Chia in Windows.
2. Start to plot a file
3. The delete button is disabled

**Expected behavior**
The delete button is enabled so that we can delete a plotting file if there is an error.

**Screenshots**
Here is a screen shot from macOS(the delete button is enabled.):
![image](https://user-images.githubusercontent.com/1309133/119455530-f8ce7e80-bd39-11eb-9805-1b14920be0c6.png)

Here are 2 screen shots from Windows (the delete button is disabled.)
![image](https://user-images.githubusercontent.com/1309133/119455693-23b8d280-bd3a-11eb-82c2-1ace7c3f58bc.png)
![image](https://user-images.githubusercontent.com/1309133/119456027-85793c80-bd3a-11eb-8eb1-55a90c70147d.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- CPU:Intel Xeon 2609V3
- Chia application version : 1.1.6

**Comment by brayster** [comment] 2021-05-25 08:02
me too. 

Version 1.1.6 Window 10

**Comment by FSys77** [comment] 2021-05-25 08:20
The GUI is utter crap! Probably programmed by an intern in under 1 week. Don't use it, use the CLI.

The Chia devs have pre-mined 21 million coins (current worth: 15 billion US$), still they give us this crappy software.

**Comment by lvpcguru** [comment] 2021-05-25 10:46
I believe there is an old note about that being disabled for now. It causes a hang in the GUI that forces a reload killing the rest of your plots as well. Most people are plotting with CLI right now

**Comment by lvpcguru** [comment] 2021-05-25 11:17
also this is a duplicate of [https://github.com/Chia-Network/chia-blockchain/issues/5975](https://github.com/Chia-Network/chia-blockchain/issues/5975)

**Comment by n4ndo** [comment] 2021-05-25 14:07
@FSys77 thats true, totally a scam this crypt.. lel

**Comment by panleicim** [comment] 2021-05-25 14:29
I close this issue as it is a feature disabled temporarily.

**Closed** 2021-05-25 14:29 UTC
Labels: bug
