### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OldButtKicking** [Chia-Network/chia-blockchain#7389] opened 2021-07-12 03:27 UTC
**Describe the bug**
It appears new pooling plots in new folders are being used but not counted toward the total plot count on the farm tab.

Create a new plot with MadMax in a new drive/folder, with the pool certificate info
Add the folder via Add new plot folder.

The total plot count does not include the new plot but the plots passed filter does

**Expected behavior**
Total plot count includes the new plot

**Screenshots**
![image](https://user-images.githubusercontent.com/58090640/125226526-1de56500-e286-11eb-9099-149e27306169.png)

**Desktop**
Windows 10 Pro

**Additional context**
this is in the log

2021-07-11T20:12:26.394 harvester chia.plotting.plot_tools: INFO     Loaded a total of 513 plots of size 50.77718091068891 TiB, in 0.26158571243286133 seconds

**Comment by temicus** [comment] 2021-07-12 04:11
Same problem. Nothing helps. Have deleted everything inkl. all folders and reinstalled. The problem remains.

**Comment by emlowe** [comment] 2021-07-12 15:28
Duplicate of #7262

**Closed by emlowe** 2021-07-12 15:28 UTC
Labels: bug
