### ISSUE TITLE
Not loading into wallet

### ISSUE THREAD

**Issue by onetakeseb** [Chia-Network/chia-blockchain#6348] opened 2021-06-02 08:01 UTC
I shut down my computer and when i booted it up again I opened up Chia and it says it is loading wallet but it has been saying that for 3 hours now...

**Comment by amirdanesh1991** [comment] 2021-06-02 10:36
I opened up Chia and it says it is loading wallet but it has been saying that for 24 hours now...

**Comment by Entretoize** [comment] 2021-06-02 14:03
Same thing for me...

**Comment by Levisvl** [comment] 2021-06-02 14:47
And same for me, how fix it?

**Comment by Entretoize** [comment] 2021-06-02 16:16
I uninstalled, deleted c:/Users/me/.chia folder and reinstalled, and it works now !

**Comment by Watchkido** [comment] 2021-06-02 16:30
Same thing for me...

**Comment by Watchkido** [comment] 2021-06-02 16:31
> I uninstalled, deleted c:/Users/me/.chia folder and reinstalled, and it works now

Great idea! How long will you have to wait to be Syncron again? 7 days?

**Comment by Elyasin** [comment] 2021-06-02 21:07
Two days for syncing with a 100 Mb/s connection, at that time the network size was in decline/stagnating. It will take longer in the future, expecting the network to grow.

With that in mind, this bug is important to fix. Or a workaround that does not force you to redo a complete sync which makes you lose days.

**Comment by Entretoize** [comment] 2021-06-03 05:31
I don't know how long it will take, I'm new to chia... maybe making a copy of the .chia folder after plotting and from time to time will help.

**Comment by Rja-A** [comment] 2021-06-03 07:15
I have not connected to the wallet for 4 days. Deleting folders and reinstalling doesn't help. 
Does anyone know how to fix this?
![ER](https://user-images.githubusercontent.com/85277951/120602962-2e6b1a00-c454-11eb-855a-a65d2a95d633.JPG)

**Comment by LoudCloudDragon** [comment] 2021-06-03 12:35
I don't know how to fix it, but since syncing the Full Node to the B.C, and syncing the wallet is a never-ending nightmare, do not **delete all** of the subfolders/files in mainnet. Only the folders containing the files of the subsystem that is wonky. You can almost always keep *config, run, and log*. (log folder and contents don't take long to rebuild so it's kind of a moot point). If the wallet is the issue, just delete the wallet folder, shutdown the node, manually check/kill all relevant PID's, fire it back up. Sometimes I will issue the restart cmd (terminal) 4, 5, 17 times before I finally see that it is moving along. Be sure to give it 3-6 minutes though

**Comment by mariano54** [comment] 2021-06-28 07:59
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:59 UTC
