### ISSUE TITLE
Not able to connect to wallet 

### ISSUE THREAD

**Issue by yoga2005live** [Chia-Network/chia-blockchain#8420] opened 2021-09-09 16:04 UTC
My Chia UI is not able to connect to wallet

**To Reproduce**
After click the chia icon it keeps saying that is not able to connect to the wallet

![image](https://user-images.githubusercontent.com/17745923/132721578-5415f003-675d-4548-a6cd-effb8103ea5e.png)

**Comment by mariano54** [comment] 2021-09-09 20:13
Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.

**Comment by yoga2005live** [comment] 2021-09-10 05:20
2021-09-09T14:19:40.201 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:42.232 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCF40> [The remote computer refused the network connection]
2021-09-09T14:19:45.240 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:46.926 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:19:46.927 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:19:47.273 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC0C0> [The remote computer refused the network connection]
2021-09-09T14:19:50.276 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:52.310 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:19:55.305 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:57.336 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:00.358 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:02.395 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:20:05.408 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:07.445 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC1C0> [The remote computer refused the network connection]
2021-09-09T14:20:10.452 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:12.475 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCAC0> [The remote computer refused the network connection]
2021-09-09T14:20:15.484 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:17.510 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56C940> [The remote computer refused the network connection]
2021-09-09T14:20:20.511 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:22.536 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC2C0> [The remote computer refused the network connection]
2021-09-09T14:20:25.537 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:27.559 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:30.568 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:32.596 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:20:35.598 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:37.622 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCF40> [The remote computer refused the network connection]
2021-09-09T14:20:40.634 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:42.665 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCA40> [The remote computer refused the network connection]
2021-09-09T14:20:45.024 harvester chia.harvester.harvester: INFO     refresh_batch: loaded_plots 0, loaded_size 0.00 TiB, removed_plots 0, processed_plots 0, remaining_plots 0, duration: 0.04 seconds
2021-09-09T14:20:45.680 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:47.719 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC940> [The remote computer refused the network connection]
2021-09-09T14:20:48.638 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:20:48.638 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:20:50.738 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:52.767 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:55.783 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:57.821 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:21:00.831 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:02.859 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:05.864 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:07.881 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EF040> [The remote computer refused the network connection]
2021-09-09T14:21:10.904 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:12.938 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFB40> [The remote computer refused the network connection]
2021-09-09T14:21:15.944 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:17.955 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFAC0> [The remote computer refused the network connection]
2021-09-09T14:21:20.957 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:23.006 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFEC0> [The remote computer refused the network connection]
2021-09-09T14:21:26.010 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:28.042 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EF5C0> [The remote computer refused the network connection]
2021-09-09T14:21:31.057 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:33.099 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:36.101 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:38.129 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:21:41.130 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:43.177 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:21:46.187 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:48.228 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFC40> [The remote computer refused the network connection]
2021-09-09T14:21:50.441 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:21:50.443 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:21:51.247 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:53.286 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:56.292 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:58.324 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:22:01.336 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:22:03.363 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]

**Comment by yoga2005live** [comment] 2021-09-10 05:20
> Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.

this is what i am getting 
2021-09-09T14:19:40.201 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:42.232 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCF40> [The remote computer refused the network connection]
2021-09-09T14:19:45.240 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:46.926 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:19:46.927 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:19:47.273 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC0C0> [The remote computer refused the network connection]
2021-09-09T14:19:50.276 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:52.310 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:19:55.305 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:19:57.336 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:00.358 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:02.395 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:20:05.408 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:07.445 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC1C0> [The remote computer refused the network connection]
2021-09-09T14:20:10.452 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:12.475 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCAC0> [The remote computer refused the network connection]
2021-09-09T14:20:15.484 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:17.510 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56C940> [The remote computer refused the network connection]
2021-09-09T14:20:20.511 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:22.536 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC2C0> [The remote computer refused the network connection]
2021-09-09T14:20:25.537 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:27.559 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:30.568 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:32.596 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:20:35.598 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:37.622 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCF40> [The remote computer refused the network connection]
2021-09-09T14:20:40.634 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:42.665 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FCA40> [The remote computer refused the network connection]
2021-09-09T14:20:45.024 harvester chia.harvester.harvester: INFO     refresh_batch: loaded_plots 0, loaded_size 0.00 TiB, removed_plots 0, processed_plots 0, remaining_plots 0, duration: 0.04 seconds
2021-09-09T14:20:45.680 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:47.719 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5FC940> [The remote computer refused the network connection]
2021-09-09T14:20:48.638 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:20:48.638 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:20:50.738 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:52.767 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:20:55.783 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:20:57.821 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:21:00.831 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:02.859 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:05.864 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:07.881 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EF040> [The remote computer refused the network connection]
2021-09-09T14:21:10.904 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:12.938 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFB40> [The remote computer refused the network connection]
2021-09-09T14:21:15.944 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:17.955 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFAC0> [The remote computer refused the network connection]
2021-09-09T14:21:20.957 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:23.006 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFEC0> [The remote computer refused the network connection]
2021-09-09T14:21:26.010 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:28.042 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EF5C0> [The remote computer refused the network connection]
2021-09-09T14:21:31.057 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:33.099 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:36.101 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:38.129 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:21:41.130 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:43.177 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]
2021-09-09T14:21:46.187 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:48.228 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F5EFC40> [The remote computer refused the network connection]
2021-09-09T14:21:50.441 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'error_code': 12, 'error_message': 'Invalid authentication token'}
2021-09-09T14:21:50.443 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token
2021-09-09T14:21:51.247 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:53.286 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CD40> [The remote computer refused the network connection]
2021-09-09T14:21:56.292 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:21:58.324 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CC40> [The remote computer refused the network connection]
2021-09-09T14:22:01.336 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-09T14:22:03.363 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001881F56CEC0> [The remote computer refused the network connection]

**Comment by Stepyon** [comment] 2021-09-10 14:04
The same issue on Raspberry pi 4 after upgrading to 1.2.6. But on Windows works fine.

**Comment by Stepyon** [comment] 2021-09-10 14:53
The same issue on Raspberry pi 4 8Gb after upgrading to 1.2.6. But on Windows works fine.
![IMG_20210910_155042](https://user-images.githubusercontent.com/23343477/132873370-3b748992-b00b-4e28-8eab-b243ecf960cc.jpg)

**Comment by mariano54** [comment] 2021-09-10 16:13
Looks like your node is zombie. have you tried restarting your computer?

**Comment by Stepyon** [comment] 2021-09-10 18:05
> Looks like your node is zombie. have you tried restarting your computer?

I tried, didn't help, connecting forever. What should I do now? On 1.2.5 I had no issues before.

**Comment by loppefaaret** [comment] 2021-09-13 15:06
try closing down Chia, open it up, and then look in `debug.log` for any messages from `full_node` - we need to know what is happening to the `full_node`

**Comment by yoga2005live** [comment] 2021-09-13 20:32
I lost two days because the only that i was able to do was resync the whole node again 👎

**Comment by thomasjvnk** [comment] 2021-09-14 00:38
> try closing down Chia, open it up, and then look in `debug.log` for any messages from `full_node` - we need to know what is happening to the `full_node`

i'm having this issue

here is the full_node message:

2021-09-04T17:06:56.150 full_node full_node_server        : ERROR    Exception: Failed to fetch block 813038 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 813038 from None, timed out

2021-09-04T17:06:56.152 full_node full_node_server        : ERROR    Exception: Failed to fetch block 813038 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 813038 from None, timed out

2021-09-05T09:27:12.229 full_node full_node_server        : WARNING  Cannot write to closing transport 69.178.113.57
2021-09-05T13:51:44.013 harvester chia.harvester.harvester: WARNING  Looking up qualities on E:\plot chia\plot-k32-2021-08-10-18-10-f0ac27a71e522be79f298d40643788c21af1987964a911f0b2dae350fce90642.plot took: 5.437026739120483. This should be below 5 seconds to minimize risk of losing rewards.
2021-09-07T02:08:14.526 full_node full_node_server        : ERROR    Exception: database or disk is full, {'host': '68.227.1.80', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 328, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 1202, in respond_block
  File "chia\consensus\blockchain.py", line 265, in receive_block
  File "chia\consensus\blockchain.py", line 364, in _reconsider_peak
  File "chia\full_node\coin_store.py", line 81, in new_block
  File "chia\full_node\coin_store.py", line 232, in _add_coin_record
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: database or disk is full

2021-09-07T02:08:15.468 full_node full_node_server        : ERROR    Exception: database or disk is full, {'host': '190.19.109.46', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 328, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 1202, in respond_block
  File "chia\consensus\blockchain.py", line 265, in receive_block
  File "chia\consensus\blockchain.py", line 364, in _reconsider_peak
  File "chia\full_node\coin_store.py", line 81, in new_block
  File "chia\full_node\coin_store.py", line 232, in _add_coin_record
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: database or disk is full

2021-09-07T02:08:15.559 full_node full_node_server        : WARNING  Banning 68.227.1.80 for 10 seconds
2021-09-07T02:22:49.959 full_node full_node_server        : WARNING  Banning 85.201.34.43 for 10 seconds
2021-09-08T06:19:45.563 full_node full_node_server        : WARNING  Cannot write to closing transport 47.148.158.242
2021-09-08T22:25:17.998 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-10T12:02:32.328 full_node full_node_server        : ERROR    Exception: Failed to fetch block 839852 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 839852 from None, timed out

2021-09-10T12:02:32.333 full_node full_node_server        : ERROR    Exception: Failed to fetch block 839852 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 839852 from None, timed out

2021-09-10T19:13:50.372 full_node full_node_server        : WARNING  Cannot write to closing transport 91.125.65.77

**Comment by loppefaaret** [comment] 2021-09-16 14:48
`sqlite3.OperationalError: database or disk is full`
You've out of space on the filesystem that holds the blockchain

**Comment by loppefaaret** [comment] 2021-09-16 14:52
> > Looks like your node is zombie. have you tried restarting your computer?
> 
> I tried, didn't help, connecting forever. What should I do now? On 1.2.5 I had no issues before.

if you are still facing problem, i suggest you open a support discussion to get further help:
https://github.com/Chia-Network/chia-blockchain/discussions/categories/support
including ERROR from your `debug.log` from the `full_node` so we can identify what the issue is!

**Comment by loppefaaret** [comment] 2021-09-16 14:53
> I lost two days because the only that i was able to do was resync the whole node again 👎
sorry for the inconvinience you experienced, but i am glad you had the issue resolved!
on that note, this issue is closed

**Closed by loppefaaret** 2021-09-16 14:53 UTC
Labels: bug
