### ISSUE TITLE
Missing XCH, Pending transactions, Doublespend non existing XCH[Bug] 

### ISSUE THREAD

**Issue by Oscillator098** [Chia-Network/chia-blockchain#13963] opened 2022-11-19 19:02 UTC
### What happened?

Hi, in the picture below I came across many issues:
After winning a block (Self pooling) +0.25 to xch...3wys i tried to claim +1.75 on xch...289y that did not show in my wallet.
I Increased Derivation index from 2000 to 5000 also;
  inbound_rate_limit_percent: 100
  initial_num_public_keys: 900
I have maybe several hundreds of transactions.

After I tried to flush that +1.75XCH by sending -7.5XCH to another wallet xch...k8t5 another duplicate transaction appeared out of nowhere of -7.5XCH that I don't even have in this particular wallet.

Lastly, I tried to dry out my entire wallet to 0 by sending -0.1748 to myself on this same wallet with another address xch...w75c. Transaction got stuck at "Pending".

Expected balance on this wallet is supposed to be 1.9248... XCH. 

I tried several restarts of XCH client, changing num pub keys, derivation index... nothing.

I run farming on this windows machine with full node.

What could it be? Is this known bug?

EDIT: I even deleted wallet database and still nothing. I can't remove even those "Pending transactions"

![image](https://user-images.githubusercontent.com/47561865/202866423-5055922e-83e0-4277-985d-4102439e523a.png)

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment] 2022-11-19 19:09
When there are many transactions, the derived index can become very large. The synchronization of the wallet will become very slow, which is a big problem

**Comment by nqzhang** [comment] 2022-11-19 19:11
From the low version to the latest version, I think the only way is to use a new wallet

**Comment by nqzhang** [comment] 2022-11-19 19:13
The synchronization of the wallet is really bad. It turned out that the synchronization of the full node was also a problem, but it was solved very well later. But the synchronization of the wallet is getting worse, especially after the emergence of the derived index

**Comment by nqzhang** [comment] 2022-11-19 19:16
If someone accepts the offer first, you even need to manually delete the unconfirmed transaction. Someone raised a related issue a long time ago, but it has not been resolved
https://github.com/Chia-Network/chia-blockchain/issues/11101

**Comment by nqzhang** [comment] 2022-11-19 19:18
All I can say is that chia's wallet is totally a garbage

**Comment by Oscillator098** [comment] 2022-11-24 11:27
I keep receiving transactions and all are just stuck and increasing in "pending". Deleting database wallet is not working, nor Delete unconfirmed transactions. My wallet it useless and balance is stuck.

**Comment by Oscillator098** [comment] 2022-11-28 07:43
Is this a known bug... my wallet is keep accumulating "Pending transactions" and I can't fix it. 
![image](https://user-images.githubusercontent.com/47561865/204221159-f63f384d-75ad-4cd5-a596-6701c3af0104.png)

**Comment by Oscillator098** [comment] 2022-12-06 16:51
New machine, new Chia 1.6.1. Install . Wallet only mode. Wallet fully synced I still have Pending balance = Total balance

**Comment by emlowe** [comment] 2022-12-15 21:08
I had considerable trouble following this issue. You are talking about Pending transactions, but all the transactions in your screenshots show Confirmed.

Unclear if you are asking about the `Pending Total Balance` box - this is expected that normally your `Total Balance` should equal the `Pending Total Balance`. We realize this is confusing - but this is actually the expected state. Generally one has Total == Spendable == Pending Total

`Pending Total` is defined as your `Total Balance` + `Pending Balance`. When your `Pending Balance` is zero, then clearly your `Pending Total` will equal your `Total Balance`

**Comment by Oscillator098** [comment] 2022-12-18 09:11
Hm... I was following what is happening for past month and based on what you said it could very well be a visual bug. 
I just won a block and +0.25 quickly arrived, however when I claimed +1,75 (Self pooling) the transaction showed in Spendable Balance == Pending balance but it is not showing in Transactions nor in .\chia wallet get_transactions.
That is why I was sure it did not arrived because I assumed that it needs to be in Confirmed transaction listed .\chia wallet get_transactions to be in your wallet..
The other one I was missing few weeks ago arrived days later in  .\chia wallet get_transactions but it was all the time in my "Spendable == Pending balance). (mempool was empty all the time).
It looks like it is either lagging or a visual bug in GUI.

After the restart of machine and resynching the wallet, same thing. No +1,75 transaction anywhere except it is shown in my Spendable Balance == Pending balance.

![image](https://user-images.githubusercontent.com/47561865/208286879-9d80d8a7-47c8-4756-b2c6-c182011c3c52.png)

**Comment by emlowe** [comment] 2023-01-05 21:18
To clarify - Your balance seems correct and includes the 1.75 self pool rewards. But this transaction (the claim) seems to be missing from the transaction list.

So this is the issue you are having?

**Comment by Oscillator098** [comment] 2023-01-09 06:40
Yes, the 1.75 XCH got to some wallet I own but it is unknown for me. It has only this transaction (1.75XCH) even thought my xch_target_address is different. And it is now showing in my transaction list in GUI neither in get_transactions. I managed to spend it.
I was doing some debugging with pool help.
It is probably a bug.
Is it possible for this to be derivation path bug where Chia client doesn't know that I own that particular wallet because I never used that xch address? In my config it is some completely different address and this unknown one is somehow generated that I don't know of.

**Comment by heget** [comment] 2023-06-01 07:33
> To clarify - Your balance seems correct and includes the 1.75 self pool rewards. But this transaction (the claim) seems to be missing from the transaction list.
> 
> So this is the issue you are having?

I can confirm this bug, the claim is missing in the transaction list also in latest version 1.8.1
Could this be related to the derivation index setting?

**Comment by emlowe** [comment] 2024-02-07 19:47
Marking as duplicate of #13251

**Closed by emlowe** 2024-02-07 19:47 UTC
Labels: bug, GUI, Windows, Wallet, full_node, sync, offers, 1.6.1
