### ISSUE TITLE
Plotting error  3/4 when i parralel mode

### ISSUE THREAD

**Issue by chia888** [Chia-Network/chia-blockchain#5068] opened 2021-05-15 05:40 UTC
Starting phase 3/4: Compression from tmp files into "D:\\plot-k32-2021-05-15-09-48-d0aeb53e4776d8b3546899a6c8b7a3fca273c4735206ed1e450607f749a92f5f.plot.2.tmp" ... Sat May 15 12:31:37 2021
Compressing tables 1 and 2
Caught plotting error: bad allocation
[1860] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by Jufik** [comment] 2021-05-15 07:22
duplicate of #1847
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation

**Closed** 2021-05-15 20:05 UTC
Labels: duplicate
