### ISSUE TITLE
[BUG] can not add the Pool URL

### ISSUE THREAD

**Issue by ChrystianDuarte** [Chia-Network/chia-blockchain#9102] opened 2021-11-03 13:54 UTC
**Describe the bug**
I am migrate from 1.2.7 version  to 1.2.10 version. an when i tried to add a pool i can not add.
also I tried to add for CLI but  shows following error

`PS C:\Users\cduarte\AppData\Local\chia-blockchain\app-1.2.10\resources\app.asar.unpacked\daemon> .\chia plotnft join -i 1 -u https://na1.pool.space -y
{'authentication_token_timeout': 5,
 'description': 'Welcome to Space Pool. By creating this Plot NFT, you agree '
                'to the following terms https://pool.space/terms',
 'fee': 0.01,
 'logo_url': 'https://pool.space/logo-250.png',
 'minimum_difficulty': 1,
 'name': 'Space Pool',
 'protocol_version': 1,
 'relative_lock_height': 64,
 'target_puzzle_hash': '0x2f2xxxxx315d41xxxxxx7'}

Will join pool: https://na1.pool.space with Plot NFT 1638839818.
Error performing operation on Plot NFT -f 16xxxxxxxxxxx wallet id: 1: {'error': "'Wallet' object has no attribute 'get_current_state'", 'success': False}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000xxxxxxxxx0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed`

**To Reproduce**

1. Go to 'POOL option in the GUI'
2. Click on ' join a pool'
4. when I try to add the url, i can not to add.

**Expected behavior**
add a URL.

**Screenshots**
![4DD23D2F-4B9F-4C85-B2FC-9F0AAC13B866](https://user-images.githubusercontent.com/19255861/140071347-a8cdf2b1-a06f-4943-bdfc-c5976b2f2d9a.jpeg)

**Desktop**

- OS: Windows
- OS Version/Flavor: Windows 10 Home
- CPU: AMD Ryzen 5 5600x

**Additional context**
I try in another pools but the bug is the same.
we open  a channel support whith 3 equals cases
https://github.com/Chia-Network/chia-blockchain/discussions/9072#discussioncomment-1576829

**Comment by shaneo257** [comment] 2021-11-04 07:42
it is a known issue in 1.2.10 that people are unable to join using the GUI, and this will be fixed in the next release, you can use CLI

**Comment by loppefaaret** [comment] 2021-11-04 11:31
duplicate of #8944 - closing

**Closed by loppefaaret** 2021-11-04 11:31 UTC
Labels: bug
