### ISSUE TITLE
Slow response time with portable plots 1.2.0 for MacOS exFAT

### ISSUE THREAD

**Issue by jonnybutler** [Chia-Network/chia-blockchain#7359] opened 2021-07-11 02:08 UTC
I am running into issues where my portable plots are finding proofs (partials) but the response time is super long and they are considered invalid by the pool I joined.

- Chia version 1.2.0
- Mac OS Catalina 10.15.7
- iMac Pro, 3.2 Ghz Xeon, 32 gb ram
- The computer is connected to my router via ethernet
- Plotting with a fast high tbw Sabrent NVME connected via a thunderbolt 3 external enclosure.
- Farming drives are mostly Seagate external Backup Plus 8TB drives, and a Western Digital 14 tb drive. I believe these are using 5200 rpm drives inside. I have formatted them all exFat since I was planning on having a raspberry Pi 4 do farming and the file format should work on linux.  
- The drives are connected directly to the iMac Pro.
- I’m connected to Space Pool and it says pooling. My wallet and full node are sync’d. Seeing plenty of connections to other nodes using port 8444.

I’ve started to create plots using the NFT generated when I joined Space Pool.

What’s odd is that most of the logs are fine except for when finding a partial:

```
2021-07-09T20:04:40.260 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 0.01266 s. Total 348 plots
2021-07-09T20:04:49.449 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 0.01871 s. Total 348 plots
2021-07-09T20:04:54.369 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 417995711b... Found 1 proofs. Time: 134.45386 s. Total 348 plots
2021-07-09T20:05:00.679 harvester chia.harvester.harvester: INFO     2 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 1.67033 s. Total 348 plots
2021-07-09T20:05:09.085 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 0.01356 s. Total 348 plots
2021-07-09T20:05:19.127 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 0.01275 s. Total 348 plots
2021-07-09T20:05:29.085 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 38c6cf796d... Found 0 proofs. Time: 0.01329 s. Total 348 plots
```

These are taking around 100-200 seconds.  In the case that the drives might be going to sleep, I created a cronjob to touch a dummy file every minute on the 2 drives with plots and that does not seem to make a difference.

I’m not sure what to do besides try to move to a faster storage medium or try a different format for my drives, but that seems odd.  I also tried a different pool and the issue was still there.

**Comment by jonnybutler** [comment] 2021-07-13 15:33
I've traced the issue down to the combination of Mac OS + Chia with exFat formatted drives.  Reformatting to APFS solved the issue and now the proof/partial retrieval is under 2 seconds usually.  This should be noted somewhere (or is there a way to speed it up via the application?).  The exFat drive works just fine on my raspberry pi 4 for farming.

**Comment by wondras** [comment] 2021-07-14 02:11
I'm having the exact same issue, except that I am using old plot files (mostly from 1.1.7) with v1.2.
Using macOS 10.14, external USB drives with exFAT partitions. TImes are 100-150 seconds when a proof is found, 5 seconds max when no proof is found.

**Comment by MaD088** [comment] 2021-07-14 10:55
I have the same problem with a Mac M1 16Gb memory. I am synched to the pool but am not getting any thing fromthere. Tried with different pools and my files are on an APFS WD 8tb external hard drive. Any idea of how to resolve this? I've seen on youtube that many people are experiencing this problem and installing python somewhat fixed the problem for some of them but not everybody. Any idea would be welcome! Can some one tell me how I can check my partials? Thanks in advance for your help :)

**Comment by jonnybutler** [comment] 2021-07-14 18:09
@MaD088 -- looks like 1.2.2 which just came out should fix your issue?

**Comment by MaD088** [comment] 2021-07-14 21:13
Effectively :) Finally officially pooling :D

**Comment by AndyRPH** [comment] 2021-07-16 16:38
I'm having the same thing.  Both on an intel MacBook Pro and an M1 MacBook Pro.  External USB seagate backup+ drives, ExFAT formatted.  the M1's partial proofs take 15 seconds each, and intel macbookpro's take about 160 seconds each. 

Has it always been this way, and just prior to pools there were no partial proofs and since I haven't gotten a full proof, I never knew?  Or is something buggy with a recent chia update?   95%+ of all my found 0 proofs that still pass the plot filter return in under 2 seconds though.

**Comment by AndyRPH** [comment] 2021-07-16 18:22
Adding in some data: 
chia plots check on a solo plot, on a exfat usb drive, 10 minutes, 
chia plots check on a nft plot, same exfat usb drive, 8 mins.
chia plots check on the same solo plot on M1 internal ssd APFS filesystem:  <1 second
chia plots check on the same nft plot on M1 internal ssd APFS filesystem:   <1 second 

Is chia plots check a good representation of how long it would take to report back a valid found solution if I got lucky? or a valid partial proof to a pool? 

It seems that at least on OS X exFAT filesystems are a terrible idea for Chia.  And this is unrelated to solo vs NFT plots.

**Comment by smiletracer** [comment] 2021-07-16 18:42
> It seems that at least on OS X exFAT filesystems are a terrible idea for Chia. And this is unrelated to solo vs NFT plots.

Correct. exFAT on macOS is an issue with Chia, and causes CPU usage to spike overtime (specifically the "launchd" system process) per the bug report #4396 you referenced. I discovered this back in May and reported it on that thread.

**Comment by AndyRPH** [comment] 2021-07-16 18:56
> > It seems that at least on OS X exFAT filesystems are a terrible idea for Chia. And this is unrelated to solo vs NFT plots.
> 
> Correct. exFAT on macOS is an issue with Chia, and causes CPU usage to spike overtime (specifically the "launchd" system process) per the bug report #4396 you referenced. I discovered this back in May and reported it on that thread.

Are we certain it's only on macOS and only with Chia?

**Comment by jonnybutler** [comment] 2021-07-16 19:10
Plots are working nicely on my raspberry pi 4 running 64 bit raspbian.  Proof retrieval times are good for pools at least, usually less than 2 seconds.  So, it seems to be something Mac related.  My guess is that it's the portability of the Python libraries used or an OS level issue.

**Comment by smiletracer** [comment] 2021-07-16 19:11
> Are we certain it's only on macOS and only with Chia?

I know I can have a full 14TB ExFat drive full of plots mounted on Mac--while not having Chia farming it while the Mac copies all the file to another 14TB APFS drive (which takes a good day to complete), without any issues with LaunchD or system slowdowns. So I don't think it is anything involving normal system access of the files. But if Chia farms an ExFat drive, in less than an hour, and LaunchD process is at 100% slowing the system to a crawl.

It's possible this is a Python issue, not a Chia issue. On the #4396 thread, I speculate if maybe it is caused by having an older Python installed as the Mac's default python is 2.7, where as Chia requires 3.7 or higher. This caused a separate issue recently with not being able to connect to pools due to bad SSL certs in 2.7. (Version Chia 1.2.2 fixed that certificate issue.) But makes me wonder since back in May (when #4396 was discovered) I was on the same Mac farming that had Python 2.7 as system default at the time.

**Comment by rsokolowski** [comment] 2021-07-16 20:28
Glad to see this thread. I have over 200 drives connected to plotters (3900x and i7-11700k) and harvesters (HP 520 Thin Client) running Ubuntu 20 LTS (desktop and server). All the drives and 5tb USB ones. Some are WD elements, and some are Seagate expansion portable and one touch. All but Seagate One Touch are NTFS. Those one touch drives are exFat.  I've plotted 20 of those. All of them are unusable for farming. I'm not sure whether it is 1.20 related, because I've moved them to harvesters around the time when changed to 1.20. i need to check logs. Somehow plotters were able to plot to those drives and farm from them (before being moved to harvesters) and I didn't notice issue back then. Right now I can't farm on those exFat drives on plotters as well.

**Comment by smiletracer** [comment] 2021-07-16 20:31
> I'm not sure whether it is 1.20 related, because I've moved them to harvesters around the time when changed to 1.20. 

I know 1.2.1 had some optimizations regrading harvesting / farming performance overall. If you haven't yet updated to 1.2.1 or 1.2.2, give that a try.

**Comment by rsokolowski** [comment] 2021-07-16 20:32
Note that in my case i don't even need to wait for proofs. Even scanning the drive during harvester setup is very slow. On T520 it takes few seconds to process one plot file while on NTFS drive it takes low couple hundred Ms.

**Comment by AndyRPH** [comment] 2021-07-16 20:35
try a chia plots check on a single plot from drives with different filesystems...

**Comment by wondras** [comment] 2021-07-16 21:33
Great idea @AndyRPH to use the plots check function. Waiting for a proof takes a **long** time for most of us.

I only noticed this problem when I was playing around with some of the Chia forks, since I can find proofs much more frequently there. I didn't see any of these extremely long times until I started running forks based on Chia 1.2.x, so I decided to compare official Chia 1.1.7 to 1.2.2 using a check on the same solo plot file. 

The following tests were performed after a reboot with no other applications running:

```
git clone -b 1.1.7 https://github.com/Chia-Network/chia-blockchain.git
mv chia-blockchain chia-blockchain_1.1.7
cd chia-blockchain_1.1.7
sh install.sh
. ./activate
chia plots add -d /Volumes/SkyPlots/chia_plots
chia plots check -g 00af496a23ca09c
```

```
git clone -b 1.2.2 https://github.com/Chia-Network/chia-blockchain.git
mv chia-blockchain chia-blockchain_1.2.2
cd chia-blockchain_1.2.2
sh install.sh
. ./activate
chia plots add -d /Volumes/SkyPlots/chia_plots
chia plots check -g 00af496a23ca09c
```

Results were as follows:
![image](https://user-images.githubusercontent.com/8431402/126009496-9d40daf8-1697-4e73-a97a-06b984ebe92f.png)

Version 1.1.7:  57 seconds
Version 1.2.2:  17 minutes, 58 seconds

I would rate the impact of this issue as fairly high. Yes, ExFAT has poor performance and reliability, but nonetheless it is commonly used on Macs, as it is the only natively available file system with large file support and cross-platform compatibility. Whether ExFAT, macOS, Python, Chia, or something else is at the heart of the drastic change in performance between Chia v1.1 and v1.2, the consequences for Mac Chia farmers are enormous. They will have **no** indication that anything is wrong until they hit a proof. If they do hit a proof, they are **certain** to miss the reward. If they aren't scanning logs, they'll never know they should have won.

**Comment by smiletracer** [comment] 2021-07-16 21:41
Curious, what version of Python do you have set as your Mac's system default. Check via "python --version"

**Comment by smiletracer** [comment] 2021-07-16 21:42
Also I assume your "SkyPlots" volume is ExFat? Have you compared the same test with plots on APFS?

**Comment by jonnybutler** [comment] 2021-07-16 21:44
My system had 3.9 set as the default. For pools, response seemed to be accepted around 40 seconds but now I am at under 1 usually with APFS. The messaging in the logs said that under 5 was best to avoid issues.

**Comment by mressler** [comment] 2021-07-16 22:07
I'm having identical issues on MacOS with Chia 1.2.2. The Python version in my virtual environment is 3.9.5.

**Comment by wondras** [comment] 2021-07-16 22:11
@smiletracer good questions!  Apparently 2.7 is still my system default:
```
$ python --version
Python 2.7.16
```
However, the venv set up by `install.sh` uses 3.9.6:
```
(venv) mac2015:chia-blockchain_1.1.7 xxxxx$ python --version
Python 3.9.6
```

Yes, 'SkyPlots' is an external Seagate portable 5 TB drive with ExFAT partitions. I've seen similar times on a Seagate desktop external 8 TB with ExFAT as well.

I copied the plot used in the previous tests to the internal SSD w/APFS, changed the plot paths, and ran the check again. I did multiple runs, and the times were generally 0.8-1.1 seconds for both versions.

Using `time chia plots check -g 00af496a23ca09c` to measure the full execution time including startup, the times averaged to about:

Version 1.1.7:  1.28 seconds
Version 1.2.2:  1.30 seconds

There may be slightly more overhead for v1.2.2, but on a "real" file system and drive, it is insignificant.

Unfortunately, I don't have a spare external hard drive at the moment to format as both ExFAT and APFS to directly compare file system performance on HDDs. (Can you guess why?) However, if it would be helpful, I may be able to arrange it.

**Comment by smiletracer** [comment] 2021-07-16 23:23
@wondras Yeah I just took did my own test with Chia 1.2.2 on Big Sur 11.4. I used a 1TB WD SSDs formatted as ExFat. Copied a plot to it, added it as a chia directory, and ran the plot check (default 30 challenges). I then did the same check for a plot on one of my APFS formatted 14TB drives... 

Results:
APFS HDD: 19 seconds
ExFat SSD: (...still running as of 30 minutes ago!)

During the ExFat test, LaunchD process began spiking at 100% in the same ~0% to 100% cycle as per the original report #4396 back in May.

Also my python version is 3.9.6, so this rules out any difference between Python versions being the cause.

I was going to do a test with an SSD formatted with APFS for an apples to apples comparison, but obviously there's no point, given the above result. ExFat is still buggy as heck with Chia and/or Python on Mac.

But, I did do a plots check test with an ExFat formatted SSD connected via USB on my Ubuntu Linux plotting system...

Result:
ExFat SSD on Ubuntu: 2 seconds

So clearly not something Chia or Python is doing that doesn't jive with ExFat as a format in general. It's something about the interaction between Chia and Python on the Mac with Apple's ExFat implementation.

**Comment by Handri-Kosada** [comment] 2021-07-17 03:49
I have pi4 8gb with ubuntu 20.02 + chia 1.2.2
external usb hdd with exfat and NOT using FUSE to mount.

same issue, looking for partial is very long compared to OG Plots.

never have this issue before.

**Comment by wondras** [comment] 2021-07-18 02:38
As a short-term workaround, I set up Ubuntu 20.04 in a VirtualBox VM, and I am passing the USB devices through to it. I'm able to run Chia and multiple forks at once, and receive rewards. It will occasionally exceed 5 seconds if many plots pass the filter at once, but only by a 1-3 seconds

**Comment by hoffmang9** [comment] 2021-07-18 17:20
This is most likely caused by this change - https://github.com/Chia-Network/chiapos/commit/3feab20dca377ee0c3723419a02cf6901709a309

[Gulrak](https://github.com/gulrak/filesystem) doesn't seem to be happy with the parallel reads. This change was to support faster look ups on most filesystems and to support Backblaze's chia optimizations. We use Gulrak to support Mojave but could drop it if we drop Mojave support...

**Comment by Handri-Kosada** [comment] 2021-07-19 05:44
it also affecting pi4 ubuntu 20.02
the partial is very slow

I use external usb hdd with exfat. never have issues before.
so I guess it affecting all exfat filesystem?


> This is most likely caused by this change - [Chia-Network/chiapos@3feab20](https://github.com/Chia-Network/chiapos/commit/3feab20dca377ee0c3723419a02cf6901709a309)
> 
> [Gulrak](https://github.com/gulrak/filesystem) doesn't seem to be happy with the parallel reads. This change was to support faster look ups on most filesystems and to support Backblaze's chia optimizations. We use Gulrak to support Mojave but could drop it if we drop Mojave support...

**Comment by hoffmang9** [comment] 2021-07-19 22:12
The fix will work cross platform so will be interesting to see.

**Comment by emlowe** [comment] 2021-07-21 18:28
Anyone with the issue can pull main and set parallel_read to False in config.yaml for their harvesters - this will use the sequential option that was in 1.1.7.

**Comment by thepoison606** [comment] 2021-07-24 14:52
> Anyone with the issue can pull main and set parallel_read to False in config.yaml for their harvesters - this will use the sequential option that was in 1.1.7.

How can i do that? Already followed the instruction from the install page but my config.yaml file doesn't have the parallel_read line :(

**Comment by timdmackey** [comment] 2021-07-26 05:58
I ran into this same issue with using exFat on macOS. 8 cores with 16GB memory, and it was taking 90+ seconds to find a valid partial. Now that I reformatted the drive as HFS+, it's taking less than a second to find a partial.

**Comment by emlowe** [comment] 2021-07-27 01:44
Release 1.2.3 has introduced the parallel_read option in config.yaml to solve this issue. If you upgrade, you will need to manually add the setting under harvester. 
```
harvester:
  parallel_read: False
```

**Closed by emlowe** 2021-07-27 01:44 UTC
