### ISSUE TITLE
[BUG] Farmer with no local plots shows no activity for remote harvesters

### ISSUE THREAD

**Issue by salsaly4** [Chia-Network/chia-blockchain#2522] opened 2021-04-24 01:04 UTC
Full-node/farmer host with NO local plots shows nothing in GUI/chia farm summary

**To Reproduce**

1. Set up farmer node on Linux with no local plots
2. Copy the CA and harvesters as described in [Wiki](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)
3. Get the messages from harvesters in farmer's debug.log like:
`2508be0d26a0e0fbe3ec39028d35afdbe
2021-04-24T03:55:35.461 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 51.225.18.71 3b408fbc1eeec65e5a3304e969513cc3e8ef4bcf05682a1ced197d82d422e03b
2021-04-24T03:55:35.462 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 25.211.74.35 8e522bb87b099348d7c91441d9597edd07d09f62f55a061a2e5033ef210675df
2021-04-24T03:55:35.469 farmer farmer_server              : INFO     <- farming_info from peer 1c1a28aca8b10a9e057277800d5d7e952583ad8ce4eac0002e07ba94bca9f6ed 127.0.0.1
2021-04-24T03:55:35.507 farmer farmer_server              : INFO     <- farming_info from peer 8e522bb87b099348d7c91441d9597edd07d09f62f55a061a2e5033ef210675d`
4. There is no 'Last Attempted Proof' in the remote GUI connected to farmer node
5. There are zeroes in `show farm summary` on the farmer node

**Expected behavior**
On a farmer node without local plots, `show farm summary` should show statistics for all connected harvesters.
In a remote GUI connected to farmer node without local plots, the 'Farm' tab should show statistics and summary for all connected harvesters.

**Additional context**
Just curious — is this only the matter of displaying things, or my harvesters doing nothing until the farmer node has at least one plot locally? This was never indicated, and is a real pain in the... you know, farmer node.

**Comment by pubyun** [comment] 2021-04-24 02:21
same issue

**Comment by ddowhy** [comment] 2021-04-24 02:44
I was wondering this myself.  Have had 1500+ plots going for 5 days now with no blocks found.  Only my remote harvester has plots. My main node has no plots and I suspect something is foul here, I should have found several blocks by now.

**Comment by etimes2008** [comment] 2021-04-24 09:59
plot file copy main node?

**Comment by salsaly4** [comment] 2021-04-24 10:15
There is no word on having to get the plots on the main node in documentation, so I tried that. Ok, I've moved one plot to the full node/farmer, get this number in the Farm tab in GUI and in `chia farm summary`, and Last Attempted Proof started showing my harvesters. But! There is still only local plot that displayed in the Farm tab and `chia farm summary` output — oh, not again.

**Comment by tanhao0068** [comment] 2021-04-24 14:36
Plot count: Unknown
Total size of plots: Unknown

same issue

**Comment by ddowhy** [comment] 2021-04-24 17:23
1700+ plots on 6 days and no plots found with remote harvestor connected to a farmer on full node which had no local plots.  

I suspect this is bugged and you won't find blocks.

So GUESS WHAT, I just switched 2 hours ago to turn my remote harvester into a full node with a local harvestor, and I've already found a block.  I think remote harvesters is broken.  There were no errors for me, no ssl issues, everything looked good in logs on both remote harvester and the full node showing as communication going back and forth.  It was showing as if it was receiving plots and the harvester repeatedly said plots were eligible for farming but to find 0 blocks with 1500-1700 plots over 6 days...I mean there's bad luck I get that part (been mining eth for 5 years now), but like given the network was only 200PB last weekend to now I should have found probably 10 or more blocks.   I'm pretty sure remote harvesters are broken in some edge case that isn't obvious.  I suggest people don't use remote harvesters and just figure out how to run full nodes on all the machines with plots on them.

**Comment by Teveillan** [comment] 2021-04-24 22:45
same issue

**Comment by phantom-rabbit** [comment] 2021-04-25 12:03
same issue

**Comment by hoffmang9** [comment] 2021-04-25 17:30
This is not a bug but is an enhancement we plan to make.

**Comment by dongxicc** [comment] 2021-04-29 10:34
same problem,It's make me very confused

**Comment by dongxicc** [comment] 2021-04-29 10:36
I have one fullNode and 80 harvesters with plots on other machines,It seems very slow

**Comment by snow2flying** [comment] 2021-04-29 14:57
> This is not a bug but is an enhancement we plan to make.
no, it is a big issue

**Comment by yapwenbin** [comment] 2021-04-29 15:01
So the temporary fix is to put at least 1 plot on the full node?

**Comment by snow2flying** [comment] 2021-04-29 15:02
> This is not a bug but is an enhancement we plan to make.



> This is not a bug but is an enhancement we plan to make.

the code and the doc doesnt match, hope you can make it.we can not run remote harvester, there is no any plot in any time.

**Comment by snow2flying** [comment] 2021-04-29 15:05
> So the temporary fix is to put at least 1 plot on the full node?

if you put one, you just have one,you maybe lost any others . the remote harvester do have issue.

**Comment by hoffmang9** [comment] 2021-04-29 15:07
This is a duplicate enhancement request. Closing.

**Closed by hoffmang9** 2021-04-29 15:07 UTC
Labels: enhancement

**Comment by sharyuke** [comment] 2021-05-15 09:53
same issue
