### ISSUE TITLE
After upgrading Chia to version 2.01, the cooperative became empty[Bug] 

### ISSUE THREAD

**Issue by zsvvv** [Chia-Network/chia-blockchain#16498] opened 2023-10-03 14:47 UTC
### What happened?

After upgrading Chia to version 2.01, the cooperative became empty
I am a self-farmer, and I have nowhere to claim the newly mined 1.75 rewards. What should I do?

### Version

2.01

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment] 2023-10-04 16:04
We think you mean you can't find your plotnft - perhaps attaching a screenshot might help.
You can also try the wallet resync feature in Settings->Advanced

**Comment by BrandtH22** [comment] 2023-10-05 18:09
This is a duplicate of the support discussion:
https://github.com/Chia-Network/chia-blockchain/discussions/16497

Closing so this conversation can be managed in the support discussion

**Closed by BrandtH22** 2023-10-05 18:09 UTC
Labels: bug
