### ISSUE TITLE
[Bug] install 1.6.1(arm)

### ISSUE THREAD

**Issue by laozhang713** [Chia-Network/chia-blockchain#13960] opened 2022-11-19 03:43 UTC
### What happened?

The 1.6.0 CLI of arm is running normally, but it cannot be installed to 1.6.1 normally

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
root@22-5-29-1129:~# dpkg -i chia-blockchain-cli_1.6.1-1_arm64.deb 
(Reading database ... 131365 files and directories currently installed.)
Preparing to unpack chia-blockchain-cli_1.6.1-1_arm64.deb ...
Unpacking chia-blockchain-cli (1.6.1) over (1.6.0) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive chia-blockchain-cli_1.6.1-1_arm64.deb (--install):
 cannot copy extracted data for './opt/chia/chia' to '/opt/chia/chia.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 chia-blockchain-cli_1.6.1-1_arm64.deb
root@22-5-29-1129:~#
```

**Comment by MumfMeisterT** [comment] 2022-11-23 20:34
It looks like your .deb file might be corrupted. Can you try to re-download & install to see if that fixes? 
If not, can you confirm what version of linux you're running?

**Comment by emlowe** [comment] 2022-12-08 00:26
Closing issue. Unable to reproduce with `http://download.chia.net/install/chia-blockchain-cli_1.6.1-1_arm64.deb`

```
(venv) elowe@chiapi ➜  chia-blockchain git:(release/1.7.0) ✗ sudo dpkg -i chia-blockchain-cli_1.6.1-1_arm64.deb 
Selecting previously unselected package chia-blockchain-cli.
(Reading database ... 108815 files and directories currently installed.)
Preparing to unpack chia-blockchain-cli_1.6.1-1_arm64.deb ...
Unpacking chia-blockchain-cli (1.6.1) ...
Setting up chia-blockchain-cli (1.6.1) ...
```

**Closed by emlowe** 2022-12-08 00:26 UTC
Labels: bug, support, Linux, CLI, 1.6.1, need info
