### ISSUE TITLE
Deleting partially completed plots doesn't free up disk right away

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#7536] opened 2021-07-15 16:41 UTC
**Describe the bug**
When deleting a plot that is partially complete, disk is not freed up for other plots. 
**To Reproduce**

Preconditions:
* Using GUI to plot
* Mac Pro desktop Intel x86, 32GB RAM, 1TB internal SSD for plotting, 2TB external drive 
 

1. Checking current storage under apple menu>about this Mac> storage. Observe that 900GB of 1TB is free on SSD
2. Add 5 plots, targeting internal SSD for temp storage, external drive as final directory 
3. Begin plotting until almost out of temp storage space
4. Remove three plots to free up disk to enable remaining plots to complete
5. Disk is not freed up
6. Results: 7. Remaining plots stuck in retry "Error 1" mode endlessly, reported available storage under apple>about this Mac>storage doesn't show that the delete partial plots freed up space 
7. Quitting the Chia Blockchain app and/or rebooting doesn't result in the temp storage being deleted. Partial plots no longer display in the GUI but user has to go to temp directory and manually delete. 
 
**Expected behavior**
1. Deleting partial plots should delete them from temp folder and free up space without further user intervention.
2. If the remaining partial plots that were not deleted were errored out due to insufficient disk, they should gracefully resume plotting

**Desktop**
- OS: Mac OS 
- OS Version/Flavor: Big Sur 11.4
- CPU: 3.5GHz 6-core Intel Xeon E5

**Additional context**

**Comment by hoffmang9** [comment] 2021-07-18 21:40
By deleting - do you mean you used a Finder window or do you mean you hit the delete button in the GUI? The latter is really delete from queue.

**Comment by artra5253** [comment] 2021-07-18 22:35
> **Describe the bug**
> 
> When deleting a plot that is partially complete, disk is not freed up for other plots. 
> 
> **To Reproduce**
> 
> 
> 
> Preconditions:
> 
> * Using GUI to plot
> 
> * Mac Pro desktop Intel x86, 32GB RAM, 1TB internal SSD for plotting, 2TB external drive 
> 
>  
> 
> Steps to reproduce the behavior:
> 
> 
> 
> 1. Checking current storage under apple menu>about this Mac> storage. Observe that 900GB of 1TB is free on SSD
> 
> 2. Add 5 plots, targeting internal SSD for temp storage, external drive as final directory 
> 
> 3. Begin plotting until almost out of temp storage space
> 
> 4. Remove three plots to free up disk to enable remaining plots to complete
> 
> 5. Disk is not freed up
> 
> 6. Results: 7. Remaining plots stuck in retry "Error 1" mode endlessly, reported available storage under apple>about this Mac>storage doesn't show that the delete partial plots freed up space 
> 
> 7. Quitting the Chia Blockchain app and/or rebooting doesn't result in the temp storage being deleted. Partial plots no longer display in the GUI but user has to go to temp directory and manually delete. 
> 
>  
> 
> **Expected behavior**
> 
> 1. Deleting partial plots should delete them from temp folder and free up space without further user intervention.
> 
> 2. If the remaining partial plots that were not deleted were errored out due to insufficient disk, they should gracefully resume plotting
> 
> 
> 
> **Desktop**
> 
> - OS: Mac OS 
> 
> - OS Version/Flavor: Big Sur 11.4
> 
> - CPU: 3.5GHz 6-core Intel Xeon E5
> 
> 
> 
> **Additional context**
> 
> 
> 
>

**Comment by hoffmang9** [comment] 2021-07-18 22:41
You did not answer my question. Which method of "Remove three plots to free up disk to enable remaining plots to complete" did you use?

**Comment by paulhainsworth-chia** [comment] 2021-07-18 23:46
I hit delete button in the GUI. I expected that would delete from disk.
Understood if that is intended to remove from queue but we should clarify
verbiage to remove ambiguity.

**Comment by emlowe** [comment] 2021-07-22 03:44
I believe a duplicate of #1871

**Closed by emlowe** 2021-07-22 03:44 UTC
Labels: bug
