### ISSUE TITLE
Node cant sync anymore (version 1.8.1 and 1.8.2)

### ISSUE THREAD

**Issue by Krysinski** [Chia-Network/chia-blockchain#15687] opened 2023-07-06 00:14 UTC
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/14326
OS Linux Mint 19.3
Node stuck sync at 04.07.2023 10:26 UTC. 
Clearing DB not help. Update from 1.8.1 to 1.8.2 not help. Add peers manualy not help.
Part of log:
2023-07-06T03:54:30.684 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 1135, in new_peak_from_untrusted
  File "chia/wallet/wallet_node.py", line 1144, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 1263, in fetch_and_update_weight_proof
Exception: weight proof response was none
2023-07-06T03:54:30.686 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-06T03:54:30.687 wallet wallet_server              : WARNING  Banning 172.92.14.156 for 120 seconds
2023-07-06T03:54:32.091 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-06T03:54:32.091 wallet wallet_server              : WARNING  Banning 172.92.14.156 for 120 seconds
2023-07-06T03:54:32.092 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-06T03:54:32.092 wallet wallet_server              : WARNING  Banning 172.92.14.156 for 120 seconds

**Comment by Krysinski** [comment] 2023-07-08 19:45
Node starts sync after copying db from another PC.

**Comment by timudjinka** [comment] 2023-07-13 17:59
I'm joining you. The problem is the same. A complete clean reinstallation of the wallet helped for half a day. Half a day later, the problem started again.
![Снимок23](https://github.com/Chia-Network/chia-blockchain/assets/118344524/4add9a14-57ea-4dcc-b040-f2f4a3ea51ae)


2023-07-13T20:35:58.948 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.950 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:58.952 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('93.51.77.74'), _port=8444) did not respond in time.
2023-07-13T20:35:58.954 wallet wallet_server              : WARNING  Banning 93.51.77.74 for 120 seconds
2023-07-13T20:35:58.956 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.958 wallet wallet_server              : WARNING  Banning 188.82.78.187 for 120 seconds
2023-07-13T20:35:58.960 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.962 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:58.965 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.967 wallet wallet_server              : WARNING  Banning 188.82.78.187 for 120 seconds
2023-07-13T20:35:58.970 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.972 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:58.974 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('93.51.77.74'), _port=8444) did not respond in time.
2023-07-13T20:35:58.976 wallet wallet_server              : WARNING  Banning 93.51.77.74 for 120 seconds
2023-07-13T20:35:58.977 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('93.51.77.74'), _port=8444) did not respond in time.
2023-07-13T20:35:58.979 wallet wallet_server              : WARNING  Banning 93.51.77.74 for 120 seconds
2023-07-13T20:35:58.981 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.982 wallet wallet_server              : WARNING  Banning 188.82.78.187 for 120 seconds
2023-07-13T20:35:58.984 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.986 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:58.988 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('93.51.77.74'), _port=8444) did not respond in time.
2023-07-13T20:35:58.990 wallet wallet_server              : WARNING  Banning 93.51.77.74 for 120 seconds
2023-07-13T20:35:58.993 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:58.995 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:58.997 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:59.000 wallet wallet_server              : WARNING  Banning 188.82.78.187 for 120 seconds
2023-07-13T20:35:59.002 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:59.004 wallet wallet_server              : WARNING  Banning 69.245.187.178 for 120 seconds
2023-07-13T20:35:59.007 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('93.51.77.74'), _port=8444) did not respond in time.
2023-07-13T20:35:59.008 wallet wallet_server              : WARNING  Banning 93.51.77.74 for 120 seconds
2023-07-13T20:35:59.010 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-07-13T20:35:59.012 wallet wallet_server              : WARNING  Banning 188.82.78.187 for 120 seconds

**Comment by timudjinka** [comment] 2023-07-13 18:02
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 784, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 82, in subscribe_to_phs
ValueError: None response from peer 188.82.78.187 for register_interest_in_puzzle_hash
2023-07-13T20:52:28.086 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 348, in safe_handle
  File "aiohttp\client_ws.py", line 151, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 646, in _send_frame
  File "aiohttp\http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

2023-07-13T20:52:28.090 wallet chia.rpc.rpc_server        : WARNING  Exception: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 348, in safe_handle
  File "aiohttp\client_ws.py", line 151, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 646, in _send_frame
  File "aiohttp\http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 396, in inner
  File "chia\rpc\rpc_server.py", line 369, in connection
  File "chia\rpc\rpc_server.py", line 356, in safe_handle
  File "aiohttp\client_ws.py", line 151, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 646, in _send_frame
  File "aiohttp\http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>

**Comment by timudjinka** [comment] 2023-07-14 15:05
> Node starts sync after copying db from another PC.

It didn't help me. The node was in sync for about 5 minutes, and then everything was the same again.

**Comment by timudjinka** [comment] 2023-07-15 07:58
The problem was solved by switching the synchronization of the wallet to a local node installed on the second computer in the LAN.

**Comment by wjblanke** [comment] 2023-07-19 16:45
yes it looks like you have some network issues outside of chia. glad its fixed!

**Closed by wjblanke** 2023-07-19 16:45 UTC
