### ISSUE TITLE
Windows Chia client ver 1.2.0: 

### ISSUE THREAD

**Issue by Hawstly** [Chia-Network/chia-blockchain#7242] opened 2021-07-08 17:12 UTC
On the Farm Tab:

Plot count tile not updating to reflect actual plot count. Seems like the function that updates that tile is not triggering.

In the below tile labeled Last Attempted Proof tile; Plots Passed Filter count (1/1501) is correct of actual count.

**Comment by gotovac** [comment] 2021-07-08 17:22
I'm having the same issue using the Madmax plotter (v0.1.1 on Windows) and the Chia GUI client v1.20 to make portable plots for a pool. After plotting successfully via Madmax and copying to my final directory that is listed in my config.yaml file, the only way to get the GUI to show the correct number of plots is to manually refresh using the _Refresh plots_ button under the _Plots_ tab. Even after using the command `chia farm summary` it shows an incorrect amount of plots. 

I think it's also worth mentioning that this was not the case when I was using the beta version of the Chia client (v.1.1.795) as then the GUI would show the correct amount of plots farming and would automatically refresh it as Madmax copied the plots to my final farming directory.

**Comment by emlowe** [comment] 2021-07-12 15:39
Duplicate of #7223

**Closed by emlowe** 2021-07-12 15:39 UTC
