### ISSUE TITLE
Synk is impossible! Peak height Never ends!

### ISSUE THREAD

**Issue by Mazyar-mi** [Chia-Network/chia-blockchain#5787] opened 2021-05-22 12:30 UTC
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Mazyar-mi** [comment] 2021-05-22 12:36
![Chia Not Synced](https://user-images.githubusercontent.com/84626305/119226767-13c5a680-bb20-11eb-825c-98155c9b24d2.jpg)

**Comment by Mazyar-mi** [comment] 2021-05-22 14:07
![Chia Not Synced 2](https://user-images.githubusercontent.com/84626305/119229322-b4ba5e80-bb2c-11eb-8e63-020639b4745b.jpg)

**Comment by lvpcguru** [comment] 2021-05-23 10:39
Did you update to 1.1.6? This included a few sync resolutions.

Also make sure you have the 8444 port forwarded to your machine and the port open on your firewall. This will help with syncing

**Comment by siaarzh** [comment] 2021-05-24 16:00
Duplicate of #3298

See https://github.com/Chia-Network/chia-blockchain/issues/3298#issuecomment-845414120, https://github.com/Chia-Network/chia-blockchain/issues/3298#issuecomment-830738275 for possible solutions

**Comment by lvpcguru** [comment] 2021-05-25 19:13
@Mazyar-mi How did it go? Dont forget to close the issue when your resolved.

**Comment by Mazyar-mi** [comment] 2021-05-28 21:45
Update 1.1.6
Problem solved

**Closed** 2021-05-28 21:45 UTC
Labels: bug
