### ISSUE TITLE
Harvester SSL error after 1.3.4 update

### ISSUE THREAD

**Issue by jason-unleashed** [Chia-Network/chia-blockchain#11422] opened 2022-05-04 01:41 UTC
I updated both farmer and harvester to 1.3.4
When starting the harvester (chia start harvester -r) I receive the following:
```
(venv) xxxx@xxxxxxxxxxx:~/chia-blockchain $ chia start harvester -r
chia_harvester: stopped
chia_harvester: started
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f99fe6320>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
```
I can see the harvester from the farmer:
```
Farming status: Farming
Total chia farmed: 0.750000002011
User transaction fees: 2.011e-09
Block rewards: 0.75
Last height farmed: 1483780
Local Harvester
   1828 plots of size: 180.921 TiB
Remote Harvester for IP: 192.168.0.12
   984 plots of size: 97.390 TiB
```
And in the log, I can see I'm finding proofs and sending them to my pool.

**Comment by stefan-lange** [comment] 2022-05-04 05:09
Reason for that should be the old python version. You should update to 3.8 or 3.9, if you can. 3.7 is EOL

**Comment by jason-unleashed** [comment] 2022-05-04 16:02
Thanks, I updated python to 3.9 and updated the symlink.  No change.  I confirmed ```python3 -V``` reported 3.9.12 but the error message in Chia remained the same.  

At this point, things got worse... 

For grins, I ran ```install.sh``` again but it refused to run.  It complained about a dependency, sorry didn't capture the exact message.   apt refused to install anything, I changed the symlink back to python 3.7, install.sh spit out some different dependency requirements, apt again refused to comply with my request to install.

This was a rpi4 harvester with just under 1k plots out of commission.  Not worth the time to monkey around with it anymore, I just moved my drives to the primary farmer.

**Comment by stefan-lange** [comment] 2022-05-04 16:33
You could investigate some time into how to use docker (if you not already know) and docker-compose. This makes app deployment with different versions much simpler.

But hey, with your appoach you have saved some energy :-D

**Comment by pnoch** [comment] 2022-05-06 16:09
just recopy the CA folder from farmer to each harvester

**Comment by funskey** [comment] 2022-05-07 21:00
I can confirm I am facing the exact same issue after updating my farmer and rpi4 harvester to 1.3.4. The farmer is seeing the harvester and sending signage_points to it which the harvester is using to check for proofs. I see this in the harvester debug.log

2022-05-08T02:20:17.945 harvester chia.plot_sync.sender   : DEBUG    _send_next_message send plot_sync_invalid: PlotSyncPathList: identifier {'message_id': 3, 'sync_id': 1651956617, 'timestamp': 1651956617}, count 0, final True
2022-05-08T02:20:17.947 harvester harvester_server        : DEBUG    -> plot_sync_invalid to peer 192.168.0.3 f**********
2022-05-08T02:20:17.953 harvester harvester_server        : DEBUG    <- plot_sync_response from peer  f********** 192.168.0.3
2022-05-08T02:20:17.955 harvester chia.plot_sync.sender   : DEBUG    set_response valid PlotSyncResponse: identifier {'message_id': 3, 'sync_id': 1651956617, 'timestamp': 1651956617}, message_type 81, error None
2022-05-08T02:20:17.955 harvester harvester_server        : DEBUG    Time taken to process plot_sync_response from  f********** is 0.002675294876098633 seconds
2022-05-08T02:20:18.047 harvester chia.plot_sync.sender   : DEBUG    _send_next_message send plot_sync_keys_missing: PlotSyncPathList: identifier {'message_id': 4, 'sync_id': 1651956617, 'timestamp': 1651956618}, count 0, final True
2022-05-08T02:20:18.048 harvester harvester_server        : DEBUG    -> plot_sync_keys_missing to peer 192.168.0.3  f**********
2022-05-08T02:20:18.054 harvester harvester_server        : DEBUG    <- plot_sync_response from peer  f********** 192.168.0.3
2022-05-08T02:20:18.056 harvester chia.plot_sync.sender   : DEBUG    set_response valid PlotSyncResponse: identifier {'message_id': 4, 'sync_id': 1651956617, 'timestamp': 1651956618}, message_type 82, error None

The harvester is checking for proofs and the farmer shows all the harvester plots in farm summary. I tried chia init -c [farmer ca] again for the harvester but op's error doesn't go away. Should i be worried?

**Comment by emlowe** [comment] 2022-05-11 22:02
Closing the original issue - note @funskey your issue appears to be a duplicate of #11466

**Closed by emlowe** 2022-05-11 22:02 UTC
