### ISSUE TITLE
P图完成显示同步中，然后就没动静了[BUG]

### ISSUE THREAD

**Issue by liuzhongsheng** [Chia-Network/chia-blockchain#2953] opened 2021-04-28 01:02 UTC
![QQ截图20210428090058](https://user-images.githubusercontent.com/11880549/116330558-5dacbc80-a800-11eb-97eb-617b54b49e65.png)
请问这种情况正常吗

**Comment by royimous** [comment] 2021-04-28 01:17
This is not a bug. Close this. Read the FAQ on how to get support.

**Comment by dorkmo** [comment] 2021-04-28 01:28
looks like you might not be synced

**Comment by liuzhongsheng** [comment] 2021-04-28 04:10
文档说放开端口就可以。我放开了还是没同步，全节点状态倒是在同步

**Comment by liuzhongsheng** [comment] 2021-04-28 04:11
> 这不是错误。关闭这个。阅读有关如何获得支持的常见问题解答。

按照文档的同步依然不行

**Comment by dorkmo** [comment] 2021-04-28 05:43
how many nodes are you connected to?

**Comment by liuzhongsheng** [comment] 2021-04-28 05:45
> 您连接了多少个节点？

4个但是好像都不行，打算使用vpn试试

**Comment by dorkmo** [comment] 2021-04-28 05:46
probably need to have more. have you done the port forwarding for 8444 ?
https://github.com/Chia-Network/chia-blockchain/wiki/Port-8444

**Comment by liuzhongsheng** [comment] 2021-04-28 05:48
> 可能需要更多。您完成了8444的端口转发吗？
> https://github.com/Chia-Network/chia-blockchain/wiki/Port-8444

完成了，但是好像依然无效

**Comment by dorkmo** [comment] 2021-04-28 05:53
yeah, you should almost immediately get 50 peers if its working. A vpn might be worth a try just to see if it would help. you might try adding some introducer peers manually too if you havent already, introducer-apne.chia.net:8444

**Comment by liuzhongsheng** [comment] 2021-04-28 05:54
> explorer-apne.chia.net

对，我转发好像没起作用，不知道是否需要重启

**Comment by liuzhongsheng** [comment] 2021-04-28 06:43
![image](https://user-images.githubusercontent.com/11880549/116358250-04f51800-a830-11eb-97ad-c8fc59417c28.png)
不知道这样算不算连接上了

**Comment by dorkmo** [comment] 2021-04-28 12:02
it doesnt look like you have any Up/Down data being sent, except from that one with 76mb. usually you would see a little data to each peer.

**Comment by dorkmo** [comment] 2021-04-28 14:00
does it show "open" when you test on port checker? https://www.yougetsignal.com/tools/open-ports/

**Comment by liuzhongsheng** [comment] 2021-04-28 14:03
> 在端口检查器上进行测试时，它显示“打开”吗？https://www.yougetsignal.com/tools/open-ports/

14.110.218.138:8444一直就是打开状态

**Comment by dorkmo** [comment] 2021-04-28 14:21
i added you, lets see if it works lol 
![image](https://user-images.githubusercontent.com/1923070/116419834-0c51fc80-a803-11eb-89ed-71cdb5440567.png)

**Comment by dorkmo** [comment] 2021-04-28 14:22
i wonder if you might have a bad database, you might try deleting your chia folder?

**Comment by liuzhongsheng** [comment] 2021-04-28 14:25
> 我想知道您是否有一个错误的数据库，您可以尝试删除chia文件夹吗？

删除会不会影响到正在P的图呢？

**Comment by dorkmo** [comment] 2021-04-28 14:25
try clicking the trash can next to that 49.76.196.103 node. that seems weird

**Comment by liuzhongsheng** [comment] 2021-04-28 14:29
> 请尝试点击该49.76.196.103节点旁边的垃圾箱。看起来很奇怪

谢谢我试试

**Comment by liuzhongsheng** [comment] 2021-04-28 14:35
> 请尝试点击该49.76.196.103节点旁边的垃圾箱。看起来很奇怪

^_^我还是不删除他，那可是最快的一个了

**Closed** 2021-04-30 05:51 UTC
Labels: bug
