### ISSUE TITLE
[BUG]Not Synced

### ISSUE THREAD

**Issue by madmmmax** [Chia-Network/chia-blockchain#2271] opened 2021-04-21 13:08 UTC
**Describe the bug**
Full Node status is Not Synced
Wallet status is Not Synced
I have plotted 2 k-32-101G files. always Not available.
What can I do?

**Desktop (please complete the following information):**
Windows10 1909 x64
Chia Ver.1.0.5

**Additional context**
I have set the port forwarding 8444 to 8444, WAN 50542 to  LAN 8447,  WAN50557 to LAN 8449, did not work

![Snipaste_2021-04-21_21-05-05](https://user-images.githubusercontent.com/64778400/115558609-7e977e00-a2e5-11eb-8e2f-ed760ff4f200.jpg)

![Snipaste_2021-04-21_21-05-20](https://user-images.githubusercontent.com/64778400/115558631-835c3200-a2e5-11eb-91ad-b2b65e600c98.jpg)

**Comment by Repraance** [comment] 2021-04-21 14:03
same problem

**Comment by Q454206464** [comment] 2021-04-21 14:13
Me too!!!!

**Comment by bakabakayaro** [comment] 2021-04-21 14:19
As for me, I get Synced and Not Synced every 15-20 minutes

**Comment by AbnSalim** [comment] 2021-04-21 14:24
can't synced since 7 hours ago
block at height 162021

**Comment by madmmmax** [comment] 2021-04-21 14:47
Give some advice?
My 2 friends have same condition
Its emergency

**Comment by Franpepper** [comment] 2021-04-21 15:22
port forwarding are for udp and tcp? 
You can try to use dmz for 8440 - 8450

**Comment by a1147211355** [comment] 2021-04-21 15:37
Me too!!

**Comment by madmmmax** [comment] 2021-04-21 15:37
> port forwarding are for udp and tcp?
> You can try to use dmz for your local ip adress

Yes for sure, udp and tcp.
DMZ is too danger for my  environment, The Chia PC connected to main LAN.

**Comment by corynadilo** [comment] 2021-04-21 16:16
Same, will not sync for over 24 hours now. . .

**Comment by anderzheng** [comment] 2021-04-21 16:53
Me too. turn to "Not synced", From 4/22 22:47.
 it worked well before. nothing changed, what's the problem?

**Comment by madmmmax** [comment] 2021-04-22 01:24
still not synced, over 24 hours.

**Comment by Franpepper** [comment] 2021-04-22 01:29
> 
> 
> > port forwarding are for udp and tcp?
> > You can try to use dmz for your local ip adress
> 
> Yes for sure, udp and tcp.
> DMZ is too danger for my environment, The Chia PC connected to main LAN.

Can you explain to me how your network is composed?

**Comment by wellswong1990** [comment] 2021-04-22 02:41
+1

**Comment by jenkinrocket** [comment] 2021-04-22 02:58
Same.

**Comment by VingeChen** [comment] 2021-04-22 03:15
same
![image](https://user-images.githubusercontent.com/30143245/115650559-04561080-a35c-11eb-86c6-49c3fec50684.png)

**Comment by VingeChen** [comment] 2021-04-22 03:15
![image](https://user-images.githubusercontent.com/30143245/115650580-13d55980-a35c-11eb-9b07-c7e957d8f792.png)

**Comment by jenkinrocket** [comment] 2021-04-22 03:57
I just kept trying, to reload it, closing the app after a few min (despite the fact that it seemed to still be reloading). I did this a BUNCH of times, closing it completely and restarting each time. Eventually that seemed to fix it.

**Comment by berlef80** [comment] 2021-04-22 04:00
+1

**Comment by VingeChen** [comment] 2021-04-22 04:03
> 我一直尝试尝试重新加载它，在几分钟后关闭应用程序（尽管它似乎仍在重新加载）。我做了很多次，将其完全关闭，然后每次重新启动。最终，这似乎可以解决它。
![image](https://user-images.githubusercontent.com/30143245/115653980-c4def280-a362-11eb-853f-17ed9e622b98.png)

**Comment by VingeChen** [comment] 2021-04-22 04:04
> I just kept trying, to reload it, closing the app after a few min (despite the fact that it seemed to still be reloading). I did this a BUNCH of times, closing it completely and restarting each time. Eventually that seemed to fix it.
![image](https://user-images.githubusercontent.com/30143245/115654023-db854980-a362-11eb-955f-e0c46e82e417.png)

**Comment by madmmmax** [comment] 2021-04-22 04:59
> same
> ![image](https://user-images.githubusercontent.com/30143245/115650559-04561080-a35c-11eb-86c6-49c3fec50684.png)

I uninstalled 1.0.5, upgrade to latest version which is 1.1.0, imported plot final directory, still same.
I just cant figure out why.

**Comment by madmmmax** [comment] 2021-04-22 05:00
> I just kept trying, to reload it, closing the app after a few min (despite the fact that it seemed to still be reloading). I did this a BUNCH of times, closing it completely and restarting each time. Eventually that seemed to fix it.

I tried couple times, Its not for me.

**Comment by madmmmax** [comment] 2021-04-22 05:59
> > > port forwarding are for udp and tcp?
> > > You can try to use dmz for your local ip adress
> > 
> > 
> > Yes for sure, udp and tcp.
> > DMZ is too danger for my environment, The Chia PC connected to main LAN.
> 
> Can you explain to me how your network is composed?

![Snipaste_2021-04-22_13-51-39](https://user-images.githubusercontent.com/64778400/115662691-ee534a80-a371-11eb-8df8-eb74b09427f9.jpg)
I am not a IT guy, I am not sure if its clear.
Router and Openwrt running on Unraid as VMs.
DHCP and Port forwarding on Router.
But I think if all the applications and websites work fine on Chia PC, What makes Chia' synchronization like this?
I have a Nextcloud and couple private websites need port forwarding to share with my friends and they are all good.

**Comment by mariano54** [comment] 2021-04-22 06:19
Please see the FAQ on port forwarding: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Closed by mariano54** 2021-04-22 06:19 UTC
Labels: bug

**Comment by madmmmax** [comment] 2021-04-22 06:22
> Please see the FAQ on port forwarding: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

My 8444 port is open.
![Snipaste_2021-04-22_14-22-17](https://user-images.githubusercontent.com/64778400/115665659-2b214080-a376-11eb-9fa8-baba7575a9f8.jpg)

**Comment by madmmmax** [comment] 2021-04-22 06:24
> Please see the FAQ on port forwarding: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

![Snipaste_2021-04-22_14-23-17](https://user-images.githubusercontent.com/64778400/115665758-4db35980-a376-11eb-9d8a-c2cfd957aae6.jpg)

My 8444 is open. But not working for Chia Sync.

**Comment by Q454206464** [comment] 2021-04-22 06:28
thank you for share~I shut down the firewall and&nbsp;Antivirus software，is work！！！





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG]Not Synced (#2271)






请参阅港口转发的常见问题：https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

我的8444端口开了


—
您正在接收此消息，因为您已评论。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Q454206464** [comment] 2021-04-22 06:29
thank you for share~I shut down the firewall and Antivirus software，is work！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG]Not Synced (#2271)





  
我一直尝试尝试重新加载它，在几分钟后关闭应用程序（尽管它似乎仍在重新加载）。我做了很多次，将其完全关闭，然后每次重新启动。最终，这似乎可以解决它。

**Comment by Q454206464** [comment] 2021-04-22 06:31
if you still can not&nbsp;Sync.&nbsp;I think the VPN can help you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG]Not Synced (#2271)





  
Please see the FAQ on port forwarding: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
  

 
My 8444 is open. But not working for Chia Sync.

**Comment by madmmmax** [comment] 2021-04-22 06:31
> thank you for share~I shut down the firewall and Antivirus software，is work！！！
> […](#)
The firewall on the router is turned off, and there is no anti-virus software installed on Chia PC.

**Comment by Q454206464** [comment] 2021-04-22 06:35
If you can read Chinese, the picture should be able to help you







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] [BUG]Not Synced (#2271)





  
thank you for share~I shut down the firewall and Antivirus software，is work！！！
 …
 The firewall on the router is turned off, and there is no anti-virus software installed on Chia PC.

**Comment by Q454206464** [comment] 2021-04-22 06:45
I can also，I tried all possible ways，don't know what kind of&nbsp; worked.thank god it is working now。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG]Not Synced (#2271)






我只是不断尝试，重新加载它，关闭应用程序后几分钟（尽管事实上，它似乎仍在重新加载）。我这样做了很多次，完全关闭它，并重新启动每一次。最终这似乎解决了问题。

—
您正在接收此消息，因为您已评论。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by prinze77** [comment] 2021-04-22 21:23
same

**Comment by NathanielaJean** [comment] 2021-04-23 13:41
This is usually a system clock issue, which is causing the display of "Not synced", even though you are. Your clock must be set to the exact time, and cannot be more than 5 minutes off. Check your phone and your computer and ensure the time is the same.
 guys make sure your windows is activated and the time zone is correct.

**Comment by bepcyc** [comment] 2021-04-23 17:22
So, the port 8444 is suddenly closed for everyone here and the time got out of sync? That doesn't sound like an explanation. Why did it work before for everyone?
I'm experiencing the same issue now and I'm pretty sure it's a bug. Opening port does not help, syncing time does not help.

**Comment by Franpepper** [comment] 2021-04-23 17:32
> 
> 
> > > > port forwarding are for udp and tcp?
> > > > You can try to use dmz for your local ip adress
> > > 
> > > 
> > > Yes for sure, udp and tcp.
> > > DMZ is too danger for my environment, The Chia PC connected to main LAN.
> > 
> > 
> > Can you explain to me how your network is composed?
> 
> ![Snipaste_2021-04-22_13-51-39](https://user-images.githubusercontent.com/64778400/115662691-ee534a80-a371-11eb-8df8-eb74b09427f9.jpg)
> I am not a IT guy, I am not sure if its clear.
> Router and Openwrt running on Unraid as VMs.
> DHCP and Port forwarding on Router.
> But I think if all the applications and websites work fine on Chia PC, What makes Chia' synchronization like this?
> I have a Nextcloud and couple private websites need port forwarding to share with my friends and they are all good.

Maybe the problem is in your internal network. Are you using Windows? Check firewall settings, and antivirus. Try to ping to another computer in your network across port 8444.

**Comment by coinbirds** [comment] 2021-04-24 07:15
I have same problem. Port 8444 is closed to different PC 
![viber_image_2021-04-24_09-13-59](https://user-images.githubusercontent.com/35643214/115950795-a5200980-a4dd-11eb-8344-40af8d6bccfa.jpg)

**Comment by kjmathue** [comment] 2021-04-24 19:29
We fixed a "Not Synced" issue persisting for a week and several restarts and indefinite waits. The issue was with the System Time being off (drifted somehow, possibly due to the BIOS time not being set ever and hence Windows was never updating the BIOS time) by several hours. The PC synced once the System Time was corrected.

**Comment by AyeBraine** [comment] 2021-04-25 00:07
I have the same issue, opened the port, synchronized the clock in various combinations (with auto, without auto but from server etc.), reset the gui deleting the sqlite profiles. I also tried leaving the Chia GUI instance that doesn't sync (connected via WiFi to the main local router) the only instance on the local network. 

It doesn't sync, and doesn't connect to outside peers. Although if you delete the files and initialize the profile again, it sometimes easily connects to a peer (and start syncing), only to revert in less than a minute to Not Synced.

**Comment by stylefieber** [comment] 2021-04-25 09:07
Same issue here. 1.1.0.

Everything was okay. Port wasn't open. Is now, but nothing changed. There are several connections but no further syncing for me.
Is network load too high, so that many new clients with lower height have to be synced first?

Another machine in my network is synced.

What else could I do? Restart did not help.

**Comment by AbnSalim** [comment] 2021-04-25 09:32
> Same issue here. 1.1.0.
> 
> Everything was okay. Port wasn't open. Is now, but nothing changed. There are several connections but no further syncing for me.
> Is network load too high, so that many new clients with lower height have to be synced first?
> 
> Another machine in my network is synced.
> 
> What else could I do? Restart did not help.

I got blocked at height 162021 4 days ago. version 1.0.5
Here is my solution:
1.The height data are stored with sqlite at somewhere on your computer
My system is windows and I find it an disk C
I backup the sql file and delete it
Then the height become 0 and start sync at 0
This is not a good way because it took me a long time to synced again
You have another machine,maybe you can just copy the sql file?
2.Manual connet to the node.chia.com(I can't remember exactly) with 8444
This solution I find on other issue
But this is not good either
First, this domain can not be visit in china , so if you are in china you need proxy
Second, this connect only work 5 minutes then closed, I don't know why

And I haven't block since last time,Maybe it's still a network problem

**Comment by stylefieber** [comment] 2021-04-25 09:55
Thank you@AbnSalim

I just could temporarily fix it. I looked at the connections from the working machine and opened a new connection on the other machine with one of the ip addresses shown on the working machine (under "connections"). Before I click connect, I disconnect the connection on the working machine. Now it is updating. It might have something to do with the fact that 2 clients with the same wallet key try to update with the same public ip address.

**Comment by alewir** [comment] 2021-04-25 18:27
Same issue here. It was working for couple of days and suddenly without any change from my side I see:
![image](https://user-images.githubusercontent.com/3266706/116004789-ab5cd580-a604-11eb-86a1-c0b676015fec.png)
My system time is correct.
Antivirus/firewall is not blocking it.

**Comment by AyeBraine** [comment] 2021-04-25 18:31
@all please note that a new version of GUI was released (1.1.2). I seem to have solved my problem: nuked all chia data, uninstalled the old version, and installed the new (and also solved an unrelated lan connectivity issue). Currently both machines connect to nodes and, after few sputters of "Not Synced", are actually slowly synching (still half a day to go, as usual).

**Comment by alewir** [comment] 2021-04-25 18:52
Same here - just killed 1.1.1 and installed 1.1.2 over it and it's farming again...

**Comment by ducnv1406** [comment] 2021-04-26 01:44
> Same here - just killed 1.1.1 and installed 1.1.2 over it and it's farming again...

Sure, I have same problem (Not Synced)
Kill old version and install 1.1.2, it works

**Comment by Vadimhtml** [comment] 2021-04-26 07:40
+1

**Comment by bouda05** [comment] 2021-04-26 12:42
I still have issue with sync on 1.1.2 
![obrazek](https://user-images.githubusercontent.com/83223072/116084033-a304a900-a69d-11eb-92af-a8e85c9e74dc.png)

**Comment by Franpepper** [comment] 2021-04-26 13:19
for all those who have problems to synchronize use chiadb.net and port 8444. with this server you can synchronize without problems

**Comment by lucca2011** [comment] 2021-04-26 18:01
> So, the port 8444 is suddenly closed for everyone here and the time got out of sync? That doesn't sound like an explanation. Why did it work before for everyone?
> I'm experiencing the same issue now and I'm pretty sure it's a bug. Opening port does not help, syncing time does not help.

Agree. Always always not synced, so sad.

**Comment by totaldev** [comment] 2021-04-26 23:58
I think that i have same behavior, but i use cmd only. Don't ready for full debug but found some error message in ~/chia/mainnet/log/debug.log

`2021-04-27T02:48:57.878 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /home/deployer/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/deployer/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/deployer/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/home/deployer/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport`

**Comment by ducnv1406** [comment] 2021-04-27 01:49
Did you try Full Node > Connect to other peers

node.chia.net 8444 or
chiadb.net 8444

I saw that, at first I have Not Synced issue, after update one of them, it works
So pls try

**Comment by ducnv1406** [comment] 2021-04-27 01:52
Even I check 8444 with ping.eu, it closed but Chia still synced :)

**Comment by swissarmybox** [comment] 2021-04-27 02:46
> for all those who have problems to synchronize use chiadb.net and port 8444. with this server you can synchronize without problems

@Franpepper how do you do that? I am on Windows 10.

**Comment by ducnv1406** [comment] 2021-04-27 02:48
![image](https://user-images.githubusercontent.com/83194135/116177236-a94a6200-a73d-11eb-8ebc-5570aa0673a7.png)

**Comment by swissarmybox** [comment] 2021-04-27 02:48
> ![image](https://user-images.githubusercontent.com/83194135/116177236-a94a6200-a73d-11eb-8ebc-5570aa0673a7.png)

Appreciate it thank you!

**Comment by dvejok** [comment] 2021-04-27 10:41
Tried to connect for other IP / Port what i  found here - no working.
Reload router not working.. 
All antiviruses closed and time zone is correct.

Last try: delete old version and install new

**Comment by bogdanboogy** [comment] 2021-04-27 11:39
Hello, 

my issue was that I run out of free space on plotting disk because antoher issue. 

It started to sync again as soon as I free up space. 

Maybe you have same issue

Also being connected to peer node.chia.net:8444 looks like it is working better regarding download speed.

**Comment by madmmmax** [comment] 2021-04-29 12:35
> @ALL please note that a new version of GUI was released (1.1.2). I seem to have solved my problem: nuked all chia data, uninstalled the old version, and installed the new (and also solved an unrelated lan connectivity issue). Currently both machines connect to nodes and, after few sputters of "Not Synced", are actually slowly synching (still half a day to go, as usual).

Thanks for your help, Its really worked for me.

**Comment by Sonatix** [comment] 2021-04-30 17:16
client autodelete node.chia.net 8444 node after couple of minutes >.>
Still can't resolve "not synced" problem

**Comment by BluefireXD** [comment] 2021-05-01 11:19
> client autodelete node.chia.net 8444 node after couple of minutes >.>
> Still can't resolve "not synced" problem
> cna telnet and ping chiadb.net 8444 but client do nothing when i try to add this peer

Same issue. 
Some of my PCs are synced and some not. All in the same network, all with same windows configurations and all with chia v1.1.2
Added "node.chia.net 8444" synced for a couple of minutes and it disappeared.

**Comment by stylefieber** [comment] 2021-05-01 12:58
Try disconnect some ips from clients which are synced. I guess that you always can have a max number of connections per public ip.
And then you can connect to ips in your internal network so they can sync faster via local network.

**Comment by eclipsebs** [comment] 2021-05-01 13:24
chiadb.net and node.chia.net doesn't work anymore. HELP!

**Comment by ducnv1406** [comment] 2021-05-02 01:57
There is newer version, pls update to check if your issue can be solved

![image](https://user-images.githubusercontent.com/83194135/116799538-5b11d600-ab24-11eb-86c2-8250f68d6a6a.png)

**Comment by wetchler** [comment] 2021-05-03 06:20
I still have this issue on 1.1.3 -- though I have several computers on the network plotting and running nodes. Port 8444 is open on the router. Thoughts?

**Comment by stylefieber** [comment] 2021-05-03 07:39
Yes. Take some working connection from one client and connect it with the other one. But before you click connect, disconnect the ip from the working host.

Additionally you can connect your hosts internally via local ip addresses.

**Comment by eclipsebs** [comment] 2021-05-03 08:48
For me it works regardless of version. In my first version, the local IP connection worked at the beginning, then only sometimes. In version 1.1.2 worked only with chiadb.net:8444 . In version 1.1.3, I was able to connect to chiadb.net for the first time in many cases. I don't know why, but chiadb.net always close the synchro around 3:30 UTC + 1 (Berlin).

**Comment by morovid95** [comment] 2021-05-03 14:17
I had the same issue. First i checked my Bios and my System time it need to be the same! after this it doesn't work and i deleted my .chia directory and restarted chia after this it goes syncing very well for me (sry for my English)

**Comment by yogi19871987** [comment] 2021-05-04 14:12
> Jeśli chodzi o mnie, jestem zsynchronizowany i niezsynchronizowany co 15-20 minut

me tooo

**Comment by dor7dev** [comment] 2021-05-05 13:00
Happens for me too

**Comment by zarga12** [comment] 2021-05-07 11:48
I had the same issue. just relolad :+1:

**Comment by kazacuuu** [comment] 2021-05-07 20:41
> same problem

Issue solved for me when i changed the date/time because was incorrect. Try that GOOD LUCK

**Comment by BluefireXD** [comment] 2021-05-07 21:20
> > same problem
> 
> Issue solved for me when i changed the date/time because was incorrect. Try that GOOD LUCK

Do you mean the Peak Time? System Time (WIndows)?

**Comment by kazacuuu** [comment] 2021-05-07 21:31
System windows time

Sent from Yahoo Mail on Android 
 
  On Fri., 7 May 2021 at 3:20 p.m., Patrick ***@***.***> wrote:   




same problem


Issue solved for me when i changed the date/time because was incorrect. Try that GOOD LUCK


Do you mean the Peak Time? System Time (WIndows)?

**Comment by justnewbiem** [comment] 2021-05-10 23:46
> > client autodelete node.chia.net 8444 node after couple of minutes >.>
> > Still can't resolve "not synced" problem
> > cna telnet and ping chiadb.net 8444 but client do nothing when i try to add this peer
> 
> Same issue.
> Some of my PCs are synced and some not. All in the same network, all with same windows configurations and all with chia v1.1.2
> Added "node.chia.net 8444" synced for a couple of minutes and then it disappeared.

hey..same pb..after a few minutes node.chia.net 8444 dissapperaing..did u solve the pb..? actullay after getting some data (like 0.2/0.6) then dissapperating..

**Comment by justnewbiem** [comment] 2021-05-11 00:18
> Try disconnect some ips from clients which are synced. I guess that you always can have a max number of connections per public ip.
> And then you can connect to ips in your internal network so they can sync faster via local network.

hey..

what is the max number of connection do u know it..?

**Comment by BluefireXD** [comment] 2021-05-11 00:45
Chia Client is buggy as hell. Im still randomly loosing connections. You never can be sure that your rig is farming 100%.

**Comment by justnewbiem** [comment] 2021-05-11 00:49
> Chia Client is buggy as hell. Im still randomly loosing connections. You never can be sure that your rig is farming 100%.

thanx alot for ur reply.. i have never lose the connection..always "Synced".. my only pb is i cannot open port 8444..i tried all thing on modem but no success.. yes u r right that our rigs r not working fully ( maybe pb is port maybe ram or etc ) the only thing is that we have to wait for chia.. if we have luck.. :(

**Comment by BluefireXD** [comment] 2021-05-11 11:49
yey 12h hours out of sync. No manuell connect via node.chia.net possible...
Often it helps to restart chia.. but then temp plot progress is lost...yey

**Comment by dazhazit** [comment] 2021-05-13 14:05
In truth I'm about to give up on this. Line 273 of server.py  seems to be checking some kind of peer id and crapping out. What's that all about eh?
Port 8444 is correctly opened via uPnP on my router and at least some of the hosts are pingable.
chiadb.net and node.chia.net etc have both been tried but I have never been able to connect from the very get go on the windows client. 
To be quite honest this is not what I was expecting for something trading on the crypto market now and not very professional or polished from supposed experts in the crypto field.
Seriously unimpressed.
Actually I'm going to bump this as a new thread as even 1.1.5 doesn't do the trick. You need to sort this and pretty rapidly.

**Comment by Fusseldieb** [comment] 2021-05-13 14:22
Same problem.

Makes absolutely no sense because it was working just fine a couple of days earlier.

I have 1TB plotted and can't even use it. Seen that I probably won't even get a single dollar out of this per day **even if it works**, I might just give up.

**Comment by cihansardaslar** [comment] 2021-05-15 14:14
Still same problem guys... Any solutions? got 9 plots doing nothing and still killing my ssd for nothing....

**Comment by Claptou** [comment] 2021-05-15 15:42
Same

**Comment by cihansardaslar** [comment] 2021-05-15 15:50
Hey guys, I was able to fix the problem by opening ports 8444, 8448, 8449.

On firewall I opened both inbound and outbound and both tcp and udp. So i had 6 news rules for inbound and 6 new rules for outbound. 

Let me know if it works for you as well! :)

**Comment by dvejok** [comment] 2021-05-17 22:00
> Hey guys, I was able to fix the problem by opening ports 8444, 8448, 8449.
> 
> On firewall I opened both inbound and outbound and both tcp and udp. So i had 6 news rules for inbound and 6 new rules for outbound.
> 
> Let me know if it works for you as well! :)

Nah, not helped

**Comment by madmmmax** [comment] 2021-05-18 01:58
> > Hey guys, I was able to fix the problem by opening ports 8444, 8448, 8449.
> > On firewall I opened both inbound and outbound and both tcp and udp. So i had 6 news rules for inbound and 6 new rules for outbound.
> > Let me know if it works for you as well! :)
> 
> Nah, not helped

Hey, Once I fixed this issue, I realized if you set up Port forwarding and UPnP correctly, Sync always work. No matter how many times reboot Chia or PC.
But at the very start phase, it gonna take some time to initialize or something.
When I first received replies said that I have to re-check my configuration of Port Forwarding, I just thought that was a joke,
But.. the truth is I certainly did that wrong.

**Comment by oonqt** [comment] 2021-05-22 06:37
It synced up until about 210k, then it just conked out and stop syncing. Tried wiping the entire DB to start from scratch and now it won't even sync at all, just sits at "Syncing 0/blockchainheight" for hours. I have my ports forwarded, time synced, tried reinstalling, tried restarting host, tried restarting router, nothing works. The fact that this has basically zero attention from maintainers is honestly pathetic.

**Comment by borito62** [comment] 2021-05-22 08:13
Me too, about 3 days synchronisation and i m only halfway. It's normal ? It s very long.
I have a plot but it is in synchronization. I should have waited before plot?
![Screenshot_20210522-101050_Microsoft Remote Desktop](https://user-images.githubusercontent.com/84617947/119219472-15727880-bae6-11eb-8090-6498312daf18.jpg)

**Comment by borito62** [comment] 2021-05-22 09:17
![Screenshot_20210522-111025_Microsoft Remote Desktop](https://user-images.githubusercontent.com/84617947/119221308-02b07180-baef-11eb-8f38-04f679f9de63.jpg)
I dont set up port forwarding on my firewall but we see that the communication works no?

**Comment by alewir** [comment] 2021-05-22 09:18
I was having troubles with it for weeks now. I thought that update to the 1.1.5 fixed it but it was just a pure luck. This is because it's not an issue with ports forwarding etc. but it's some reconnection/timeout issue. Sometimes it just hangs in Not synced state and doesn't even seem to do any further retry. (This happens usually when the connection is overloaded, e.g. moving plots over network locations.) What I've learned about it is that what helps here is just restarting the app couple of times and after each restart waiting for couple of minutes - eventually it starts syncing but after some time it will break again and one has do go through restarting manually again... So now it seems for me as an obvious bug in the app.
