### ISSUE TITLE
[Bug] [Wallet]

### ISSUE THREAD

**Issue by santivu** [Chia-Network/chia-blockchain#12585] opened 2022-07-25 14:14 UTC
### What happened?

Several farmers (like me), were receving during varios months thousands of small transactrions of 0.000000000002 XCH every day, so at the end our wallet is so huge, with more than 1.768.140 transactions.
There are two big problems I'm suffering:

1. Traumatic synchronization process. A normal farmer, deleting the wallet and starting the client, can get the wallet fully synchonize in about 15 minutes. In my case (if I'm lucky and nothing happens), it takes around 30 hours.
Also if trying to get a fresh cold wallet, the process never complete. When arriving to the curent peak, it never achieve it.

2. I was forced to create a new wallet with 24-word, just to help me into manage my XCH savings. Most of the times, when I win a block and try to transfer the 2 XCH from my farming walleto to the clean one, the client process crash, I can imagine due to the huge amount of blocks to move. BTW, after reopening the client, sometimes the transaction is correctly performed.

Could you consider any cleaning process or so in order to help in cases like mine?

Many thanks,

![Captura de pantalla 2022-07-25 160446](https://user-images.githubusercontent.com/88079415/180798214-5488f022-7f05-493f-870c-3a5c55fc6148.png)

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by jeansalim** [comment] 2022-07-26 08:37
Same here. On CLI, using the wallet is a nightmare

**Comment by wallentx** [comment] 2022-07-28 17:39
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/12524

**Closed by wallentx** 2022-07-28 17:39 UTC
Labels: bug, sync
