### ISSUE TITLE
[BUG]Not receiving XCH rewards

### ISSUE THREAD

**Issue by REIS77-COMMITS** [Chia-Network/chia-blockchain#7838] opened 2021-07-28 11:34 UTC
Hello all,

I am having a problem. Can anyone help me with it? I have this showing up in my wallet history: Incoming | xch16s6mvftf7w528u336rrggt8594594e7zmn3d58nz2nz6dej85yyswm86q4 | 07/10/2021 18:05:37 | Confirmed at height 552369 | 1,749999999999 but no such amount in my wallet. My full node and wallet are synced. I am using Chia Blockchain in two different computers with the same seed phrases. My second computer does not show that transaction in wallet history. I have already installed the latest version of Chia Blockchain in both computers.

Thanks,

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by markusmazurczak** [comment] 2021-07-29 07:33
This is not a bug. Please use the "Discussion"-section and close this ticket: https://github.com/Chia-Network/chia-blockchain/discussions/categories/support

**Closed** 2021-07-29 08:01 UTC
Labels: bug
