### ISSUE TITLE
[BUG][ubuntu 20.04LTS][CLI Plotting] Task/Process abort with no reason, no error logs.

### ISSUE THREAD

**Issue by dicoolx** [Chia-Network/chia-blockchain#2713] opened 2021-04-25 15:52 UTC
[ubuntu 20.04LTS][CLI Plotting] Task/Process abort with no reason, no error report.

cpu: amd 5950X, oc 4.65Ghz
dram: 128gb ddr4 3200mhz
SSD: pm9a3[ 960G+1.92T, raid0 by mdadm]

Here is the bash
screen -d -m -S chia1 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 0h && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp1 -2 /mnt/plot -d /media/xxx/4t_01 |tee /home/xxx/chialogs/chia1_1_.log'
screen -d -m -S chia2 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 0h && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp2 -2 /mnt/plot -d /media/xxx/4t_02 |tee /home/xxx/chialogs/chia2_1_.log'
screen -d -m -S chia3 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 0h && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp3 -2 /mnt/plot -d /media/xxx/4t_03 |tee /home/xxx/chialogs/chia3_1_.log'
screen -d -m -S chia4 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 0h && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp4 -2 /mnt/plot -d /media/xxx/4t_04 |tee /home/xxx/chialogs/chia4_1_.log'
screen -d -m -S chia5 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 0h && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp5 -2 /mnt/plot -d /media/xxx/4t_05 |tee /home/xxx/chialogs/chia5_1_.log'
screen -d -m -S chia6 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 55m && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp6 -2 /mnt/plot -d /media/xxx/4t_06 |tee /home/xxx/chialogs/chia6_1_.log'
screen -d -m -S chia7 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 55m && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp7 -2 /mnt/plot -d /media/xxx/4t_07 |tee /home/xxx/chialogs/chia7_1_.log'
screen -d -m -S chia8 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 55m && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp8 -2 /mnt/plot -d /media/xxx/4t_08 |tee /home/xxx/chialogs/chia8_1_.log'
screen -d -m -S chia9 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 55m && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp9 -2 /mnt/plot -d /media/xxx/4t_09 |tee /home/xxx/chialogs/chia9_1_.log'
screen -d -m -S chia10 bash -c 'cd /home/xxx/chia-blockchain && . ./activate && sleep 55m && chia plots create -k 32 -b 5000  -r 4 -u 128 -n 2 -t /mnt/plot/temp10 -2 /mnt/plot -d /media/xxx/4t_10 |tee /home/xxx/chialogs/chia10_1_.log'

After I started the bash, within 30 mins, the first 5 tasks aborted  one by one with no reason and no error logs.
I tried to revise the buffer from 5000 to 3400, still happened.

**Comment by hoffmang9** [comment] 2021-04-25 17:11
This looks like a problem with your file system.

**Comment by royimous** [comment] 2021-04-25 21:50
It looks like you're using the script from Chia Decentral. Even has the extra apostrophe and no space before `tee`.

Did you format the temp drive to xfs?

**Comment by hoffmang9** [comment] 2021-04-25 21:54
Closing because tech support and not a bug.

**Closed by hoffmang9** 2021-04-25 21:54 UTC
Labels: bug
