### ISSUE TITLE
Chia 1.3.1 app stuck when opening. MacOS Mojave[Bug] 

### ISSUE THREAD

**Issue by kamba89** [Chia-Network/chia-blockchain#10819] opened 2022-03-21 06:59 UTC
### What happened?

Tried on two different macs with clear MacOS Mojave Installed. 
Chia 1.3.1 app stuck when opening. 
But works fine on the same Mac with Catalina.

While the installation instructions state:
_"MacOS Mojave or newer"_

### Version

1.3.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by S1m0nP1** [comment] 2022-03-21 09:17
Have a look at this issue: https://github.com/Chia-Network/chia-blockchain/issues/10687

Should be fixed in next release

**Comment by emlowe** [comment] 2022-03-22 22:07
Duplicate of #10687

**Closed by emlowe** 2022-03-22 22:07 UTC
Labels: bug

**Comment by networkjackbb** [comment] 2022-03-23 18:35
I just downloaded 1.3.1 to update my 1.2.11 and I'm hanging on the "Loading keyring status" message.
