### ISSUE TITLE
GUI Doesn't show all plots from all harvesters/farmers (1.2.0)

### ISSUE THREAD

**Issue by zuboje** [Chia-Network/chia-blockchain#7260] opened 2021-07-09 01:11 UTC
**Current behavior**

Running chia farm summary I receive this:

```
Last height farmed: 488128
Local Harvester
   1084 plots of size: 108.065 TiB
Remote Harvester for IP: x.x.x.x
   6377 plots of size: 631.152 TiB
```

GUI shows 6377

![image](https://user-images.githubusercontent.com/5181730/125008333-2a17bb00-e017-11eb-84c5-047424df434e.png)

**Expected behavior**

GUI Should show all plots

**Setup**
Farmer, Full Node: Windows 10 20H2, Chia 1.2.0
Harvester: Windows Server 2019, chia 1.2.0

**Notes**
While I do understand that this feature is new it is fairly buggy, it takes a lot of time to show, it doesn't update when new plots are added. I know that harvester is working as expected because in "filter" I can see correct number, but total count is not working as expected. In addition to this in some instances to resolve it, you have to close GUI and re-open, but it doesn't work all the time

**Comment by RyanWendel** [comment] 2021-07-09 02:38
I am having similar issues.  

Setup
Farmer, full node: Windows, Chia 1.2.0
Harvester, farmer Ubuntu 20.04.2 LTS, Chia 1.2.1.dev0
Harvester, farmer Ubuntu 20.04.2 LTS, Chia 1.2.1.dev0

The screenshot below shows that my GUI farmers plot count isn't synching up with the plots passed filter.  It shows 1,849 plot count and 194.644TiB in space.  Which is what it's said all day, but the plots passed filter is showing all the plots?  I am not sure what is going on there.  
![image](https://user-images.githubusercontent.com/9411161/125013945-bc7d8600-e03a-11eb-8307-b147d9b72087.png)

My pool NFT is also not working or at least not working well.  It doesn't show any of my plots that were created with the -c contract key.  I have plots created on my main farmer using the chia plotters.  All of my harvesters have created plots with the madmax plotters using the correct -c contract key
![image](https://user-images.githubusercontent.com/9411161/125015062-c3a59380-e03c-11eb-8c7b-fd9b2e43472d.png)

The total plots and even total size on my main framer for local plots is wrong.  
The expected results for my local farm should be around 200TiB and my total farm space should be closer to 330TiB.  
![image](https://user-images.githubusercontent.com/9411161/125014697-2ba7aa00-e03c-11eb-9295-3907e5197c47.png)

On my harvester, chia farm summary is completely wrong, it doesn't even show total local plots.  
![image](https://user-images.githubusercontent.com/9411161/125014864-70cbdc00-e03c-11eb-8410-596f1f018749.png)

On my other Ubuntu harvester it's the same story. 
![image](https://user-images.githubusercontent.com/9411161/125014944-95c04f00-e03c-11eb-9f35-c6f3da0bdb9a.png)

All in all this update to 1.2.0 has been a disaster for my current setup.

**Comment by elarkasi** [comment] 2021-07-09 03:07
a temporary solution is the refresh plots option on plots page

**Comment by RyanWendel** [comment] 2021-07-09 03:19
> a temporary solution is the refresh plots option on plots page

That also does nothing for my plots.

**Comment by mbaric1** [comment] 2021-07-09 11:05
See #7262 and Chia-Network/chia-blockchain-gui#487

**Comment by hhenrry501** [comment] 2021-07-10 04:15
same here. so frustrated. is it still farming tho? even if not showing all the plots

**Comment by hhenrry501** [comment] 2021-07-10 04:15
fresh button dont work

**Comment by Sagittarius** [comment] 2021-07-10 18:57
try to change log level to DEBUG, it works for me

**Comment by emlowe** [comment] 2021-07-12 15:40
Duplicate of #7223

**Closed by emlowe** 2021-07-12 15:40 UTC
