### ISSUE TITLE
[Bug] Log file running wild with errors

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#12040] opened 2022-06-23 19:08 UTC
### What happened?

Latest Beta 1.3.6943.0 is producing wallet chia.wallet.wallet_node    : ERRORs

### Version

1.3.6943.0 

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-23T15:03:24.136 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.143 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.152 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.157 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.162 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.164 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.170 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.172 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.174 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.175 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.178 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.179 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.184 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop

2022-06-23T15:03:24.186 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 372, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:372>> got Future <Future pending> attached to a different loop
```

**Comment by wallentx** [comment] 2022-06-23 23:26
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/11980

**Closed by wallentx** 2022-06-23 23:26 UTC
Labels: bug
