### ISSUE TITLE
GUI 1.2.2 does not automatically detect plots created with CLI Plots

### ISSUE THREAD

**Issue by FVierra27** [Chia-Network/chia-blockchain#7729] opened 2021-07-22 15:56 UTC
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/7697

<div type='discussions-op-text'>

<sup>Originally posted by **JimbiniBambini** July 21, 2021</sup>
Hey guys, 

I would be so happy if you would add a feature (or fix a BUG), which automatically detects new plots added by CLI to the specified directories (same directory in GUI and CLI).

Curently everything what was created with CLI on the same PC, where the main node is running and on the harvester must be updated manually over the GUI (refresh plots --> after they are added). 

Thank a lot! </div>

Having same problem with 1.2.2. Create plots with plotman rsync to separate farmer. The GUI doesn't update number of plots until I hit refresh.

**Comment by emlowe** [comment] 2021-07-22 20:29
Duplicate of #7262

**Closed by emlowe** 2021-07-22 20:29 UTC
