### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by guntoro2001** [Chia-Network/chia-blockchain#7366] opened 2021-07-11 08:16 UTC
[](url)**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: windows 10 pro
- OS Version/Flavor: 20H2/19042.1083
- CPU: Core i7 9700F

**Additional context**
![Plot error](https://user-images.githubusercontent.com/30783289/125187678-f62cd780-e25a-11eb-81db-35d9243b747c.jpg)

**Comment by emlowe** [comment] 2021-07-12 15:50
Seems a duplicate of #7361

**Closed by emlowe** 2021-07-12 15:50 UTC
Labels: bug
