### ISSUE TITLE
I cant input text in the join pool.   

### ISSUE THREAD

**Issue by kinkymann** [Chia-Network/chia-blockchain#9042] opened 2021-10-31 07:38 UTC
I cant enter text or anything in the pool address.  i cant copy paste..   (pool tab)

**Comment by shaneo257** [comment] 2021-10-31 08:46
its a known issue in 1.2.10, you can either join a pool via the cli or download the latest beta software from https://www.chia.net/download/ with the fix
if you download the beta software, you wont be able to get support

**Comment by kinkymann** [comment] 2021-10-31 12:31
Ok understood.. thank you..

**Comment by temicus** [comment] 2021-10-31 22:21
Same problem 🙁

**Comment by emlowe** [comment] 2021-11-01 16:18
You can use the CLI. Duplicate of #8944

**Closed by emlowe** 2021-11-01 16:18 UTC
Labels: bug

**Comment by temicus** [comment] 2021-11-01 17:35
@emlowe how can I join a pool using existing nft plots... can't find info. Have tried with "join" but it doesn't work...
