### ISSUE TITLE
[BUG] WALLET LOSES CONNECTION SUDDENLY ONCE IN 2 DAYS (INTERNET IS STABLE)

### ISSUE THREAD

**Issue by tzlsgr** [Chia-Network/chia-blockchain#5749] opened 2021-05-21 22:09 UTC
Hello,
i have the following problem
i hafe a full node in a pc running 3 plots at a time and everything goes well..suddeenly once in two days node loses connection to wallet (not synced) i have to restart the software to be able to connect 
i saw only connecting to wallet for hours
internet is stable 
i have an other computer connected to an other wallet in the same network and everything is fine
this thing happend suddenly 3 times in 7 days
***edit*** This happend only when some plots passed filter

- OS: win10 
- OS Version/Flavor: win 10 pro
- CPU: i5-6500

**Comment by mariano54** [comment] 2021-06-28 08:13
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:13 UTC
Labels: bug
