### ISSUE TITLE
v1.1.7 did not solve the issue of Connecting to Wallet

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#6528] opened 2021-06-06 15:35 UTC
**Describe the bug**
Installed version 1.1.7 over 1.1.6. Opened the app. Connecting to wallet still takes a long time. Force reload has the same result. It's now 30 minutes after opening the app still Connecting to wallet. Killed the app and opened it still same issue.
![Screen Shot 2021-06-06 at 11 28 51 PM](https://user-images.githubusercontent.com/225284/120930442-d6683800-c71f-11eb-940b-30ff569bf5b3.png)

**To Reproduce**
Install latest version over the old app.

**Expected behavior**
Open the wallet or GUI immediately.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Catalina (10.15.7)
- CPU: iMac (27-inch, Late 2013)

**Additional context**
This is a poor GUI. The app should open regardless of issue with wallet. There are other parts of the app the can be loaded already like the plotting feature. Push any sync or wallet connection to the background and just show/load the app. We can plot I think although wallet still connecting. Just display the "Connecting to wallet" when user clicks Wallet from menu.

**Comment by WesleyAJGdeVries** [comment] 2021-06-06 15:53
maybe your cache is corrupt

**Comment by Zenage98** [comment] 2021-06-06 16:28
man, don't unistall anything, if you have wifi or any other kind of connection try disabling it, not simply setting it off, i've got the same error on windows, and i solved it by disabling totally my wifi card, idk if you can do it in macos

**Comment by joelrb** [comment] 2021-06-06 16:32
> maybe your cache is corrupt

I have been clearing that cache/db since 1.1.5... no luck for me.

**Comment by joelrb** [comment] 2021-06-06 16:33
> man, don't unistall anything, if you have wifi or any other kind of connection try disabling it, not simply setting it off, i've got the same error on windows, and i solved it by disabling totally my wifi card, idk if you can do it in macos

I did not uninstall. I installed over existing app.

**Comment by CiobanuCatalin** [comment] 2021-06-06 17:11
Hi. I have the same problem. I tried everything.
![error](https://user-images.githubusercontent.com/85452965/120933549-50d68f00-c703-11eb-8e28-8f74b01edd9b.jpg)

**Comment by Zenage98** [comment] 2021-06-06 17:28
> > man, don't unistall anything, if you have wifi or any other kind of connection try disabling it, not simply setting it off, i've got the same error on windows, and i solved it by disabling totally my wifi card, idk if you can do it in macos
> 
> I did not uninstall. I installed over existing app. I don't use wifi.. it's connected to router via cable.

yes but your machine has wifi, even if you don't use it

**Comment by joelrb** [comment] 2021-06-06 18:01
> > > man, don't unistall anything, if you have wifi or any other kind of connection try disabling it, not simply setting it off, i've got the same error on windows, and i solved it by disabling totally my wifi card, idk if you can do it in macos
> > 
> > 
> > I did not uninstall. I installed over existing app. I don't use wifi.. it's connected to router via cable.
> 
> yes but your machine has wifi, even if you don't use it

yeah it has but it's turned off. my other machine don't have this issue.

**Comment by mariano54** [comment] 2021-06-28 07:55
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:55 UTC
Labels: bug
