### ISSUE TITLE
GUI SHOWS WHITE SCREEN - FORCE RELOAD DOESNT HELP

### ISSUE THREAD

**Issue by aje247** [Chia-Network/chia-blockchain#6144] opened 2021-05-28 02:01 UTC
This has been happening multiple times a day for the past week.

**Comment by VikingoGarage** [comment] 2021-05-28 07:14
yeah , mee too , this is the error 

![image](https://user-images.githubusercontent.com/84959197/119944850-29e1c580-bf6b-11eb-8899-02b893285fef.png)

**Comment by adwebinc** [comment] 2021-05-30 22:20
Yes.  I have this error happen on all three of my plotting machines.  Force close and reboot the machine and restart Chia is the only way to get the app back.  This also strands several plots and is a waste of resources.

**Comment by mariano54** [comment] 2021-06-28 08:30
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:30 UTC
