### ISSUE TITLE
[BUG] Unable to Sync

### ISSUE THREAD

**Issue by AK1244** [Chia-Network/chia-blockchain#4304] opened 2021-05-09 15:27 UTC
**Describe the bug**
Unable to Sync wallet

**To Reproduce**
Restart app

**Expected behavior**
Normally when I restart the app it says not synced then a couple minutes later it says synced. 

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 19042.964
- CPU: AMD Ryzen 7 5800x

**Comment by Muffexx** [comment] 2021-05-09 15:28
Duplicate of #4296
Please consider searching the existing bugs before creating new ones.

**Comment by DFAnk1** [comment] 2021-05-09 15:35
It just synced again !

**Comment by usertest001** [comment] 2021-05-09 15:39
没交付，服务器被拔网线了？？？

**Comment by wrosko** [comment] 2021-05-09 16:09
Shouldn't be active, should be mark as resolved given network problem and @Muffexx comment

**Closed** 2021-05-09 19:31 UTC
Labels: bug
