### ISSUE TITLE
[BUG] can't connect to wallet

### ISSUE THREAD

**Issue by BraedenDias** [Chia-Network/chia-blockchain#5707] opened 2021-05-21 13:01 UTC
I tied to connect and it took all night and it still did not load

**Comment by 321SK** [comment] 2021-05-21 13:51
Fist all plots are gone an now can't connect :-(

**Comment by kittinzaa** [comment] 2021-05-21 14:16
Same I tried the third time loading for 20 min then come up with a blank screen.
Will try to do aclean install Chia to see it will help.

**Comment by raizac** [comment] 2021-05-21 15:45
still can not connect to wallet !

**Comment by digplan** [comment] 2021-05-21 16:04
If Windows, try go to Task Manager. Kill start_wallet, start_harvester etc.. processes.  (Don't kill any running plotting processes!)  close then restart the GUI

**Comment by wbendick** [comment] 2021-05-21 16:30
Try rebooting and see if you can connect

**Comment by raizac** [comment] 2021-05-21 16:52
not working I have tried to reinstall made sure it can go through my firewall / AV 
![image](https://user-images.githubusercontent.com/82903529/119171955-e9de8800-ba2a-11eb-84d5-08dd96ac9b60.png)

**Comment by gribliq** [comment] 2021-05-22 00:40
It seems that I have the solution, the only thing I did is overwrite the initial-config.yaml file
here it is
https://github.com/Chia-Network/chia-blockchain/edit/main/chia/util/initial-config.yaml#L273

**Comment by Connor-Knabe** [comment] 2021-05-22 11:23
If restarting/reinstalling doesn't fix it you can try moving all of the files in C:\Users\%username%\.chia\mainnet\wallet\db to a new folder called backup in that same directory and try starting again

This fixed it for me

**Comment by marcoalmeidausa** [comment] 2021-05-22 18:50
I have the same problem.

**Comment by mariano54** [comment] 2021-06-28 08:13
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:13 UTC
Labels: bug
