### ISSUE TITLE
Windows GUI Key ring loop [BUG]

### ISSUE THREAD

**Issue by Flantas** [Chia-Network/chia-blockchain#6675] opened 2021-06-10 21:58 UTC
On the window GUI if i select they key ring there is no way to get back to the plotter GUIwith out selecting a key. If i only have one key on the machine the GUI gets stuck in a loop trying to load the key thats already being used.

**To Reproduce**

1. Go to 'windows GUI version 1.1.7'
2. Click on 'key ring on left side'
3. Scroll down to 'try to get back to plotter menu'

**Expected behavior**
There should be a simple tab like farm or plotter that can display current key info with an option/ button to attempt to switch keys.

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10 pro
- OS Version/Flavor: 20H2
![key hang up](https://user-images.githubusercontent.com/85711252/121602524-06a82300-ca0d-11eb-9459-97768eeb98c4.PNG)

- CPU: xeon x3470

**Additional context**
the picture is the DEV console loop
![key hang up](https://user-images.githubusercontent.com/85711252/121602577-20e20100-ca0d-11eb-93db-671ce98609ab.PNG)

**Comment by bobro2** [comment] 2021-06-11 20:49
Same here

**Comment by gromran** [comment] 2021-06-12 07:45
Close all Chia related treads (task manager) and start chia

**Comment by bobro2** [comment] 2021-06-12 09:03
I did try following:
- Uninstall chia
- Remove all chia folders (.chia, Local/chia-blockchain, Roaming/Chia Blockchain)
- Restarted PC
- Installed 1.1.7
- Stuck on Connecting to wallet

Win 10 Pro, 20H2 version

Weird thing is that it also happens to me with 1.1.6 but 1.1.5 is working just fine

**Comment by cafsantos7** [comment] 2021-06-14 15:48
> I did try following:
> 
> * Uninstall chia
> * Remove all chia folders (.chia, Local/chia-blockchain, Roaming/Chia Blockchain)
> * Restarted PC
> * Installed 1.1.7 GUI version
> * Stuck on Connecting to wallet
> 
> Win 10 Pro, 20H2 version
> 
> Weird thing is that it also happens to me with 1.1.6 but 1.1.5 is working just fine

I have the same issue. Did I manage to solve it?

**Comment by bobro2** [comment] 2021-06-14 17:31
> > I did try following:
> > 
> > * Uninstall chia
> > * Remove all chia folders (.chia, Local/chia-blockchain, Roaming/Chia Blockchain)
> > * Restarted PC
> > * Installed 1.1.7 GUI version
> > * Stuck on Connecting to wallet
> > 
> > Win 10 Pro, 20H2 version
> > Weird thing is that it also happens to me with 1.1.6 but 1.1.5 is working just fine
> 
> I have the same issue. Did I manage to solve it?

No, I think it has something to do with windows DNS settings. Maybe windows firewall has some issues.

**Comment by Flantas** [comment] 2021-06-22 20:23
The people who have replied to this issue so far don't seem to grasp what the issue is. its a simple menu swap that locks up the gUI and shouldn't require a restart. Thanks to everyone that had suggestions on how to work around it but it's a QOL bug that needs fixed not worked around. If anyone who works with the GUI code would like more details please email on PM me. I am fully registered now.

**Comment by bobro2** [comment] 2021-06-23 21:47
It is probably not a GUI issue. Even in the CMD I am having problems. Seems connected to my DNS settings.

```
File "chia\server\start_farmer.py", line 68, in <module>
  File "chia\server\start_farmer.py", line 64, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 220, in async_run_service
  File "chia\server\start_service.py", line 160, in run
  File "chia\server\start_service.py", line 136, in start
  File "chia\server\server.py", line 218, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('::', 8447, 0, 0): only one usage of each socket address (protocol/network address/port) is normally permitted
[7680] Failed to execute script start_farmer
Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 219, in async_run_service
  File "chia\server\start_service.py", line 93, in __init__
  File "chia\wallet\wallet_node.py", line 317, in set_server
  File "chia\server\node_discovery.py", line 645, in __init__
  File "chia\server\node_discovery.py", line 66, in __init__
  File "dns\resolver.py", line 732, in __init__
  File "dns\resolver.py", line 928, in read_registry
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "dns\name.py", line 942, in from_text
dns.name.EmptyLabel: A DNS label is empty.
[6380] Failed to execute script start_wallet
Traceback (most recent call last):
  File "chia\server\start_full_node.py", line 65, in <module>
  File "chia\server\start_full_node.py", line 60, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 220, in async_run_service
  File "chia\server\start_service.py", line 160, in run
  File "chia\server\start_service.py", line 136, in start
  File "chia\server\server.py", line 218, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8444): only one usage of each socket address (protocol/network address/port) is normally permitted
```

I did try to change all "localhost" findings in config.yaml for "127.0.0.1" but that did not help

**Comment by bobro2** [comment] 2021-06-24 19:51
OK guys, I found the issue. It had something to do with my ISP router DNS addresses. I did change my DNS statically to cloudflare, you can find complete tutorial here https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/windows You only need to change IPv4 address.

**Comment by mariano54** [comment] 2021-06-28 07:54
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:54 UTC
Labels: bug
