### ISSUE TITLE
i can't connect to my wallet. it takes 2 hrs. still not connected

### ISSUE THREAD

**Issue by haroon889** [Chia-Network/chia-blockchain#5687] opened 2021-05-21 09:54 UTC
**Describe the bug**

i can't connect to my wallet. it takes 2 hrs. still not connected
**To Reproduce**
i can't connect to my wallet. it takes 2 hrs. still not connected

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by PIVEC96** [comment] 2021-05-21 10:05
Yes I have the same problem it has been going on for a week and still the same just the original screen is attached to the wallet and nothing

**Comment by edgehome** [comment] 2021-05-21 12:15
same here

**Comment by kittinzaa** [comment] 2021-05-21 14:17
I think so many people having this problem at the moment.

**Comment by wbendick** [comment] 2021-05-21 16:43
Did you try to reboot?

**Comment by haroon889** [comment] 2021-05-21 16:44
เมื่อ ศ. 21 พ.ค. 2564 เวลา 23:43 Will Bendick ***@***.***>
เขียนว่า:

**Comment by PIVEC96** [comment] 2021-05-22 10:36
I deleted everything and reinstalled it and still the same

**Comment by haroon889** [comment] 2021-05-23 19:34
Same as me sir i did it everything

**Comment by mariano54** [comment] 2021-06-28 08:13
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:13 UTC
Labels: bug
