### ISSUE TITLE
chia Blackchiaen Loading pool plot NFTs[BUG]

### ISSUE THREAD

**Issue by aliaredo** [Chia-Network/chia-blockchain#7136] opened 2021-07-06 14:17 UTC
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mariano54** [comment] 2021-07-06 14:24
can you explain in detail what the issue is?

**Comment by gromran** [comment] 2021-07-06 16:19
there is no "pool" in the official windows release.

**Comment by aliaredo** [comment] 2021-07-06 16:37
chia blockchain 1.1.795 
![chia](https://user-images.githubusercontent.com/49101164/124636725-28b88800-de89-11eb-91de-3be6c4861d33.JPG)

**Comment by gromran** [comment] 2021-07-06 16:59
https://github.com/Chia-Network/chia-blockchain/releases

this is not a official release. So you build by your own (or download somewhere), but are unable to correctly fill out a bug report?

**Comment by aliaredo** [comment] 2021-07-06 18:06
okay i downloaded but where is my Plots ?
![chia_1](https://user-images.githubusercontent.com/49101164/124646964-9cf92880-de95-11eb-9af6-e3417db04faf.JPG)
![chia_2](https://user-images.githubusercontent.com/49101164/124646981-a2ef0980-de95-11eb-925e-3fbca64f12df.JPG)

**Comment by aliaredo** [comment] 2021-07-06 18:07
i have 187 plots

**Comment by mariano54** [comment] 2021-07-07 07:08
@seeden any idea?

**Comment by aliaredo** [comment] 2021-07-07 16:13
any idea ???

**Comment by aliaredo** [comment] 2021-07-07 16:14
i dont see my Plots i have 187 ??

**Comment by mariano352** [comment] 2021-07-07 17:30
I have the same issue

**Comment by seeden** [comment] 2021-07-07 19:47
It is a known issue. It will be fixed after the next release. Meanwhile, we are going to add a refresh plots button for the next release.

**Comment by jivkohd** [comment] 2021-07-07 20:39
![wwwwwwwwwwwwwww](https://user-images.githubusercontent.com/87095342/124825592-84b00900-df7c-11eb-96e0-9bfa92b66815.png)

**Comment by jivkohd** [comment] 2021-07-07 20:41
![ssssssssssssssss](https://user-images.githubusercontent.com/87095342/124825699-aa3d1280-df7c-11eb-9b27-2e96350c8f65.png)
I wait, I wait I wait, I wait and nothing

**Comment by mariano54** [comment] 2021-07-08 04:06
Fixed in 1.2 release

**Closed by mariano54** 2021-07-08 04:06 UTC
Labels: bug

**Comment by mariano352** [comment] 2021-07-08 05:56
I've downloaded the Chia Blockchain 1.2.0 version and it hasn't fixed this bug yet
![Pantalla3](https://user-images.githubusercontent.com/87089629/124869762-0a8d7d80-df98-11eb-9941-de6e079c3bb3.jpg)
![Pantalla2](https://user-images.githubusercontent.com/87089629/124869764-0b261400-df98-11eb-97e3-3e8cf2d17e70.jpg)
![Pantalla1](https://user-images.githubusercontent.com/87089629/124869765-0bbeaa80-df98-11eb-9ec9-f6c10c820935.jpg)
, í'm having the same problem

**Comment by juangoco** [comment] 2021-07-09 14:06
> I've downloaded the Chia Blockchain 1.2.0 version and it hasn't fixed this bug yet
> ![Pantalla3](https://user-images.githubusercontent.com/87089629/124869762-0a8d7d80-df98-11eb-9941-de6e079c3bb3.jpg)
> ![Pantalla2](https://user-images.githubusercontent.com/87089629/124869764-0b261400-df98-11eb-97e3-3e8cf2d17e70.jpg)
> ![Pantalla1](https://user-images.githubusercontent.com/87089629/124869765-0bbeaa80-df98-11eb-9ec9-f6c10c820935.jpg)
> , í'm having the same problem

 its happend to me too when i install the new version and i dont know what to do

**Comment by heshelk2** [comment] 2021-08-20 19:37
im having tehe exact same issue wiht my two machines on ver 1.2.3 running on windows 10 and  win server 16
