### ISSUE TITLE
[Bug] OG Plots causing high harvester latency on version 2.4.1  

### ISSUE THREAD

**Issue by chiaseednetwork** [Chia-Network/chia-blockchain#18261] opened 2024-06-30 16:52 UTC
### What happened?

OG Plots causing high harvester latency on version `2.4.1`  tried upgrading from `2.2.1` to newest version and latency climbed from on average `6 s` to  plus `50 s`  also happens on version `2.3.1` as well.

### Version

2.4.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
Plot details

Total plots: 28903 Total OG: 28903 Total plotNFT: 0
Plot Sizes

K32 28903 100%

Compression
C0 28903 100%
```

**Comment by wjblanke** [comment] 2024-07-03 16:26
Is your parallel_decompressor_count set to 0 in config.yaml? Also what is your plots_refresh_parameter value? You could try regenerating the config to make sure you have defaults.

Also what filesystem is your plots on?
Does limiting the number of plots change the timing issue?

I'd like to create a build for you that has an older version of chiapos if you are OK with trying it. We are trying to see where the regression could have happened.

**Comment by wjblanke** [comment] 2024-07-05 19:39
If you can try building the 241olderchiaposwjb branch and running it, that will let us know if the newer chiapos is causing your slowdowns.

**Comment by wjblanke** [comment] 2024-07-17 16:26
Lets remove gulrak from macos. it's no longer needed anyway and one less dependency to worry about

**Comment by wjblanke** [comment] 2024-09-11 16:20
Closing because of no new information. If you still have issues, reopen and please let us know if the 241olderchiaposwjb regression test improves things for you or keeps things the same. We don't have access to a large farm running under MacOS.

**Closed by wjblanke** 2024-09-11 16:20 UTC
Labels: bug
