### ISSUE TITLE
Chia 1.3.1 MacOS app stuck when opening on "Loading keyring status"[Bug] 

### ISSUE THREAD

**Issue by networkjackbb** [Chia-Network/chia-blockchain#10904] opened 2022-03-26 17:08 UTC
### What happened?

Updated from MacOS GUI 1.2.11  to 1.3.1 and upon launch, the app displays: Loading Keyring Status and does not get any farther..

### Version

1.3.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
none available
```

**Comment by networkjackbb** [comment] 2022-03-26 17:09
MacOS 10.14.6 on Intel MBP13

**Comment by emlowe** [comment] 2022-03-28 15:41
Current the 1.3.x DMG does not work on 10.14 Mojave - you need to install from source. Duplicate of #10687

**Closed by emlowe** 2022-03-28 15:41 UTC
Labels: bug
