### ISSUE TITLE
[BUG] Connecting to Wallet

### ISSUE THREAD

**Issue by cjedwards** [Chia-Network/chia-blockchain#5840] opened 2021-05-23 01:57 UTC
There is little need to re-explain the bugs with sync and connecting.
I will offer some help

#1 have a GUI with a real app with a real language and REST, (electron/react) are kidding me? are you 14?

#1 as above

#1 is a good idea

**Comment by exhau** [comment] 2021-05-23 03:48
it's 2021.

**Comment by lvpcguru** [comment] 2021-05-23 10:08
what bugs as of 1.1.6? Syncing was sped up quite a bit and resolved my wallet sync other than the 30min last night I was connected to (likely an older client) one specific node.

**Comment by cjedwards** [comment] 2021-05-23 15:37
This was a reinstall of windows (new primary boot drive SSD) Same network same machine (otherwise)
I took more than 24 hrs of fails and I gave up and started plotting anyway. 
Dear lord don't hit "reload" or force or you get to have super fun watching the blank screen and a spinner with "0 feedback on WTF it was actually doing". 7 hours later my plots were done I rebooted yet again the app finally started to connect.  

Then it took 4 more hours of slowly creeping up to be able to use my farm. which I did not plot in fear that the system would show me SFA again.
How bad will this be if it actually becomes a success? Should we expect to wait 3-4 days? a week or month?

Yes it is 2021, a good time to learn that you shouldn't use little play tools if you want to be in the big leagues.
The (windows)app is clearly poorly written and the UI is utterly horribad. "Any" competent coder could have written that(better) in a proper lang in a week.  (there is a good reason all these niche languages die in a few years, they are garbage)

And not to mention this entire concept will fall on its face without some kind of bounds from keeping the Chinese mega farms from owning the majority of it all(prob already too late) , so there goes your de-centralized system.

I "might" grow my farm past 100 TB but this sure seems like vapour coin and a giant waste of HDD's

**Comment by samy63** [comment] 2021-05-23 23:46
![image](https://user-images.githubusercontent.com/84105006/119280454-ca657c00-bc31-11eb-9d10-702de04692d2.png)

**Comment by lvpcguru** [comment] 2021-05-25 19:20
> 
> 
> ![image](https://user-images.githubusercontent.com/84105006/119280454-ca657c00-bc31-11eb-9d10-702de04692d2.png)

what? whos issue is this?

**Comment by lvpcguru** [comment] 2021-05-25 19:23
> 
> 
> This was a reinstall of windows (new primary boot drive SSD) Same network same machine (otherwise)
> I took more than 24 hrs of fails and I gave up and started plotting anyway.
> Dear lord don't hit "reload" or force or you get to have super fun watching the blank screen and a spinner with "0 feedback on WTF it was actually doing". 7 hours later my plots were done I rebooted yet again the app finally started to connect.
> 
> Then it took 4 more hours of slowly creeping up to be able to use my farm. which I did not plot in fear that the system would show me SFA again.
> How bad will this be if it actually becomes a success? Should we expect to wait 3-4 days? a week or month?
> 
> Yes it is 2021, a good time to learn that you shouldn't use little play tools if you want to be in the big leagues.
> The (windows)app is clearly poorly written and the UI is utterly horribad. "Any" competent coder could have written that(better) in a proper lang in a week. (there is a good reason all these niche languages die in a few years, they are garbage)
> 
> And not to mention this entire concept will fall on its face without some kind of bounds from keeping the Chinese mega farms from owning the majority of it all(prob already too late) , so there goes your de-centralized system.
> 
> I "might" grow my farm past 100 TB but this sure seems like vapour coin and a giant waste of HDD's

Hey its open sourced so anyone willing can propose replacement GUIs :) 

any progress on your syncing?

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
