### ISSUE TITLE
Transaction still pending after > 12 hours

### ISSUE THREAD

**Issue by PortalMiner** [Chia-Network/chia-blockchain#11116] opened 2022-04-10 14:38 UTC
Transaction will not complete. Error code "INVALID_FEE_TOO_CLOSE_TO_ZERO"
Win10
Chia 1.3.3
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8459217/debug.log)

**Comment by Zero545** [comment] 2022-04-11 16:44
I have the same problem with Chia 1.3.3 on Ubuntu.

**Comment by emlowe** [comment] 2022-04-11 17:41
This is a duplicate of #10873

When you get this particular error (and some other related errors) - your transaction will remain pending. You can sometimes get the transaction to be retried by restarting the wallet.

This error happens when the mempool is full and your transaction does not have a large enough fee to kick another transaction out of the mempool, so the error is expected. However, the wallet should (perodically) retry pending transactions, and this does not appear to be happening correctly in 1.3.x

**Closed by emlowe** 2022-04-11 17:41 UTC
