### ISSUE TITLE
When adding or removing drives or adding plots it wont refresh [BUG]

### ISSUE THREAD

**Issue by coolpro313** [Chia-Network/chia-blockchain#7714] opened 2021-07-21 23:37 UTC
**Describe the bug**
The bug is that whenever i add or remove drives or even add plots the software does not refresh it still shows the same amount of plots that was counted and the same drives nor add them if i'm plotting requiring me either add the drives then close out the wallet and reopen it same for removing drives for either maintenance or transferring the files to a new drive and same when a plot is finished

**To Reproduce**

Try add a drive remove a drive and create a plot can be just 1 file on the drives to reproduce but with my setup i have 30TB worth of plot files

**Expected behavior**
I expect it to automatically update the plots list if i either add and remove drives and add a plot count when i create a plot to a drive that's on the list

**Screenshots**
https://user-images.githubusercontent.com/56607498/126572798-8cc89ac4-5a5e-47d2-b5ac-f7338b1ca91e.mp4

**Desktop**

- OS: Windows
- OS Version/Flavor: Windows 10
- CPU: Intel Core I7 11700K 11 Gen

**Additional context**
In the video I only did the add and removing drives part takes too long to record the create plots part

**Comment by emlowe** [comment] 2021-07-22 03:14
Duplicate of #7262

**Closed by emlowe** 2021-07-22 03:14 UTC
Labels: bug
