### ISSUE TITLE
[BUG] Joining Pool or Pool Change Not Possible in 1.2.10. -- Unable to type any text into the Connect to Pool

### ISSUE THREAD

**Issue by vdx660** [Chia-Network/chia-blockchain#9071] opened 2021-11-01 16:04 UTC
**Describe the bug**
I'm unable to type text into the Connect to Pool text box which results in not being able to join or change pools.

1. Open Chia
2. Click on Pool
3. Find and Pool and click on either Join Pool or Change Pool
4. Click on Connect to Pool
3. Type any text or url

**Expected behavior**
I'm NOT able to type text or url into the Connect to Pool Textbox

**Screenshots**
![image](https://user-images.githubusercontent.com/23503436/139701438-213889f2-d6d7-439f-829f-053831df03e9.png)

**Comment by emlowe** [comment] 2021-11-01 16:18
Yes, known issue, workaround is to use the CLI. Duplicate of #8944

**Closed by emlowe** 2021-11-01 16:18 UTC
Labels: bug
