### ISSUE TITLE
[Bug] No private keys for one or both addresses. Safe only if you are sending rewards to another wallet.

### ISSUE THREAD

**Issue by jackwalk** [Chia-Network/chia-blockchain#10659] opened 2022-03-11 02:02 UTC
### What happened?

![20220311100041](https://user-images.githubusercontent.com/811100/157787792-6a44636b-24e5-45d2-a92f-2b4b1b6304ce.png)

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
...
```

**Comment by jackwalk** [comment] 2022-03-11 02:03
New computer

New installation

**Comment by iJeys** [comment] 2022-03-11 09:58
Same problem
1.2.11 works
1.3.0. no

**Comment by emlowe** [comment] 2022-03-11 21:56
This is a duplicate of #10587

**Closed by emlowe** 2022-03-11 21:56 UTC
Labels: bug
