### ISSUE TITLE
無法同步

### ISSUE THREAD

**Issue by hamson88** [Chia-Network/chia-blockchain#17231] opened 2024-01-06 01:50 UTC
### What happened?

無法同步， 用24註記詞登入新版裡面幣消失
![S__50266123](https://github.com/Chia-Network/chia-blockchain/assets/155788907/1d52dd85-5d68-41bc-a425-d62a699beab9)
![S__50266125](https://github.com/Chia-Network/chia-blockchain/assets/155788907/dea24304-33bf-4f5a-bf6a-ae77cbcc45a0)
![S__50266126](https://github.com/Chia-Network/chia-blockchain/assets/155788907/efc5372c-1a93-4558-933b-c43d40ec8d21)
![S__50266127](https://github.com/Chia-Network/chia-blockchain/assets/155788907/d9542986-13a2-4274-b39e-9366cbec51e1)

### Version

1.1.7

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment] 2024-01-09 17:39
closing as this is a duplicate of #17229

**Closed by BrandtH22** 2024-01-09 17:39 UTC
Labels: bug
