### ISSUE TITLE
[Bug] bladebit ramplot

### ISSUE THREAD

**Issue by prologisticsbeliani** [Chia-Network/chia-blockchain#16425] opened 2023-09-26 04:49 UTC
### What happened?

Trying to plot K-32 compressed 7 on Chia blockchain 2.0.1, nothing happened for more than 1 hour, in the logs I see the config only

### Version

2.0.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Bladebit Chia Plotter
Version      : 3.0.0
Git Commit   : 02a8e68dcf0e971c72fc8377b89cdd081b80b843
Compiled With: msvc 19.29.30151

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 56
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : aeb84bb82fe9d0a229510551a519455eb67e13e19e18de4526f15c008d6af4a650cbc0771e4bdf97d5f012f70aadb873
 Pool contract address : xch16t4fcly842rnp85s43uz7x5qfa63ghv8y3wjulnz4lgsys64ryksv9jm0p
 Compression Level     : 7
 Benchmark mode        : disabled
```

**Comment by BrandtH22** [comment] 2023-09-26 16:46
Closing as this is a duplicate of this support discussion:
https://github.com/Chia-Network/chia-blockchain/discussions/16426

Please use the support discussion for further troubleshooting this issue.

**Closed by BrandtH22** 2023-09-26 16:46 UTC
Labels: bug
