### ISSUE TITLE
[Bug] I'm having trouble claiming rewards.

### ISSUE THREAD

**Issue by catxch** [Chia-Network/chia-blockchain#11173] opened 2022-04-14 11:27 UTC
### What happened?

After i update version 1.3.0 - 1.3.3 every time i press reward The wallet is pending like that and nothing happens. And I can't get the reward.

I deleted everything and reinstalled and completed syncing both the node and the wallet but still not getting any reward.

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-14T17:51:44.023 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '108.184.203.88', 'port': 8444} did not respond in time.
2022-04-14T17:51:44.023 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '108.184.203.88', 'port': 8444} did not respond in time.
2022-04-14T17:51:44.024 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '223.25.82.38', 'port': 8444} did not respond in time.
2022-04-14T17:51:59.361 wallet chia.wallet.wallet_node    : ERROR    Exception while adding state: Was not able to obtain solution None Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 635, in receive_and_validate
  File "chia\wallet\wallet_state_manager.py", line 813, in new_coin_state
  File "chia\wallet\wallet_node.py", line 1375, in fetch_puzzle_solution
ValueError: Was not able to obtain solution None


2022-04-14T18:11:59.764 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x1cd26eba8f37dc5662cc5327c45e81749cba8c02b835473bce433f44ca6f94a4'}
2022-04-14T18:11:59.811 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x1cd26eba8f37dc5662cc5327c45e81749cba8c02b835473bce433f44ca6f94a4'}

2022-04-14T18:20:40.134 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
2022-04-14T18:20:40.135 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
2022-04-14T18:20:40.346 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
2022-04-14T18:20:40.347 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
2022-04-14T18:20:40.426 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
2022-04-14T18:20:40.473 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xb175b25ef7afaefba9b14c01624b66b94d5a81abe48ec7a516bf0b8d700a42c8'}
```

**Comment by catxch** [comment] 2022-04-17 04:21
Can anyone give some advice on how to fix my problem?

**Comment by catxch** [comment] 2022-04-17 04:31
Three days later I still have the same problem.

2022-04-17T11:27:29.350 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x1667021ccf959936f71b883729bfafc70a138c4a5ce8e242bb5a165db99d5a3c'}
2022-04-17T11:27:29.380 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x1667021ccf959936f71b883729bfafc70a138c4a5ce8e242bb5a165db99d5a3c'}

**Comment by chiavivi** [comment] 2022-04-19 08:16
目前好像没有解放方案

**Comment by emlowe** [comment] 2022-04-19 23:38
Please try with version 1.3.4 - we haved fixed several bugs in this area

**Comment by emlowe** [comment] 2022-04-21 17:19
Closing issue as duplicate of #11230 - please refrain from opening the same issue multiple times

**Closed by emlowe** 2022-04-21 17:19 UTC
Labels: bug, Wallet

**Comment by catxch** [comment] 2022-04-22 02:44
As you suggested, let's remove db and resync until I succeed. I've already done it. Remove everything, reinstall chia 1.3.4, but this problem is the same. No matter how much mojo I wear,
![1650593325782](https://user-images.githubusercontent.com/103640664/164583334-e0dfe393-07a7-4388-bfd7-ee396d07aaf6.jpg)
![1650428340900](https://user-images.githubusercontent.com/103640664/164583421-40ac3c19-13a1-4b22-97da-9f7373b20bd3.jpg)
log
 'status': 3,
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}
2022-04-19T11:11:43.674 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}

2022-04-22T01:46:54.580 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}
2022-04-22T01:46:54.713 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}

2022-04-22T09:39:58.817 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}
2022-04-22T09:39:58.822 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}

This is a log error each time I press Confirm, there is a different error, but every time it is completely steady until I press delete the bank.

**Comment by emlowe** [comment] 2022-04-22 19:03
`INVALID_FEE_TOO_CLOSE_TO_ZERO` - this means the mempool is full and your supplied fee is too low to get your transaction into the mempool.
Note, due to a separate bug, after this error the transaction will remain stuck until you manuall remove it with the delete unconfirmed action
You should delete unconfirmed transactions, and then try with a bigger fee, I might suggest 0.005 XCH.

**Comment by catxch** [comment] 2022-04-23 02:55
> `INVALID_FEE_TOO_CLOSE_TO_ZERO` - this means the mempool is full and your supplied fee is too low to get your transaction into the mempool. Note, due to a separate bug, after this error the transaction will remain stuck until you manuall remove it with the delete unconfirmed action You should delete unconfirmed transactions, and then try with a bigger fee, I might suggest 0.005 XCH.

You look at it in figure 1, you see that I put a 0.1 xch fee, it doesn't change anything.
It's probably for other reasons.

**Comment by catxch** [comment] 2022-04-23 03:01
I think there's some kind of business stuck in the system. You can develop gui Can it retrospectively repeal past business?  @emlowe @wallentx

**Comment by catxch** [comment] 2022-04-23 06:05
I tried a new pool and moved the newly created pool several times normally, but for my old pool bag i couldn't claim or move the pool. My current problem is in trouble.
@emlowe @wallentx

**Comment by chiavivi** [comment] 2022-10-11 09:29
确实没有解决问题，我的和你一样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月22日(星期五) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [Bug] I&#39;m having trouble claiming rewards. (Issue #11173)






按照您的建议，让我们删除 db 并重新同步，直到成功为止。我已经做过了。把什么都去掉，重新安装 chi a 1 . 3 . 4 ，但是这个问题还是一样。不管我戴了多少魔法


日志
“状态”： 3，
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}
2022-04-19T11:11:43.674 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
wallet _ node :警告 Spend Bundle 已被 Full Node 拒绝。2022-04-19T11:11:43.674 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}

'ASSERT_ANNOUNCE_CONSUMED_FAILED',
“状态”： 3，

2022 - 04 - 22T01 : 46 :54.580钱包wallet _ node :警告 Spend Bundle 已被 Full Node 拒绝。{' error ':' Double _ Spend ',' status ': 3 ,' tx id ':'0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}
2022 - 04 - 22T01 : 46 :54.713钱包wallet _ node :警告 Spend Bundle 已被 Full Node 拒绝。{' error ':' Double _ Spend ',' status ': 3 ,' tx id ':'0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}
2022-04-22T09:39:58.817 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
wallet _ node :警告 Spend Bundle 已被 Full Node 拒绝。2022-04-22T09:39:58.817 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
'INVALID_FEE_TOO_CLOSE_TO_ZERO',
“状态”： 3，

'txid'： '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}

2022-04-22T09:39:58.822 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
2022-04-22T09:39:58.822 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',警告 Spend Bundle 已被 Full Node 拒绝。2022-04-22T09:39:58.822 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO','INVALID_FEE_TOO_CLOSE_TO_ZERO',“状态”： 3，.
'txid'： '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}这是一个日志错误每次我按下确认，有不同的错误，但每次都是完全稳定的，直到我按删除银行。—直接回复此邮件，在 GitHub 上查看.或

**Comment by nqzhang** [comment] 2022-10-27 07:36
一直到1.6.1都是这个鸟样 没救了
