### ISSUE TITLE
[BUG] Chia plots check Taking ~1 hour on Mac OS when on ExFat Drive

### ISSUE THREAD

**Issue by youngfong13** [Chia-Network/chia-blockchain#7603] opened 2021-07-17 19:51 UTC
I run chia plots check from the CLI when it gets to the part "Starting to test each plot with 30 challenges each" it takes ~1 hour _per_ plot.

To reproduce run chia plots check from CLI on Mac OS on an exFAT drive.

I would expect the plot checking to take much less time per plot. 

Mac OS 11.4
Chia 1.2.2
Python 3.9.6
**USB 3.0 HDD exFAT**

3.1 GHz Dual-Core Intel Core i7
16 GB 1867 MHz DDR3

**Comment by Qwinn1** [comment] 2021-07-17 20:31
It takes quite a bit longer than that per plot.  Maybe 20 seconds or so I guess?  How many plots were you checking during the run that took 15 minutes total?  That would be a lot for 1 plot, but about right for a disk full of them.

**Comment by youngfong13** [comment] 2021-07-17 20:40
> It takes quite a bit longer than that per plot. Maybe 20 seconds or so I guess? How many plots were you checking during the run that took 15 minutes total? That would be a lot for 1 plot, but about right for a disk full of them.

Thanks for the reply. It is taking 15 minutes plus per plot not total. On other machines the plot check takes ~1 second per plot.

**Comment by AndyRPH** [comment] 2021-07-17 23:06
Are they on an exFAT formatted drive?

**Comment by youngfong13** [comment] 2021-07-18 00:07
> Are they on an exFAT formatted drive?

Yeah

**Comment by youngfong13** [comment] 2021-07-18 00:44
I just moved one of the plots to a drive formatted Mac OS Extended (Journaled) and it took about 16 seconds.

**Comment by Qwinn1** [comment] 2021-07-18 01:03
> I just moved one of the plots to a drive formatted Mac OS Extended (Journaled) and it took about 16 seconds.

Out of curiosity, on what OS and file system are you able to do a plot check in 1 second?  Cause it takes 15-20 seconds for me on Ubuntu btrfs.

**Comment by youngfong13** [comment] 2021-07-18 01:18
> > I just moved one of the plots to a drive formatted Mac OS Extended (Journaled) and it took about 16 seconds.
> 
> Out of curiosity, on what OS and file system are you able to do a plot check in 1 second? Cause it takes 15-20 seconds for me on Ubuntu btrfs.

I was reading the timestamps wrong, sorry, on Ubuntu with exFAT it takes 15-20 seconds.

**Comment by youngfong13** [comment] 2021-07-18 01:22
> > I just moved one of the plots to a drive formatted Mac OS Extended (Journaled) and it took about 16 seconds.
> 
> Out of curiosity, on what OS and file system are you able to do a plot check in 1 second? Cause it takes 15-20 seconds for me on Ubuntu btrfs.

Sometimes when I run chia plots check (Ubuntu exFAT) it takes 15-20 seconds. Perhaps it caches the test? Because when I rerun it right after, it takes less than 1 second each.

**Comment by AndyRPH** [comment] 2021-07-18 01:48
There's some kind of problem with chia and exfat and OS X.  A couple open GitHub issues about it.  Not sure if it's fixable by chia, or if it's truly an issue with osx's exfat implementation.   I'd suggest moving away from exfat.

**Comment by emlowe** [comment] 2021-07-18 02:47
Almost certainly related to #7359

**Comment by smiletracer** [comment] 2021-07-18 17:30
...And #4396

**Comment by madrigo64** [comment] 2021-07-19 04:33
I think the problem is with encryption of files

**Comment by hoffmang9** [comment] 2021-07-19 22:05
We have a fix for this coming. It is a problem with exFAT on MacOS that surfaced when we added parallel proof look ups. We will be adding a configuration option to use the non parallel look ups to support exFAT.

**Comment by AndyRPH** [comment] 2021-07-19 22:22
Will this present a performance hit that exfat in general should be a non-preferred file system for Apple users?

**Comment by hoffmang9** [comment] 2021-07-19 23:31
Setting this option will just take you back to the e.g. 1.1.7 MacOS proof lookup speed on exFAT - which was fine.

**Comment by emlowe** [comment] 2021-07-21 18:28
Anyone with the issue can pull main and set parallel_read to False in config.yaml for their harvesters - this will use the sequential option that was in 1.1.7.

**Comment by Handri-Kosada** [comment] 2021-07-24 11:28
> Anyone with the issue can pull main and set parallel_read to False in config.yaml for their harvesters - this will use the sequential option that was in 1.1.7.

Tried this. 

But my pi4 still slow on harvesting the plots. 
is pi4 not capable anymore as harvester?

Never have this problem before 1.2.x

**Comment by emlowe** [comment] 2021-07-27 01:46
Release 1.2.3 has introduced the parallel_read option in config.yaml to solve this issue. If you upgrade, you will need to manually add the setting under harvester. 
```
harvester:
  parallel_read: False
```

**Closed by emlowe** 2021-07-27 01:46 UTC
Labels: bug
