### ISSUE TITLE
[BUG] installation fails on pre-release version of Ubuntu due to Python 3.9

### ISSUE THREAD

**Issue by lvcivs** [Chia-Network/chia-blockchain#1840] opened 2021-04-13 07:29 UTC
The pre-release version of Ubuntu (21.04) ships with Python 3.9.

This causes an issue with the install.sh script, which fails when trying to install `python3.8-venv` on line 44 of the script. If you change that to `python3.9-venv` it works fine.

This is obviously easy enough to work around. Just wanted to give a heads up as this new Ubuntu release will be out in ca. 10 days and at that point a lot of people are going to upgrade and potentially run into this issue.

**Comment by hoffmang9** [comment] 2021-04-13 07:31
Oh yeah... It's April...

Thanks!

**Comment by jjhesk** [comment] 2021-04-14 01:48
also we have installed 3.6.5

**Comment by lvcivs** [comment] 2021-04-14 11:32
> also we have installed 3.6.5

Chia requires Python 3.7+, check the Readme.

**Comment by kocoten1992** [comment] 2021-04-20 20:28
friendly ping, it is out in less than 48h.

**Comment by xxxcrow** [comment] 2021-04-22 22:32
#2412 #8d7a667d7e01e67ac02967ef6321c2bccb6a6794

**Comment by xxxcrow** [comment] 2021-04-22 22:33
#2412 #8d7a667

**Comment by xxxcrow** [comment] 2021-04-22 22:34
Duplicate of #2412

**Comment by sargonas** [comment] 2021-04-28 18:11
In the interest of helping out with some house keeping of the Issue backlog, I suggest someone close this out as it was fixed with PR https://github.com/Chia-Network/chia-blockchain/pull/2418 when support for 21.04 was added.

**Closed** 2021-04-29 03:40 UTC
Labels: bug
