### ISSUE TITLE
NO Connecting to the wallet and white screen [BUG]

### ISSUE THREAD

**Issue by SHEKHAR007E** [Chia-Network/chia-blockchain#6845] opened 2021-06-18 08:24 UTC
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mariano54** [comment] 2021-06-28 07:54
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:54 UTC
Labels: bug
