### ISSUE TITLE
Part of the NFT disappeared, they are on version 1.6.2[Bug] 

### ISSUE THREAD

**Issue by DmitryYamen** [Chia-Network/chia-blockchain#14644] opened 2023-02-22 12:57 UTC
### What happened?

After the update, part of the NFT disappeared, they are on version 1.6.2

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by djerfy** [comment] 2023-02-22 22:47
@DmitryYamen, you can try this in GUI?
1. Go to "Settings" and "NFT"
2. Disable "Hide objectionable content"

**Comment by MumfMeisterT** [comment] 2023-02-23 20:50
Duplicate of #1493. Linking and closing current ticket.

**Closed by MumfMeisterT** 2023-02-23 20:50 UTC
Labels: bug, Investigate - Support, GUI, Windows, NFT, 1.7.0
