### ISSUE TITLE
Wallet Won't Connect After Update (Error Text Below)

### ISSUE THREAD

**Issue by HaveSomeBugs** [Chia-Network/chia-blockchain#6076] opened 2021-05-26 20:08 UTC
OS: Ubuntu

File "/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/chia-blockchain/chia/server/start_wallet.py", line 92, in main
    return run_service(**kwargs)
  File "/chia-blockchain/chia/server/start_service.py", line 226, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/chia-blockchain/chia/server/start_service.py", line 220, in async_run_service
    return await service.run()
  File "/chia/server/start_service.py", line 160, in run
    await self.start()
  File "/chia-blockchain/chia/server/start_service.py", line 128, in start
    await self._node._start(**kwargs)
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 153, in _start
    self.wallet_state_manager = await WalletStateManager.create(
  File "/chia-blockchain/chia/wallet/wallet_state_manager.py", line 138, in create
    self.blockchain = await WalletBlockchain.create(
  File "/chia-blockchain/chia/wallet/wallet_blockchain.py", line 112, in create
    await self._load_chain_from_store()
  File "/chia-blockchain/chia/wallet/wallet_blockchain.py", line 123, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_heights_dicts()
  File "/chia-blockchain/chia/wallet/wallet_block_store.py", line 283, in get_peak_heights_dicts
    curr_height = hash_to_height[curr_header_hash]
KeyError: b'\x8e\x83-\x0f\xb1\xf5\x07C]\xc5\x05\xee\x02\x97\xe3kO\x9b\xe3vZR:Fv\\\x01\xc6\xe6\xc6\xfd\xdf'

**Comment by nodaone** [comment] 2021-05-26 21:49
Same here for W10 & V1.16:

Error message after trying to start wallet (node = synced):

PS C:\Users\(...)\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 220, in async_run_service
  File "chia\server\start_service.py", line 160, in run
  File "chia\server\start_service.py", line 128, in start
  File "chia\wallet\wallet_node.py", line 154, in _start
  File "chia\wallet\wallet_state_manager.py", line 145, in create
  File "chia\wallet\wallet_blockchain.py", line 112, in create
  File "chia\wallet\wallet_blockchain.py", line 123, in _load_chain_from_store
  File "chia\wallet\wallet_block_store.py", line 283, in get_peak_heights_dicts
KeyError: b'(KEY)'
[8140] Failed to execute script start_wallet

**Comment by nodaone** [comment] 2021-05-26 21:52
My steps into trying to solve the problem [here](https://github.com/Chia-Network/chia-blockchain/discussions/6049).

**Comment by D34dly1** [comment] 2021-05-27 00:35
I finally managed to solve my wallet not syncing.  I'm running Win 10 I have update 1.16.  I searched different posts about people having syncing issues.  I tried everything from allowing everything Chia through my firewall.  Then I did port forwarding on my router for 8444 and then I even did 8449 not sure if it was needed but I kept getting errors with port 8449 so I did it anyways.  Then I even set my IP as a Static IP hoping that would fix it.  I even set my firewall to allow the Chia app. But ultimately I think what I did that managed to fix my syncing issue was shut down my Chia GUI.  Then opened the task manager and ended any tasks related to Chia.  Then went into the .Chia folder and navigated to the wallet folder and deleted everything in the DB folder.  Started the Chia GUI back up and then it started syncing and by the end of time I got off work my wallet was fully synced.  I get zero errors on my debug log.  The GUI is finally working 100%.  I hope this helps.

**Comment by nodaone** [comment] 2021-05-27 16:15
> I finally managed to solve my wallet not syncing. I'm running Win 10 I have update 1.16. I searched different posts about people having syncing issues. I tried everything from allowing everything Chia through my firewall. Then I did port forwarding on my router for 8444 and then I even did 8449 not sure if it was needed but I kept getting errors with port 8449 so I did it anyways. Then I even set my IP as a Static IP hoping that would fix it. I even set my firewall to allow the Chia app. But ultimately I think what I did manage to fix my syncing issue was shuting down my Chia GUI. Then opened the task manager and ended any tasks related to Chia. Then went into the .Chia folder and navigated to the wallet folder and deleted everything in the DB folder. Started the Chia GUI back up and then it started syncing and by the time I got off work my wallet was fully synced. Also before deleting the contents of the DB folder I had two wallets, after deleting all the files I only have 1 wallet. So i think maybe having the two wallets was causing the main wallet to no sync. I get zero errors on my debug log. The GUI is finally working 100%. I hope this helps. 

Hi D34dly1, thanks for your reply and sharing! I have tried the same things, but no luck.
I keep getting this error: 

PS C:\Users\(...)\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> .\chia start wallet chia_wallet: Already running, use `-r` to restart
chia_full_node: Already running, use `-r` to restart
PS C:\Users\(...)\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> .\chia wallet show
Connection error. Check if wallet is running at 9256
PS C:\Users\(...)\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon>

So I am kind of out of options..

**Comment by nodaone** [comment] 2021-05-28 22:06
A solution that worked for me after trying sooo many things:

In this folder "C:\Users(...).chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
then I started the GUI..
This worked for me, I hope it solves your problems as well. Good luck

**Comment by jmoe28** [comment] 2021-06-01 15:40
> 
> 
> A **solution** that worked for me after trying sooo many things:
> 
>     1. In this folder "C:\Users(...).chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
> 
>     2. Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
> 
>     3. then I started the GUI..
>        This worked for me, I hope it solves your problems as well. Good luck

Thanks GUI started afterwards

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
