### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eNaimi-dt3cc** [Chia-Network/chia-blockchain#11679] opened 2022-05-27 21:21 UTC
### What happened?

Before Chia version 1.3, every Chia pool I connected to, All plots were calculated,
And for that, I received chia currency,
But after version 1.3, Whatever pool I connect to, Only a quarter of the plots in the pools count,
And the daily and monthly income is a quarter, For example, before for 500 plots,
I received about 0.3 chia a month, But now for 500 plots, I get about 0.08 chia,
And I checked this amount for a few pools

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment] 2022-05-27 22:58
closing as duplicate of #11677

**Closed by emlowe** 2022-05-27 22:58 UTC
Labels: bug
