### ISSUE TITLE
[Bug] stop getting rewards if run db upgrade before wallet db has been upgraded

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10439] opened 2022-02-25 20:05 UTC
### What happened?

Scenario: Have a fully working 1.2.11 farmer that is pooling with no issues, and are ready to git checkout 1.3.0 when it releases. You read the release notes and are really interested in the db upgrade, because you have a small root volume on your farmer, and you could really use the extra space. You've decided the first thing you are gonna do after checking out the release tag, and re-running sh install.sh, is to run chia db upgrade, let that run, and when it finishes, delete your old v1 db so that you can enjoy your additional free ~30gb of space.

Syncing the wallet DB also updates the wallet info in config.yaml as it syncs. like if you have a brand new setup and are syncing from 0, and you don't touch your config.yaml, as you sync you wallet db, your config.yaml will be updated with the pooling info, since plotNFTs are on-chain.

From a functioning 1.2.11, if the first action performed when moving from 1.2.11 to 1.3 is chia db upgrade, this will update the paths to the db in the config.yaml to point to the v2 db, instead of the v1. I'm not sure if it attempts to update other details or not.. Bill had mentioned that 1.2.11 and 1.3 have config.yaml values that are not compatible with each other. - keep this in mind.
If you then do chia start farmer to get things back up and running, the first thing that will automatically happen is that the chia wallet db will automatically upgrade from v1 to v2. I think that this too updates the config.yaml with the proper file paths to the v2 wallet dbs.
When the wallet db update is complete, the user might have to sync a few blocks to get back up to date, since they had to stop it all during the update to 1.3, and the db upgrade.
The user sees that everything gets synced, and all looks well in the logs, so they let things sit as normal.

Then a few days later, they see that they have not been getting any rewards. No errors in the logs. All looks normal. What is wrong? There have been the regular checks for eligible plots.. but after closer inspection, have not found a single proof since the upgrade. They haven't been finding any proofs, because locally, at least, their Farmer has been SELF-POOLING. chia wallet show shows this data. chia plotnft show returns nothing, and hasn't since the upgrade. You check with your pool admin, but they say you haven't left the pool. The pool still has their singleton showing. They check their config.yaml and there is no pool url, and the Payout instructions (pool will pay to this address): is pointing to some address other than the one they had previously set. Correction to the config.yaml is attempted, but nothing is working.
You blow away your wallet DB, and let it re-sync. Fortunately, the new 1.3 wallet syncs much faster. When it gets done syncing, you see that you are now sending partials back to your pool. Your chia plotnft show command still spits out 0 info, and your chia wallet show command doesn't seem to be showing what it should.

Theory: Running a chia db upgrade prior to having the 1.3 wallet db auto upgraded to v2, and fully synced (and thus, the config.yaml being updated to compatible 1.3 spec) makes the chia db upgrade command zero out some incompatible info in config.yaml, that somehow leaves it in a state where the following wallet upgrade and sync are unable to write out what it needs into the config.yaml, or be aware that it should. 

It is possible that when running a chia db upgrade before letting the wallet auto-upgrade, that the chia db upgrade command changes the db paths for both the blockchain db, AND the wallet db to point to their v2 location. Thus, when the first run happens, the chia wallet is not aware that the wallet db needs to be UPGRADED to a v2 wallet, and instead performs a sync from 0 on the wallet db.

### Version

1.2.12 dev355

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by esaung** [comment] 2022-02-25 20:06
from @wallentx

**Comment by wallentx** [comment] 2022-02-25 22:47
I will be attempting to replicate this over the weekend. Will report back with any findings.

**Comment by arvidn** [comment] 2022-02-25 23:09
the `chia db upgrade` command will (by default) update the `config.yaml` to make the full node's `database_path` point to the newly converted v2 database file. It does this after the conversion completes.

However, the potential race condition with some other service also updating the config has quite a small window. Here's the code where it's done. https://github.com/Chia-Network/chia-blockchain/blob/main/chia/cmds/db_upgrade_func.py#L51

```
        config = load_config(root_path, "config.yaml")
        new_db_path = db_pattern.replace("_v1_", "_v2_")
        config["full_node"]["database_path"] = new_db_path
        print(f"database_path: {new_db_path}")
        save_config(root_path, "config.yaml", config)
```

There's no `await`, so anyone having their updates to the configs be clobbered would have to be a separate process (which the wallet is, in fact, all other services would be, since `chia db upgrade` starts a new process).

It seems unlikely that we would hit this race condition, but rare events still happen sometimes. I think there's likely some other issue, that's more likely to happen, that's behind this issue. Perhaps the wallet not being synced is a problem in itself.

However, the next step in eliminating config file races would probably be to implement file locking.

**Comment by wallentx** [comment] 2022-02-28 20:27
I think I discovered yesterday what may have happened. There was a bug that I believe may have been resolved, that was relating to zombie processes with the wallet. That, in combination with some other bugs (or odd behaviors) I think were the culprit to the origin of this particular GH issue, which I have not yet been able to reproduce entirely.

Regarding the output of `chia wallet show` and the accuracy of the details surrounding `plotnft` and pooling config:
If `synced` is representative of having the wallet data downloaded up to the most recent `wallet height`, then the state of the wallet being synced is accurate. But if there are subprocesses or something that are having to work though all that data do to "stuff" before accurate info can be presented within the `chia wallet show` command, then the readiness and usability of the wallet is _not_ actually true. I propose that `synced` should not be shown until all aspects of the output of `chia wallet show` are expected to be accurate.

**Comment by wallentx** [comment] 2022-03-01 08:25
I think the culprit may have been related to something invoking the `restore db from backup? S to start from scratch` prompt in the background, and never acknowledging it. https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/settings/default_settings.py

As I've been unable to replicate the subject described in the steps of this issue, I feel good about closing this.

**Comment by wallentx** [comment] 2022-03-02 05:07
@altendky experienced this exact issue in the wild.

**Comment by esaung** [comment] 2022-03-02 06:22
from @altendky:
1) we are writing to the config about every second for any setup with a plot nft (i think) and 2) somehow i lost my pool url in the config file.  2) is possibly related to https://github.com/Chia-Network/chia-blockchain/issues/10439.  i did just do my db upgrade to v2 'recently'.

**Comment by mariano54** [comment] 2022-03-03 20:52
This should now be fixed since we now only write once to the config.

**Closed by mariano54** 2022-03-03 20:52 UTC
Labels: bug
