### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'src.cmds.init_funcs'

### ISSUE THREAD

**Issue by volkanpaksoy** [Chia-Network/chia-blockchain#1611] opened 2021-03-31 03:49 UTC
**Describe the bug**
Getting this error while installing on Ubuntu Server 20.04.2 LTS (Upgraded from 18.04)

**To Reproduce**

1. Follow the installation steps as shown in the wiki (https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian):

```
sudo apt-get update
sudo apt-get upgrade -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest
cd chia-blockchain

sh install.sh

. ./activate

sh install-gui.sh
```
2. Run 

```
chia keys generate
```

3. Get this error with full stack trace:

```
Traceback (most recent call last):
  File "/home/user/chia/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/user/chia/chia-blockchain/src/cmds/chia.py", line 76, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/chia/chia-blockchain/src/cmds/keys.py", line 18, in generate_cmd
    from .init_funcs import check_keys
ModuleNotFoundError: No module named 'src.cmds.init_funcs'
```

**Expected behavior**
Successful key generation

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu Server 20.04.2
- CPU: Intel Core i7

**Additional context**
I upgraded to 20.04 from 18.04 by running do-release-upgrade command

**Comment by hoffmang9** [comment] 2021-03-31 03:53
Known bug. Dupe of already reported issue.

**Closed by hoffmang9** 2021-03-31 03:53 UTC
Labels: bug

**Comment by volkanpaksoy** [comment] 2021-03-31 03:56
I did search "init_funcs" in all issues before posting. It didn't return any results that's why I posted it.

Is there any ETA on when it's going to be fixed?

**Comment by hoffmang9** [comment] 2021-03-31 04:10
Tomorrow
