### ISSUE TITLE
wallet not synced

### ISSUE THREAD

**Issue by nuistzj2014** [Chia-Network/chia-blockchain#6031] opened 2021-05-26 01:05 UTC
Wallet height: 149504
Sync status: Not synced

why stopped at 149504?

**Comment by TheVino** [comment] 2021-05-26 01:24
What version are you running?
1.1.6 solved a lot with synch issues from my point of view.

Try this: https://www.reddit.com/r/chia/comments/n5d77c/little_fix_for_the_non_syncing_users/
Helped me a lot.

**Comment by room101-dev** [comment] 2021-05-26 03:45
Wallet syncs if you use the cmd-line tools, I just did it yesterday 'for' fun, not that matters, its better to use explorer if you want to know a balance.
There is no utility in the blockchain, as the 'chia farm summary' doesn't work, it returns all zeros, the DEV has blown this issue off for months.
You can't do anything with the GUI, its 99% broken crap.
If you start from scratch expect 2-3 days to download the blockchain, then start the wallet, which will take another day, they'll both sync

cmd line is 

chia show -s // for blockchain sync status
chia wallet show // for wallet status

first start with 'chia start node', then 'chia start wallet', there is no point in 'chia start farmer' as nothing works, unless you start from scratch and build 'plots', the system will not let get farmer stat's, which means your count is always zero, the 'chia plots show' will show your paths, all these components are different, written by different people, and some broken, and some more broke.

**Comment by nuistzj2014** [comment] 2021-05-26 08:28
Thanks a lot !
I update the chia, restart the wallet node, then it works.

**Comment by nodaone** [comment] 2021-05-28 22:08
A **solution** that worked for me after trying sooo many things:

1. In this folder "C:\Users(...).chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
2. Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
3. then I started the GUI..
This worked for me, I hope it solves your problems as well. Good luck

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
