### ISSUE TITLE
[Bug] chia show -r cannot disconnect full node

### ISSUE THREAD

**Issue by andrew2hart** [Chia-Network/chia-blockchain#9682] opened 2021-12-28 07:40 UTC
### What happened?

There is a full node connected to mine that will not disconnect.  Nothing is logged but see the command output instead

### Version

1.2.11

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) chia@pi8:~/chia-blockchain$ chia show -c
Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
WALLET    127.0.0.1                              Dec 28 07:23:06    854.2|4.2    
FARMER    127.0.0.1                              Dec 07 13:00:13     47.4|0.0    
FULL_NODE 88.97.46.151                            8444/8444  738f078d... Nov 25 09:57:09      0.0|0.0    
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 93.51.123.86                            8444/8444  05fcbe67... Dec 28 07:24:25    188.9|1743.7 
                                                 -SB Height:  1341304    -Hash: 4c2313bc...
(venv) chia@pi8:~/chia-blockchain$ chia show -r 738f078d
Attempting to disconnect NodeID 738f078d
NodeID 738f078d... FULL_NODE 
(venv) chia@pi8:~/chia-blockchain$ chia show -c
Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
WALLET    127.0.0.1                              Dec 28 07:24:46    854.2|4.2    
FARMER    127.0.0.1                              Dec 07 13:00:13     47.4|0.0    
FULL_NODE 88.97.46.151                            8444/8444  738f078d... Nov 25 09:57:09      0.0|0.0    
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 93.51.123.86                            8444/8444  05fcbe67... Dec 28 07:25:08    188.9|1743.7 
                                                 -SB Height:  1341306    -Hash: 9c38677f...
```

**Comment by emlowe** [comment] 2022-01-03 23:47
Likely a duplicate of #9172

**Closed by emlowe** 2022-01-03 23:47 UTC
Labels: bug
