### ISSUE TITLE
Chia doesn't work on ubuntu 22.04 jammy jellyfish

### ISSUE THREAD

**Issue by mooky31** [Chia-Network/chia-blockchain#11113] opened 2022-04-09 09:02 UTC
Hello,

I just upgraded my ubuntu from 20.04 to 22.04.
Chia doesn't want to start any more : this version uses python 3.10, whereas chia wants python <= 3.9.9

Could you please make it usable on the new ubuntu LTS ?

Thank you

**Comment by jlobue10** [comment] 2022-04-09 14:32
So let's clarify something here, Chia does in fact work with Ubuntu 22.04, just not with the default provided Python 3.10 (at least for now), so there are some extra steps required to get it to work and install from source on Ubuntu 22.04. I'll do my best to walk you through what worked for me (I'm running Kubuntu 22.04 on my main farmer and a separate harvester).

First, you will need to download the Gzipped source tarball of Python 3.9.12 from here https://www.python.org/downloads/release/python-3912/ .

Go to the directory where the downloaded tarball exists and type `tar xzvf Python-3.9.12.tgz` in the command line. This will extract the tarball. Now go into the extracted directory.

Run these commands in order, one by one.

`sudo apt-get update`
`sudo apt-get install openssl python3-distutils build-essential libncurses*-dev liblzma-dev libgdbm-dev libsqlite3-dev libbz2-dev tk-dev libreadline-dev`
`./configure --enable-loadable-sqlite-extensions --enable-optimizations`
`make`
`sudo make altinstall`

This should have compiled and installed Python3.9 as an alternate to Python 3.10 for the system. You can confirm whether it worked or not by running `python3.9 --version` from the command line. You should see a response of `Python 3.9.12` if it worked correctly.

Now go into the chia-blockchain directory where you're trying to install from. If there's currently a venv folder, I'd suggest deleting it with `rm -rf venv/` from the command line. Now recreate the venv folder using this command (still from the chia-blockchain folder) `python3.9 -m venv venv` . This will force python3.9 for the created virtual environment.

Now make a few edits to the install.sh file that's in the chia-blockchain folder. Make line 128 look like this.
`#sudo apt-get install -y python3.9-venv python3-distutils openssl`
Adding the # comments out the line, if you're unaware. The installer will fail and quit after trying to install the nonexistent python3.9-venv for Ubuntu 22.04, so we'll comment the line out to skip that step.

On lines 274, 275, 278, and 279 change `python` to `python3.9` (forcing python3.9 to be used) and then run sh install.sh and the installer should finish successfully. Follow the rest of the instructions for the Github Readme for the GUI installer (if desired). As an alternative, you can always just download the deb package and install with `sudo dpkg -i chia-blockchain_1.3.3_amd64.deb` .

**Comment by mooky31** [comment] 2022-04-10 09:15
Thank you for the solution. Indeed it works, but that's complicated and by the way I was not comfortable using an OS in a development version. By the way I solved the problem for myself by downgrading back to 20.04.

I think it would be a good idea to make it work more easily, without having to install a second version of python from source, and modify chia sources by hand.
Are there any plans to make chia support ubuntu 22.04 "out of the box", ie. correct the standard install.sh and use python 3.10 ?

**Comment by jlobue10** [comment] 2022-04-10 15:08
Well I'm not a Chia dev, and I'm not familiar with the complexities of why Python 3.9 is required and why Python 3.10 currently doesn't work. Ubuntu 22.04 is also still in beta for roughly two more weeks, so I would not realistically expect support for it until it's no longer a beta. I'm sure they can edit the install.sh file however is necessary to either perform similar steps that I outlined above or for some other solution that they determine to work with Ubuntu 22.04 out of the box.

Also, the first version of beta Ubuntu 22.04 did have Python 3.9 support before it was removed. It's possible that Python 3.9 support will be recompiled and added back to the official Ubuntu 22.04 LTS before the official release, but I'm not sure that will happen. Either way, someone can easily get chia to work from source by following the steps that I outlined (it's not really that difficult) and copying / pasting the commands into the terminal. Until Ubuntu 22.04 is officially out (no longer a beta), I don't think it's fair to expect official Chia support. Those are my two cents.

**Comment by emlowe** [comment] 2022-04-11 19:25
Marking as a duplicate of #8807, we are working on 3.10 support

**Closed by emlowe** 2022-04-11 19:25 UTC

**Comment by Gnomuz** [comment] 2022-04-20 22:13
Thanks for the comprehensive how-to by jlobue10. I experimented on a brand new Ubuntu 22.04 install and finally got it to work. I had to install `libssl-dev` and `libffi-dev` to make it work, if that can help others.

**Comment by jlobue10** [comment] 2022-04-21 00:44
Thanks for the feedback Gnomuz. I edited my guide to add the two dependencies that you mentioned. I must have already had them installed for other software packages on my system. I have the newest Chia 1.3.4 working on three different Kubuntu 22.04 systems at home, so I'm confident that my steps work consistently, and are repeatable by almost anyone. I'm waiting to see how quickly 1.3.5 is released by the Chia devs. If there is a bit of a delay (take the time and do it right, don't skimp on testing please), then I have a feeling that the Github page and/ or the Chia subreddit will get inundated with similar posts and comments. It's really not that difficult to compile and install Python 3.9.x from source in the meantime and force 3.9 to be used for the Chia virtual environment and installation process. We will see. Ubuntu 22.04 (and all its flavors) is officially out of beta tomorrow April 21, 2022, so we will see just how many 'Chia is broken on Ubuntu 22.04' posts/ comments there will be. If 1.3.5 is a ways out in time, I may retype this temporary fix as a post on the Chia subreddit (if someone else doesn't beat me to it).

**Comment by Gnomuz** [comment] 2022-04-21 09:20
Also running smoothly here, chia 1.3.4 on Ubuntu server 22.04 (headless server). And I agree it's not such a complicated task to follow your detailed steps to get it to run on 22.04.
The only drawback I see is that when install.sh is edited in `chia-blockchain` directory, the `chia version` command returns `1.3.5.dev0` instead of `1.3.4`. That is purely cosmetic ofc, but now that the chia version is reported in the user-agent to pool servers by the farmer process when submitting partial proofs, it may raise issues.
I know my own pool displays the current version on the web dashboard, and currently doesn't interpret 1.X.Y.dev0 as 1.X.(Y-1), and displays `<1.3.0` instead.
Would you by chance have any idea how we could build and get the correct version number in the end ?
Thanks in advance.

**Comment by Gnomuz** [comment] 2022-04-21 09:38
I answer my own question, as I found a workaround for the version : I left `install.sh` untouched in the `chia-blockchain` directory, copied and edited it somewhere else, and launched the amended version from within `chia-blockchain` directory. Now `chia version` is happily reporting `1.3.4` as expected !
