### ISSUE TITLE
"Connecting to wallet" endless [BUG]

### ISSUE THREAD

**Issue by korolevsv** [Chia-Network/chia-blockchain#6819] opened 2021-06-17 01:13 UTC
**Describe the bug**
After exiting the GUI and starting it again, there is a "Connecting to wallet" mesage and a spinning circle.
Occured several times on 2 different PCs.

**To Reproduce**
The last time it in such a way: 
1. Create a plot
2. Exit GUI
3. Copy db folder from another (synchronized) PC to make this one synchronized, too (but sometimes it occured without this step).
4. Run GUI
5. "Connecting to wallet" endless

**Expected behavior**
GUI connectes to wallet, sidebar appears.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
![Connecting](https://user-images.githubusercontent.com/8134234/122315224-519ccb80-cf22-11eb-8c4e-6f43f2601e6c.png)

- OS Version/Flavor: 10.0.1763
- CPU: Intel Core i7-6700

**Additional context**

**Comment by korolevsv** [comment] 2021-06-17 01:19
GUI 1.1.7

**Comment by housemafiadl** [comment] 2021-06-17 05:08
I have the same problem plis help. I just restart the computer, but when i try to conect to chia, it didnt work. What should i do?

**Comment by korolevsv** [comment] 2021-06-17 10:40
After 10 hours have connected, asked for a key and have got Synced status

**Comment by keybil7091** [comment] 2021-06-17 12:57
Does the chia program have to stay open for 10 hours?not connecting to wallet

**Comment by bluerdge** [comment] 2021-06-17 15:26
Same problem here!! HELP!!

**Comment by Pitark1241** [comment] 2021-06-17 15:54
Wanted to start chia on a freshly installed computer got the same issue. I havent created a wallet yet and it still stuck on "connecting to wallet"

**Comment by bingoldsby** [comment] 2021-06-17 16:19
This appears to be due to a corrupt database. I fixed mine by navigating to my users/username/.chia/mainnet/wallet and deleting the db directory, and /users/username/.chia/mainnet/db and deleting the blockchain files. After restarting the directory/files are  recreated and chia started back up.

**Comment by Paco-mac** [comment] 2021-06-17 17:17
> Esto parece deberse a una base de datos corrupta. Arreglé el mío navegando a mis usuarios / username / .chia / mainnet / wallet y eliminando el directorio db, y /users/username/.chia/mainnet/db y eliminando los archivos de blockchain. Después de reiniciar, el directorio / los archivos se vuelven a crear y chia inicia una copia de seguridad.

No me funciono.

**Comment by bluerdge** [comment] 2021-06-17 17:36
> This appears to be due to a corrupt database. I fixed mine by navigating to my users/username/.chia/mainnet/wallet and deleting the db directory, and /users/username/.chia/mainnet/db and deleting the blockchain files. After restarting the directory/files are recreated and chia started back up.

THIS WORKED FOR ME!!   Thank U!

**Comment by korolevsv** [comment] 2021-06-17 17:55
> 
> 
> This appears to be due to a corrupt database. I fixed mine by navigating to my users/username/.chia/mainnet/wallet and deleting the db directory, and /users/username/.chia/mainnet/db and deleting the blockchain files. After restarting the directory/files are recreated and chia started back up.

Actually I tried to UPDATE the database - took VALID database from another computer.
If you delete db - it starts syncing from scratch and it takes 2-3 days for me.


> 
> 
> Does the chia program have to stay open for 10 hours?not connecting to wallet

I had been waiting for 2 hours before went to sleep and there was "Connecting to wallet" message.
In the morning it was OK with Synced status.

**Comment by korolevsv** [comment] 2021-06-17 17:58
> 
> 
> After 10 hours have connected, asked for a key and have got Synced status

After system reboot have got this "Connecting to wallet" message again :-(.

**Comment by Paco-mac** [comment] 2021-06-18 08:57
Me funciono:
Desinstale el chia clockchain, elimine las carpetas en user/.chia y en C:\Users\ ussuario\AppData\Local\chia-blockchain.
Reinicio.
Instalar de nuevo y conecto.

**Comment by automation13** [comment] 2021-06-18 18:35
> This appears to be due to a corrupt database. I fixed mine by navigating to my users/username/.chia/mainnet/wallet and deleting the db directory, and /users/username/.chia/mainnet/db and deleting the blockchain files. After restarting the directory/files are recreated and chia started back up.

it takes 3 days to sync blockchain DB and wallet DB. How to check if my DB corrupted?

**Comment by automation13** [comment] 2021-06-18 18:39
> > This appears to be due to a corrupt database. I fixed mine by navigating to my users/username/.chia/mainnet/wallet and deleting the db directory, and /users/username/.chia/mainnet/db and deleting the blockchain files. After restarting the directory/files are recreated and chia started back up.
> 
> Actually I tried to UPDATE the database - took VALID database from another computer.
> If you delete db - it starts syncing from scratch and it takes 2-3 days for me.
> 
> > Does the chia program have to stay open for 10 hours?not connecting to wallet
> 
> I had been waiting for 2 hours before went to sleep and there was "Connecting to wallet" message.
> In the morning it was OK with Synced status.

How to check my DB? I feel like mine is corrupted/not valid

**Comment by korolevsv** [comment] 2021-06-20 22:23
> 
> 
> > After 10 hours have connected, asked for a key and have got Synced status
> 
> After system reboot have got this "Connecting to wallet" message again :-(.
> This time only for 10 minutes.

Today again:
After system reboot got
![Closing down](https://user-images.githubusercontent.com/8134234/122689993-4b169880-d22f-11eb-8c3e-c4a1c1ffbace.png)
 "Connecting to wallet".
Had been waited 30 min, tried to Exit.
Got "Closing down node and server" message ENDLESS AGAIN :-(.
I could understand there could be a problem to connect to the wallet because of corrupted database (thoug why it was corrupted???) BUT WHAT THE PROBLEM TO CLOSE ALL TASKS ANd EXIT ???????

**Comment by korolevsv** [comment] 2021-06-20 22:32
Does anybody from Chia read this Github???
Have you open a ticket for this bug?
Could you advice something accept deleting the database and starting syncing again (this process took 4 days :-((( )?

**Comment by john2barnard** [comment] 2021-06-20 22:37
These issues resolved for me when I updated to version 1.1.7

**Comment by 85256638** [comment] 2021-06-22 23:37
Devs wake up, many people are having this issue!

**Comment by mariano54** [comment] 2021-06-28 07:54
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:54 UTC
Labels: bug
