### ISSUE TITLE
[Bug] 1.7 rc7: Offer Files broken, cannot upload to Dexie/Offerbin

### ISSUE THREAD

**Issue by joshpainter** [Chia-Network/chia-blockchain#14527] opened 2023-02-09 00:12 UTC
### What happened?

1. Create any offer file.
2. Try to upload to Dexie or Offerbin.
3. Both result in "invalid offer" error.

Attempting to manually upload results in same error from Dexie.

Accepting other offers still seems to work fine.

Workaround: downgrade to 1.7 rc6.

### Version

1.7 rc7

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by denisu** [comment] 2023-02-11 20:46
The cause is an updated offer puzzle. dexie accepts `1.7.0-rc8` offers now, but keep in mind that they won't show up in the public offers list until the official `1.7.0` release.

**Comment by esaung** [comment] 2023-02-13 15:27
Thanks @denisu !

**Comment by emlowe** [comment] 2023-05-30 18:21
Closing issue

**Closed by emlowe** 2023-05-30 18:21 UTC
Labels: bug, GUI, Windows, offers, 1.7.0
