### ISSUE TITLE
[BUG] No of Plots Do Not Update Until After I Reload the Chia App

### ISSUE THREAD

**Issue by vdx660** [Chia-Network/chia-blockchain#7715] opened 2021-07-21 23:41 UTC
**Describe the bug**
I have 20 Plots as shown below:
![image](https://user-images.githubusercontent.com/23503436/126572308-aadea497-9dc4-4046-96b7-8bb51f1207bd.png)

My number of Plots shows 18
![image](https://user-images.githubusercontent.com/23503436/126572379-112b7b42-3880-4110-b510-4f8880c82fb0.png)

I have waited several hours but it doesn't update until I Reload Chia App
![image](https://user-images.githubusercontent.com/23503436/126572661-8bb472a9-7609-4c19-a4d0-c13712ec8f9f.png)

Now I have 20 Plots
![image](https://user-images.githubusercontent.com/23503436/126572703-423cd536-95b3-47ee-9082-de5a4db53699.png)

**To Reproduce**

Steps to reproduce the behavior, On the open Chia App do the following:

1. Click on Pool [You will see No of Plots at 18]
2. Select a Pool > Add Plot > Specify Size, Number of Plots = 2, Temporary Directory, Final Directory > Create
3. Wait for the Plotting to Complete
4. Click on Pool [You will still see No of Plots at 18]
5. Click on View > Reload
6. Select Pool Key
7. Click on Pool [You will now see No of Plots at 20]

**Expected behavior**
No of Plots in Pool should updated after a few minutes of completion

**Screenshots**
See above:

**Desktop**

- OS: Windows 10
- CPU: lntel(R) Core(TM) i5-2400 CPU @ 3.10GHz

**Comment by emlowe** [comment] 2021-07-22 03:13
Duplicate of #7262

**Closed by emlowe** 2021-07-22 03:13 UTC
Labels: bug
