### ISSUE TITLE
[BUG] Wrong lookups sequence after refreshing plots manually

### ISSUE THREAD

**Issue by temicus** [Chia-Network/chia-blockchain#7403] opened 2021-07-12 11:01 UTC
**Describe the bug**
After refreshing the plots manually after few hours the sequence of the lookups shown in the GUI in Farm/Last Attempted Proof is random.

**To Reproduce**
1. Go to GUI Plots and click on "refresh plots"
2. Wait few hours
3. Open Farm/Last Attempted Proof and check the lookups times - they are not sequential and random.

**Expected behavior**
The lookups times are are always not sequential.

**Screenshots**
<img width="1026" alt="Bildschirmfoto 2021-07-12 um 12 48 50" src="https://user-images.githubusercontent.com/41941819/125277082-49616180-e311-11eb-8a18-63f7c8b136d0.png">

**Desktop**
Chia 1.2.0 on Win 10

**Comment by emlowe** [comment] 2021-07-14 19:21
Duplicate of https://github.com/Chia-Network/chia-blockchain-gui/issues/488

**Closed by emlowe** 2021-07-14 19:21 UTC
Labels: bug
