### ISSUE TITLE
Multi NFT Offer Failure

### ISSUE THREAD

**Issue by L4bb3rs** [Chia-Network/chia-blockchain#13839] opened 2022-11-05 21:23 UTC
### What happened?

Offers created for more then 1 NFT in exchange for XCH fail. Resulting in error can't create 2 identical coins.

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by kjlynch1974** [comment] 2022-11-05 21:28
Here is a screenshot of the error. ![Chia 1 6 1 error](https://user-images.githubusercontent.com/117544790/200141950-2ac90394-e3a4-44bb-b28e-ac44783396de.png)

**Comment by Lowestofttim** [comment] 2022-11-05 21:33
I can confirm this is the case.

**Comment by 9x9NFT** [comment] 2022-11-05 22:25
Debug log from Light Wallet 1.6.1 on attempt to accept the offer: (getting same error in gui as mentioned above) 

https://dexie.space/offers/A4mgwi5w6BNQTjGY3ydtgdJY4qMTky9LZFnKAkYJgagY

2022-11-05T23:11:46.194 wallet chia.wallet.wallet         : DEBUG    About to select coins for amount 214999999997
2022-11-05T23:11:46.195 wallet chia.wallet.wallet         : DEBUG    Selected closest greater coin: b'\xf2W/k\xf4\x8fv\x98\x9d\x0cf\x96\xa2\x82\xf3\x17|}&N\x03YN\xb8)\xd7\x1f\xa2g\xc4\xa8\xa6'
2022-11-05T23:11:46.242 wallet chia.wallet.wallet         : DEBUG    Generating transaction for: bae24162efbd568f89bc7a340798a6118df0189eb9e3f8697bcea27af99f8f79 200000000000 {Coin { parent_coin_info: 37ac90fea1742249dcb3bca0430c533ec0916218879b3713a40e2520628981d6, puzzle_hash: 13103db141c654b2129d907a1ecf19fad30da75c2fceaedd8fa46eeac8df8976, amount: 899000000000 }}
2022-11-05T23:11:46.252 wallet chia.wallet.wallet         : DEBUG    Got back max send amount: 960220719623
2022-11-05T23:11:46.253 wallet chia.wallet.wallet         : INFO     coins is not None {Coin { parent_coin_info: 37ac90fea1742249dcb3bca0430c533ec0916218879b3713a40e2520628981d6, puzzle_hash: 13103db141c654b2129d907a1ecf19fad30da75c2fceaedd8fa46eeac8df8976, amount: 899000000000 }}
2022-11-05T23:11:46.254 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'ValueError'>Traceback (most recent call last):
  File "chia\wallet\trade_manager.py", line 512, in _create_offer_for_ids
  File "chia\wallet\trade_manager.py", line 796, in check_for_special_offer_making
  File "chia\wallet\nft_wallet\nft_wallet.py", line 891, in make_nft1_offer
  File "chia\wallet\wallet.py", line 469, in generate_signed_transaction
  File "chia\wallet\wallet.py", line 370, in _generate_unsigned_transaction
ValueError: Cannot create two identical coins

2022-11-05T23:11:46.255 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 324, in safe_handle
  File "chia\rpc\rpc_server.py", line 315, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1272, in take_offer
ValueError: Cannot create two identical coins

2022-11-05T23:11:46.256 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "take_offer", "data": {"error": "Cannot create two identical coins", "success": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id": "29dfbddd5c85b9a9fc5c1a61b05cb64eacee6f873bf98a753425d7c7ed3a9383"}', extra='')
2022-11-05T23:11:53.340 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"command":"get_sync_status","data":{},"origin":"wallet_ui","destination":"chia_wallet","ack":false,"request_id":"0aefc7dc5c96c59a2454a4992411c4f349e1f468d881b3732d4f2d69f2742d17"}', extra='')
2022-11-05T23:11:53.342 wallet chia.rpc.rpc_server        : DEBUG    Rpc call <- get_sync_status
2022-11-05T23:11:53.345 wallet chia.rpc.rpc_server        : DEBUG    Rpc response -> get_sync_status
2022-11-05T23:11:53.346 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "get_sync_status", "data": {"genesis_initialized": true, "success": true, "synced": true, "syncing": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id": "0aefc7dc5c96c59a2454a4992411c4f349e1f468d881b3732d4f2d69f2742d17"}', extra='')
2022-11-05T23:11:53.795 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"command":"running_services","data":{},"origin":"wallet_ui","destination":"daemon","ack":false,"request_id":"8be80fc5d429f4ae4318436d90e172f470d900181201876f16723261ecf81add"}', extra='')

**Comment by wallentx** [comment] 2022-11-10 20:55
Since this has been merged into main, are you able to install the latest dev build and see if the issue is resolved?

**Comment by 9x9NFT** [comment] 2022-11-11 00:20
Tried with a new offer as the one from the example had been cancelled. Working now as expected. Thanks for the quick fix!

**Closed** 2022-11-11 09:32 UTC
Labels: bug, GUI, Windows, offers, NFT, 1.6.1
