### ISSUE TITLE
chia 1.6.1 install errors ubuntu 22.04 missing dependencies

### ISSUE THREAD

**Issue by airtac** [Chia-Network/chia-blockchain#13820] opened 2022-11-04 15:32 UTC
```console
$ sudo apt -f install ./chia-blockchain_1.6.1_arm64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'chia-blockchain:arm64' instead of './chia-blockchain_1.6.1_arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 chia-blockchain:arm64 : Depends: libgtk-3-0:arm64 but it is not installable
                         Depends: libnotify4:arm64 but it is not installable
                         Depends: libnss3:arm64 but it is not installable
                         Depends: libxss1:arm64 but it is not installable
                         Depends: libxtst6:arm64 but it is not installable
                         Depends: libatspi2.0-0:arm64 but it is not installable
                         Depends: libuuid1:arm64 but it is not installable
                         Depends: libsecret-1-0:arm64 but it is not installable
                         Recommends: libappindicator3-1:arm64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by chuihairu** [comment] 2022-11-05 02:23
try `sudo apt install -f`

**Comment by chuihairu** [comment] 2022-11-05 03:18
try `sudo apt install -f`

**Comment by Zyzonix** [comment] 2022-11-08 23:26
Are you sure, that you're running on ARM not AMD, bc. you're trying to install the ARM-Version?

**Comment by emlowe** [comment] 2023-01-06 19:20
Unable to reproduce - installing the deb file on the correct ARM system results in downloading and installing all dependencies correctly. Closing issue.

**Closed by emlowe** 2023-01-06 19:20 UTC
Labels: support, Linux, 1.6.1, need info
