### ISSUE TITLE
Update to 1.3.0 and my XCH is missing and farm offline[Bug] 

### ISSUE THREAD

**Issue by jacklingbn** [Chia-Network/chia-blockchain#10589] opened 2022-03-08 10:13 UTC
### What happened?

i just update to 1.3.0 and my space pool farm notify me farm offline, and i check gui pool tab its' wrong pool, and "this Plot NFT is assigned to a different key", and my XCH is Missing from 5.99 -> 1.577 now.

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by babipanghang** [comment] 2022-03-08 10:34
Duplicate of #10585 ?

**Comment by ciciban74** [comment] 2022-03-08 23:35
and i just updated to 1.3.0 and i missed the XCH too. Everything is synchronized, wallet, full node and all plots I see. SpacePoole farm normal as before. 
What I noticed is that my receive address is not the same ithas changed and shows me incoming transactions from just the last four days.
Can anyone help me since I didn't quite understand what I needed to do from last post.
Thank you

**Comment by loppefaaret** [comment] 2022-03-09 09:54
What the reference to the comment in #7138 is saying, is to try and manually remove your wallet database, and let it resync it from 0:
Closing down Chia and then in Chia's working directory, which is located under your users home folder (on Windows `C:\Users\<USERNAME>\.chia\mainnet\wallet\db\`) you can try and remove the .sqlite file that has the same fingerprint as the wallet/key that is the owner of the plotNFT that is messing up.
Then when you open up Chia again, it will resync your wallet from 0, and that can potential fix the issue.

please backup your `~\.chia\mainnet\config\config.yaml` and you wallet database if you try this, just so in the event you need it back, you got it.

**Comment by mariano54** [comment] 2022-03-10 02:13
The plotNFT syncing should be fixed by: https://github.com/Chia-Network/chia-blockchain/pull/10631
Download: https://github.com/Chia-Network/chia-blockchain/actions/runs/1959674376
Note: you will need to delete the wallet DB and start again.

**Comment by emlowe** [comment] 2022-03-10 19:39
Consolidating issues - marking duplicate of #10590

**Closed by emlowe** 2022-03-10 19:39 UTC
Labels: bug

**Comment by xlgosx** [comment] 2022-04-09 15:31
> ### What happened?
> i just update to 1.3.0 and my space pool farm notify me farm offline, and i check gui pool tab its' wrong pool, and "this Plot NFT is assigned to a different key", and my XCH is Missing from 5.99 -> 1.577 now.
> 
> ### Version
> 1.3.0
> 
> ### What platform are you using?
> Windows
> 
> ### What ui mode are you using?
> GUI
> 
> ### Relevant log output
> _No response_

Looks like for me going back to 1.2.11 from 1.3.3 solved my problem of missing chia, something wrong with 1.3.0 and above with the quick sync update causing some wallet confirmation not to be performed.
