### ISSUE TITLE
Created new Key and Wallet not synced. i made a payment to unsynced wallet...Lucky only 0.0000000001 ..Mainet does sync but new Wallet still not syncing...Old KEY wallet does sync.

### ISSUE THREAD

**Issue by TonyCollins** [Chia-Network/chia-blockchain#5755] opened 2021-05-22 00:34 UTC

**Comment by mariano54** [comment] 2021-06-28 08:14
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:14 UTC
