### ISSUE TITLE
[BUG] Plot Count on Your Farm Overview and Number of Plots on Your Pool Overview are not being updated on the full node (v1.2.2))

### ISSUE THREAD

**Issue by Jacek-ghub** [Chia-Network/chia-blockchain#7518] opened 2021-07-15 04:37 UTC
**Describe the bug**
I am running a full node that only runs a harvester (no plotting, no adding new plots from other plotters to this box - a fixed number of plots), and one additional plotter/harvester.  With Chia v1.2.0 I created a self-pool, and all new plots are created for that pool.  However, when that plotter/harvester generates a new pool based plot, the "Plot Count" field on "Your Farm Overview" is not being updated, at least until I restart that full node.  On the other hand, "Last Attempted Proof" section properly shows all plots on that remote harvester.

Also, on "Your Pool Overview" the "Number of Plots" field is not being updated (until the full node is restarted).

**To Reproduce**

1. Run one full node 
2. Run one remote harvester/plotter  
3. Generate one plot on that remote harvester
4. Check the full node UI - those two fields are not being updated

**Desktop**

- OS: Win 10, latest
- CPU: yes, of course

**Comment by lazydrone** [comment] 2021-07-15 16:39
having the same issue, but if I select "Refresh Plots" it'll update the plot count (without having to totally restart the node)

**Comment by Jacek-ghub** [comment] 2021-07-15 16:56
@lazydrone Thank you!  Works like a charm!

**Comment by emlowe** [comment] 2021-07-15 20:57
Duplicate of #7262

**Closed by emlowe** 2021-07-15 20:57 UTC
Labels: bug

**Comment by Jacek-ghub** [comment] 2021-07-16 19:22
@emlowe Can this be fixed instead of marking as duplicate?  Is there any ETA when it is expected to be done?
