### ISSUE TITLE
[Bug][Wallet][Critical] Wallet full re-sync does not syncs all transactions - leading incorrect balance

### ISSUE THREAD

**Issue by andriitalkstech** [Chia-Network/chia-blockchain#10646] opened 2022-03-10 10:34 UTC
### What happened?

Description: Wallet does not continue to sync all transactions if full-node restart while the first sync.

Steps:
* Delete wallet DB
* Set wallet setting config **initial_num_public_keys: 500**
* Start Full-node and start syncing a wallet
* After a few initial blocks synced - restart Full-Node
* Wait until loaded.

Result: 
Wallet balance is incorrect. Not all transactions got synced. Wallet says "Synced"

Expected: 
The wallet is not synced - since syncing processes were interrupted with a node-restart. Wallet continues to sync transactions.
The balance is correct.

Workaround:
* Close Full-Node
* Delete wallet DB
* Start and keep the full-node running until the wallet is fully synced without any interruptions. 

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by SametBasturkk** [comment] 2022-03-10 11:09
Same thing happened +1

**Comment by Ealrann** [comment] 2022-03-10 12:57
Here too, without changing the config.

**Comment by malambert35** [comment] 2022-03-10 13:08
Here too

**Comment by evan00520** [comment] 2022-03-10 15:52
me2

**Comment by mariano54** [comment] 2022-03-10 19:15
Can someone take this ticket?

**Comment by andriitalkstech** [comment] 2022-03-10 19:37
@Yostra I'm open to testing fixes in dev builds, providing logs, and assisting.
Find me on Keybase @andriitalkstech

**Comment by Yostra** [comment] 2022-03-10 19:37
Awesome, I'll ping you when ready

**Comment by navyfeng** [comment] 2022-03-11 09:04
> ### What happened?
> Description: Wallet does not continue to sync all transactions if full-node restart while the first sync.
> 
> Steps:
> 
> * Delete wallet DB
> * Set wallet setting config **initial_num_public_keys: 500**
> * Start Full-node and start syncing a wallet
> * After a few initial blocks synced - restart Full-Node
> * Wait until loaded.
> 
> Result: Wallet balance is incorrect. Not all transactions got synced. Wallet says "Synced"
> 
> Expected: The wallet is not synced - since syncing processes were interrupted with a node-restart. Wallet continues to sync transactions. The balance is correct.
> 
> Workaround:
> 
> * Close Full-Node
> * Delete wallet DB
> * Start and keep the full-node running until the wallet is fully synced without any interruptions.
> 
> ### Version
> 1.3
> 
> ### What platform are you using?
> Windows
> 
> ### What ui mode are you using?
> GUI
> 
> ### Relevant log output
> _No response_

NOT initial_num_public_keys
initial_num_public_keys_new_wallet: 5 --> 500
and resync wallet. just try

**Comment by andriitalkstech** [comment] 2022-03-11 10:48
> > ### What happened?
> > Description: Wallet does not continue to sync all transactions if full-node restart while the first sync.
> > Steps:
> > 
> > * Delete wallet DB
> > * Set wallet setting config **initial_num_public_keys: 500**
> > * Start Full-node and start syncing a wallet
> > * After a few initial blocks synced - restart Full-Node
> > * Wait until loaded.
> > 
> > Result: Wallet balance is incorrect. Not all transactions got synced. Wallet says "Synced"
> > Expected: The wallet is not synced - since syncing processes were interrupted with a node-restart. Wallet continues to sync transactions. The balance is correct.
> > Workaround:
> > 
> > * Close Full-Node
> > * Delete wallet DB
> > * Start and keep the full-node running until the wallet is fully synced without any interruptions.
> > 
> > ### Version
> > 1.3
> > ### What platform are you using?
> > Windows
> > ### What ui mode are you using?
> > GUI
> > ### Relevant log output
> > _No response_
> 
> NOT initial_num_public_keys initial_num_public_keys_new_wallet: 5 --> 500 and resync wallet. just try

Thanks for your comment - the change of the config is a suggestion of a dev team, so I will trust them at this point.
Also the problem is not only that balance is not right, but also that wallet isn't syncing if the process of a sync has been disrupted.

**Comment by Ealrann** [comment] 2022-03-16 13:02
@Yostra @mariano54 
Chia team, this bug makes the Chia wallet almost impossible to use for some people, and is reported multiple times ( #10664, #10699, #10714, #10766, #10627, #10625 ). For now, my only solution is to rollback to 1.2.x, which means days of synchronizations. On different computers, clean setup, I cannot sync correctly my wallet with 1.3.

I guess you're probably busy on some Atari and Asteroid big project, but I really feel abandoned due to lack of communication. Are you working on it? Do you need help testing/finding the cause? Is there any workaround? I suspect that people having this issue also have a plotnft not synced (since it depends on the wallet synchronization), so could it impact the farming?

**Comment by skaviani** [comment] 2022-03-18 22:53
i do have the same issue on ubuntu...

**Comment by skaviani** [comment] 2022-03-19 13:33
i was able to help myself as i saw 2 version of my wallet (blockchain_wallet_v1_mainnet_xxxx and blockchain_wallet_v2_mainnet_xxxx) in wallet folder.... just renamed both files and now it showing the right balance..!!

**Comment by emlowe** [comment] 2022-04-29 16:56
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment] 2022-05-11 21:59
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5

**Closed by emlowe** 2022-05-11 21:59 UTC
Labels: bug, Wallet, balance
