### ISSUE TITLE
[Bug] Pool UI incorrectly shows self pooling

### ISSUE THREAD

**Issue by donwalling** [Chia-Network/chia-blockchain#10670] opened 2022-03-11 15:24 UTC
### What happened?

After upgrading to 1.3.0, the Pool UI shows "Status | Self Pooling" but actually its still a member of spacepool and afaict its still contributing partials and collecting rewards. 

When I click on "Join Pool" the form is pre-filled with the correct pool details, and clicking on "Change" button doesn't do anything.

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
what log would be relevant?
```

**Comment by emlowe** [comment] 2022-03-11 22:54
Likely duplicate of #10590

**Closed by emlowe** 2022-03-11 22:54 UTC
Labels: bug
