### ISSUE TITLE
[BUG] port reuse

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#1177] opened 2021-03-07 01:47 UTC
```
(venv) cery@cery-ll-home:~$ chia stop all -d 
Traceback (most recent call last):
  File "/home/cery/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/home/cery/chia-blockchain/src/server/start_wallet.py", line 87, in main
    return run_service(**kwargs)
  File "/home/cery/chia-blockchain/src/server/start_service.py", line 208, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/cery/chia-blockchain/src/server/start_service.py", line 202, in async_run_service
    return await service.run()
  File "/home/cery/chia-blockchain/src/server/start_service.py", line 148, in run
    await self.wait_closed()
  File "/home/cery/chia-blockchain/src/server/start_service.py", line 192, in wait_closed
    await self._rpc_close_task
  File "/home/cery/chia-blockchain/src/server/start_service.py", line 178, in close_rpc_server
    await (await self._rpc_task)()
  File "/home/cery/chia-blockchain/src/rpc/rpc_server.py", line 337, in start_rpc_server
    await site.start()
  File "/home/cery/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 9256): address already in use
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '17cccb4e04d5343a40884ddbeba475689d9c8a7fe97998b03d315839254ac591'}
(venv) cery@cery-ll-home:~$ sudo lsof -i:9256
COMMAND       PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
chia_wall 2769652 cery   15u  IPv4 579625332      0t0  TCP localhost:9256 (LISTEN)
(venv) cery@cery-ll-home:~$ sudo kill -9 2769652
```

**Comment by hoffmang9** [comment] 2021-03-07 02:10
This usually happens because you're trying to use chia stop from a newer version to stop an older version's daemon. Were you possibly in that situation?

**Comment by JsBlueCat** [comment] 2021-03-07 04:34
> This usually happens because you're trying to use chia stop from a newer version to stop an older version's daemon. Were you possibly in that situation?

yes i update the new version without stop the old one.

**Comment by hoffmang9** [comment] 2021-03-07 06:32
Closing as not a bug. Run stop before the upgrade.

**Closed by hoffmang9** 2021-03-07 06:32 UTC
Labels: bug
