### ISSUE TITLE
[Bug] Pool reward target address does not work when self-pooling

### ISSUE THREAD

**Issue by thepogona** [Chia-Network/chia-blockchain#11240] opened 2022-04-20 17:42 UTC
### What happened?

When self-pooling, if an address different than the farmer keys is specified for "reward target address", the blockchain will award .25XCH to that address every time a block is found.  Nonetheless, even if a different address is specified for "pool reward target address", 1.75XCH will still be sent to the pooling wallet, and to the farming keys when claiming the plotnft rewards, thus making it difficult to secure farming rewards easily for self-pooling farmers.

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment] 2022-04-20 23:06
This is expected, as it's not directly related to the target address in config.yaml. The Plot NFT contract locks the 1.75 and requires manual claiming - this is then sent to the current standard wallet - currently you cannot change the address where the rewards are claimed, although this is often requested (see #10707) Closing as duplicate of #10707

**Closed by emlowe** 2022-04-20 23:06 UTC
Labels: bug
