### ISSUE TITLE
Stuck in connecting to wallet I've tried on 2 different OS and tried different internet connections tried uninstalling and reinstalling on both systems still nothing. I even let it set for 2 days trying to connect to CHIA 1.1.6 had this issue with 1.1.4 and it seemed to fix itself over a period of a day or two after running a reinstall and reboot. However this is not working. I'm using a windows 10 system and a MAC OS both are running updated versions of their OS. Firewall is off . [BUG]

### ISSUE THREAD

**Issue by joestud69** [Chia-Network/chia-blockchain#6494] opened 2021-06-06 05:22 UTC
[BUG] Stuck in connecting to wallet I've tried on 2 different OS and tried different internet connections tried uninstalling and reinstalling on both systems still nothing. I even let it set for 2 days trying to connect to CHIA 1.1.6 had this issue with 1.1.4 and it seemed to fix itself over a period of a day or two after running a reinstall and reboot. However this is not working. I'm using a windows 10 system and a MAC OS both are running updated versions of their OS. Firewall is off .

**Comment by MarcusB2105** [comment] 2021-06-06 05:23
The ChiaSetup 1.1.7 is now available on the official chia.net download section. This should solve the problem.

**Comment by tryer50** [comment] 2021-06-06 05:26
> [ERROR] Atascado en la conexión a la billetera. Probé en 2 sistemas operativos diferentes y probé diferentes conexiones a Internet. Intenté desinstalar y reinstalar en ambos sistemas pero todavía no hay nada. Incluso dejé que se estableciera durante 2 días tratando de conectarme a CHIA 1.1.6. Tuve este problema con 1.1.4 y pareció solucionarse solo en un período de uno o dos días después de ejecutar una reinstalación y reiniciar. Sin embargo, esto no funciona. Estoy usando un sistema Windows 10 y un sistema operativo MAC que ejecutan versiones actualizadas de su sistema operativo. El cortafuegos está desactivado.

wait a few hours for it to appear in keybase to install 1.1.7

**Comment by dglick60** [comment] 2021-06-06 14:08
Same problem - connecting to wallet forever, Chia 1.7. Another symptom is plotting started taking forever even though computer resources at 50% or less.

**Comment by joestud69** [comment] 2021-06-06 17:20
Now I'm having an issue with the security of 1.1.7 even though firewalls are off it doesn't want to allow access. On Windows 10

On Mac now it's logged into the wallet but now it's not loading the full node page.

**Comment by Wontell** [comment] 2021-06-07 04:48
Im having the same wallet issue

**Comment by mariano54** [comment] 2021-06-28 07:56
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 07:56 UTC
Labels: bug
