### ISSUE TITLE
[Bug] NoneType object is not subscriptable

### ISSUE THREAD

**Issue by coolagrwal** [Chia-Network/chia-blockchain#10593] opened 2022-03-08 14:25 UTC
### What happened?

while trying to retrieve wallet key using mnemonic words, the error is raised "NoneType" object is not subscriptable 

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Na
```

**Comment by coolagrwal** [comment] 2022-03-08 15:21
restaring chia seems to have worked fine, hence closing issue

**Comment by coolagrwal** [comment] 2022-03-10 02:04
its still a pain, trying to generate a new key, same None type error presists, something is not right. kindly look into this

**Comment by mariano54** [comment] 2022-03-10 02:11
Can you post the full error here?

**Comment by horvathzeros** [comment] 2022-03-15 23:01
Same error on Ubuntu 21.10

I was farming and suddenly GUI crash without errors, when i try to launch again the GUI ask me for new wallet of import mnemonics but when i try to import i get the error ""NoneType" object is not subscriptable"
![image](https://user-images.githubusercontent.com/13834271/158486014-0f556557-3c7b-41be-a629-e23cd16ba255.png)

**Comment by emlowe** [comment] 2022-04-22 22:04
I've been spending some time trying to reproduce this without success.

If anyone who has seen this could post their debug.log it would be useful.

**Comment by emlowe** [comment] 2022-05-11 23:01
Closing issue as unable to reproduce

**Closed by emlowe** 2022-05-11 23:01 UTC
Labels: bug, GUI, Windows
