### ISSUE TITLE
[Bug] Getting SpendBundle warning & DOUBLE_SPEND error after buying an nft

### ISSUE THREAD

**Issue by temicus** [Chia-Network/chia-blockchain#12238] opened 2022-07-05 17:03 UTC
### What happened?

Hello,

after buying today an NFT (Chia Ghost) on skyNFT (definitely an original one) I see in my logs this warning coming every hour:

WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xaf0436240d1eba83ee7baf5....'}

### Version

Version 1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-07-05T06:47:15.035 full_node chia.full_node.full_node: INFO      Updated peak to height 2212718, weight 4711190400, hh 529888bc57063369e587d4f9462a82...., forked at 2212717, rh: 8aed88037a0dd9604da52b409b...., total iters: 883999..., overflow: False, deficit: 2, difficulty: 1920, sub slot iters: 136314880, Generator size: No tx, Generator ref list size: No tx
2022-07-05T06:47:15.088 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 2212718 timestamp: 1656996382
2022-07-05T06:47:15.223 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xaf0436240d1eba83ee7baf5152976ac.....'}
2022-07-05T06:47:16.752 full_node chia.full_node.full_node: INFO       Finished signage point 32/64: CC: 3e8614808a9878e826dc29cb9b8c.... RC: ab6cb06d54abd25e6a45ef2d3... 
2022-07-05T06:47:17.212 harvester chia.harvester.harvester: INFO     2 plots were eligible for farming 26220e1368... Found 0 proofs. Time: 0.45789 s. Total 1949 plots
2022-07-05T06:47:22.118 full_node full_node_server
```

**Comment by Stizerg** [comment] 2022-07-10 06:00
My logs are full of this warning messages and I didn't buy anything 
```
2022-07-10T15:42:19.095 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x3e8b864d2a7f6157c75161b2a5f215eb021f5fe8a28683db1f0cbb8559521fb3'}
2022-07-10T15:42:19.111 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x7ed77d01049c561d3ff5cbfd74f5716d9a560ea0107299fe82b811d45fa3cf12'}
2022-07-10T15:42:19.115 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xaeaf2ae52ea42c21c83645d1e4ae99a79ce338eb8cfabcb8c373118833ae4fc3'}
2022-07-10T15:42:19.816 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xfed2c793ac815b91b68b6cdee09bf1aec6cce41e5ad01db46f3b1e94ce7215ed'}
2022-07-10T15:44:10.879 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x3e8b864d2a7f6157c75161b2a5f215eb021f5fe8a28683db1f0cbb8559521fb3'}
2022-07-10T15:44:10.887 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x7ed77d01049c561d3ff5cbfd74f5716d9a560ea0107299fe82b811d45fa3cf12'}
2022-07-10T15:44:10.894 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xaeaf2ae52ea42c21c83645d1e4ae99a79ce338eb8cfabcb8c373118833ae4fc3'}
2022-07-10T15:44:10.902 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xfed2c793ac815b91b68b6cdee09bf1aec6cce41e5ad01db46f3b1e94ce7215ed'}
```

**Comment by aqk** [comment] 2022-07-11 20:34
Thank you for the reports. I'll start looking at this in the wallet code now.

**Comment by hbroer** [comment] 2022-07-21 18:39
I have such messages too. They are in my logs since a while. Today I just saw them after a restart today again. Only outgoing transaction I made a while ago was about offers ("you accepted" and confirmed, creation dates: April 5, 2022 10:40 AM + March 31, 2022 10:35 PM, canceled: creation date: March 27, 2022 7:15 PM; "you created" and cancelled: March 27, 2022 4:58 PM).

I don't see any open transactions in GUI and I did not found the IDs in chia exlorers.

since last restart:
```
2022-07-21T16:36:27.626 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-07-21T16:36:27.630 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-07-21T16:36:27.640 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-07-21T17:36:51.119 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-07-21T17:36:51.123 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-07-21T17:36:51.134 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-07-21T18:38:31.033 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-07-21T18:38:31.035 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-07-21T18:38:31.047 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-07-21T19:38:36.242 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-07-21T19:38:36.245 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-07-21T19:38:36.256 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
```

First time 0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475 was in the logs:
```
2022-03-27T16:49:33.716 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 612, in get_wallet_balance
KeyError: 0

2022-03-27T16:49:47.492 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 611, in get_wallet_balance
ValueError: invalid literal for int() with base 10: ''

2022-03-27T16:54:31.890 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'ValueError'>Traceback (most recent call last):
  File "chia\wallet\trade_manager.py", line 312, in _create_offer_for_ids
ValueError: You cannot offer nor request 0 amount of something

2022-03-27T16:54:31.890 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 906, in create_offer_for_ids
  File "chia\wallet\trade_manager.py", line 253, in create_offer_for_ids
Exception: Error creating offer: You cannot offer nor request 0 amount of something

2022-03-27T19:10:39.107 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 612, in get_wallet_balance
KeyError: 0

2022-03-27T19:15:43.548 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
```

1st time 0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c was in the logs:
```
2022-04-05T11:06:43.811 full_node chia.full_node.full_node: WARNING  Block validation time: 2.62 seconds, pre_validation time: 0.91 seconds, cost: 5327901838, percent full: 48.435% header_hash: cc7de6542aba0276aa2b39f263884dd26c5313ff79edc8a1c419c253cffb0ab0 height: 1793985
2022-04-05T11:07:56.605 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-04-05T11:13:47.078 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-04-05T11:14:18.691 harvester chia.harvester.harvester: WARNING  Looking up qualities on E:\_Chia Pool\plot-k32-2021-10-20-16-15-3f54c360beefa2aa9b547af1882c4a504c09bb36cfad62a768a31ed4e7a37285.plot took: 9.579213619232178. This should be below 5 seconds to minimize risk of losing rewards.
```

1st time 0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50 was in the logs:
```
2022-04-09T15:11:04.668 full_node chia.full_node.full_node: WARNING  Block validation time: 2.24 seconds, pre_validation time: 0.83 seconds, cost: 4061335590, percent full: 36.921% header_hash: 79abec2a1e73fcafdf38da3f542bea132d29654eb4e64130a6985a6abb0d5aaa height: 1813233
2022-04-09T15:11:16.654 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-04-09T15:11:16.658 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-04-09T15:11:16.900 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x013dbca35cda86fff36f1872989a5cfdc72b2595aec0224a067e637677ef7d50'}
2022-04-09T15:11:16.904 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-04-09T15:11:16.905 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1f0b6be1086ab1c7cd25ea4465f66d6a6788cf478bf7471944db6ee7ef55043c'}
2022-04-09T15:11:17.157 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x30f4983745c80076ddbeb4eb8fd8dd9c99fcfeef8e8a738b06287fa5657aa475'}
2022-04-09T15:11:34.182 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 231, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
```

**Comment by emlowe** [comment] 2022-07-21 22:52
Please note, other wallets in the wild may connect to your node and so the SpendBundle warnings can be caused by other wallet transactions and not just by your own wallet. The logging unfortunately doesn't differentiate.

**Comment by hbroer** [comment] 2022-07-23 07:24
> Please note, other wallets in the wild may connect to your node and so the SpendBundle warnings can be caused by other wallet transactions and not just by your own wallet. The logging unfortunately doesn't differentiate.

Yea did not think about that but in my case it is not very likely because the transactions ID are the same since a while and I did not found anything online which mentions them. If they are external requests than these IDs should be visible in most logs by other farmers too.

**Comment by temicus** [comment] 2022-08-01 14:19
For me its gone after the update to 1.5. 😀...

**Comment by hbroer** [comment] 2022-08-01 20:24
I have it still but the 3 previously are gone and instead I have another one after I did some offers (canceled one, accepted one, tried to accept one which was not available anymore, and one of mine got accepted). ^^ It keeps spaming my log. I belive it is caused by the canceled. I always included low fees (5000 mojos) and canceled on blockchain.

**Comment by wallentx** [comment] 2022-08-05 04:39
Currently running main, and am not seeing these anymore.

**Comment by emlowe** [comment] 2023-01-06 20:45
Marking fixed in later releases - will reopen if there are additional reports

**Closed by emlowe** 2023-01-06 20:45 UTC
Labels: bug
