### ISSUE TITLE
[BUG] ERROR Exception: Error short batch syncing, could not fetch block at height ...

### ISSUE THREAD

**Issue by j4ys0n** [Chia-Network/chia-blockchain#8430] opened 2021-09-10 15:03 UTC
**Describe the bug**
Full node stops syncing every couple days (at random). Error below.

**To Reproduce**

Run full node on Ubuntu 18.

**Expected behavior**
Node keeps syncing

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 18
- CPU: VM/Ryzen 9 5900

**Additional context**

```
2021-09-09T22:44:23.756 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 837860 <class 'ValueError'>, closing connection {'host': '195.211.206.245', 'port': 16664}. Traceback (most recent call last):
  File "chia/server/server.py", line 563, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 560, in wrapped_coroutine
  File "chia/server/server.py", line 553, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 106, in new_peak
  File "chia/full_node/full_node.py", line 411, in new_peak
  File "chia/full_node/full_node.py", line 247, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 837860

2021-09-09T22:44:23.756 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 837860, {'host': '195.211.206.245', 'port': 16664}. Traceback (most recent call last):
  File "chia/server/server.py", line 553, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 106, in new_peak
  File "chia/full_node/full_node.py", line 411, in new_peak
  File "chia/full_node/full_node.py", line 247, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 837860
```

**Comment by emlowe** [comment] 2021-09-10 16:11
These errors are expected in a P2P network where some peers don't respond properly - these peers will be dropped and you will fetch the blocks from other peers

**Comment by j4ys0n** [comment] 2021-09-10 19:11
That's not sufficient - my chain stops syncing and farming stops at that point.

**Comment by jack60612** [comment] 2021-09-10 19:12
> That's not sufficient - my chain stops syncing and farming stops at that point.

@j4ys0n its not a chia issue 
You need to portforward and get more nodes.

**Comment by j4ys0n** [comment] 2021-09-10 19:12
the p2p port is forwarded.

**Comment by jack60612** [comment] 2021-09-10 19:13
> the p2p port is forwarded.

idk you just need more nodes

**Comment by j4ys0n** [comment] 2021-09-10 19:14
why is that my problem? the node should handle that like every other blockchain client.

**Comment by jack60612** [comment] 2021-09-10 19:15
> why is that my problem? the node should handle that like every other blockchain client.

it isnt a problem and the node is working fine.

**Comment by j4ys0n** [comment] 2021-09-10 19:16
it's clearly not. that error occurs every few days and the chain stops syncing, and hence farming stops. i have significant investment into all of the drive space.

**Comment by jack60612** [comment] 2021-09-10 19:17
> it's clearly not. that error occurs every few days and the chain stops syncing, and hence farming stops. i have significant investment into all of the drive space.
It is getting a bad block from that node then promptly banning the node
That is expected

**Comment by jack60612** [comment] 2021-09-10 19:18
> it's clearly not. that error occurs every few days and the chain stops syncing, and hence farming stops. i have significant investment into all of the drive space.

Im a dev lol it is fine

**Comment by j4ys0n** [comment] 2021-09-10 19:19
it doesn't find new nodes and continue syncing the chain. how is this fine and expected behavior?
you're saying it should stop and require manual intervention?

i am a dev too. i've been a blockchain engineer for years at this point :)

**Comment by jack60612** [comment] 2021-09-10 19:19
> it doesn't find new nodes and continue syncing the chain. how is this fine and expected behavior?
> you're saying it should stop and require manual intervention?
> 
> i am a dev too. i've been a blockchain engineer for years at this point :)

IF you are only connected to 1 node that will happen

**Comment by j4ys0n** [comment] 2021-09-10 19:23
again - why is that the problem of the node operator? my node is currently connected to 20+ other nodes on the open p2p port.

**Comment by jack60612** [comment] 2021-09-10 19:25
> again - why is that the problem of the node operator? my node is currently connected to 20+ other nodes on the open p2p port.

Ok i assumed you were only connected to one as that seemed the most logical

**Comment by jack60612** [comment] 2021-09-10 19:25
> again - why is that the problem of the node operator? my node is currently connected to 20+ other nodes on the open p2p port.

message jacknelson on keybase with your debug.log and ill look at it @j4ys0n

**Comment by j4ys0n** [comment] 2021-09-10 19:26
will do - thank you

**Comment by loppefaaret** [comment] 2021-09-13 15:11
as far as i was made aware, the issue is being resolved elsewhere, closing

**Closed by loppefaaret** 2021-09-13 15:11 UTC
Labels: bug
