### ISSUE TITLE
 Wallet balance not updating

### ISSUE THREAD

**Issue by Hellika22** [Chia-Network/chia-blockchain#15982] opened 2023-08-09 07:01 UTC
### What happened?

Hello, why are transactions for 2023 not showing up in Chia Wallet? Accordingly, for this year the coins on the wallet are not visible, and a month ago they were still displayed...

### Version

ChiaSetup-1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment] 2023-08-09 18:17
Hey @Hellika22 , please note that I am closing this issue ticket as it is a duplicate of this discussion ticket:
https://github.com/Chia-Network/chia-blockchain/discussions/15981

Lets work on this support item in the above mentioned discussion ticket and we can create a bug report after going through a bit of troubleshooting if it is necessary :+1:

**Closed by BrandtH22** 2023-08-09 18:17 UTC
Labels: bug, Awaiting Response
