### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zaphrodbblbrx** [Chia-Network/chia-blockchain#5883] opened 2021-05-23 16:23 UTC
**Describe the bug**
GUI Goes to "connecting to wallet" for infinity. ive left it for over 24 hours

**To Reproduce**

1. Go to '...' Open Chia Farmer
2. Click on '....' Start Plots
3. Scroll down to '....' Come back and check 8 hours later
4. See error   Wallet stuck in connecting to wallet loop.

**Expected behavior**
I expect to open chia, schedule 4 plots on my 16 core I7, and come back 24 hours later to 4 complete plots.

I come back after as little as two hours and the whole GUI crashed

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- OS Version/Flavor: [doesnt matter, was using a 3 month old update and had the same problem as after updating windows]
- CPU: i7 8700

**Additional context**

The team really should make the Chia GUI independent of the wallet, plotting and farming processes.
my plotting speed is 25% what it should be because these crashes happen daily, to the point where its a waste of time

Hopefully the team can use their 21 million reserve chia ($21 Billion dollars????) to actually make a GUI that functions

21 billion and no working product

**Comment by zaphrodbblbrx** [comment] 2021-05-23 16:24
I should mention this PC is an Etherium Rig which runs stable for months at a time. The only time it reboots is when windows forces an update. theres 32 GB of ram and hundreds of TB of unfilled space.

I've stopped ether mining this week and the issue contintued to persist

**Comment by lvpcguru** [comment] 2021-05-24 17:10
Are you updated to 1.1.6 yet? 

You can check the C:\Users<your_username_here>.chia\mainnet\plotter\ folder for the running plots until they complete so that you dont have to close the GUI until your plots are wrapped.

Also CLI is def the way to go with plotting for now. The GUI having all the roles in one makes things hard to manage. 
I myself migrated my full node to an ubuntu box and used the guide [Connecting the UI to a Remote Daemon](https://github.com/Chia-Network/chia-blockchain-gui/blob/main/remote.md) to give me the windows GUI wanted for wallet and sync status monitoring and the best part is the services are all on ubuntu and headless so they dont close when I close the GUI.

Do you have anything in the debug log of note?

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
