### ISSUE TITLE
Not synced

### ISSUE THREAD

**Issue by Commodoreuno** [Chia-Network/chia-blockchain#5221] opened 2021-05-16 18:23 UTC
Hello there 

I have recurring problems with synchronization. My Port 8444 is open (Fritzbox) and the Version of Chia is 1.1.5. There are some errors in the Log file, but I have no idea of the meaning. At the moment I'm totally overwhelmed.

2021-05-16T19:50:35.645 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

2021-05-16T20:02:58.243 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

2021-05-16T20:03:24.621 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T20:09:27.397 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-16T20:10:20.436 full_node full_node_server        : WARNING  Banning 183.178.100.183 for 600 seconds
2021-05-16T20:10:20.439 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 183.178.100.183

2021-05-16T20:13:26.651 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

**Comment by korobov-e** [comment] 2021-05-16 19:11
Have a close issue

**Comment by temicus** [comment] 2021-05-16 20:08
I have also no sync since 2 hr :( without any log message. 8444 is open.
nothing helps.
Have tried to connect a friendly port but it also doesnt work... getting than this message in log:

2021-05-16T21:54:22.008 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

**Comment by grafbcn** [comment] 2021-05-16 21:01
I have same problem in my MS Windows 2016, and my friend in MS Windows 2019. But other people with Windows 10 don't has this problem. And any people say with 1.1.4 work fine. I think the problem is with Windows Server version or with 1.1.5.

**Comment by HFBerman87** [comment] 2021-05-17 20:18
I am having the same "2021-05-16T19:09:45.852 full_node full_node_server : ERROR Exception: Error short batch syncing, could not fetch block at height 290829, None. Traceback (most recent call last):" on Windows Server 2012R2

**Comment by corner22** [comment] 2021-05-18 18:06
> I am having the same "2021-05-16T19:09:45.852 full_node full_node_server : ERROR Exception: Error short batch syncing, could not fetch block at height 290829, None. Traceback (most recent call last):" on Windows Server 2012R2

I am getting same error on Windows 10. Chia v1.1.5.

**Comment by ccurran** [comment] 2021-05-18 23:18
Same error. Version 1.1.5 on Windows 10 Pro.

2021-05-18T19:14:40.996 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 301574 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 225, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 301574

**Comment by profitraff** [comment] 2021-05-19 04:19
Same error. Version 1.1.5 on Windows 10 Pro

**Comment by reedog117** [comment] 2021-05-19 18:35
Same error. 1.1.5 on Linux.

**Comment by moseath** [comment] 2021-05-20 03:38
Same here, try to sync more than 5 hrs.
V1.15 - Window10

**Comment by sudo-mk-sandwich** [comment] 2021-05-20 07:05
Same here. 1.1.5 Linux Mint

**Comment by blackflash** [comment] 2021-05-21 17:37
Tried with 1.1.6 a getting same :/ :(

**Comment by grafbcn** [comment] 2021-05-26 15:04
After update to 1.1.6 I have same exception, but now Sync don't stop and run. I don't know if is good notice.

**Comment by sudo-mk-sandwich** [comment] 2021-05-26 16:24
After updating to 1.1.6 and switching to Win 7, it syncs well now.

**Comment by SoMoney** [comment] 2021-05-31 16:57
Running 1.6 on Win10 and seeing these as well after a fresh install.
My C:\Users\<username>\.chia\mainnet\db\blockchain_v1_mainnet.sqlite  file is slowly growing as these are happening so
  I believe it's because the chia client is still building a database out of all my plots.    I bet if I set this box to only harvest and moved my farming to the NAS exclusively these errors would be few.

**Comment by NEITG** [comment] 2021-06-05 16:29
Getting these errors since updating to 1.1.6, Windows 2019..

Started with:

`full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError`

`wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError`

Then over and over these:

`2021-06-05T12:47:17.484 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T12:47:17.484 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T12:47:17.484 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-05T12:47:17.609 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T12:47:18.094 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables`

**Comment by mariano54** [comment] 2021-06-28 08:00
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue

**Closed by mariano54** 2021-06-28 08:00 UTC
