### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by agueromauro** [Chia-Network/chia-blockchain#5864] opened 2021-05-23 11:09 UTC
Do not open the wallet, it stays charging for hours
![Captura](https://user-images.githubusercontent.com/84665403/119257978-2bdc0b00-bb9e-11eb-932e-16fef867a034.PNG)

**Comment by mariano54** [comment] 2021-06-28 08:18
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.

**Closed by mariano54** 2021-06-28 08:18 UTC
Labels: bug
