### ISSUE TITLE
When opening Chia program, stuck on loading configuration [Bug] 

### ISSUE THREAD

**Issue by chrismikefowler1** [Chia-Network/chia-blockchain#10091] opened 2022-02-03 12:58 UTC
### What happened?

I installed the 1.2.12241 and then reverted.  still stuck on loading configuration.  It was working up until 2 days ago.  I have 70TB.

### Version

1.2.12241

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by mariano54** [comment] 2022-02-03 16:04
I'm seeing the same problem.

**Comment by mariano54** [comment] 2022-02-03 16:04
This is a gui issue not chia-blockchain it seems, command line works fine.

**Comment by AbcZee** [comment] 2022-02-03 18:50
i am having the same problem, since yesterday

**Comment by pandeliev** [comment] 2022-02-03 20:41
Me too. It try to sync but after long time it says Not availble.

**Comment by esaung** [comment] 2022-02-03 21:29
what did you have installed prior to 1.2.12241?

does it sound related to this issue? - https://github.com/Chia-Network/chia-blockchain/issues/10082

**Comment by chrismikefowler1** [comment] 2022-02-03 22:03
I had the regular update installed. Yes it sounds the same, but this is a
windows and that is a MAC.

**Comment by esaung** [comment] 2022-02-07 21:01
the issue is the same on both mac and windows and is something that we are looking into fixing.

can you clarify the version that your regular update shows?

**Comment by chrismikefowler1** [comment] 2022-02-07 21:03
The 1.2.11 for windows

**Comment by esaung** [comment] 2022-02-07 21:06
Thanks, there have been some fixes merged in the later 1.2.12 builds available in the "beta section". can you try those builds and see if you can get past the screen that you were stuck on before?

**Comment by chrismikefowler1** [comment] 2022-02-08 13:03
I tried older versions of chia, and now since it won't work anyways I've tried the wallet version that says don't use on an active farming machine.  This version gets apast the main screen, but is only a wallet.  I could not find the "beta section" with anything more than the "latest beta" but I tried the 1.2.10 with no luck. I will try all of the beta's if you can send me a link or show me how to navigate to that screen to get them.

**Comment by esaung** [comment] 2022-02-08 15:35
Hi @chrismikefowler1 , the latest stable build of Chia is 1.2.11 (I believe this is the version that you reverted back to). 

The 1.2.11 release is what you see on this part of the download page:
<img width="1052" alt="Screen Shot 2022-02-08 at 9 29 40 AM" src="https://user-images.githubusercontent.com/93196638/153019680-03f283d4-7714-4af9-a8d6-f87a0a1e9e4e.png">


The light wallet beta from the download page is just a wallet and contains access to our newer features like managing different CAT tokens and making/accepting offers. The light wallet does not contain any of the farming tools (eg. plotting, joining pools, etc.).

The light wallet beta is accessible on this part of the download page:
<img width="498" alt="Screen Shot 2022-02-07 at 1 40 09 PM" src="https://user-images.githubusercontent.com/93196638/153019817-e15315ea-bc4a-413e-99a7-b75213a986a8.png">

The issue that you originally submitted was versioned 1.2.12 and those are working builds of our next version, so it contains the latest and greatest changes, but is not an official release, so it's to help you see what's coming, but there are going to be some rough edges with it.

Those beta builds are available under this section:
![Screen Shot 2022-02-03 at 12 49 04 PM](https://user-images.githubusercontent.com/93196638/153020239-c66932f0-53cd-41ed-acb1-6b7dedb30c50.png)

If you want to run something stable and farm, then stick with 1.2.11. If you want to play with the new capabilities like CAT tokens and Offers, then run the light wallet (and heed the warning if you are setup to farm). If you want to try our the bleeding edge of updates, then download from the "latest Beta" section.

**Comment by chrismikefowler1** [comment] 2022-02-08 16:27
I understand all of those things you have just submitted to me.  So I have reverted back to the 1.2.11 and I am not able to move past the Beginning screen. I am stuck at loading configuration. I have tried all of the current available versions.  I am not able to farm.

**Comment by esaung** [comment] 2022-02-08 17:32
Got it thanks. a couple of questions: you had a farm set up and running before running into this issue? can you share a screenshot of the beginning screen that you are stuck on?

**Comment by Riyadaljuboory** [comment] 2022-02-08 17:41
I'm having same issue since 3 weeks.

**Comment by esaung** [comment] 2022-02-08 22:39
Can you please confirm that the screenshot stuck on "loading configurations" is running the 1.2.11 build? and when you reverted back to 1.2.11, how did you revert back to 1.2.11?

can you also attach logs - they should generally be: c:\Users\$username\.chia\mainnet\log\debug.log ?

**Comment by chrismikefowler1** [comment] 2022-02-09 00:53
Yes that is 1.2.11 - when going back to the prior version i used the main download screen and installed

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8028523/debug.log)
.

**Comment by chrismikefowler1** [comment] 2022-02-10 00:56
this also happens while i have he beta version installed. I've tried everything i can do from here, except for deleting and reinstalling.  I'd prefer not to do that. i'm sync'd

**Comment by paninaro** [comment] 2022-02-10 01:52
Hi @chrismikefowler1. The screenshot you shared showing the "Loading configuration" screen is something that was added to the 1.2.12 builds -- 1.2.11 doesn't appear to have that screen. So I'm thinking that installing 1.2.11 on-top of the 1.2.12 build didn't actually do what was expected. I would recommend verifying the version, which you can view from the Help > About Chia Blockchain menu item.

You should be able to safely uninstall and reinstall without losing your farm configuration. The important data resides in `\Users\<your_windows_username>\.chia` and in `\Users\<your_windows_username\.chia_keys`. Just to be extra safe, I would quit the Chia application, rename (or backup) those directories (e.g. rename the .chia directory to backup_chia and .chia_keys to backup_chia_keys), and then perform the uninstall from the Settings app in Windows (you can also check the installed version there).

After uninstalling, you can rename `backup_chia` back to `.chia` and `backup_chia_keys` to `.chia_keys`, and then install 1.2.11. Hopefully that will get your farm back online.

**Comment by chrismikefowler1** [comment] 2022-02-10 01:59
![image](https://user-images.githubusercontent.com/84326972/153322584-c6b75675-9ffb-4160-be58-90453d0025a2.png)

**Comment by chrismikefowler1** [comment] 2022-02-10 02:21
![image](https://user-images.githubusercontent.com/84326972/153324831-8bdab075-7d34-42f1-aa5d-65d7dcc82436.png)

**Comment by chrismikefowler1** [comment] 2022-02-10 02:21
![image](https://user-images.githubusercontent.com/84326972/153324843-90f8b3ce-7062-460b-b679-128887a7b4c6.png)

**Comment by chrismikefowler1** [comment] 2022-02-10 02:22
well, following what you just said, i seem to have lost everything in my wallet and i'm not sync'd - so can you replenish my wallet i've lost? 3 chia

**Comment by chrismikefowler1** [comment] 2022-02-10 02:23
![image](https://user-images.githubusercontent.com/84326972/153325076-912a0ef2-c606-49f5-9cca-7721fe852bc8.png)

**Comment by paninaro** [comment] 2022-02-10 02:28
Sorry that it's syncing from scratch... Moving the backup_chia and backup_chia_keys directories back to their .chia and .chia_keys names should have preserved everything before uninstalling -- I do it commonly while testing.

@emlowe any sage advice to share?

**Comment by chrismikefowler1** [comment] 2022-02-10 02:29
Well, I did that. And it did not work. Will my chia come back when it syncs?

**Comment by chrismikefowler1** [comment] 2022-02-10 02:30
It did fix the loading screen issue.

**Comment by paninaro** [comment] 2022-02-10 02:31
Yes, your wallet balance should come back once sync'd

**Comment by chrismikefowler1** [comment] 2022-02-10 02:32
Thanks for your reply.

**Comment by esaung** [comment] 2022-02-10 02:46
Thanks @paninaro for your help. @chrismikefowler1 - glad you'll be back to a "normal" state once you get all synced up. Please confirm you're back to what you expected once you get all synced up so we can close this issue.

**Comment by chrismikefowler1** [comment] 2022-02-12 14:27
All back up and fixed. Sync'd and plotting.  Thank you guys.

**Comment by chrismikefowler1** [comment] 2022-02-12 17:31
& farming*

**Comment by chrismikefowler1** [comment] 2022-02-27 22:39
All fixed now.

**Comment by emlowe** [comment] 2022-03-08 21:39
Closing issue

**Closed by emlowe** 2022-03-08 21:39 UTC
Labels: bug

**Comment by pipilu2022** [comment] 2022-07-06 06:37
I have the same problem , with chia 1.4.0, windows 10
![33](https://user-images.githubusercontent.com/101960047/177484923-a8ad972f-c723-404e-958f-c6f9532a6e21.png)

**Comment by pipilu2022** [comment] 2022-07-06 06:37
I use 2 computers ,the same problem

**Comment by cruix89** [comment] 2022-07-09 13:34
same problem in ubuntu 22.04

**Comment by Hermes88** [comment] 2022-07-11 15:58
![MicrosoftTeams-image](https://user-images.githubusercontent.com/55690272/178306454-30ade3c6-1388-4461-98cd-a5e2f88e42b7.png)
same problem on MacOs 10.13

**Comment by manprinsen** [comment] 2022-09-08 17:00
Any updates or suggestions?
Im running macOS 10.13.6 and Chia 1.5.1

**Comment by paninaro** [comment] 2022-09-08 17:55
> Any updates or suggestions? Im running macOS 10.13.6 and Chia 1.5.1

@manprinsen please include your debug.log with debug logging enabled: `chia configure --set-log-level DEBUG` (or check https://github.com/Chia-Network/chia-blockchain/wiki/Logging-Messages-Reference)

**Comment by manprinsen** [comment] 2022-09-09 11:03
> > Any updates or suggestions? Im running macOS 10.13.6 and Chia 1.5.1
> 
> @manprinsen please include your debug.log with debug logging enabled: `chia configure --set-log-level DEBUG` (or check https://github.com/Chia-Network/chia-blockchain/wiki/Logging-Messages-Reference)

Well, this seems very hard. I get this error message:
pool-100-0-0-128:daemon a1286$ ./chia configure --set-log-level DEBUG
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "chia/cmds/plots.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "chia/plotting/util.py", line 7, in <module>
ImportError: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/blspy.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libgmp.10.dylib
  Expected in: flat namespace
 in /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libgmp.10.dylib
[20335] Failed to execute script 'chia' due to unhandled exception!

When i run ./chia -h:
pool-100-0-0-128:daemon a1286$ ./chia -h
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "chia/cmds/plots.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "chia/plotting/util.py", line 7, in <module>
ImportError: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/blspy.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libgmp.10.dylib
  Expected in: flat namespace
 in /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libgmp.10.dylib
[20326] Failed to execute script 'chia' due to unhandled exception!

**Comment by paninaro** [comment] 2022-09-09 17:05
@manprinsen right, 10.13 isn't an officially supported platform. That said, you might have some luck building and installing from source. https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL. Hope that helps.

**Comment by paninaro** [comment] 2022-09-09 17:13
Update: expect problems with 10.13, even if you somehow are able to install from source. If you're able to update to 10.14, that would be the recommended path. Sorry for the wrong info.

**Comment by Sftmrbullet** [comment] 2023-01-09 07:20
Hello I had the same issue - on the PC where i could not start gui I simply installed version 1.2. After starting it, it already knew mnemonic key (I do not know where it was saved, I unninstalled previous version, clear registry etc... ) I deleted this wallet in 1.2. After updating to latest version everything went well.
