### ISSUE TITLE
[BUG] after updating

### ISSUE THREAD

**Issue by Ildar123q** [Chia-Network/chia-blockchain#2995] opened 2021-04-28 10:01 UTC
![image](https://user-images.githubusercontent.com/83343089/116385809-da03c780-a821-11eb-94bc-1859fa059d0f.png)

**Comment by lvcivs** [comment] 2021-04-28 11:35
duplicate of #2692

**Comment by lipalong** [comment] 2021-04-28 23:38
Yes, see the comments in #2692 
Also, we've made the wording for this error more clear in the next release.

**Closed by lipalong** 2021-04-28 23:38 UTC
Labels: bug
