### ISSUE TITLE
MacOS restarting/crashing caused by Chia app

### ISSUE THREAD

**Issue by kieranx** [Chia-Network/chia-blockchain#1617] opened 2021-03-31 09:11 UTC
Has happened to me twice now, this is on an intel MacBook Pro. Fans go crazy for a second and then the machine crashes and restarts. The error log given on restart is this:

panic(cpu 0 caller 0xffffff8010dcc605): "compressed PTE 0xfffffe825d9c50e8 0xc010000000000000 has extra bits 0x8000000000000000: corrupted? Adjacent PTEs: 0x800000005f975067@0xfffffe825d9c50e0, 0x4000000000000000@0xfffffe825d9c50f0"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.81.3/osfmk/i386/pmap_internal.h:869
Backtrace (CPU 0), Frame : Return Address
0xffffffc13682b730 : 0xffffff8010cbab4d 
0xffffffc13682b780 : 0xffffff8010dfd7e3 
0xffffffc13682b7c0 : 0xffffff8010dede1a 
0xffffffc13682b810 : 0xffffff8010c5fa2f 
0xffffffc13682b830 : 0xffffff8010cba3ed 
0xffffffc13682b950 : 0xffffff8010cba6d8 
0xffffffc13682b9c0 : 0xffffff80114bef9a 
0xffffffc13682ba30 : 0xffffff8010dcc605 
0xffffffc13682bb70 : 0xffffff8010d4b64b 
0xffffffc13682bbf0 : 0xffffff8010d4a09c 
0xffffffc13682bc70 : 0xffffff8010d4d8f1 
0xffffffc13682bf00 : 0xffffff8010dee430 
0xffffffc13682bfa0 : 0xffffff8010c5f91f 

Process name corresponding to current thread: Chia
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000010a00000
KernelCache base:  0xffffff8010c00000
Kernel slide:      0x0000000010a10000
Kernel text base:  0xffffff8010c10000
__HIB  text base: 0xffffff8010b00000
System model name: MacBookPro16,1 (Mac-E1008331FDC96864)
System shutdown begun: NO
Hibernation exit count: 0

System uptime in nanoseconds: 769957799279310
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0002bc45c51e3e54
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000d0d6a00c8 0x0000000000000000
last started kext at 764449222217601: >usb.!UUserHCI	1 (addr 0xffffff7fb159f000, size 102400)
last stopped kext at 764519459922760: >usb.!UUserHCI	1 (addr 0xffffff7fb159f000, size 102400)
loaded kexts:
@filesystems.exfat	1.4
|SCSITaskUserClient	436.40.6
>!ATopCaseHIDEventDriver	4030.5
>!AHIDALSService	1
>AGPM	119
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
@fsplaceholder	1.14.0
@fileutil	20.036.15
@kext.AMDRadeonX6000	4.0.2
@kext.AMDRadeonServiceManager	4.0.2
@filesystems.autofs	3.0
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>AGDCBacklightControl	6.2.2
>!AMCCSControl	1.14
>!A!IKBLGraphics	16.0.1
>BridgeAudioCommunication	100.2
>!AAVEBridge	6.1
>!AGFXHDA	100.1.431
>!AMuxControl2	6.2.2
|IO!BSerialManager	8.0.3d9
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IPCHPMC	2.0.1
>!ABridgeAudio!C	100.2
>!A!ICFLGraphicsFramebuffer	16.0.1
>!AThunderboltIP	4.0.3
>!AHV	1
>!ADiskImages2	1
>!A!ISlowAdaptiveClocking	4.0.0
>BCMWLANFirmware4378.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4355.Hashstore	1
>!ABCMWLANBusInterfacePCIeMac	1
@filesystems.apfs	1677.81.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!A!BHIDKeyboard	223
>!AHIDKeyboard	223
>!AHS!BDriver	4030.5
>IO!BHIDDriver	8.0.3d9
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
@kext.triggers	1.0
@kext.AMDRadeonX6100HWLibs	1.0
@kext.AMDRadeonX6000Framebuffer	4.0.2
@kext.AMDSupport	4.0.2
>!ABacklightExpert	1.1.0
@kext.AMDRadeonX6000HWServices	4.0.2
>!ASMBus!C	1.0.18d1
>X86PlatformPlugin	1.0.0
>!AGraphicsControl	6.2.2
|IOAVB!F	930.1
>IOPlatformPlugin!F	6.0.0d8
|IONDRVSupport	585
|IOAccelerator!F2	439.52
|IO!BHost!CUARTTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
@!AGPUWrangler	6.2.2
@!AGraphicsDeviceControl	6.2.2
|IOGraphics!F	585
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
|IOSlowAdaptiveClocking!F	1.0.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
>IOImageLoader	1.0.0
>corecapture	1.0.4
>!AThunderboltPCIDownAdapter	4.1.1
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssI2C	3.0.60
>!A!ILpssDmac	3.0.60
>!ABSDKextStarter	3
|IOSurface	289.3
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
@filesystems.hfs.encodings.kext	1
>usb.!UVHCIBCE	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCI	1.2
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by kieranx** [comment] 2021-03-31 09:15
Actually, I see at least 2 others reported this "kernel panic" also. Apple states:

"The most likely cause is faulty software. If the kernel panic is caused by a known problem, the faulty software is identified." 

There is something happening with Chia which is causing this -- it clearly identifies Chia in the log, and several people are reporting it.

**Comment by mariano54** [comment] 2021-03-31 10:21
Can you provide more info on your computer model and Mac OS version?

**Comment by kieranx** [comment] 2021-03-31 11:03
> Can you provide more info on your computer model and Mac OS version?

Sure:

macOS Big Sur
MacBook Pro 16 inch 2019
2.3 Ghz 8-Core Intel Core i9
32 GB DDR4 RAM

If you need anything else, let me know.

**Comment by eFishCent** [comment] 2021-04-01 17:17
I have run into this problem with Intel macs running Big Sur. My thinking at the time was it was my docking station causing the problem. I have rolled back all my intel based Mac products to Catalina, and haven't had a problem since.

I should note kernel panics has happened with just full node running, no plotting going on.

**Comment by adaptdefymike** [comment] 2021-04-01 23:39
My Mac (had the same issue)


![image](https://user-images.githubusercontent.com/81542383/113364606-70be9f00-93b0-11eb-9b23-c1aa689ca12f.png)

Panic(CPU 2, time 174495324383228): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff86c81b45f0, spinlock owner: 0xffffff86a78d2120, current_thread: 0xffffff86a78d2120, spinlock_owner_cpu: 0x2
RAX: 0xffffff86c9efc890, RBX: 0xffffff9362e83e68, RCX: 0x00000000000002b4, RDX: 0x0000712e00000000
RSP: 0xffffffb0c7e0baa0, RBP: 0xffffffb0c7e0bae0, RSI: 0xffffff86a78d2120, RDI: 0xffffff9362e83e68
R8:  0xffffffb0c7e0bc60, R9:  0xffffff800770f110, R10: 0x0000000000ffffff, R11: 0x0000000000000000
R12: 0xffffff86a78d2120, R13: 0x0000000000000000, R14: 0x0000712e6cc74275, R15: 0xffffff86c9efc890
RFL: 0x0000000000000086, RIP: 0xffffff80076ccb7d, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffffa065e80f80 : 0xffffff80077ed5bb 
0xffffffa065e80fd0 : 0xffffff800765fbdd 
0xffffffb0c7e0bae0 : 0xffffff80076ccd04 
0xffffffb0c7e0bb10 : 0xffffff800770d930 
0xffffffb0c7e0bb30 : 0xffffff800770f149 
0xffffffb0c7e0bbe0 : 0xffffff800770f646 
0xffffffb0c7e0bc50 : 0xffffff800770e694 
0xffffffb0c7e0bd10 : 0xffffff80077125e8 
0xffffffb0c7e0bd50 : 0xffffff8007c23364 
0xffffffb0c7e0bd70 : 0xffffff8007c2344e 
0xffffffb0c7e0bdb0 : 0xffffff8007c7bfdd 
0xffffffb0c7e0be30 : 0xffffff8007c774e5 
0xffffffb0c7e0bee0 : 0xffffff8007c77311 
0xffffffb0c7e0bf40 : 0xffffff8007d698cb 
0xffffffb0c7e0bfa0 : 0xffffff80076601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

Mac OS version:
20D91

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000007400000
KernelCache base:  0xffffff8007600000
Kernel slide:      0x0000000007410000
Kernel text base:  0xffffff8007610000
__HIB  text base: 0xffffff8007500000
System model name: MacBookPro11,5 (Mac-06F11F11946D27C5)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 174495324426048
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00009eb3dbd3d33a
  Sleep   : 0x000071538693d71a 0x000000006fdb7e7c 0x00005f0f637f100d
  Wake    : 0x0000715395d162c8 0x0000000070362bb5 0x000071538d7d1eb9
last started kext at 50226140167: com.google.drivefs.filesystems.dfsfuse	45.2.0 (addr 0xffffff7fa9803000, size 86016)
loaded kexts:
com.google.drivefs.filesystems.dfsfuse	45.2.0
@filesystems.exfat	1.4
>!A!BMultitouch	99
>AudioAUUC	1.70
>AGPM	119
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@fileutil	20.036.15
@filesystems.autofs	3.0
@kext.AMDFramebuffer	4.0.2
>!AUpstreamUserClient	3.6.8
@kext.AMDRadeonX4000	4.0.2
@kext.AMDRadeonServiceManager	4.0.2
>!AHDAHardwareConfigDriver	283.15
>!AHDA	283.15
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
>!A!IHD5000Graphics	16.0.1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.3d9
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>AGDCBacklightControl	6.2.2
>!ABacklight	180.3
>!AMuxControl	6.2.2
>eficheck	1
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!IFramebufferAzul	16.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>!ACameraInterface	7.6.0
>!AThunderboltIP	4.0.3
>!ASMCLMU	212
>!AMCCSControl	1.14
>!ALPC	3.1
|Broadcom!B20703USBTransport	8.0.3d9
@kext.AMD7000!C	4.0.2
>!AFIVRDriver	4.1.0
>!ATopCaseHIDEventDriver	4030.5
>!UTopCaseDriver	4030.5
|IO!BUSBDFU	8.0.3d9
|SCSITaskUserClient	436.40.6
>!UCardReader	511.60.2
@filesystems.apfs	1677.81.1
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	346
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!A!BHIDKeyboard	223
>!UAudio	401.4
@kext.triggers	1.0
@kext.AMDRadeonX4030HWLibs	1.0
@kext.AMDRadeonX4000HWServices	4.0.2
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOSerial!F	11
|IOAVB!F	930.1
>!ABacklightExpert	1.1.0
>!AGraphicsControl	6.2.2
@!AGPUWrangler	6.2.2
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
|IOAccelerator!F2	439.52
|IOSlowAdaptiveClocking!F	1.0.0
|IONDRVSupport	585
>!ASMBusPCI	1.0.14d1
>!ASMBus!C	1.0.18d1
>IOPlatformPlugin!F	6.0.0d8
|Broadcom!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
>!AThunderboltEDMSink	5.0.3
>!AThunderboltDPOutAdapter	8.1.4
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
@kext.AMDSupport	4.0.2
@!AGraphicsDeviceControl	6.2.2
|IOGraphics!F	585
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>usb.ethernet.asix	5.0.0
>!AHS!BDriver	4030.5
>IO!BHIDDriver	8.0.3d9
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>!AHIDKeyboard	223
>usb.IOUSBHostHIDDevice	1.2
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AXsanScheme	3
|IOAHCIBlock!S	332
|IO80211!F	1200.12.2b1
>corecapture	1.0.4
>!A!ILpssGspi	3.0.60
|IOAHCI!F	294
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!ABSDKextStarter	3
|IOSurface	289.3
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1
panic(cpu 0 caller 0xffffff80077e2960): "Spinlock acquisition timed out: lock=0xffffff86c81b45f0, lock owner thread=0xffffff86a78d2120, current_thread: 0xffffff86c9efc890, lock owner active on CPU 0x2, current owner: 0xffffff86a78d2120, time: 174495324456061"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.81.3/osfmk/i386/locks_i386.c:505
Backtrace (CPU 0), Frame : Return Address
0xffffffa045ad6af0 : 0xffffff80076bab4d 
0xffffffa045ad6b40 : 0xffffff80077fd7e3 
0xffffffa045ad6b80 : 0xffffff80077ede1a 
0xffffffa045ad6bd0 : 0xffffff800765fa2f 
0xffffffa045ad6bf0 : 0xffffff80076ba3ed 
0xffffffa045ad6d10 : 0xffffff80076ba6d8 
0xffffffa045ad6d80 : 0xffffff8007ebef9a 
0xffffffa045ad6df0 : 0xffffff80077e2960 
0xffffffa045ad6e30 : 0xffffff80076daff6 
0xffffffa045ad6e60 : 0xffffff8007708d7b 
0xffffffa045ad6f20 : 0xffffff80077d98b3 
0xffffffa045ad6f60 : 0xffffff80077f6eaa 
0xffffffa045ad6f80 : 0xffffff80077ed5bb 
0xffffffa045ad6fd0 : 0xffffff800765fbdd 
0xffffffb0ccdd3db0 : 0xffffff80077123d1 
0xffffffb0ccdd3e10 : 0xffffff8007c795e9 
0xffffffb0ccdd3f00 : 0xffffff8007c78716 
0xffffffb0ccdd3f40 : 0xffffff8007d698cb 
0xffffffb0ccdd3fa0 : 0xffffff80076601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

**Comment by mariano54** [comment] 2021-04-07 11:23
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/1672, let's keep the discussion there

**Closed by mariano54** 2021-04-07 11:23 UTC
