### ISSUE TITLE
[Bug] Chia won't start - no error reported

### ISSUE THREAD

**Issue by nicecatch** [Chia-Network/chia-blockchain#9569] opened 2021-12-14 23:38 UTC
### What happened?

Trying to run chia on a fresh install of arch linux

```
$ chia start farmer -r
Daemon not started yet
Starting daemon
Daemon not started yet
Failed to create the chia daemon
```

Debug level on config.yaml is set to DEBUG and this is what is inside debug.log

```
$ cat debug.log
2021-12-14T23:35:46.870 daemon chia.daemon.server         : INFO     Starting Daemon Server
2021-12-14T23:35:46.872 daemon chia.daemon.server         : INFO     Waiting Daemon WebSocketServer closure
```

I have tried also on 1.2.8 but it yields the same result

How can I get more info about what is going wrong?  

"ps aux" doesn't show any chia process in the background before hand - but once it try to start it I see there are some chia_daemon processes hanging that I have to kill manually
Ports, according to netstat, are free as well

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by springjools** [comment] 2021-12-15 17:53
I'm having the same issue on wsl2/Debian Bullseye. There's not even a log file created yet. The folder ~/.chia/mainnet/log/ is empty

**Comment by nicecatch** [comment] 2021-12-15 18:39
I have installed chia from the aur - https://aur.archlinux.org/packages/chia-bin/
It uses the packages for ubuntu and it is 1.2.11 but at least it starts

I tried to downgrade chia but it was yielding the same result. I suppose there must be something broken with a dependency or with python on archlinux (long shot but with no error messages it's really hard to tell)

**Comment by toonlynx** [comment] 2021-12-16 20:45
The same problem at archlinux after update system and chia.
I'm try to rename .chia folder but its not resolve problem.
File debug.log has no errors.

**Comment by toonlynx** [comment] 2021-12-16 21:13
[chia.txt](https://github.com/Chia-Network/chia-blockchain/files/7730440/chia.txt)
Strace result

**Comment by emlowe** [comment] 2021-12-16 22:05
What version of python? I think arch might be using python 3.10 now and there are some issues with chia with python 3.10

**Comment by emlowe** [comment] 2021-12-16 22:07
Yes, it appears are using python 3.10 from that trace file. I'm marking as duplicate of #8807

**Closed by emlowe** 2021-12-16 22:07 UTC
Labels: bug

**Comment by toonlynx** [comment] 2021-12-17 00:11
(venv) /media/zusik/toonlynx/crypto/chia_latest/chia-blockchain toonlynx@lynx > python -V                       
Python 3.10.1

**Comment by emlowe** [comment] 2021-12-17 00:44
You will need to downgrade to python 3.9 for chia
