### ISSUE TITLE
GUI: Farming status is green "Farming" but plots are unmounted

### ISSUE THREAD

**Issue by jurajmichalak1** [Chia-Network/chia-blockchain#1526] opened 2021-03-26 18:32 UTC
v1.0.0

I was checking status of farming via GUI (x11vnc headless) once a day on my storage "server" and everything was OK
![image](https://user-images.githubusercontent.com/23061228/112666110-19727900-8e5c-11eb-8a8c-b238650b5f55.png)

I went to add new plotted plots to my farm and find out that exernal drive has been unmounted 3 days ago due to error, dmesg:
```
[Wed Mar 24 16:16:05 2021] print_req_error: I/O error, dev sdb, sector 0
[Wed Mar 24 16:16:05 2021] sd 8:0:0:0: [sdb] Synchronizing SCSI cache
[Wed Mar 24 16:16:05 2021] sd 8:0:0:0: [sdb] Synchronize Cache(10) failed: Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK
[Wed Mar 24 16:16:06 2021] Buffer I/O error on dev sdb1, logical block 243826688, lost sync page write
[Wed Mar 24 16:16:06 2021] JBD2: Error -5 detected when updating journal superblock for sdb1-8.
[Wed Mar 24 16:16:06 2021] Aborting journal on device sdb1-8.
[Wed Mar 24 16:16:06 2021] Buffer I/O error on dev sdb1, logical block 243826688, lost sync page write
[Wed Mar 24 16:16:06 2021] JBD2: Error -5 detected when updating journal superblock for sdb1-8.
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] 488378645 4096-byte logical blocks: (2.00 TB/1.82 TiB)
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] Write Protect is off
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] Mode Sense: 4f 00 00 00
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] Optimal transfer size 268431360 bytes
[Wed Mar 24 16:17:14 2021]  sdb: sdb1
[Wed Mar 24 16:17:14 2021] sd 7:0:0:0: [sdb] Attached SCSI disk
```
I think it was caused physically by me (pushed with hand into USB connector when I was removing another USB drive). But after that I checked via GUI whether everything is OK, but was not :)

so I checked CLI and found out
```
$ chia plots check
17:57:20.154  src.plotting.check_plots         : INFO     Loading plots in config.yaml using plot_tools loading code

17:57:30.672  src.plotting.plot_tools          : INFO     Searching directories ['/mnt/2tb_sg_backup/chia-network/created_plots']
17:57:30.672  src.plotting.plot_tools          : WARNING  Directory: /mnt/2tb_sg_backup/chia-network/created_plots does not exist.
17:57:30.673  src.plotting.plot_tools          : INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.07572340965270996 seconds
17:57:30.673  src.plotting.check_plots         : INFO
17:57:30.673  src.plotting.check_plots         : INFO
17:57:30.673  src.plotting.check_plots         : INFO     Summary
17:57:30.673  src.plotting.check_plots         : INFO     Found 0 valid plots, total size 0.00000 TiB
```
But in GUI:
![image](https://user-images.githubusercontent.com/23061228/112677154-a5d76880-8e69-11eb-9af0-c77e888d506b.png)

After I mounted drive again it's working:
```
17:59:34.965  src.plotting.check_plots         : INFO     Summary
17:59:34.965  src.plotting.check_plots         : INFO     Found 3 valid plots, total size 0.50695 TiB
17:59:34.965  src.plotting.check_plots         : INFO     1 plots of size 32
17:59:34.966  src.plotting.check_plots         : INFO     2 plots of size 33
```
But how can I check that I'm really farming?
I'm really not sure.
Thank you in advance.

**Comment by Dravenex** [comment] 2021-03-27 12:26
Yeah, I have the same problem. GUI says "farming" but "Last Attempted Proof" is hours ago. Normally it should update every few seconds. I discovered that restarting the process "start_farmer.exe" starts farming again. But a few minutes/hours later the same problem happens. It's pretty annoying. Because of this issue I "farmed" 3 days without getting rewards.

**Comment by mariano54** [comment] 2021-03-29 04:43
This will be fixed in 1.0.2, the issue is that the harvester crashes occasionally.

**Comment by mariano54** [comment] 2021-04-07 11:36
This is fixed. Please let me know if you experience more harvester crashes.

**Closed by mariano54** 2021-04-07 11:36 UTC

**Comment by Dravenex** [comment] 2021-04-07 11:41
Days ago I updated to 1.0.3 and yesterday the harvester/Farmer crashed again. I needed to restart my PC to get it running again. Restarting harvester and farmer didn’t help. What’s the difference between farmer and harvester?

**Comment by mariano54** [comment] 2021-04-07 11:55
They are two different processes, harvester deals with reading and writing to disk, and farmer deals with signing blocks.

Do you have any errors in this file: ~/.chia/mainnet/log/debug.log?

**Comment by Dravenex** [comment] 2021-04-11 18:49
My farmer paused again at 17:51. Debug Log says the following:

14:46:14.431 full_node full_node_server        : WARNING  Cannot write to closing transport 72.49.99.37
17:51:52.382 harvester src.harvester.harvester : ERROR    Error using prover object Destination buffer is too small
17:51:52.383 harvester src.harvester.harvester : ERROR    File: J:\plot-k32-2021-02-18-12-33-4c5973a824dcd2c92b1638295cb72489a237326e1faca558331937705a74b4a1.plot Plot ID: b'LYs\xa8$\xdc\xd2\xc9+\x168)\\\xb7$\x89\xa272n\x1f\xac\xa5X3\x197pZt\xb4\xa1', challenge: b2121b33341a9810487e558b28058d19ff9c9b36ada75e14f8eb402103571732, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x0000016A0E7C4EB0>, pool_public_key=<G1Element 9089f325b108afe4915ee653d0ce3df14d6e3bda3608c1e816a467c68182b7dd34e54223062b4219abc792838baad341>, pool_contract_puzzle_hash=None, plot_public_key=<G1Element 805487d7ae9cc8f31ce6f896afb54f0c3c1fc81dbf5bab3d7b83465d919b4b98cf95ef567a232c0a42b1b8b0f6a78893>, file_size=108812303821, time_modified=1613768061.0)
