### ISSUE TITLE
[BUG]Not active for 60 seconds, restarting all chains

### ISSUE THREAD

**Issue by maguobin1** [Chia-Network/chia-blockchain#2956] opened 2021-04-28 01:50 UTC
Not active for 60 seconds, restarting all chains

**Comment by royimous** [comment] 2021-04-28 04:50
This is not a bug. Close this. If you want support, read the FAQ on how to get it.

**Closed** 2021-04-28 05:30 UTC
Labels: bug

**Comment by maguobin1** [comment] 2021-04-28 05:50
thank you, date sync slow How to solve it

**Comment by dorkmo** [comment] 2021-04-28 05:54
if youre able to, you might copy your logs and post them here

**Comment by maguobin1** [comment] 2021-04-28 05:56
2021-04-28T13:43:06.222 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-04-28T13:44:06.352 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-04-28T13:45:06.493 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-04-28T13:46:06.578 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-04-28T13:47:06.703 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains

**Comment by maguobin1** [comment] 2021-04-28 05:56
(venv) [root@iZj6cgn5dbzl3js2gfica7Z mainnet]# du -sh db/
47M	db/
(venv) [root@iZj6cgn5dbzl3js2gfica7Z mainnet]#

**Comment by dorkmo** [comment] 2021-04-28 05:59
are you trying to run a timelord?

**Comment by wangqty** [comment] 2021-05-04 13:57
the same to me.

2021-05-04T13:55:37.438 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
2021-05-04T13:55:37.438 timelord chia.timelord.timelord   : DEBUG    Resetting chains
