### ISSUE TITLE
the new harvester throws ERROR with communicating to farmer

### ISSUE THREAD

**Issue by tntlt** [Chia-Network/chia-blockchain#7738] opened 2021-07-23 00:17 UTC
I'm getting the following error om the new harvester (v1.2.2):

2021-07-22T20:10:36.189 harvester chia.server.rate_limits : WARNING  Invalid message: 4, 4 is not a valid ProtocolMessageTypes
2021-07-22T20:10:36.189 harvester harvester_server        : ERROR    Exception: 4 is not a valid ProtocolMessageTypes <class 'ValueError'>, closing connection {'host': 'x.x.x.x', 'port': 8447}. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/server.py", line 490, in api_call
    f"<- {ProtocolMessageTypes(full_message.type).name} from peer "
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 4 is not a valid ProtocolMessageTypes

2021-07-22T20:10:36.190 harvester harvester_server        : DEBUG    Inbound_handler task cancelled
2021-07-22T20:10:36.191 harvester harvester_server        : INFO     Connection closed: x.x.x.x, node id: xxx
2021-07-22T20:10:36.192 harvester harvester_server        : WARNING  Banning x.x.x.x for 10 seconds

**Comment by emlowe** [comment] 2021-07-23 02:49
All harvesters and farmer need to both be at 1.2.0+

Thie message is probably caused by an old farmer

**Comment by Jacek-ghub** [comment] 2021-07-23 03:57
@emlowe 

Yeah, "probably caused by an old farmer" is a really good description of the state of the Chia system.  Things are broken, and the best answer from the source is a guess.

Would it be possible to not push the CLI started harvester to the background, so it could still push some critical errors to the console?  Currently, harvester is pushed to the background (on Windows), but the console still needs to be open.  Once, the console is closed, harvester is gone as well.  So, may as well use that console for something, other than cluttering the desktop.

Would it be possible to add to the RPC protocol module-version stamp, as such that confused module (harvester in that case) would know that there is a version mismatch and some action needs to be taken?  At least, the message from the log file would be clear, not really requiring an authoritative guess for an answer.  Not having such version-stamping is basically a software negligence.

Would there be a possibility to add an error reporting RPC part, where all modules would report critical issues, so the full node, so that UI could alert users to at least known issues (if not all ERRORs / WARNINGs)?

Why do we all end-users need to fish for those errors, and wonder what those mean, when it takes just one engineer during the coffee break to add such basic thing.

**Comment by tntlt** [comment] 2021-07-23 12:23
After matching version on all nodes everything got fixed.
Thanks!

**Comment by emlowe** [comment] 2021-07-23 14:23
Closing issue

**Closed by emlowe** 2021-07-23 14:23 UTC
